### ISSUE TITLE
ANR while stopping broadcast.

### ISSUE THREAD

**Issue by vipulpurohit** [begeekmyfriend/yasea#1]
Hello,
Thanks for a pure java rtmp streaming library.
I'm facing a issue while stopping the broadcast, the application hangs and just stop responding.
I'm getting these log when I stop broadcast.

```
I/Yasea: stop audio worker thread
04-20 19:29:04.939 12009-12009/net.ossrs.sea I/SrsEncoder: stop aencoder
04-20 19:29:04.947 12009-12151/net.ossrs.sea I/OMXMaster: clearPlugins: 0 key=aec50290 value=0
04-20 19:29:04.947 12009-12151/net.ossrs.sea I/OMXMaster: clearPlugins: 1 key=aec50358 value=b47fe544
04-20 19:29:04.950 12009-12151/net.ossrs.sea I/OMXMaster: clearPlugins: 2 key=aee0b140 value=b47fe2a4
04-20 19:29:04.952 12009-12009/net.ossrs.sea I/SrsEncoder: stop vencoder
04-20 19:29:04.964 12009-12009/net.ossrs.sea I/SrsEncoder: stop muxer to SRS over RTMP
04-20 19:29:04.964 12009-12009/net.ossrs.sea D/RtmpConnection: closeStream(): setting current stream ID to -1
04-20 19:29:04.965 12009-12009/net.ossrs.sea I/SrsMuxer: worker: disconnect SRS ok.
04-20 19:29:04.965 12009-12264/net.ossrs.sea D/WriteThread: WriteThread: wrote packet: RTMP Command (command: closeStream, transaction ID: 0), size: 24
04-20 19:29:04.965 12009-12264/net.ossrs.sea D/WriteThread: WriteThread: waiting...
04-20 19:29:04.966 12009-12265/net.ossrs.sea I/RtmpConnection: shutdown(): Shutting down read/write threads
04-20 19:29:04.966 12009-12009/net.ossrs.sea D/AndroidRuntime: Shutting down VM
04-20 19:29:04.980 12009-12009/? I/SrsEncoder: stop muxer to SRS over RTMP
04-20 19:29:04.985 12009-12019/? I/art: Debugger is no longer active
04-20 19:29:05.966 12009-12264/? D/WriteThread: WriteThread: waiting...
04-20 19:29:06.966 12009-12264/? D/WriteThread: WriteThread: waiting...
04-20 19:29:07.966 12009-12264/? D/WriteThread: WriteThread: waiting...
04-20 19:29:08.967 12009-12264/? D/WriteThread: WriteThread: waiting...
04-20 19:29:09.967 12009-12264/? D/WriteThread: WriteThread: waiting...
04-20 19:29:10.968 12009-12264/? D/WriteThread: WriteThread: waiting...
```

**Comment by begeekmyfriend** [comment]
I have met it too. The write thread of RTMP module fails to stop while shutting down because the 'closeStream' command is still sent into outputStream buffer. So that is synchronization issue on thread shutting down. I will fix is as soon as possible.

**Comment by begeekmyfriend** [comment]
https://github.com/begeekmyfriend/yasea/commit/5f37bd808bc34420454f5b6e3dfc2dc6d499483c

**Comment by Muthukathiravan** [comment]
Same issue occur for me also..
07-19 11:46:43.269 27385-5300/? D/WriteThread: WriteThread: wrote packet: RTMP Audio, size: 92
07-19 11:46:43.269 27385-5300/? D/WriteThread: WriteThread: waiting...
07-19 11:46:43.269 27385-5300/? D/WriteThread: WriteThread: wrote packet: RTMP Video, size: 4644
07-19 11:46:43.269 27385-5300/? D/WriteThread: WriteThread: wrote packet: RTMP Audio, size: 94
07-19 11:46:43.279 27385-5300/? D/WriteThread: WriteThread: waiting...
07-19 11:46:43.279 366-5374/? E/mm-camera-CORE: aec_process_stats_calc_ysum(113): E

**Comment by begeekmyfriend** [comment]
@Muthukathiravan the latest version has fixed this bug.

**Comment by Muthukathiravan** [comment]
I am using latest version only.
https://github.com/begeekmyfriend/yasea
i have download from the app above the link

**Comment by begeekmyfriend** [comment]
@Muthukathiravan the log of original issue shows that there are no RTMP packets sent to the socket and then the write thread is still waiting and not to be closed. However I can not see any similar signs in the log you provided. Would you please provide more details?

**Comment by Muthukathiravan** [comment]
85
07-19 12:17:16.259 27385-27676/? D/WriteThread: WriteThread: waiting...
07-19 12:17:16.289 27385-27676/? D/WriteThread: WriteThread: wrote packet: RTMP Audio, size: 95
07-19 12:17:16.289 27385-27676/? D/WriteThread: WriteThread: waiting...
07-19 12:17:16.289 366-28812/? E/mm-camera-CORE: aec_process_stats_calc_ysum(113): E
07-19 12:17:16.289 27385-27676/? D/WriteThread: WriteThread: wrote packet: RTMP Audio, size: 97
07-19 12:17:16.289 27385-27676/? D/WriteThread: WriteThread: waiting...
07-19 12:17:16.329 27385-27676/? D/WriteThread: WriteThread: wrote packet: RTMP Audio, size: 93
07-19 12:17:16.329 27385-27676/? D/WriteThread: WriteThread: waiting...
07-19 12:17:16.329 27385-27676/? D/WriteThread: WriteThread: wrote packet: RTMP Video, size: 4510
07-19 12:17:16.329 27385-27676/? D/WriteThread: WriteThread: waiting...
07-19 12:17:16.329 366-28812/? E/mm-camera-sensor: port_sensor_handle_aec_update:832 g 5.619218 lux idx 343.261078, nr-y: 5.619218, nr-cbcr: 5.619218, asf: 5.619218
07-19 12:17:16.349 27385-27676/? D/WriteThread: WriteThread: wrote packet: RTMP Audio, size: 93
07-19 12:17:16.349 27385-27676/? D/WriteThread: WriteThread: waiting...
07-19 12:17:16.349 27385-27676/? D/WriteThread: WriteThread: wrote packet: RTMP Audio, size: 96
07-19 12:17:16.349 27385-27676/? D/WriteThread: WriteThread: waiting...
07-19 12:17:16.359 366-28812/? E/mm-camera-CORE: aec_process_stats_calc_ysum(113): E

Same log print for me,If you want anything specify what are the details you want

**Comment by begeekmyfriend** [comment]
Your log shows there is no ANR. the RTMP packets are being sent to the socket. Did you stop yasea? Otherwise there should have no RTMP packets sent.

**Comment by Muthukathiravan** [comment]
I din not stop yasea..What is the solution for this issue

**Comment by begeekmyfriend** [comment]
@Muthukathiravan Didn't you see the button?

**Comment by Muthukathiravan** [comment]
share your mail id
