### ISSUE TITLE
 MediaCodecInfo.CodecCapabilities.COLOR_FormatSurface

### ISSUE THREAD

**Issue by Nook2007** [begeekmyfriend/yasea#10]
Hi, can i use MediaCodecInfo.CodecCapabilities.COLOR_FormatSurface for MediaFormat.KEY_COLOR_FORMAT to get data from surface?

**Comment by begeekmyfriend** [comment]
There seems no difference between `MediaCodec` and `MediaRecorder` that way. In fact, yasea needs some pre-processing on getting the YUV frames from the camera before sending them into the encoder like cropping, flipping and rotation. For instance, the original video data source in android is a landscape picture and what I want is a portrait one, then I need to rotate and may be flip the whole YUV frame.

`COLOR_FormatSurface` can really work indeed. But if I do not know the specific color format, how do I make the YUV frame transformation on pre-processing?

**Comment by Nook2007** [comment]
We don't need pre-process frames, at the output we get raw h264 (with COLOR_FormatSurface or another, it does not matter) from mediacodec. I noticed that when use COLOR_FormatSurface - SPS and PPS are not sent. I'm trying to add them, but it still does not work
[https://gist.github.com/Nook2007/92f460c87d8556d35ab5676f40a5e840](url)

**Comment by begeekmyfriend** [comment]
Where is your raw h.264 data from? Does it wrapped in the byte buffer returned by `getOutputBuffers()` of `MediaCodec`? Typically the SPS and PPS are wrapped in the IDR frame generated by the encoder if you do not miss them. 

The gist code seems unreliable. See [SrsFlvMuxer.java](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/sea/SrsFlvMuxer.java#L859) to find out the right way.

After all I am afraid I will not try this on yasea for I am busy with other issues.

**Comment by llxxhm** [comment]
@Nook2007 我的也是H264的祼数据, 希望通过writeSampleData来推流, 没有成功, 请问你怎么解决的呢
