### ISSUE TITLE
用小米3推流，播放端没有画面

### ISSUE THREAD

**Issue by GorexLyton** [begeekmyfriend/yasea#101]
你好，我遇到一个问题。用HTC手机推流时，播放端可以正常观看。但是用小米3推流的时候出现了一些问题，播放端没有正常的画面，只有一片绿色。请问这种问题是什么原因造成的，要如何处理？谢谢。

**Comment by GorexLyton** [comment]
我用的是硬编。

**Comment by begeekmyfriend** [comment]
Color format的问题，可以追踪一下`mVideoColorFormat`这个变量
