### ISSUE TITLE
如何降低视频的清晰度和大小

### ISSUE THREAD

**Issue by atlearn** [begeekmyfriend/yasea#107]
你好，我想问一下。我这边是修改了相机的分辨率了，所设置的分辨率是手机相机支持的，但是发现视频的清晰度和RTMP流大小没有改变，怎么改变RTMP流的大小。

**Comment by begeekmyfriend** [comment]
`setOutputResolution` and `setVideoSmoothMode`

**Comment by atlearn** [comment]
可以详细点吗?setVideoSmoothMode这方法我找不到，谢谢啦

**Comment by begeekmyfriend** [comment]
`MainActivity.java`

**Comment by atlearn** [comment]
MainActivity.java只能找到setVideoResolution，这个设置了没效果，清晰度还是一样。然后setOutputResolution 在libenc.cc里，这个我也不知道具体怎么设置

**Comment by begeekmyfriend** [comment]
你根本没仔细看

**Comment by atlearn** [comment]
好的吧  不好意思 我在仔细研究下。
