### ISSUE TITLE
怎么样才能直推音频啊？

### ISSUE THREAD

**Issue by cdcdec** [begeekmyfriend/yasea#108]
怎么样才能直推音频啊？

**Comment by begeekmyfriend** [comment]
提问之前先仔细看看代码好吗？https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/SrsPublisher.java#L166

**Comment by 401885064** [comment]
谢谢这个提问       快速定位解决
