### ISSUE TITLE
Supporting Adobe FMS server

### ISSUE THREAD

**Issue by satyamub** [begeekmyfriend/yasea#11]
Hi @begeekmyfriend .. I am trying your library however when I add my URL which is a Adobe FMS server to start streaming, sometimes, it hangs, some times it shows first frame and then hangs and some times, it is published however, when I want to play in wowza server test player, it does not show anything.

**Comment by begeekmyfriend** [comment]
First please confirm what you are testing is under the latest version of this repository and without any modified. By the way, the latest commit is https://github.com/begeekmyfriend/yasea/commit/7281158f1c56fa529dff7b91b9e70832b25c8fc0
Second please confirm that you have tested at the public domain srs.net and the [on-line player](http://www.ossrs.net/players/srs_player.html)  works well.
If the above steps get verified and your case is still not in the right way, please attach with Android Studio to see the debug log. For instance, if there is log showing as
> WriteThread: wrote video data, size 1234
then it connected on the server and is publishing, then you need to check if the server and the player works well.

**Comment by satyamub** [comment]
@begeekmyfriend .. I have my own encoder in iOS and the server works well there. I am working on a application for Android for the same purpose.

Your first two points works like, I have downloaded the latest one today and testing it. If I try to test using your server address, it works more lessly .

I am using the wowza test player to test.

I am doing the later part of the suggestion and will get back to you.

**Comment by begeekmyfriend** [comment]
Hello, how are things going? I remember you have said that the player shows nothing on wawza. Just now I commented a patch in [issue#9](https://github.com/begeekmyfriend/yasea/issues/9#issuecomment-216476688). It seemed the same thing happened on Nginx-RTMP. I think it is worth a try on wawza too. Just sync the latest version.

**Comment by satyamub** [comment]
how do get this new version to check?

**Comment by begeekmyfriend** [comment]
Just download the ZIP file

**Comment by begeekmyfriend** [comment]
FMS has been verified to be all right.

Case of Wowza is here: https://github.com/begeekmyfriend/yasea/issues/14#issuecomment-217867576

You can try it on branch Wowza: https://github.com/begeekmyfriend/yasea/tree/wowza

**Comment by begeekmyfriend** [comment]
Fixed on both nginx and wowza. https://github.com/begeekmyfriend/yasea/commit/0307650290d39f3409668ad5dc62dbcc951bb61e

**Comment by satyamub** [comment]
@begeekmyfriend  how can I download the new code!!!

**Comment by begeekmyfriend** [comment]
https://github.com/begeekmyfriend/yasea/archive/master.zip

**Comment by satyamub** [comment]
Yeah I tried this now when I start publishing in your rump path.. its started off and I can see the video playing in Wowza. The main issue is I got a FMS server configured. I want this library to publish the RTMP packet to that server which its not doing... Its showing the below Logcat means its trying to write however when I try to open that link. Its not showing anything...

WriteThread: wrote packet: RTMP Audio, size:194

**Comment by satyamub** [comment]
What type of server you are using? if you don't mind sharing the info though!!

**Comment by satyamub** [comment]
Please check the log below

05-10 12:06:07.435     960-1469/net.ossrs.sea D/WriteThread﹕ WriteThread: waiting...
05-10 12:06:07.445     960-1469/net.ossrs.sea D/WriteThread﹕ WriteThread: wrote packet: RTMP Audio, size: 93
05-10 12:06:07.445     960-1469/net.ossrs.sea D/WriteThread﹕ WriteThread: waiting...
05-10 12:06:07.465     960-1469/net.ossrs.sea D/WriteThread﹕ WriteThread: wrote packet: RTMP Audio, size: 99
05-10 12:06:07.465     960-1469/net.ossrs.sea D/WriteThread﹕ WriteThread: waiting...
05-10 12:06:07.505     960-1469/net.ossrs.sea D/WriteThread﹕ WriteThread: wrote packet: RTMP Audio, size: 98
05-10 12:06:07.505     960-1469/net.ossrs.sea D/WriteThread﹕ WriteThread: waiting...
05-10 12:06:07.525     960-1469/net.ossrs.sea D/WriteThread﹕ WriteThread: wrote packet: RTMP Audio, size: 92
05-10 12:06:07.525     960-1469/net.ossrs.sea D/WriteThread﹕ WriteThread: waiting...
05-10 12:06:07.545     960-1469/net.ossrs.sea D/WriteThread﹕ WriteThread: wrote packet: RTMP Audio, size: 94
05-10 12:06:07.545     960-1469/net.ossrs.sea D/WriteThread﹕ WriteThread: waiting...
05-10 12:06:07.565     960-1469/net.ossrs.sea D/WriteThread﹕ WriteThread: wrote packet: RTMP Audio, size: 94
05-10 12:06:07.565     960-1469/net.ossrs.sea D/WriteThread﹕ WriteThread: waiting...
05-10 12:06:07.595     960-1469/net.ossrs.sea D/WriteThread﹕ WriteThread: wrote packet: RTMP Video, size: 1497
05-10 12:06:07.595     960-1469/net.ossrs.sea D/WriteThread﹕ WriteThread: waiting...
05-10 12:06:07.605     960-1469/net.ossrs.sea D/WriteThread﹕ WriteThread: wrote packet: RTMP Audio, size: 95
05-10 12:06:07.605     960-1469/net.ossrs.sea D/WriteThread﹕ WriteThread: waiting...
05-10 12:06:07.625     960-1469/net.ossrs.sea D/WriteThread﹕ WriteThread: wrote packet: RTMP Audio, size: 94
05-10 12:06:07.625     960-1469/net.ossrs.sea D/WriteThread﹕ WriteThread: waiting...
05-10 12:06:07.645     960-1469/net.ossrs.sea D/WriteThread﹕ WriteThread: wrote packet: RTMP Audio, size: 93
05-10 12:06:07.645     960-1469/net.ossrs.sea D/WriteThread﹕ WriteThread: waiting...
05-10 12:06:07.645     960-1469/net.ossrs.sea D/WriteThread﹕ WriteThread: wrote packet: RTMP Audio, size: 96
05-10 12:06:07.645     960-1469/net.ossrs.sea D/WriteThread﹕ WriteThread: waiting...
05-10 12:06:07.685     960-1469/net.ossrs.sea D/WriteThread﹕ WriteThread: wrote packet: RTMP Audio, size: 92
05-10 12:06:07.685     960-1469/net.ossrs.sea D/WriteThread﹕ WriteThread: waiting...
05-10 12:06:07.695     960-1469/net.ossrs.sea D/WriteThread﹕ WriteThread: wrote packet: RTMP Video, size: 2456

**Comment by begeekmyfriend** [comment]
The log is normal. yasea is uploading both AV streams to the server.

If you are looking for business version, I recommend
[BravoMediaServer](https://github.com/ossrs/srs/wiki/BravoMediaServer) maintained by [chnvideo](http://www.chnvideo.com/) where the author of SRS takes office.
[Nimble Streamer](https://wmspanel.com/nimble) maintained by a Russian company.

**Comment by satyamub** [comment]
If yasea is uploading then why its not showing the frames anywhere. I am sure the server is working correctly because its working good with iOS version encoder. Can you help me tracking the issue. Any help would be appreciated.

**Comment by begeekmyfriend** [comment]
You mean FMS? It is good for my environment. I have no idea about its configuration though. I advice you to consult the server staff. So far yasea has been tested on FMS, Wowza, Ngnix-RTMP, SRS, Red5 and Nimble Streamer.

**Comment by satyamub** [comment]
@begeekmyfriend can you please let me know some configuration which needs to be changed like you must have FMS configurations

**Comment by begeekmyfriend** [comment]
Send your `/opt/adobe/fms/conf` to my email.

**Comment by satyamub** [comment]
okay one more thing is that I want to show the user the preview screen upfront before publish. I have tried to do that however I am not able to show that preview before. I even tried to call setonclicklistener programatically to start the publish process from oncreate still its not opening the preview screen. Please help.

**Comment by begeekmyfriend** [comment]
You mean preview YUV data or h.264/AAC data? Data just from the surface or after preprocessing before publishing?

**Comment by satyamub** [comment]
"data just from the surface" to show the user that broadcast will be started if you click on "Publish".

**Comment by satyamub** [comment]
Just camera preview and then when the user click on publish, the ramp push should start!!

**Comment by begeekmyfriend** [comment]
You may control this [chunk](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/sea/MainActivity.java#L356-L366) just to preview and not to publish at the beginning. Note that do NOT enable [mEncoder](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/sea/MainActivity.java#L294-L306) at preview callback. You had better do it yourself since other guys might not hold the same idea, good luck.

**Comment by satyamub** [comment]
I put this below code in concrete however this does not make the preview

       startCamera();

        aworker = new Thread(new Runnable() {
            @Override
            public void run() {
                android.os.Process.setThreadPriority(android.os.Process.THREAD_PRIORITY_AUDIO);
                startAudio();
            }
        });
        aloop = true;
        aworker.start();

**Comment by begeekmyfriend** [comment]
Then just comment out [this](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/sea/MainActivity.java#L295) and [that](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/sea/MainActivity.java#L305)

**Comment by satyamub** [comment]
no my friend still no luck.. Still I am not getting the preview... in fact onpreviewFrame is not getting called

**Comment by begeekmyfriend** [comment]
Do nothing but just comment out these two lines.

**Comment by satyamub** [comment]
@begeekmyfriend  I got the preview and I will send the con file very shortly to your email.
Please do something for YUVtransformation or tell me the way to stop the preview rotation.

**Comment by satyamub** [comment]
Hi @begeekmyfriend ... as FMS is converted into AMS so yeah.. which file you want to see inside "conf" let me know.
