### ISSUE TITLE
SocketException while stop publish

### ISSUE THREAD

**Issue by fifa1016** [begeekmyfriend/yasea#114]
add an if statement can avoid this exception.

WriteThread.java

line 65:
              **if( active ) {** //// add this
                    out.flush();
                **}**
            } catch (SocketException se) {
                Log.e(TAG, "WriteThread: Caught SocketException during write loop, shutting down: " + se.getMessage());
                Thread.getDefaultUncaughtExceptionHandler().uncaughtException(this, se);
                active = false;
                continue;

**Comment by begeekmyfriend** [comment]
I have optimized the writer thread :) https://github.com/begeekmyfriend/yasea/commit/b1f35ffe89875279b91faa9c19d1ae6074457dbc

**Comment by fifa1016** [comment]
Good job

**Comment by fifa1016** [comment]
And don't forget the GPUIMAGE branch!

**Comment by begeekmyfriend** [comment]
Done https://github.com/begeekmyfriend/yasea/commit/638df0209c193e0a9343e496829a8e6674d259d5
