### ISSUE TITLE
A better choice to open AudioRecord

### ISSUE THREAD

**Issue by fifa1016** [begeekmyfriend/yasea#115]
No sound recorded on some devices,  here's the solution.

=========================SrsPublisher.java=========================
   private void startAudio() {
        if (mic != null) {
            return;
        }

        //wyx add {
//int bufferSize = 2 * AudioRecord.getMinBufferSize(SrsEncoder.ASAMPLERATE, SrsEncoder.ACHANNEL, AudioFormat.ENCODING_PCM_16BIT);
//mic = new AudioRecord(MediaRecorder.AudioSource.MIC, SrsEncoder.ASAMPLERATE, SrsEncoder.ACHANNEL, AudioFormat.ENCODING_PCM_16BIT, bufferSize);
        **mic = AudioHelper.findAudioRecord();**
        //}
        mic.startRecording();

==========================AudioHelper.java===========================
import android.content.Context;
import android.media.AudioFormat;
import android.media.AudioManager;
import android.media.AudioRecord;
import android.media.MediaRecorder;
import android.util.Log;

public class AudioHelper {
    private static final String TAG = "AudioHelper";

    /**
     * @param context
     * @return true if mute
     */
    public static boolean switchMute(Context context) {
        AudioManager audioManager;
        audioManager = (AudioManager) context.getSystemService(Context.AUDIO_SERVICE);

        int oldMode = audioManager.getMode();
        audioManager.setMode(AudioManager.MODE_IN_COMMUNICATION);
        boolean isMute = !audioManager.isMicrophoneMute();
        audioManager.setMicrophoneMute(isMute);
        audioManager.setMode(oldMode);

        return isMute;
    }

    private static int[] SAMPLE_RATES = new int[]{44100, 22050, 11025, 8000};
    private static short[] ENCODINGS = new short[]{AudioFormat.ENCODING_PCM_16BIT, AudioFormat.ENCODING_PCM_8BIT};
    private static short[] CHANNELS = new short[]{AudioFormat.CHANNEL_IN_STEREO, AudioFormat.CHANNEL_IN_MONO};

    public static AudioRecord findAudioRecord() {

        for (int rate : SAMPLE_RATES) {
            for (short encoding : ENCODINGS) {
                for (short channelConfig : CHANNELS) {
                    try {
                        Log.d(TAG, "Attempting rate " + rate + "Hz, bits: " + encoding + ", channel: "
                                + channelConfig);
                        int bufferSize = AudioRecord.getMinBufferSize(rate, channelConfig, encoding);

                        if (bufferSize != AudioRecord.ERROR_BAD_VALUE) {
                            // check if we can instantiate and have a success
                            AudioRecord recorder = new AudioRecord(MediaRecorder.AudioSource.DEFAULT, rate, channelConfig, encoding, bufferSize);

                            if (recorder.getState() == AudioRecord.STATE_INITIALIZED)
                                return recorder;
                        }
                    } catch (Exception e) {
                        Log.e(TAG, rate + "Exception, keep trying.", e);
                    }
                }
            }
        }
        return null;
    }

}

**Comment by begeekmyfriend** [comment]
Thank you for your advice :) https://github.com/begeekmyfriend/yasea/commit/6b0ed2bb348dd1624f925f0d0e103521220973fc
