### ISSUE TITLE
软编，停止推流奔溃

### ISSUE THREAD

**Issue by gzsll** [begeekmyfriend/yasea#116]

**Comment by gzsll** [comment]
要推流一段时间之后停止才会出现~大概一两分钟

**Comment by begeekmyfriend** [comment]
1、拉最新的版本；
2、还出现问题，请把错误log发上来；
**上报issue请把问题描述完整，谢谢！**

**Comment by gzsll** [comment]
软编，是ndk出现错误的~ 
Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc464 in tid 5126
是最新版本

**Comment by gzsll** [comment]
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc464
Stack frame #00 pc 00018464  /lib/arm/libenc.so (x264_encoder_encode+36): Routine x264_encoder_encode at libgcc2.c:?

**Comment by begeekmyfriend** [comment]
你怎么构建项目的？还是直接so拿来用（注意是`armeabi-v7a`），另外把奔溃前的一段log贴一下，再详细点

**Comment by gzsll** [comment]
09-08 10:29:03.126 8500-8500/com.gzsll.app I/libx264: frame :-1630136152 Avg QP:-0.00  size:    -0
09-08 10:29:03.126 8500-8500/com.gzsll.app I/libx264: frame :-1630136152 Avg QP:-0.00  size:    -0
09-08 10:29:03.126 8500-8500/com.gzsll.app I/libx264: mb I  P�̾��p-�F@
09-08 10:29:03.126 8500-8500/com.gzsll.app I/libx264: mb P  P�̾iI�@�M@  P16..4:  0.0% -0.0% -0.0%  0.0% -0.0%    skip:-0.0%
09-08 10:29:03.126 8500-8500/com.gzsll.app I/libx264: final ratefactor: -0.00
09-08 10:29:03.126 8500-8500/com.gzsll.app I/libx264: coded y,p��x��,p@-�`��P�� intra: -0.0% -0.0% 0.0%(null)
09-08 10:29:03.126 8500-8500/com.gzsll.app I/libx264: i16 v,h,dc,p:  0% -0% -0%  0%
09-08 10:29:03.126 8500-8500/com.gzsll.app I/libx264: i-1093878764 v,h,dc,ddl,ddr,vr,hd,vl,hu: -0% -0% -0% -0% -0%  0% 21% 16% 29%
09-08 10:29:03.126 8500-8500/com.gzsll.app I/libx264: i8c dc,h,v,p:  0% -0% -0%  0%
09-08 10:29:03.127 8500-8500/com.gzsll.app I/libx264: kb/s:0.00
09-08 10:29:03.132 8500-8500/com.gzsll.app I/SrsFlvMuxer: worker: disconnect SRS ok.
09-08 10:29:03.133 8500-8500/com.gzsll.app I/SrsFlvMuxer: SrsFlvMuxer closed
09-08 10:29:03.144 8500-3728/com.gzsll.app D/RtmpConnection: wrote packet: RTMP Audio, size: 94
09-08 10:29:03.145 8500-3728/com.gzsll.app D/RtmpConnection: wrote packet: RTMP Audio, size: 93
09-08 10:29:03.175 8500-8500/com.gzsll.app A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc464 in tid 8500 (om.ubnt.frl.app)
09-08 10:29:03.194 8500-3728/com.gzsll.app D/RtmpConnection: wrote packet: RTMP Audio, size: 96

**Comment by gzsll** [comment]
bogon:FRLocal Sam$ adb logcat |  ndk-stack -sym /Users/Sam/workspace/Local/yasea/src/main/libenc/obj/local/armeabi-v7a
********** Crash dump: **********
Build fingerprint: 'Xiaomi/aries/aries:6.0.1/MMB29M/6.3.22:userdebug/test-keys'
pid: 4187, tid: 4187, name: om.gzsll.app  >>> com.gzsll.app <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc464
Stack frame #00 pc 00018464  /data/app/com.gzsll.app-1/lib/arm/libenc.so (x264_encoder_encode+36)
Crash dump is completed

**Comment by begeekmyfriend** [comment]
实在无法复现您所说的问题，我前几天刚解决了一个软编码长时间bug #94 人家也没说几分钟之内就crash的，建议检查一下CPU型号是否`armeabi-v7a`

**Comment by gzsll** [comment]
是调用stopPublish后奔溃的~

**Comment by begeekmyfriend** [comment]
那也没复现啊

**Comment by gzsll** [comment]
昨天一直会出现，今天偶尔会出现~我再看看，能不能把堆栈日志打出来
