### ISSUE TITLE
修改采样率为什么没有声音了？

### ISSUE THREAD

**Issue by Mrgao9** [begeekmyfriend/yasea#117]
我想降低采样率，将它修改为 22050, 11025, 8000都不能出现声音，只有44100时正常，请问为什么将采样率降低了就没有声音了呢？是不是还需要在哪里修改呢？谢谢！

**Comment by begeekmyfriend** [comment]
Please check the comment on `AudioRecord` SDK constructor method source.
> 44100Hz is currently the only  rate that is guaranteed to work on all devices, but other rates such as 22050, 16000, and 11025 may work on some devices.

**Comment by Mrgao9** [comment]
谢谢，这个我阅读过，之前做的一个直播系统在同一Android设备下使用8000采样率也是可以的，现在将您的项目中的采样率改为8000或者其他规格采样率，都不能出现声音

**Comment by Mrgao9** [comment]
请问如果修改，只修改ASAMPLERATE这个变量就行了吗？其他的还要修改吗？

**Comment by begeekmyfriend** [comment]
你搜一下44100的所有地方

**Comment by Mrgao9** [comment]
恩恩，已经成功了，谢谢您！
