### ISSUE TITLE
frameCache.isEmpty() 

### ISSUE THREAD

**Issue by iSinch** [begeekmyfriend/yasea#118]
Hey )
Why `frameCache.isEmpty()` when startPublish in landscape ?
when in portrait - is ok

**Comment by begeekmyfriend** [comment]
Impossible.

**Comment by iSinch** [comment]
![image](https://cloud.githubusercontent.com/assets/13470331/18345278/730ea56c-75c3-11e6-9ba7-a420a33f42a5.png)

**Comment by begeekmyfriend** [comment]
You seem to modify the original code. Fetch the latest version and try again please.
