### ISSUE TITLE
Whether the libyuv  need update ?

### ISSUE THREAD

**Issue by zondaOf2012** [begeekmyfriend/yasea#121]
When APP_ABI is mips , ndk-build libyuv  compilation  fail.

**Comment by wenjue** [comment]
add the code 

![image](https://cloud.githubusercontent.com/assets/8158063/18622300/cb566742-7e5f-11e6-98df-91f0adec79db.png)

to [libyuv/Android.mk](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/libenc/jni/libyuv/jni/Android.mk#L56)

**Comment by begeekmyfriend** [comment]
@wenjue Thank you. I have picked up a bargain:-D

**Comment by wenjue** [comment]
@begeekmyfriend You're welcome!
