### ISSUE TITLE
录制视频问题

### ISSUE THREAD

**Issue by Jack1103** [begeekmyfriend/yasea#122]
我在推流的时候想录制视频，简单的录制没有问题，但我想在点击录制前一段时间就开始，所以我另起了一个ConcurrentLinkedQueue<SrsEsFrame> reFrameCache ，当未录制的时候，就进行FIFO操作，但保证队列里有两个KeyFrame，每一个关键帧的间隔大概是3秒，那么我就达到预录3-6秒的功能，当设备点击录制后，我就去掉它自带的FIFO，而是将这个队列上的数据poll放frameCache，record将对子操作。demo代码如下：
        if (bRecording && !bPaused) {
            keyFrameNum = 0;
            SrsEsFrame ft = reFrameCache.poll();
            if(!reFrameCache.isEmpty()){
                if(needToFindKeyFrame){
                    if(ft.isKeyFrame){
                        frameCache.add(ft);
                        needToFindKeyFrame = false;
                        synchronized (writeLock) {
                            writeLock.notifyAll();
                        }
                    }
                }else{
                    frameCache.add(ft);
                    synchronized (writeLock) {
                        writeLock.notifyAll();
                    }
                }
            }
        }

```
    if (true) {
        if (frame.isKeyFrame) {
            if (keyFrameNum < 4) {
                keyFrameNum++;
            }
            reFrameCache.add(frame);
        } else {
            reFrameCache.add(frame);
        }
    }
    if(keyFrameNum>3){
        reFrameCache.poll();
    }
```

但是，在效果上并没有我想要的效果，而是正常录制，而且还存在花屏。请问前辈能给我提点建议吗？

**Comment by begeekmyfriend** [comment]
1、不录制不要放进FIFO，直接丢；
2、录制的话FIFO第一帧必须是关键帧。

**Comment by Jack1103** [comment]
我的意思是想预录制，就是录制起点是触发前几秒，我可以保证第一帧是IDR，没录制的时候就FIFO的意思就是保证有缓存一段帧数据，相当于定长的队列，开始录制的起点就是缓存这段帧的第一个关键帧，这样录制的起点不就在我触发之前了，但效果没达到，但我觉得逻辑没问题，您帮我指导下，谢谢。

**Comment by begeekmyfriend** [comment]
**你的逻辑是对的，**但我无法帮你debug，只能靠你自己。

**Comment by Jack1103** [comment]
那你帮我看一下我上面的代码，有问题吗？

**Comment by Jack1103** [comment]
嗯，能不能是因为每一帧的间隔不一样，导致我们录制视频花屏呢？不过也应有预录的视频呀，不过目前是直接没有预录，还花屏。线程的问题也不应该呀，有点蒙蔽，我再研究下我的场景

**Comment by Jack1103** [comment]
我再问一个问题，对推流加水印在你源码的基础上是否可行？

**Comment by Jack1103** [comment]
不应该是水印，是时间挫到视频右上角
