### ISSUE TITLE
Low Fps 

### ISSUE THREAD

**Issue by developeralp** [begeekmyfriend/yasea#126]
How can i increase fps ?

Changing preview or output sizes  , but how  ?

I am using MTK motherboard..

I am getting 8-9-10 fps :(

Mine preview size : 1280:720
Mine output size : 960:704

**Comment by begeekmyfriend** [comment]
I said it

**Comment by developeralp** [comment]
What do you think about Qualcomm Snapdragon 617 MSM8952 chipset ? 

Is Qualcomm chipsets is suitable for live streaming via this library ?

**Comment by developeralp** [comment]
@begeekmyfriend ?

**Comment by pokipc** [comment]
sorry, what did you said?
how to increase FPS or FPS will remain low?

thanks

**Comment by begeekmyfriend** [comment]
@pokipc Buy a better phone.

**Comment by pokipc** [comment]
:-)
Its actually not from a phone.
It is from Android box Amlogic S802 x8 GPU...

should i use ultrafast instead of superfast?
maybe another change for the encoder setup?

**Comment by begeekmyfriend** [comment]
Android box? Well, I have no idea about that...

But I tell you if you are using hard encoding, the preset of x264 makes no sense. And in fact soft encoding works no better than the hard.

**Comment by developeralp** [comment]
I tried this way to increase fps ,

Changing output preview ; 1280 * 720 to 640*480

But only 4-5 fps increased :/

MTK MT6589 : 8-9 fps
Qualcomm Snapdragon 617 MSM8952 : 14-15 fps..

**Comment by pokipc** [comment]
i think we need to find a way to have some initial rtmp frames in a buffer (let say, of about 10 seconds) and only then start the rtmp transmission. 
in that way, we will have more fps as the encoder will fill the buffer all the time and the rtmp server will not "feel" the delay.
what do you think?

**Comment by begeekmyfriend** [comment]
@pokipc Do you want high latency?

**Comment by pokipc** [comment]
im quite sure. from the server point of view, it is like you just started several second later the stream. if you are not seeing both sides at the same time (camera and server), you dont know that there is delay.
but for us, within the app, it gives option to handle the frames in fixed frequency (or close to it)
