### ISSUE TITLE
Some bugs:

### ISSUE THREAD

**Issue by fifa1016** [begeekmyfriend/yasea#127]
gpuimage branch

--------------------SrsCameraView.java--------------------------

public int startCamera(){
    ....
    **return 1;** //forget this line
}
---------------------SrsPublisher.java----------------------------

public class SrsPublisher {
    // private static Context mContext; // static activity may leak
    **private static WeakReference\<Context\> mContext;**  // a better choice?

**Comment by begeekmyfriend** [comment]
Fixed https://github.com/begeekmyfriend/yasea/commit/805093d63eae9c5502593760dc6fbdb0dfaeeddb
I do not think `WeakReference` seems to be necessary for `mContext` has already been static type.

**Comment by fifa1016** [comment]
-----------------------SrsCameraView.java----------------------
//MagicFilterFactory.initFilters(type);

**MagicFilterFactory.initFilters(getContext(), type);**
------end---------
I found only FilterFactory use SrsPublisher.mContext,  so  just pass context here,  and make mContext in SrsPublisher non static.
How about this?

**Comment by begeekmyfriend** [comment]
Done https://github.com/begeekmyfriend/yasea/commit/7fc877bff9f6b104b9f9139206e80b57e641a4db

**Comment by fifa1016** [comment]
这个没看懂.  MagicFilterFactory里面的Context还是static的,   如果传一个activity进来, 在acitivy生命周期结束之后,这个static对其的引用还在. 还是会造成泄露的吧.

刚才查了下,http://blog.csdn.net/lmj623565791/article/details/40481055
后面对context的使用是getResource, 可以传递Application Context进来

public class MagicFilterFactory{
	
	private static MagicFilterType filterType = MagicFilterType.NONE;

	private static Context mContext;

	public static void initContext(Context context) {
		//mContext = context;
		**mContext = context.getApplicationContext();**
	}
...
}

这样在初始化的时候强制赋值ApplicationContext,可防止第三方使用时造成泄露的问题.

**Comment by begeekmyfriend** [comment]
我用的不是`Activity`的context，而是`GLSurfaceView`的getContext()方法获取的。不过你说的很有道理，任何UI相关的context不宜被**生命周期为程序的对象**引用，所以引用应该通过`getApplicationContext()`方法获取引用https://github.com/begeekmyfriend/yasea/commit/23953cb2c44b938bacc645442b054d03ad476862
