### ISSUE TITLE
添加Codec 

### ISSUE THREAD

**Issue by Jack1103** [begeekmyfriend/yasea#128]
博主你好，我这边为了减少回音想增加speex codec，能提供一点帮助吗？

**Comment by begeekmyfriend** [comment]
不光是推流端要弄，还有拉流端解码配合起来的

**Comment by Jack1103** [comment]
拉流是没问题的，推流这边我应该怎么做，能给点建议或者方案吗？

**Comment by banketree** [comment]
可以参考Sip的解决方案

**Comment by notedit** [comment]
https://github.com/dakatso/SpeexExample

**Comment by notedit** [comment]
网上有很多实现  善用google

**Comment by begeekmyfriend** [comment]
AEC and AGC are now provided in master branch by Android SDK.
