### ISSUE TITLE
有关美颜

### ISSUE THREAD

**Issue by ameisewang** [begeekmyfriend/yasea#130]
我想在yasea的基础上做美颜效果，但不知如何入手。这里我看到您在MagicCamera的留言，了解到您也在做这方面的事情，请教下：
1.美颜要用到GLSurfaceView，之前的推流可以在onPreviewFrame这里获取数据，那么经过了opengl的处理后的数据，需要怎样才可获得？
2.magiccamera是怎样结合到现有的yasea上的？

**Comment by begeekmyfriend** [comment]
See branch `gpuimage`

**Comment by ameisewang** [comment]
非常感谢您的回复。我也看过MagicCamera的部分代码，里面核心部分采用的是gpuimage。我现在有个疑惑是在经过opengl渲染后的数据怎样才能获得到？我的思路是在onPreviewFrame里面获得数据，将其传递给GLSurfaceView，经过其渲染展现。然后再想办法隐藏掉surfaceview。不过仍然是渲染后的数据怎么才能获得的问题，只有获得到了这部分数据才好继续进行编码和rtmp推流。
还望不吝赐教，谢谢！

**Comment by ameisewang** [comment]
我对直播推流接触时日尚短，对于美颜的部分，我的理解是直接推送美颜过的数据，不知是否正确。当然也可推送原始采集数据后由播放端进行美颜呈现，或者在服务器进行滤镜处理，这样至少保证服务器有原始的采集数据。不知真正的直播美颜是采用的哪种方式？

**Comment by begeekmyfriend** [comment]
说了这么多猜测，你跑过程序吗？

**Comment by kongdeming** [comment]
支持大牛集成美颜

**Comment by wooden1985** [comment]
https://github.com/lakeinchina/librestreaming 这个东西不错

**Comment by ameisewang** [comment]
@wooden1985 谢谢，之前已经找到这个了。

**Comment by begeekmyfriend** [comment]
Now supported
