### ISSUE TITLE
Output Video Error ?

### ISSUE THREAD

**Issue by developeralp** [begeekmyfriend/yasea#135]
Hello all,

I'm using some methods to calculate and select best preview / output size on startCamera() method , that methods works like charm in stable v1.3 .. but not latest version .. 

Orientation : portrait
My preview size : 1280 - 720 
My output size : 960 - 704 

If i use 640 - 480 for preview and 384 - 640 for output it works but how can i choose other sizes ?

So , my output looks in windows /vlc player : (I tried other players too , nothing changes)
![output](https://cloud.githubusercontent.com/assets/22075871/18580015/c1e379a8-7c01-11e6-8edd-2121bea5a922.png)

What i am doing wrong ? 
What is the correct way set preview/output size for SrsCameraView ?

**Comment by begeekmyfriend** [comment]
[MediaCodec CTS](https://android.googlesource.com/platform/cts/+/kitkat-release/tests/tests/media/src/android/media/cts/EncodeDecodeTest.java#244)

**Comment by begeekmyfriend** [comment]
Otherwise you may try soft encoding.

**Comment by developeralp** [comment]
Don't understand first answer.
Tried soft encoding but nothing changed :(

**Comment by developeralp** [comment]
Edit : tried with 608-1280 it worked..

**Comment by begeekmyfriend** [comment]
960x704 should be landscape mode.

**Comment by begeekmyfriend** [comment]
OK, my fault https://github.com/begeekmyfriend/yasea/commit/4b6089158cae96398f5d41853770c1d206419a57

**Comment by developeralp** [comment]
Thanks , trying now
