### ISSUE TITLE
FPS比较低的简单理解

### ISSUE THREAD

**Issue by bigbao9494** [begeekmyfriend/yasea#137]
你好，看过之前关于FPS低的讨论，自己也做了一个简单的测试。
如果注释掉：mEncoder.onGetYuvFrame(data);
只测试onPreviewFrame的回调，在我的MX3手机上的FPS是大概 20
如果加上mEncoder.onGetYuvFrame(data);
MX3手机上的FPS大概是 10
编码肯定要花一些时间，但是只回调也只有20，是否是Camera的问题呢？
在测试的时候我打开CPU使用率看没有增大，这说明也不是CPU的瓶颈。
我在windows上用directShow做类似的回调测试FPS也是比较低的，
是否有其它非回调的方式呢？

    private void onGetYuvFrame(byte[] data) {
        // Calculate YUV sampling FPS
        if (videoFrameCount == 0) {
            lastTimeMillis = System.nanoTime() / 1000000;
            videoFrameCount++;
        } else {
            if (++videoFrameCount >= 48) {
                long diffTimeMillis = System.nanoTime() / 1000000 - lastTimeMillis;
                mSamplingFps = (double) videoFrameCount * 1000 / diffTimeMillis;
                videoFrameCount = 0;
            }
        }
        mEncoder.onGetYuvFrame(data);
    }

**Comment by begeekmyfriend** [comment]
Buy a better phone.
