### ISSUE TITLE
Application hangs when stopping publishing.

### ISSUE THREAD

**Issue by dyckster** [begeekmyfriend/yasea#139]
When i press "Stop" button application hangs and there is nothing special in the logcat.

Last lines before hang:
`I/SrsEncoder: stop aencoder
I/SrsEncoder: stop vencoder
D/RtmpConnection: closeStream(): setting current stream ID to -1
D/RtmpConnection: wrote packet: RTMP Command (command: closeStream, transaction ID: 0), size: 24
D/AndroidRuntime: Shutting down VM
Application terminated.`

Also there is no audio output.
Tested on Motorola Nexus 6, Android 7.0 DP5 #

**Comment by begeekmyfriend** [comment]
Did you clone the latest version?

**Comment by dyckster** [comment]
Yes. I restarted my phone and it stopped succesfully for the first time. After that it hangs again. Log is mor informative now though: 
`- I/SrsEncoder: stop aencoder

 I/SrsEncoder: stop vencoder

D/RtmpConnection: closeStream(): setting current stream ID to -1

D/RtmpConnection: wrote packet: RTMP Command (command: closeStream, transaction ID: 0), size: 24

 D/AndroidRuntime: Shutting down VM

D/RtmpConnection: closeStream(): setting current stream ID to -1

D/RtmpConnection: wrote packet: RTMP Command (command: closeStream, transaction ID: 0), size: 24

 I/art: Starting a blocking GC HeapTrim

I/art: Debugger is no longer active

I/art: Starting a blocking GC Instrumentation

D/RtmpDecoder: readPacket(): header.messageType: USER_CONTROL_MESSAGE

D/RtmpConnection: handleRxPacketLoop(): Sending PONG reply..

D/RtmpConnection: wrote packet: RTMP User Control (type: PONG_REPLY, event data: [I@c33ed2e), 
size: 6

D/RtmpDecoder: readPacket(): header.messageType: COMMAND_AMF0

 D/RtmpDecoder: readPacket(): header.messageType: USER_CONTROL_MESSAGE

D/RtmpConnection: handleRxPacketLoop(): Sending PONG reply..

 D/RtmpConnection: wrote packet: RTMP User Control (type: PONG_REPLY, event data: [I@3f430cf), size: 6
`

**Comment by dyckster** [comment]
Also, is it possible to contact you somewhere for more questions?

**Comment by begeekmyfriend** [comment]
Fixed https://github.com/begeekmyfriend/yasea/commit/e6ae2328768119ef2872f85f1509f171f4fbf365

**Comment by begeekmyfriend** [comment]
Thank you for your report https://github.com/begeekmyfriend/yasea/commit/d386260dd5ce36667fef589e0058833566f4dda5

**Comment by dyckster** [comment]
@begeekmyfriend  I pulled latest version and stop button works now. Thanks!
