### ISSUE TITLE
support with android 4.xxx

### ISSUE THREAD

**Issue by friman** [begeekmyfriend/yasea#14]
Hello guys
I have tested this app on android 4.4 and send only audio, is there some way to get video properly?

Thanks on advance

**Comment by begeekmyfriend** [comment]
I am afraid I do not get your point exactly, did you have the permission to open your camera? Or what is your server? Are you using nginx-rtmp?

**Comment by friman** [comment]
Hi, thanks for your reply.
Yes, camera has whole permission and i am using nginx. Is there nginx limitation?

**Comment by begeekmyfriend** [comment]
@gouravd and @fly518420 have the same issue as yours. #9 is similar with this case. And I have built nginx-rtmp myself and it reappeared. I have to say it is an issue of nginx-rtmp and it does not always occur though. In fact, you will see the video if you wait 10 minutes or even longer.

Yasea has been tested on servers including FMS, SRS and [Nimble Streamer](https://wmspanel.com/nimble) as peer. It is all right watching both video and audio on player.

You may see the [master branch](https://github.com/arut/nginx-rtmp-module) of nginx-rtmp on github. And you will find the latest commit is 2 more years ago. As for an open project, in my opinion (the same as that of the author of SRS), it is sentenced to death. I do not think yasea should be responsible for it.

**Comment by friman** [comment]
Thanks for reply.
I leave nginx and now trying with wowza, it have large delay to display image on vlc, I means, on vlc load audio and after 1 min show video, using jwplayer or flowplayer do not get video playback, something is wrong in my side? it there some fix to do or that is wowza issue?

**Comment by begeekmyfriend** [comment]
It is strange, I have not tested on Wowza yet. Maybe yasea has not provided metadata such as resolution or frame rate in `onMetaData` function yet. https://github.com/begeekmyfriend/yasea/commit/b5e39cb218520713b9316611433dda76c59cd694 which may be needed by Wowza. I am not sure whatever.

Currently it is OK for FMS and SRS and Nimble Streamer.

**Comment by begeekmyfriend** [comment]
I have opened a new branch for your issue https://github.com/begeekmyfriend/yasea/tree/wowza in which I have added `onMetaData` function on publishing. You had better have a try on Wowza.

**Comment by friman** [comment]
I got your idea, but now another issue, it doesnot connect with any rtmp server, no only wowza, also yours. I am not able to debug, that is way I am little lost.

**Comment by friman** [comment]
One poin more is wowza or AMS authentication, any combination like 

rtmp://server1/live/app2 
flashver=FMLE/3.0\20(compatible;\20FMSc/1.0) live=true pubUser='user' 
pubPasswd='1234' playpath=test"
or
rtmp://test:test@server1/live/app2 
or
rtmp://server1/live/app2?user=user&passwdor=1234"

is not allowed due validation and options to pass these parameters. Is there some exit for it?

**Comment by begeekmyfriend** [comment]
I apologize for my carelessness https://github.com/begeekmyfriend/yasea/commit/f8dc9ba8713293368e4c394acc6e126d7e38b148

**Comment by friman** [comment]
Thank you! now it work, just my second question is still opened on my mind, how can get authentication on rtmp server if for example, follow those ffmpeg command with authentication:

rtmp://server1/live/app2 
flashver=FMLE/3.0\20(compatible;\20FMSc/1.0) live=true pubUser='user' 
pubPasswd='1234' playpath=test"
or
rtmp://test:test@server1/live/app2 
or
rtmp://server1/live/app2?user=user&passwdor=1234"

**Comment by begeekmyfriend** [comment]
Do you mean it is all right on Wowza now?

I need some research on authentication of RTMP server.

**Comment by friman** [comment]
Yes, I am getting playback on wowza now, is not like with other servers (like testing with yours for example), but at least display. 
Is ok, i will preciate if you can help me with this authentication part.
Thanks

**Comment by friman** [comment]
Well, now is failing on Table KITKAT 4.4.2, is some lib no compatible with this android version?

**Comment by friman** [comment]
Audio only when send to wowza

**Comment by begeekmyfriend** [comment]
I have mistaken the measurement of `KEY_I_FRAME_INTERVAL` that  the unit is second rather than number of video frames. https://github.com/begeekmyfriend/yasea/commit/0307650290d39f3409668ad5dc62dbcc951bb61e

I have fixed it on branch `master` under latest version. the branch `wowza` has been deleted.

**Comment by begeekmyfriend** [comment]
I have no Table KITKAT 4.4.2 at hand. You may comment out code as follows to sea what kind of exception thrown. https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/sea/MainActivity.java#L184-L198. Or you may debug with Android Studio to find out which statement results in the crash of the application.

**Comment by begeekmyfriend** [comment]
@friman Would you please tell me the color format value on Table KITKAT 4.4.2? Just check this [logging](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/sea/SrsEncoder.java#L512)

**Comment by friman** [comment]
Hi friend,
Just now is when I saw your replies. Well, i have detect some very funny, if I type an rtmp, press start, in this moment it show only audio (tested with jwplayer, flowplayer and desktop vlc player). If I stop and press start again, it display properly on jwplayer and flowplayer (audio & video), on vlc it reproduce very bad resolution, is delayed,...very bad (just for me is not matter)
The stranger is that always when set new rtmp, in first moment show only audio, if stop and start again, it work fine.
Any luck with wowza authentication?

**Comment by friman** [comment]
Ahh, the previous said happened on my tablet 4.4.2 and on samsung phone 4.4.4. With +5 always is ok.

**Comment by begeekmyfriend** [comment]
That is not an issue. We should always change the RTMP address between a previous stop and a next start in actual movement. Yasea is just a demo and exposes input to users.

I am afraid you had better do your own research on Wowza authentication. My next plan is MP4 local recording which is in higher privilege.

As for Table KITKAT 4.4.2, I need its color format logged which can be watched through Android Studio.

**Comment by begeekmyfriend** [comment]
As for color format, soft encoding feature is now added into the latest version.
