### ISSUE TITLE
Unrecognized profile when adding views

### ISSUE THREAD

**Issue by dyckster** [begeekmyfriend/yasea#141]
When I change buttons to other view types like FloatingActionButton or ImageButton app freezes at startup with `W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc` error.

**Comment by dyckster** [comment]
I did more test and so far, thats what I'v found:

It freezes when Floating Action Button, ImageButton or ImageView are present in layout.

Works fine with textviews,editext,button,togglebutton,switch,radio button.

**Comment by begeekmyfriend** [comment]
Maybe the screen cannot render these UI control on camera preview?
