### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by dyckster** [begeekmyfriend/yasea#142]
I am trying to stream to wowza server using this library, but no audio is passing to server. When I record video to device everything is ok. As i checked, wowza supports audio in mp4a-latm format.

What might be the problem?

**Comment by begeekmyfriend** [comment]
no audio is passing to server, you sure?

**Comment by dyckster** [comment]
@begeekmyfriend Yes, though in logcat it writes audio packets normally.

**Comment by begeekmyfriend** [comment]
Then it does nothing with yasea

**Comment by dyckster** [comment]
@begeekmyfriend Thats pretty sad. Thanks anyway, I will be trying to figure it out and inform you if I'd get it working.

**Comment by begeekmyfriend** [comment]
Use [SRS 2.0](https://github.com/ossrs/srs/tree/2.0release)
