### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by mranchon** [begeekmyfriend/yasea#143]
Here is my issue : failed to connect to ossrs.net/182.92.80.26 (port 1935) after 3000ms: isConnected failed: ECONNREFUSED (Connection refused)

I don't understand why I have this error when I want to publish my video.

**Comment by begeekmyfriend** [comment]
ossrs.net has been crashed (may be DDosed). You have to build your own.

**Comment by mranchon** [comment]
Thanks you !
