### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by wooden1985** [begeekmyfriend/yasea#145]
当我把代码集成到我的工程里面 运行的时候报 java.lang.NoSuchMethodError: no static or non-static method "Lnet/ossrs/yasea/SrsEncoder;.openSoftEncoder()Z"

**Comment by begeekmyfriend** [comment]
那是native代码，你有没有集成libenc.so？

**Comment by wooden1985** [comment]
放进去了

**Comment by wooden1985** [comment]
我的工程混淆过

**Comment by wooden1985** [comment]
-keep class net.ossrs.yasea.** { *; } 就好了
