### ISSUE TITLE
横竖屏切换如何改变推流尺寸

### ISSUE THREAD

**Issue by chenyongfu** [begeekmyfriend/yasea#146]
大神你好，推流的时候，手机竖屏，点击publish, 查看到的视频 尺寸假如是 1:3， 
横屏之后，查看到的视频还是这个比例，这时视频宽度明显就被缩放了。
如何修改为横屏与竖屏的比例正好相反？比如竖屏看到的视频是1:3，横屏的时候为3:1
想要的效果就是推流的效果和手机上的预览效果一样，我试着改了部分代码，改不出来，求指导，拜谢

**Comment by begeekmyfriend** [comment]
Pull the latest source.

**Comment by chenyongfu** [comment]
还是不行，我慢慢琢磨吧，谢谢啦

**Comment by begeekmyfriend** [comment]
你到底是预览效果不对，还是播放端效果不对？

**Comment by chenyongfu** [comment]
播放端，横竖屏切换之后就会卡住，服务器用的wowza

**Comment by begeekmyfriend** [comment]
onMetaData那里改一下

**Comment by chenyongfu** [comment]
onMetaData完全听不懂，只有换服务器咯，你用的什么服务器哇？求指导，多谢了

**Comment by chenyongfu** [comment]
按理说应该和服务器无关才好

**Comment by begeekmyfriend** [comment]
[onMetaData]在此，不过需要重连才能发送。服务器我用[srs](https://github.com/ossrs/srs/tree/2.0release)

**Comment by chenyongfu** [comment]
我决定改成只用横屏，横屏已然够用了
这几天研究这个，结果学会了android开发，哈哈哈
