### ISSUE TITLE
For HD (1280 * 720), the software encoder is taking around 60 ms.

### ISSUE THREAD

**Issue by issacjohngad** [begeekmyfriend/yasea#148]
While streaming a High definition video, the encoder is taking around 60 ms for doing the processing. This is reducing the FPS to 12-15. What improvements can we make to reduce this processing delay to get a reasonable FPS of around 25?

**Comment by begeekmyfriend** [comment]
Buy a better phone.

**Comment by begeekmyfriend** [comment]
Like nexus

**Comment by issacjohngad** [comment]
Hi,

We are using an Android Box (ATV1800 Enjoy TV Quad Core Box, Frequency: 2.0GHz
RAM:DDR3-1G). Do you see any other way (other than increasing the device specifications) , we can improve the frame processing time, to achieve a better FPS.

**Comment by begeekmyfriend** [comment]
`MediaCodec` is always better than soft encoding for higher FPS. Unfortunately, good picture quality can influence the output FPS. To improve the it, I think you may try increasing the bit rate as to 1k+bps.
