### ISSUE TITLE
录制视频问题

### ISSUE THREAD

**Issue by Jack1103** [begeekmyfriend/yasea#149]
前段时间忙着项目，最近有时间研究视频录制了，我想要的效果是视频预录，我之前提过Issues，我的想法是对SrsMp4Muxer进行操作，一直回调writeFrameByte进行FIFO写frameCache，保证frameCache有两个keyFrame和若干非关键帧，我通过研究觉得这样能实现预录制2-5秒，当点击录制的时候我结束代码自己的poll，然后继续写frameCache，同时record开启worker，从frameCache的第一个关键帧开始形成视频，这样我觉得就可以实现在点击的时候录制视频从点击前几秒开始了，但事与愿违，根据这个想法改了多次发现产生的视频花屏，请问能提供给我一个思路吗？

**Comment by Jack1103** [comment]
我发现 报了如下异常：
09-23 15:19:31.427 11582-13713/com.dragonfly W/System.err: java.io.IOException: write failed: EFAULT (Bad address)
09-23 15:19:31.427 11582-13713/com.dragonfly W/System.err:     at java.nio.FileChannelImpl.writeImpl(FileChannelImpl.java:503)
09-23 15:19:31.427 11582-13713/com.dragonfly W/System.err:     at java.nio.FileChannelImpl.write(FileChannelImpl.java:480)
09-23 15:19:31.427 11582-13713/com.dragonfly W/System.err:     at net.ossrs.yasea.SrsMp4Muxer.writeSampleData(SrsMp4Muxer.java:863)
09-23 15:19:31.427 11582-13713/com.dragonfly W/System.err:     at net.ossrs.yasea.SrsMp4Muxer.access$300(SrsMp4Muxer.java:62)
09-23 15:19:31.427 11582-13713/com.dragonfly W/System.err:     at net.ossrs.yasea.SrsMp4Muxer$1.run(SrsMp4Muxer.java:152)
09-23 15:19:31.427 11582-13713/com.dragonfly W/System.err:     at java.lang.Thread.run(Thread.java:818)
09-23 15:19:31.427 11582-13713/com.dragonfly W/System.err: Caused by: android.system.ErrnoException: write failed: EFAULT (Bad address)
09-23 15:19:31.427 11582-13713/com.dragonfly W/System.err:     at libcore.io.Posix.writeBytes(Native Method)
09-23 15:19:31.428 11582-13713/com.dragonfly W/System.err:     at libcore.io.Posix.write(Posix.java:261)
09-23 15:19:31.428 11582-13713/com.dragonfly W/System.err:     at libcore.io.BlockGuardOs.write(BlockGuardOs.java:308)
09-23 15:19:31.428 11582-13713/com.dragonfly W/System.err:     at java.nio.FileChannelImpl.writeImpl(FileChannelImpl.java:498)
09-23 15:19:31.428 11582-13713/com.dragonfly W/System.err: 	... 5 more

**Comment by begeekmyfriend** [comment]
首先，你自己改出来的异常别来找我帮你调试。其次，**你怎么保证播放端打开的第一帧一定是关键帧？**

**Comment by JakeRed** [comment]
这个异常我也遇到了，频繁录制视频就有这个异常，怎么保证播放端第一帧我想只要发出去的时候控制住，用该开发者的FIFO队列poll，能保证发出去是第一帧，我也想通过您的代码兴趣性研究下预录制，可是就像该开发者说的，视频没法这样。

**Comment by Jack1103** [comment]
首先我是在推流端实现录制，这样的话一定能保证录制的I帧，我没想让你帮我调试，只是对我的想法提示一下，谢谢！

**Comment by sfz67008629** [comment]
新的版本中能否添加预录功能

**Comment by begeekmyfriend** [comment]
I am not sure if https://github.com/begeekmyfriend/yasea/commit/f185b820cb5f2f5e2e3b8c3a11ddb2f851822a79 would work for you?

**Comment by begeekmyfriend** [comment]
想来想去，估计也就`sps`和`pps`没设置好吧
