### ISSUE TITLE
断线重连问题

### ISSUE THREAD

**Issue by FIAL413X** [begeekmyfriend/yasea#150]
能否支持断线重连，目前我测试把网络断开，再连接上网络，没办法自动重连

**Comment by begeekmyfriend** [comment]
自己写一个呗，你应该熟悉`SrsPublisher`的接口

**Comment by Jack1103** [comment]
题主，我写了一个网络监听，在断网的时候停止推流，但不停止录制视频，数据依然在，网络恢复后我重新推流，但是推不上去，我能保证数据流write_h264_sps_pps，异常错误为Unexpected EOF reached before read buffer was filled。

请问题主实现了断线重连了吗？

**Comment by FIAL413X** [comment]
没有实现断线重连，我这边主要是服务端的问题，我们现在用的推流服务器不支持同一个流再次重连，你应该需要在网络断开的时候stop推流线程，网络连接上之后重新去connect并且publish，如果服务器不拒绝，应该是可以的

**Comment by begeekmyfriend** [comment]
这种涉及到具体业务层面的东西不能贸然实现，所以留给用户自定义
