### ISSUE TITLE
请教一个关于声音的问题

### ISSUE THREAD

**Issue by fly518420** [begeekmyfriend/yasea#151]
我推流
使用VLC 和 ffplay 还有APP内部ijk播放都有声音
但是使用 PC （flash） 和 手机web (H5)播放都没有声音，你了解大概是什么问题吗？

**Comment by begeekmyfriend** [comment]
可能格式不支持吧

**Comment by begeekmyfriend** [comment]
Sorry. Fixed https://github.com/begeekmyfriend/yasea/commit/ad6eadefca7fa5c0fb8082f4c685b83128577992 and https://github.com/begeekmyfriend/yasea/commit/be200b1bc61376dc22ba8c69acbb2ac4c4a17a6d
