### ISSUE TITLE
Starting Camera Preview onCreate ?

### ISSUE THREAD

**Issue by developeralp** [begeekmyfriend/yasea#152]
Hello all,

I followed that methods for starting camera preview onCreate : https://github.com/begeekmyfriend/yasea/issues/90

It works great with older versions (i.e stable 1.3)

How can i make that work with latest versions ?

**Comment by developeralp** [comment]
any ideas ?

**Comment by begeekmyfriend** [comment]
https://github.com/begeekmyfriend/yasea/commit/f185b820cb5f2f5e2e3b8c3a11ddb2f851822a79
