### ISSUE TITLE
Question About MediaCodec Class...

### ISSUE THREAD

**Issue by developeralp** [begeekmyfriend/yasea#153]
Hi,

I heard , on Android API 18+ MediaCodec class can connect camera's surface view to encoder.
(http://stackoverflow.com/questions/13458289/encoding-h-264-from-camera-with-android-mediacodec)

Can we use MediaCodec class with Yasea and publish RTMP with it ?

If answer yes , is MediaCodec effects fps and app performance ?

**Comment by begeekmyfriend** [comment]
Yasea is aimed to API 16.

**Comment by developeralp** [comment]
Ok , but any ideas how to use MediaCodec or other new encoders use with Yasea ? (for api 18+)

**Comment by notedit** [comment]
Yasea supports Mediacodec.

**Comment by begeekmyfriend** [comment]
DIY
