### ISSUE TITLE
Watching Live Streams on Android 

### ISSUE THREAD

**Issue by developeralp** [begeekmyfriend/yasea#154]
I'm trying to watch a stream , published with yasea.
But i could not get it worked.

I tried this libraries ,
-Vitamio (Works after 10-15 seconds later)
-ExoPlayer (it  did not work)
-ExoMedia (same as exoplayer)
-VideoExpertsGroup/MediaPlayerSDK (works laggy)

What library do you use for watching live streams (published by yasea-rtmp) , on your app ?

**Comment by begeekmyfriend** [comment]
[ijkplayer](https://github.com/Bilibili/ijkplayer)
