### ISSUE TITLE
Low FPS of gpuImage  branch

### ISSUE THREAD

**Issue by fifa1016** [begeekmyfriend/yasea#156]
在未使用filter的情况下, 这个分支的fps经常降到个位数,  主分支基本上可以维持在20左右.

这个有办法解决吗?

**Comment by fifa1016** [comment]
更新: 在华为的 nexus 6P 上如此, 其它手机比如华为9P正常

**Comment by begeekmyfriend** [comment]
Fixed https://github.com/begeekmyfriend/yasea/commit/5211eb41699a4c1caa56a82b2bf87f013568d29c
