### ISSUE TITLE
Question about SRS

### ISSUE THREAD

**Issue by developeralp** [begeekmyfriend/yasea#158]
Hello,

I'm trying to publish to srs.

I successfully published rtmp to srs.

Mine aim is : publish srs via rtmp => output hls from srs server.

I tried this way (https://github.com/ossrs/srs/wiki/v2_EN_SampleTranscode2HLS) to change output of rtmp stream.

I can watch hls stream but i can't hear audio (with vlc) , is there a wrong with aac ? 

How can i solve that problem ?

**Comment by begeekmyfriend** [comment]
Not my business
