### ISSUE TITLE
使用PLDroidPlayer播放器取流播放方向是水平相反

### ISSUE THREAD

**Issue by justinshaohi** [begeekmyfriend/yasea#159]
你好：
        我推的时候用的是硬解，摄像头的角度为0，屏幕也是设置固定横屏，调用本地方法 NV21ToNV12(data, vPrevWidth, vPrevHeight, true, 0)转换格式再进行硬解推流，在播放的时候图像都是水平相反的，能否给我点提示可能是哪边出现问题。

**Comment by begeekmyfriend** [comment]
把`true`改成`false`应该可以了，不同`Android`手机表现不一

**Comment by justinshaohi** [comment]
可以了，谢谢。
