### ISSUE TITLE
About push the stream of time

### ISSUE THREAD

**Issue by fly518420** [begeekmyfriend/yasea#16]
Now,  Continue to push flow more than 4 hours and 30 minutes，It will stop.

**Comment by begeekmyfriend** [comment]
I have tested publishing overnight.

- Does it happen each time?

- What is the exception thrown?

- Is your networking all right?

**Comment by fly518420** [comment]
It happen each time 
The network is normal
Sorry, I forget to see the exception

**Comment by begeekmyfriend** [comment]
Enough, if it happens each time, the exception might well be `EPIPE`. I have got it.

**Comment by fly518420** [comment]
What I can do to avoid the this exception.
In other places I have seen this exception，and the most people say it's it's caused by and extend the timestamp。

**Comment by begeekmyfriend** [comment]
Nothing but re-connection since it is the Nginx-RTMP that closes the socket. Today I will verify it on Nginx-RTMP.

**Comment by begeekmyfriend** [comment]
Ah, I see. This [article](http://blog.csdn.net/win_lin/article/details/13363699) illustrates the reason.

```c
ngx_rtmp_recv(ngx_event_t *rev)  
{  
    for( ;; ) {  
        /* parse headers */  
        if (b->pos == b->start) {  
            /* chunk basic header */  
            fmt  = (*p >> 6) & 0x03;  
            csid = *p++ & 0x3f;  
            if (fmt <= 2 ) {  
                /* timestamp: big-endian 3b -> little-endian 4b */  
                pp = (u_char*)timestamp;  
                ext = (timestamp == 0x00ffffff);  
                if (fmt <= 1) {  
                    /* size: big-endian 3b -> little-endian 4b type*/  
                    pp = (u_char*)&h->mlen;  
                    h->type = *(uint8_t*)p++;  
                    if (fmt == 0) {  
                        /* stream: little-endian 4b -> little-endian 4b */  
                        pp = (u_char*)&h->msid;  
                    }  
                }  
            }  
            /* extended header */  
            if (ext) {  
                pp = (u_char*)timestamp;  
                pp[3] = *p++;  
                pp[2] = *p++;  
                pp[1] = *p++;  
                pp[0] = *p++;  
            }
```

In `ngx_rtmp_recv` function, once Nginx-RTMP receives extended time stamp in chunk type less than 3, then it will **always** parses extended time stamp in the subsequent packets whatever the chunk type is.

**Comment by begeekmyfriend** [comment]
Try https://github.com/begeekmyfriend/yasea/commit/9e35f22b7f758d0e3a5125a25f919606c71171d8 please.

**Comment by fly518420** [comment]
I get the latest code, find a new exception : java.net.UnknownHostException: Host is unresolved
It happened before.

**Comment by begeekmyfriend** [comment]
That is your networking issue.

**Comment by fly518420** [comment]
But I use the old code can push stream.

**Comment by begeekmyfriend** [comment]
Are you sure? I downloaded and tried just now you were saying.

**Comment by fly518420** [comment]
Sorry, Should be a network problem. Just in time is a coincidence

**Comment by fly518420** [comment]
It seem still have the same problem
And I will test again.

**Comment by fly518420** [comment]
Maybe you can refer to this blog [http://blog.csdn.net/jiang_shikun/article/details/46047417](librtmp 时间戳超过 0xffffff时，FMS掉连接)

**Comment by fly518420** [comment]
Maybe you can refer to this blog [librtmp 时间戳](http://blog.csdn.net/jiang_shikun/article/details/46047417)

**Comment by begeekmyfriend** [comment]
A rapid reappearance approach is adding code in `rtmp/io/WriteThread.java`. It can help find the bug though no solution occurs to me currently.

```java
                while (!writeQueue.isEmpty()) {
                    RtmpPacket rtmpPacket = writeQueue.poll();
                    ChunkStreamInfo chunkStreamInfo = rtmpSessionInfo.getChunkStreamInfo(rtmpPacket.getHeader().getChunkStreamId());
                    chunkStreamInfo.setPrevHeaderTx(rtmpPacket.getHeader());
                    if (rtmpPacket instanceof Video || rtmpPacket instanceof Audio) {
                        rtmpPacket.getHeader().setAbsoluteTimestamp((int) chunkStreamInfo.markAbsoluteTimestampTx() + 0xffffff);
                    } else {
                        rtmpPacket.getHeader().setAbsoluteTimestamp((int) chunkStreamInfo.markAbsoluteTimestampTx());
                    }
                    rtmpPacket.writeTo(out, rtmpSessionInfo.getTxChunkSize(), chunkStreamInfo);
                    Log.d(TAG, "WriteThread: wrote packet: " + rtmpPacket + ", size: " + rtmpPacket.getHeader().getPacketLength());
                    if (rtmpPacket instanceof Command) {
                        rtmpSessionInfo.addInvokedCommand(((Command) rtmpPacket).getTransactionId(), ((Command) rtmpPacket).getCommandName());
                    }
                    if (rtmpPacket instanceof Video) {
                        publisher.getVideoFrameCacheNumber().getAndDecrement();
                        calcFps();
                    }
                }
                out.flush();
```

**Comment by begeekmyfriend** [comment]
Final patch on this issue: https://github.com/begeekmyfriend/yasea/commit/5ee43c681e9c1124ce96799112e62e910756ec4a

**Comment by fly518420** [comment]
I did the test Yesterday night,and It seem still exist

**Comment by fly518420** [comment]
Stream disconnect after 10 hours.

**Comment by fly518420** [comment]
Can I catch the exception and reconnect.

**Comment by begeekmyfriend** [comment]
10 hours? That might not be extended time stamp.
