### ISSUE TITLE
推流过程中切换filter的话,帧率降低明显

### ISSUE THREAD

**Issue by fifa1016** [begeekmyfriend/yasea#160]
如果在推流之前设置filter(无论none或者beauty)等, 帧率在20以上; 

推流过程中切换的话,切换后帧率降到10~15(美颜), 或者在15~20(NONE).

这个是因为有些设置未能重置的原因吗?

机型: 三星 edge 6

**Comment by begeekmyfriend** [comment]
你确定？我的Nexus全程未掉

**Comment by fifa1016** [comment]
刚才测试了以下, 在filter反复切换之后,还是会掉帧, 有时候程度稍微轻些,由24左右掉到接近20.

参数设置:  output resolution  1280*720,
bitrate: 1200 kbps

推流server:ossrs

机型: 三星s6 edge
==================================
另一台机器 nexus 6p  华为款
参数设置同上, 反复切换filter,  发现在按钮显示为none的时候帧率正常,为24左右; 显示beauty的时候帧率在19上下浮动.   意思就是没有美颜的时候,帧率反而低?

**Comment by begeekmyfriend** [comment]
帧率本身就是浮动的，所谓的20帧左右根本就不能算掉帧，跟`filter`切换根本没关系，不行你就别开美颜测测看吧。

**Comment by fifa1016** [comment]
应该还是有关系的,  分辨率720P, 码率1M 左右, 反复切换,  帧率掉的还是挺明显的.

如果不切换,  即使开着美颜, 帧率还是在24左右.

**Comment by begeekmyfriend** [comment]
不知掉帧后是否恢复？

**Comment by fifa1016** [comment]
早上测了一下,  edge 只要一切换, 帧率马上掉,   nexus 6p 反复切换之后也会掉.

不知道你这边能不能复现

**Comment by fifa1016** [comment]
现在看只有让用户提前选择是否加filter

**Comment by begeekmyfriend** [comment]
首先主播一般不会反复切换滤镜的，从业务逻辑上就可以排除；如果一切换马上掉，那就是手机问题

**Comment by fifa1016** [comment]
嗯 现在基本满足
