### ISSUE TITLE
怎样在启动Activity自动推流

### ISSUE THREAD

**Issue by Belle92** [begeekmyfriend/yasea#161]
我将btnPublish 中的开始推流的操作直接写在onCreate 中 不能正常的推流。应该在哪个生命周期中进行推流？还是应该监听哪个的回调后进行推流操作？

**Comment by begeekmyfriend** [comment]
为啥`onCreate`就要推？

**Comment by Belle92** [comment]
额 上一版本是可以实现的 也不是非要onCreate 只是想进入直播界面主动推流 不用使用按钮让用户去操控推流开始

**Comment by begeekmyfriend** [comment]
`SrsPublisher.java`

**Comment by begeekmyfriend** [comment]
Sorry, my fault https://github.com/begeekmyfriend/yasea/commit/f185b820cb5f2f5e2e3b8c3a11ddb2f851822a79
