### ISSUE TITLE
How can I use your library to stream video to my own rtmp server?

### ISSUE THREAD

**Issue by HamedGh** [begeekmyfriend/yasea#162]
Could you add some examples? I changed rtmpUrl, but I don't know what should I do else?!

when I click on every buttons, It shows me ANR

**Comment by begeekmyfriend** [comment]
[RTMP server](https://github.com/ossrs/srs/tree/2.0release)

**Comment by HamedGh** [comment]
No, We have our own rtmp server, we don't want to rewrite it.

**Comment by begeekmyfriend** [comment]
You do not get my point.

**Comment by HamedGh** [comment]
what is your point?
