### ISSUE TITLE
libyuv failure

### ISSUE THREAD

**Issue by HamedGh** [begeekmyfriend/yasea#163]
every time I click on Switch button It shows me a picture of camera and then "libyuv failure" and then app freez

**Comment by begeekmyfriend** [comment]
Your issue was issued

**Comment by begeekmyfriend** [comment]
It also confuses me since some other users have also complained me about this issue. But it has not been reappearing on my phone and not all users have complained about it. So I am not sure whether it is a defect of my library or not.

**Comment by begeekmyfriend** [comment]
I apologize for my carelessness since it is really my fault. Now it is fixed https://github.com/begeekmyfriend/yasea/commit/42fd31eb5c6221e433ac1d1f9ce1abaa849a6f90
