### ISSUE TITLE
Yasea and Wowza

### ISSUE THREAD

**Issue by developeralp** [begeekmyfriend/yasea#165]
Hello , i cannot publish live stream to wowza media server..

i know we can use red5 or srs , but i'm running windows , and red5 is not my choice.

wowza requires authentication i.e publish url must be like that,

rtmp://nick:password@your_wowza_ip:1935/live/your_stream_name

but i cannot connect wowza with that ?

**Comment by begeekmyfriend** [comment]
The authentication is server specific and therefore is not for general purpose.`

**Comment by developeralp** [comment]
I disabled authentication and yasea still cannot connect to wowza.

**Comment by developeralp** [comment]
Another question , if i add source authentication (url must be like this : rtmp://your_server_ip:1935/live?doPublish=12345/streamName)

How can i change rtmp url on yasea like this without any errors ?
