### ISSUE TITLE
Why MediaFormat.KEY_MAX_INPUT_SIZE of a/v is zero?

### ISSUE THREAD

**Issue by b95505017** [begeekmyfriend/yasea#167]
I notice these two lines:
```java
videoFormat.setInteger(MediaFormat.KEY_MAX_INPUT_SIZE, 0);
...
audioFormat.setInteger(MediaFormat.KEY_MAX_INPUT_SIZE, 0);
```

Just wondering why you set them to zero.
Thanks for this great project!

**Comment by begeekmyfriend** [comment]
The original code is from [srs-sea](https://github.com/ossrs/srs-sea/blob/master/app/src/main/java/net/ossrs/sea/MainActivity.java#L318) , I guess this will fix [MediaCodec](http://stackoverflow.com/questions/21284874/illegal-state-exception-when-calling-mediacodec-configure) bug on Android 4.1.

**Comment by nokite** [comment]
Setting this to 0 allows me to play certain videos (HLS, DASH) on Galaxy Nexus without crashing. I'm not sure what Android versions or what Hardware is affected. My Galaxy Nexus has Android 4.3, which is higher than what other people have reported (but it's an old device).
