### ISSUE TITLE
"Invalid Audio Data"

### ISSUE THREAD

**Issue by developeralp** [begeekmyfriend/yasea#168]
Hi,

Sometimes , when i click publish button , stream not starts and a toast appears "invalid audio data"

how can i solve that ?

**Comment by begeekmyfriend** [comment]
[code](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/rtmp/DefaultRtmpPublisher.java#L55)

**Comment by begeekmyfriend** [comment]
Why not use `grep`?

**Comment by developeralp** [comment]
you are right ,  but i meant how to avoid that error

**Comment by begeekmyfriend** [comment]
I do not understand why did you generate such audio data

**Comment by developeralp** [comment]
Me too..
Maybe its a problem of my device (mtk6589)
