### ISSUE TITLE
Output Size Not Changing

### ISSUE THREAD

**Issue by developeralp** [begeekmyfriend/yasea#169]
Hi,

I'm changing output size with 

`mPublisher.setOutputResolution(720,1280);`

But nothing changes in output..

Output is still 384 - 640 on player... 

How can i solve that ?

**Comment by developeralp** [comment]
solved , my fault.

**Comment by Sonamgupta2109** [comment]
what you are doing for change the outsize when orientation change . Because i am doing the same
mPublisher.setOutputResolution(720,1280); 

but it did not work

**Comment by developeralp** [comment]
@Sonamgupta2109 
You can change outputResolution from SrsEncoder.java

**Comment by Sonamgupta2109** [comment]
Thanks for the reply. I also want to know how can i change the output size when streaming is running without stopping streaming.
 When i change orientation it does not change output size .

**Comment by begeekmyfriend** [comment]
Impossible.

**Comment by Sonamgupta2109** [comment]
So Every time when i change orientation need to restart encoding. Or there is any other way to handle it.

**Comment by begeekmyfriend** [comment]
Sure.
