### ISSUE TITLE
Rotated frame of video when user rotate the screen

### ISSUE THREAD

**Issue by satyamub** [begeekmyfriend/yasea#17]
Hi @begeekmyfriend ..how are you. Thanks for helping me yesterday. 

I have one more doubt like if I rotate the screen, the preview changed accordingly however the frames which are generated and sent are not rotated accordingly. Where to rotate that in order to get right frames in video.

I am attaching a image which is actually I have tried recording at landscape mode.

![mypic](https://cloud.githubusercontent.com/assets/13571747/15180945/19f6ab02-17a2-11e6-986b-a12fe4ce18d8.png)

**Comment by satyamub** [comment]
@begeekmyfriend  its like the sending frame should be rotated 0 degree.

**Comment by begeekmyfriend** [comment]
That involves video source layout as known as YUV transformation. I need some time to do it.

**Comment by satyamub** [comment]
@begeekmyfriend okay no problem. can you please let me know how to stop the rotation of the preview so that I would only show my user portrait preview. Like if any user go for Landscape orientation, the preview also does not change.

**Comment by satyamub** [comment]
@begeekmyfriend I have tried to read about the same.

Got links for you http://www.wordsaretoys.com/2013/10/25/roll-that-camera-zombie-rotation-and-coversion-from-yv12-to-yuv420planar/ and http://stackoverflow.com/questions/14167976/rotate-an-yuv-byte-array-on-android. Can you please take a look at these

**Comment by begeekmyfriend** [comment]
I know the how-to. But I need to unify the project.

**Comment by satyamub** [comment]
okay @begeekmyfriend .. thanks for help

**Comment by satyamub** [comment]
@begeekmyfriend  atleast let me know how to stop the image rotation of preview so that I will only support the portrait mode preview and sending images (frames) for now.

**Comment by begeekmyfriend** [comment]
See [here](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/sea/SrsEncoder.java#L178-L180) and [here](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/sea/SrsEncoder.java#L220)

**Comment by satyamub** [comment]
do I have to comment out these lines?

**Comment by begeekmyfriend** [comment]
You had better know the API utility of `MediaCodec`. That will not take your much time.

**Comment by satyamub** [comment]
@begeekmyfriend  I tried my hands.. did not succeed can you guide me through. I just want to stop rotate the preview display so that user will only able to publish through portrait mode. I can stop the orientation change.

**Comment by satyamub** [comment]
If you could adjust in the rotated frames so that user will see same thing on receive side as rotated on publishing side then that will be added advantage. That will completely resolve the issue.

**Comment by begeekmyfriend** [comment]
Adjust [here](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/sea/MainActivity.java#L237-L242) and [here](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/sea/MainActivity.java#L272)

**Comment by satyamub** [comment]
I am not sure if I am making you understand my issue or not.

I don't want my preview display to rotate when I will go landscape

I am attaching two images for references.
First one is publishing image from mobile(I locked to Portrait screen only)
![screenshot_20160513-110326](https://cloud.githubusercontent.com/assets/13571747/15238988/19a8622a-18fc-11e6-9e8a-6210b96b5f70.png)


Second one is Test player in wowza

<img width="1057" alt="screentwop" src="https://cloud.githubusercontent.com/assets/13571747/15238970/f8752f48-18fb-11e6-9276-4414a303da58.png">


I want either I get complete solution that is If I rotate the phone, the rotated image would be displayed as it is at receiving end otherwise, I want to lock the preview display orientation as well. so only one orientation will be displayed to user and that will be transmitted as well.

I tried your suggestion and not succeeded. May be I did not try well. You can let me know what exactly to try.

**Comment by satyamub** [comment]
I tried your suggestion with sending the data as it is and cropped one in below method

 bb.put(mRotatedFrameBuffer, 0, mRotatedFrameBuffer.length);
and then tried to disable rotate and flip.

but it distorted the image and I think its good in Landscape and wrong in portrait. I am not able to resolve this. can you give solution to this?

**Comment by begeekmyfriend** [comment]
I got your point.
- You should detect the camera orientation that has just been changed.
- Once detected, then you need to switch the method of transformation of YUV data.
It is a long time job.

**Comment by satyamub** [comment]
yes, may be you are right. can you do that? please

**Comment by begeekmyfriend** [comment]
If you can not wait in short time I am afraid you need to DIY or find others to help you. What you should learn:
- YUV data format layout and transformation.
- Surface orientation switch for Android.

Actually that is not in high privilege for me. I have my own schedule.

**Comment by satyamub** [comment]
Great ...how much time you require to do so?

**Comment by satyamub** [comment]
@begeekmyfriend any news from your side?

**Comment by banketree** [comment]
I solved,
remove rotateYUV420SemiPlannerFrame Or Add rotaion by rotateYUV420SemiPlannerFrame,
MediaFormat.createVideoFormat  and Camera width,height unified

**Comment by banketree** [comment]
![screenshot_2016-05-17-12-45-12](https://cloud.githubusercontent.com/assets/4402896/15311436/5e81ba02-1c2d-11e6-8e04-d9c818dc1f4f.png)

**Comment by satyamub** [comment]
@begeekmyfriend Hi nice to hear this friend did you update the code?

**Comment by fly518420** [comment]
@banketree Did you implements the landscape pushed the flow?

**Comment by begeekmyfriend** [comment]
@banketree may share his solution to others since I am in hospital these days.

**Comment by satyamub** [comment]
@begeekmyfriend Get well soon!!!

@banketree  can you share the solution to us.

**Comment by banketree** [comment]
@satyamub 
@begeekmyfriend 
of course,but wait for me to improve.

**Comment by fly518420** [comment]
@banketree hello ,I need your help,I want to know how did you implement it?

**Comment by satyamub** [comment]
@banketree Please share solution with us.. I am waiting

**Comment by begeekmyfriend** [comment]
https://github.com/begeekmyfriend/yasea/commit/540a40c2f571e6a1b67c1f1b6560cb182992fd43. There is still little thing about preview or whatever which I think you can handle with.

**Comment by banketree** [comment]
good,i will share my solution with 360’.

**Comment by satyamub** [comment]
@begeekmyfriend @banketree where is the solution

**Comment by begeekmyfriend** [comment]
The latest version on master branch.
