### ISSUE TITLE
Audio issue on retry publish

### ISSUE THREAD

**Issue by junknown** [begeekmyfriend/yasea#170]
When the public for the first time, a rtpm stream on my agile streamer server, everything seems ok. But if you stop the stream, and you try to publish again, it will be sent a stream without audio.
The cause seems to be that was not well resetted the field "aac_specific_config" of class SrsFlv. In fact, when the stream restart, method  writeAudioSample can not use the correct frame.
As quickfix I regenerated the instance of SrsFlv in "stop" method of SrsFlvMuxer. Now all seems to work fine.

**Comment by begeekmyfriend** [comment]
Thank you for your report https://github.com/begeekmyfriend/yasea/commit/be200b1bc61376dc22ba8c69acbb2ac4c4a17a6d

**Comment by junknown** [comment]
Thanks to you for your quick support.
