### ISSUE TITLE
"Unsupported resolution 1280x720"

### ISSUE THREAD

**Issue by brbegg** [begeekmyfriend/yasea#171]
Trying to stream from Samsung SM-T217S. When I tap "publish", it says "Unsupported resolution 1280x720", then claims to connect to the rtmp server. The camera preview stays blank and never connects to the server. The "record" function yields a corrupted video. Switching between hard and soft encoders doesn't help. 

I noticed this problem on Version 2.0.

1.1 and 1.2 crash when I click publish.

1.0 works just fine.

**Comment by begeekmyfriend** [comment]
No, the information tells that the camera on the phone does not support this resolution. See [here](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/SrsCameraView.java#L73). That means you cannot set that resolution any more on this phone. Try another by invoking this [API](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/MainActivity.java#L71).

**Comment by developeralp** [comment]
Hi,

Camera.Size sizeHd = camParams.getPrefferedVideoSize();//or something like that

This code will give you best preview size.(i.e : 1280-720 gives me same error , but that method works 🤔with 1920-1080)

You may need change focus mode.
