### ISSUE TITLE
Starting Back Camera Issues

### ISSUE THREAD

**Issue by developeralp** [begeekmyfriend/yasea#173]
If i change front camera to back camera (before publishing) , output of video is rotating wrong..

How can i solve that  ? 

Another question  , is there a way to start camera preview before publishing with SrsCameraView.java ?

**Comment by begeekmyfriend** [comment]
Q1: Switch [the boolean argument](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/SrsEncoder.java#L421)

Q2: Just invoke `mCameraView.startCamera()`, **DIY**
