### ISSUE TITLE
关于arm64-v8a平台的问题。。

### ISSUE THREAD

**Issue by z2045217** [begeekmyfriend/yasea#177]
我试了好几天。也看了＃74的回答。也试了shishuo365的静态库。但是我把shishuo365的arm64的静态库替换了libenc下的lib里面的静态库。还是出现问题。
[arm64-v8a] Compile++      : enc <= libenc.cc
[arm64-v8a] Prebuilt       : libyuv.so <= jni/lib/
[arm64-v8a] StaticLibrary  : libstdc++.a
[arm64-v8a] SharedLibrary  : libenc.so
/Users/carneting12345/project/yasea-gpuimage/app/src/main/libenc/obj/local/arm64-v8a/libyuv.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
make: **\* [/Users/carneting12345/project/yasea-gpuimage/app/src/main/libenc/obj/local/arm64-v8a/libenc.so] Error 1
本人菜鸟，水平实在有限。已经困扰了好几天。希望作者能施以援手。谢谢。

**Comment by begeekmyfriend** [comment]
@shishuo365

**Comment by shishuo365** [comment]
@z2045217 v1.1版本是带有完整64位ABI支持；v1.1.1版本去除了64位ABI支持；

**Comment by shishuo365** [comment]
@z2045217  @begeekmyfriend 
纠正一下上面的回答：导致这个问题的原因是 libyuv 的编译脚本中没有生成 arm64-v8a 库，与 libx264 没有关系，请修改 yasea 项目中 Android.mk 文件来支持生成对应的库。

**Comment by z2045217** [comment]
我试的就是v1.1版本的。但是错误还是上面那个。adding symbols: File in wrong format。我用的是linux64位系统的ndk-r10e.是不是这个原因。

**Comment by shishuo365** [comment]
请先了解 Application.mk 的语法，然后修改下面的文件，增加生成libyuv的 arm64-v8a 库
https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/libenc/jni/Application.mk

**Comment by z2045217** [comment]
我刚才看了下libyuv目录下的android.mk。这是其中的一段话。
ifeq ($(TARGET_ARCH_ABI),armeabi-v7a)
    LOCAL_CFLAGS += -DLIBYUV_NEON
    LOCAL_SRC_FILES += \
        source/compare_neon.cc.neon    \
        source/rotate_neon.cc.neon     \
        source/row_neon.cc.neon        \
        source/scale_neon.cc.neon
endif

ifeq ($(TARGET_ARCH_ABI),arm64-v8a)
    LOCAL_CFLAGS += -DLIBYUV_NEON
    LOCAL_SRC_FILES += \
        source/compare_neon64.cc    \
        source/rotate_neon64.cc     \
        source/row_neon64.cc        \
        source/scale_neon64.cc 
endif
我编译arm64-v8a的时候。在obj中出现了arm64-v8a的libyuv.so的库。

**Comment by begeekmyfriend** [comment]
`Application.mk`呢？

**Comment by z2045217** [comment]
这两个Application.mk。我已经修改了。
https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/libenc/jni/libyuv/jni/Application.mk
https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/libenc/jni/Application.mk

**Comment by z2045217** [comment]
在libenc/obj/local下已经出现了arm64-v8a的目录。目录里面有libyuv.so库。还有一些没有编译玩的enc文件。

**Comment by z2045217** [comment]
两个目录下的application.mk我都修改成了这样的。
APP_ABI := arm64-v8a
APP_PLATFORM := android-21
后面的我也还试了
APP_ABI := arm64-v8a
APP_PLATFORM := android-16
但是错误都是一样。adding symbols: File in wrong format。。

**Comment by shishuo365** [comment]
看一下 ndk-gcc 的版本，
64位ABI使用 gcc4.9
32位ABI使用 gcc4.8

**Comment by lzx1** [comment]
怎么指定ndk-gcc版本呢？

**Comment by z2045217** [comment]
我查了下版本。。显示是这个。gcc version 5.3.1 20160413 (Ubuntu 5.3.1-14ubuntu2)

**Comment by begeekmyfriend** [comment]
@lzx1 貌似只能写成`build.sh`的 [形式](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/libenc/jni/libx264/android_build.sh#L5)
@z2045217 这里的`gcc`指的是`ndk`里的`gcc`，不是系统自带的

**Comment by z2045217** [comment]
现在好多手机都是arm64-v8a的cpu。作者能增加下这个库吗。

**Comment by chinabigcat** [comment]
多谢诸位大师指导！

**Comment by shishuo365** [comment]
https://github.com/shishuo365/libx264-android/releases

**Comment by shishuo365** [comment]
使用有错误的可以参照这里（最省力的方法是直接使用编译好的release）

**Comment by begeekmyfriend** [comment]
大家好，我花了点时间尝试arm64-v8a，可以运行。但经测试发现OpenGL ES驱动对v8a的支持效率不高，体现在美颜滤镜掉帧，定位到glReadPixels这个函数的benchmark，而v7a是没有问题的。另外这既不是libx264的问题也不是libyuv的问题，目前看来尚不存在有效解决手段，故决定不放arm64-v8a了。
