### ISSUE TITLE
Compiling Native Libraries(arm64-v8a ,armeabi,x86,x64...)

### ISSUE THREAD

**Issue by developeralp** [begeekmyfriend/yasea#179]
Hi  ,
I'm trying to compile libyuv and libx264.

I reviewed https://github.com/begeekmyfriend/yasea/issues/74 but i can't solve that.

also , i looked https://github.com/shishuo365/libx264-android/releases , can't understand it.

libx264 have static libraries but how can i use them ?
(if i can use libx264 static libraries , how about libyuv ?) 

I'm using that way to compile native libraries in android studio : http://stackoverflow.com/a/26693354/5013103

But i'm getting these errors , 

![error3](https://cloud.githubusercontent.com/assets/22075871/19230208/f17df5ca-8edb-11e6-863e-d148a5b9d313.png)

If i remove arm64-v8a 
I'm getting that error : 

![errorx86](https://cloud.githubusercontent.com/assets/22075871/19230420/0bf7c97a-8edd-11e6-9f72-28556c1dc55b.png)

Is not there an easy way to do it ?

**Comment by GeniusAtamans** [comment]
I have same problem.
I set APP_ABI := armeabi armeabi-v7a arm64-v8a mips x86 x86_64 to both Application.mk files, and get same error.
Can you build and share so files for this types processors?

**Comment by vleonidov** [comment]
Hello, I've compiled and built this library. Please take a look at the attachments. 
[jniLibs.zip](https://github.com/begeekmyfriend/yasea/files/532381/jniLibs.zip)

**Comment by GeniusAtamans** [comment]
Thanks

**Comment by developeralp** [comment]
@vleonidov 
Thanks , you have been very helpful.

**Comment by begeekmyfriend** [comment]
The latest code has supported.
