### ISSUE TITLE
About resolution

### ISSUE THREAD

**Issue by fly518420** [begeekmyfriend/yasea#18]
When I change the resolution , Camera-JNI: Callback buffer was too small! Expected 522240 bytes, but got 518400 bytes!  hanpped.

**Comment by begeekmyfriend** [comment]
What is your resolution?

**Comment by fly518420** [comment]
previewSize 720 720 
streamSize 720 480

**Comment by fly518420** [comment]
The preview resolution and SurfaceView size does not match , It will be out of shape .
If I set 1920 * 1080 for preview resolution, It will prompt Camera-JNI: Callback buffer was too small! Expected xxx bytes, but got xxx bytes! hanpped.

**Comment by begeekmyfriend** [comment]
YUV data size = width * height * 3 / 2
