### ISSUE TITLE
Nexus 7 doesn't work

### ISSUE THREAD

**Issue by alexsqian** [begeekmyfriend/yasea#180]
App constantly freezes when a button is pressed, occasionally shows a libyuv failure.
When set to hard encoding a toast says use soft encoding, when set to soft encoding a toast says use hard encoding.
Unable to press publish without the app freezing.

**Comment by begeekmyfriend** [comment]
The text on the button shows that the encoder you want to switch but not the one you have chosen.

As for Nexus 7, I guess that it is the camera API compatibility, try to substitute `Camera2` to the original.
