### ISSUE TITLE
推流和视频录制

### ISSUE THREAD

**Issue by JakeRed** [begeekmyfriend/yasea#183]
大哥，我就想问一个问题，在MP4录制的时候writeLock.wait(500)除了等待framecache有数据，这个时间间隔还有什么其他用途吗，我可不可以先让他有了500帧再直接录制到本地，生成一个视频文件？

**Comment by begeekmyfriend** [comment]
你不喜欢注释吗？

**Comment by JakeRed** [comment]
我能看注释，可是你的注释太少了，我就一个问题，问了你几次你也没理我，我就想问堆积framechche，能不能延迟录像？
![image](https://cloud.githubusercontent.com/assets/21214880/19424537/86e5b956-945c-11e6-9901-3dd2a813d8a1.png)

**Comment by begeekmyfriend** [comment]
能否我不知道。不过你要明白一点，开源没有免费提供额外技术支持的义务，而你的录制就是在我开源基础上额外的需求，yasea是推流工具。

**Comment by JakeRed** [comment]
预录制的时候，FIFO存一定量的frameCache，能不能实现，还是说录制的根本不在这个方法？

**Comment by JakeRed** [comment]
好的，谢谢你！
