### ISSUE TITLE
Network weak导致的问题

### ISSUE THREAD

**Issue by Jack1103** [begeekmyfriend/yasea#184]
我这边使用了你的推流到我们的软件中，但偶尔会发生Network weak的提示，然后不一会儿程序将报如下错误：
RtmpConnection: Caught exception while reading/decoding packet, shutting down: Unexpected EOF reached before read buffer was filled。

我应该怎么debug，去掉这个错误，概率太大了。

**Comment by begeekmyfriend** [comment]
服务端的问题，你用`rtmp://ossrs.net/app/stream`对比下

**Comment by begeekmyfriend** [comment]
不仅是服务端，还有你网络的问题，无法读取socket了

**Comment by Jack1103** [comment]
这个错换了你的服务器也能稳定复现，手机为mi 4.

**Comment by begeekmyfriend** [comment]
那就是你网络太差了，还没其他人抱怨过这个问题

**Comment by Jack1103** [comment]
ios 那边用的代码推流没问题。

**Comment by begeekmyfriend** [comment]
既然有network weak的提示，那就是网络问题错不了。iOS重连了吗？

**Comment by Jack1103** [comment]
我觉得可能是他的视频文件小，分辨率之类的，我就是想说断网重连怎么解决，下午看了下，当网络断开会报几个错，那么我就关掉推流，网络恢复后我重新推流，问题是网络恢复后我推流总报Unexpected EOF reached before read buffer was filled，不是很理解，求指教。

**Comment by begeekmyfriend** [comment]
你的版本有没有[异常捕获代码](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/rtmp/io/RtmpConnection.java#L519)？

**Comment by Jack1103** [comment]
我的版本是前两天才更新的，有这块代码，nexpected EOF reached before read buffer was filled一下午没搞明白,谢谢大神指导。

**Comment by begeekmyfriend** [comment]
那就去掉，当`IOException`处理吧

**Comment by Jack1103** [comment]
确定不是EOFException

**Comment by begeekmyfriend** [comment]
你的异常在[这儿](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/rtmp/Util.java#L95)

**Comment by Jack1103** [comment]
我在我的代码中没有实现断网重连的逻辑，便重新clone了您的源码，然后进行断网重连推流的操作，然后再您的APP中，Network weak赫然林立，Camera都是重新申请的，为啥效果这样呢，求指导，谢谢！

**Comment by begeekmyfriend** [comment]
“赫然林立”，你用的一手好词，但那还是你自己的事情——用长城宽带了吗？

**Comment by Jack1103** [comment]
这一次不能说网络的问题了，因为我买了一个路由器，网也不用之前的网了，出现这个情况的原因我还在查，但是你想想：在不断网的时候，点击推流/关流都不会有任何问题，当我推流的时候关闭网络，推流会断开，当我恢复网络连接的时候，点击推流“赫然林立”的Network weak 就不停出现，流推不出去了。谢谢您耐心教导，谢谢。

**Comment by Jack1103** [comment]
您能帮我看一下吗？

**Comment by begeekmyfriend** [comment]
那是因为你路由器还没连好呗，我都亲自试了

**Comment by Jack1103** [comment]
你的步骤是：
1，点击推流；
2，关闭wifi网络，并保证蜂窝数据关闭，不要onDestroy() MianActivity;让他在后台运行。
3，2秒后重连wifi网络。
4，点击推流，NetWork weak 就出来了。
我旨在模拟断网广播的情况，断开重连，您试一下。

**Comment by Jack1103** [comment]
您看能复现吗？

**Comment by begeekmyfriend** [comment]
跟你说了我都试过了。
如果你还是“林立”，那你就把demo里的toast关闭啊，这并非SDK的部分，是你自己定制的。
**你该不会连demo和SDK都不分吧**

**Comment by Jack1103** [comment]
我把toast关掉了的，打的Log，然后一直就在，流也不推，我再查查我的原因。

**Comment by Jack1103** [comment]
对不起，我找到了原因，您的demo断开推流后地址变了，所以成功推上去了，但是我这边地址没变，所以推不上去，这个的原因可以说不在你，但也可以说算一个不足。

**Comment by Jack1103** [comment]
如果断开后换个地址，那就没问题，老地址就是不行。
