### ISSUE TITLE
分辨率和视频比例

### ISSUE THREAD

**Issue by Jack1103** [begeekmyfriend/yasea#185]
当设置分辨率为mPublisher.setPreviewResolution(640, 480)时，输出的视频流为花屏，请问如果我想让其输出视频为4：3而且画面不变性应该怎么设置参数？

谢谢

**Comment by begeekmyfriend** [comment]
你一定改了其它地方，直接改`setPreviewResolution`是不会有花屏的

**Comment by Jack1103** [comment]
实际上我没改其他地方，setPreviewResolution设置不好使，直接改vPrevWidth好使。

然后今天遇到一个新问题，我想断网后断流，网络恢复后重推，但是当网恢复后，推不上去了，总报错，我确定就写了一个网络监听，异常信息为：Unexpected EOF reached before read buffer was filled。

我还得请教一下您。

**Comment by begeekmyfriend** [comment]
就是socket读不了

**Comment by Jack1103** [comment]
socket读不了，但是我已经调用重新连接了呀，请教一下，谢谢！
