### ISSUE TITLE
第一版怎么只传声音不传视频

### ISSUE THREAD

**Issue by 18518756793** [begeekmyfriend/yasea#186]
第一版怎么只传声音不传视频。

**Comment by begeekmyfriend** [comment]
1.你确定第一版存在这个问题？
2.为啥还要用第一版？

**Comment by 18518756793** [comment]
我用的第一版，第一版想实现只传 音频的功能。因为第二版 ，我的 pad 硬件貌似不支持。

**Comment by 18518756793** [comment]
我的问题就是第一版怎么实现 只传 音频

**Comment by begeekmyfriend** [comment]
第二版是`gpuimage`分支，你还是用`master`上的[最新版](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/SrsPublisher.java#L195)吧，同第一版通用的

**Comment by begeekmyfriend** [comment]
抱歉issue太多忘记回复你的问题了

> mPublisher.setSendAudioOnly(true);
