### ISSUE TITLE
readBytesUntilFull方法的疑问

### ISSUE THREAD

**Issue by Jack1103** [begeekmyfriend/yasea#189]
在您提供的服务器上不存在这个问题，但是在我们的服务器上，只要第二次推流就每次都会：throw new IOException("Unexpected EOF reached before read buffer was filled");我想问一下我应该怎么处理这个问题，如果抛出去掉，那推流也上不去了。谢谢您。帮我指导下？

**Comment by Jack1103** [comment]
或者说您给告诉我一下，遇到这个问题服务器应该怎么配吗？

**Comment by begeekmyfriend** [comment]
估计只能抓包了，然后在源代码里加打印，看具体读到哪个包的哪个字段出事

**Comment by Jack1103** [comment]
那问您一下，您的服务器是SRS吗？怎么搭的服务器？

**Comment by begeekmyfriend** [comment]
nginx和SRS都试过，网宿和网易上都有测试账号。SRS的搭建方法见[README](https://github.com/ossrs/srs/tree/2.0release)

**Comment by Jack1103** [comment]
那问一下我连rtmp://ossrs.com/app/stream 这个是SRS2.0吗？

**Comment by begeekmyfriend** [comment]
是`ossrs.net`，不太清楚，好像是1.0

**Comment by Jack1103** [comment]
谢谢，我们这边服务器换2.0就好了

**Comment by Jack1103** [comment]
我遇到一个新问题，较长时间没推流（一晚上），再推流的时候，设备推上流，不一会儿就断开了，然后因为写了重连，又连上了，然后又断开，又重连，，，循环断开重连且都连上，只是不一会儿就断开，然后看的时候就卡着了

**Comment by begeekmyfriend** [comment]
你的重连逻辑没写好#150
