### ISSUE TITLE
如何更改分辨率

### ISSUE THREAD

**Issue by crazyhl** [begeekmyfriend/yasea#19]
请问如何修改分辨率，根据不同的手机分辨率

**Comment by begeekmyfriend** [comment]
Unfortunately we have not a unified solution in the current. But you may query the `getSupportedPictureSizes` method to select one.

**Comment by crazyhl** [comment]
是的，我也是利用getSupportedPictureSizes这个方法去取得的一个分辨率，然后crop那个分辨率如何设置比较好，我总是卡住或者 Camera-JNI: Callback buffer was too small! Expected xxx bytes, but got xxx bytes!出现这个错误

**Comment by begeekmyfriend** [comment]
Show me your parameters.

**Comment by crazyhl** [comment]
VHEIGHT:720
VWIDTH:1280
VCROP_WIDTH:720
VCROP_HEIGHT:1280

然后我在addCallbackBuffer之前根据我现有的分辨率重新设置了一下buffer
mYuvFrameBuffer = new byte[SrsEncoder.VWIDTH * SrsEncoder.VHEIGHT * 3 / 2];
        mCamera.addCallbackBuffer(mYuvFrameBuffer);

**Comment by begeekmyfriend** [comment]
It is all right for my Nexus which is the only device on hand right now.

**Comment by banketree** [comment]
16:9 等比例  需要操作图片编码代码

**Comment by lisnstatic** [comment]
@crazyhl 
想问一下，你是不是想预览和推流的时候都是宽大于高？我现在想做的是竖屏，但是预览和推流都是宽大于高的那种，不知道您弄出来了吗？

**Comment by begeekmyfriend** [comment]
@lisnstatic 现在横竖屏可以动态切换了，你下载最新的master试试

**Comment by lisnstatic** [comment]
@begeekmyfriend  我想竖屏的预览窗口是640x480的，然后接流的时候也是640x480的。如果我设置编码宽高是640x480就会重影。

**Comment by lisnstatic** [comment]
@begeekmyfriend 新的master确实在横屏后接收到的流是横屏。我现在是想竖屏（但预览窗口是16：9，就是小屏播放器那样），推流得到也是16：9的（和我预览窗口一样），试了各种方法不是重影就是ANR。您有好的建议吗，这个问题已经困扰很久了，先多谢了~多谢~

**Comment by begeekmyfriend** [comment]
一个妥协方案是，把crop的宽高设成16:9，比如512:288（如果芯片是MTK的话数值必须保持32x）。更好的办法使用libyuv做缩放处理，降低手机功耗（发热）

**Comment by begeekmyfriend** [comment]
@lisnstatic 一个妥协方案是，把crop的宽高设成16:9，比如512:288（如果芯片是MTK的话数值必须保持32x）。更好的办法使用libyuv做缩放处理，降低手机功耗（发热）

**Comment by begeekmyfriend** [comment]
Yasea主干合并了，大家尝尝鲜吧，这次有惊喜～

**Comment by lisnstatic** [comment]
@begeekmyfriend  现在用全屏推流了，上面的问题就不存在了。但是转屏的时候都要重启推流，这个体验不好，如果不重启的话这个方法MediaFormat.createAudioFormat(MediaFormat.MIMETYPE_AUDIO_AAC, ASAMPLERATE, ach);就不会再执行，导致接收端还是竖屏，有什么办法吗

**Comment by begeekmyfriend** [comment]
@lisnstatic 不必重连，但宽高nexus 三星 小米都试了倒置以后编码器必须重启，就增加了响应时间，无法避免

**Comment by begeekmyfriend** [comment]
@crazyhl 你就做成全屏吧，反正最终都这样

**Comment by lisnstatic** [comment]
@begeekmyfriend 不重启的话，videoformat宽高不变，推送出去的流的宽高不变还是竖屏，接收端不会变成横屏的，怎么解决呢？

**Comment by begeekmyfriend** [comment]
@lisnstatic 永远竖屏推是吗，那我为你开个分支吧

**Comment by lisnstatic** [comment]
@begeekmyfriend 是的，固定竖屏。但手机横过来，推出去和接收到的都是横屏的。感谢~

**Comment by begeekmyfriend** [comment]
@lisnstatic Branch [portrait-forever](https://github.com/begeekmyfriend/yasea/tree/portrait-forever) for you.

**Comment by lisnstatic** [comment]
@begeekmyfriend 太感谢了，百忙之中还替小弟解决问题，我们建个群吧，很多小问题大家可以在群里沟通，你还能指点，你建一个，把群号公开出来哈~

**Comment by tz-xiaomage** [comment]
@begeekmyfriend 请问一下，关于这个分辨率的问题，我发现你最新的版本将宽高都是写死的final，是不建议修改分辨率还是？
不知道我们能不能通过获取手机所支持的分辨率，然后选择一个想要的大小进行设置？会有兼容性问题吗？
还有一个看不太懂的地方，就是
![image](https://cloud.githubusercontent.com/assets/12270504/15785772/a82e7b42-29eb-11e6-9037-8e91ae56384f.png)
这两个参数是为了做什么，希望能得到你的解答，感谢！

**Comment by tz-xiaomage** [comment]
@begeekmyfriend 这个crop裁剪出来的640*384是最终推送过去的宽高吗？

**Comment by tz-xiaomage** [comment]
@begeekmyfriend 在接收端看来，是依旧640*480的，所以应该不是裁剪完推送过去，那裁剪只是为了适配宽高？也就是ui上面显示的是640*384的宽度？然而实际上推送过去的是640*480？

**Comment by begeekmyfriend** [comment]
@tz-xiaomage 我调整了采样分辨率和剪裁分辨率，比例一致为16:9了https://github.com/begeekmyfriend/yasea/commit/c9c5ee8816ab76e9b270a92a26f89e14788bcd20

**Comment by begeekmyfriend** [comment]
@tz-xiaomage 为了达到你的效果，我把采样分辨率设为1280x720（只有16:9才能不变形），推流分辨率1024x576，这种大分辨率对于千元机来说已经很吃力了，我的OPPO A11输出帧率只有5.0fps。

**Comment by begeekmyfriend** [comment]
@tz-xiaomage 测试效果不理想，太卡了，连录制都卡，编码/推流分辨率还是必须得保持640左右的宽度才能顺畅，但是采集分辨率是可以设成720p的，关键还是缩放，缩放啊！

**Comment by tz-xiaomage** [comment]
@begeekmyfriend 我主要是希望能改成预览是宽高为4:3的比例，而推流过去也是4:3的比例

**Comment by begeekmyfriend** [comment]
@tz-xiaomage 手机屏幕都不是4:3的，怎么预览？

**Comment by tz-xiaomage** [comment]
@begeekmyfriend 手机是固定竖屏，宽度是占满的，而高度是宽度的四分之三

**Comment by tz-xiaomage** [comment]
@begeekmyfriend 而预览也是一样这个大小，宽度占满，高度是宽度的四分之三

**Comment by begeekmyfriend** [comment]
@tz-xiaomage crop仅是内存中的剪裁，实际呈现的仍是采样分辨率。

**Comment by tz-xiaomage** [comment]
@begeekmyfriend   也就是说，采集预览大小是640*480，播放器收到的也是640*480，那裁剪的目的是为了什么啊？

**Comment by tz-xiaomage** [comment]
@begeekmyfriend 实在是不好意思，我是菜鸟，如果清楚这个crop的值是为了做什么，我想就能通过遍历手机支持的分辨率，然后选择一个4:3的比例设置给宽高


![image](https://cloud.githubusercontent.com/assets/12270504/15809396/f2f4106e-2bc2-11e6-98c3-986e28efd606.png)

我能不能这样理解：
你设置为640*480，是因为分辨率太高会造成推流卡，就像你上面说的：编码/推流分辨率还是必须得保持640左右的宽度才能顺畅。
然后又因为手机屏幕的不同，而640*480在铺面屏幕的情况下，会让画面变形，所以你crop成16:9的比例然它显示在手机上面，也就是你设置的640*384，这样就能让预览画面看起来不变形，然而实际上推送到服务器的分辨率依旧是640*480？

**Comment by begeekmyfriend** [comment]
that is it

**Comment by tz-xiaomage** [comment]
这个是横屏的
![image](https://cloud.githubusercontent.com/assets/12270504/15810467/7eafee30-2bd1-11e6-9f95-1bb3e2f03404.png)

这个是竖屏的
![image](https://cloud.githubusercontent.com/assets/12270504/15810484/b5de18f0-2bd1-11e6-9c98-e05984dd74ab.png)

我突然发现，用你最新的master进行推流，然后我的播放器收到的画面宽高居然是384，横屏情况下是高度为384，竖屏情况下是宽度为384。

有个想法，不知道能不能让推流在竖屏的情况下，推的流像素是横屏情况下的样子，也就是竖屏推流宽高为640x384，而不是384x640

这个是推流端竖屏时候推流过去的样子，也就是宽高为384x640
![image](https://cloud.githubusercontent.com/assets/12270504/15810559/99710140-2bd2-11e6-8d0b-8d3dc1eb7a0f.png)

这个是推流端横屏时候推流过去的样子，也就是宽高为640x384
![image](https://cloud.githubusercontent.com/assets/12270504/15810564/a65a1e3c-2bd2-11e6-96ce-237f39078219.png)

能不能让竖屏的时候，推流过去的宽高为横屏时候的宽高？

**Comment by tz-xiaomage** [comment]
我非常确定推流过去的是裁剪之后的画面大小，我尝试将VCROP_WIDTH改为480，发现播放器接收到的是480
![image](https://cloud.githubusercontent.com/assets/12270504/15810653/5ad23f3e-2bd3-11e6-8d80-4dbde1e85520.png)

**Comment by tz-xiaomage** [comment]
@begeekmyfriend 如果是裁剪成什么样，推过去就是什么样的话，那就更好的，感觉宽高都能定制了

**Comment by begeekmyfriend** [comment]
@tz-xiaomage 我新建了[libyuv分支](https://github.com/begeekmyfriend/yasea/tree/libyuv)，解决了你的等比例缩放问题。目前只能做到这一步，接下来要看你自己的了，你懂的。

**Comment by begeekmyfriend** [comment]
https://github.com/begeekmyfriend/yasea/commit/4fbb1328a32b836086b86d82f7c2723c58241deb merged.
