### ISSUE TITLE
咨询一个硬编码的问题mediacodec

### ISSUE THREAD

**Issue by fly518420** [begeekmyfriend/yasea#190]
我使用硬编码 
int eobIndex = dstVideoEncoder.dequeueOutputBuffer(eInfo, WAIT_TIME);
这个地方得到的数据eInfo很小 导致观看的时候黑屏。
可以指点一下 吗？

**Comment by fly518420** [comment]
开始推流的时候 观看的时候第一帧画面会一闪而过的 然后就一直黑屏，观看有画面的时候 eInfo 的数据正常的，然后就非常小的一个固定值了，然后观看就黑屏了

**Comment by begeekmyfriend** [comment]
你讲得这么简略我也没法帮你。。。
