### ISSUE TITLE
mediacodec封装成flv回放时间不准确问题

### ISSUE THREAD

**Issue by hike2008** [begeekmyfriend/yasea#191]
流媒体服务器自动生成了flv回放, 但是播放读取的总时长不准确, 拖动超过一定长度就会从头开始播放

**Comment by begeekmyfriend** [comment]
这似乎不是推流端的问题吧。。。

**Comment by hike2008** [comment]
主要使用 三方云推流的SDK, 还有iOS端推流, 生成的flv生成就比较准确,  尝试设置时间戳都从0 开始, 短时间视频相对准确一些, 但是长了依然不准确

**Comment by begeekmyfriend** [comment]
你用的哪家服务器？

**Comment by hike2008** [comment]
流媒体服务器是百度的

**Comment by begeekmyfriend** [comment]
尝试换一家吧，或者用开源诸如[SRS 2.0 release](https://github.com/ossrs/srs/tree/2.0release)也行

**Comment by hike2008** [comment]
百度的是有什么问题么

**Comment by hike2008** [comment]
我试试看吧, 谢谢

**Comment by hike2008** [comment]
使用了srs尝试了下, 时长还是会虚高 , 不准确, 比如 47分钟的视频, 读取的总时长 是 1小时13分钟左右

**Comment by begeekmyfriend** [comment]
你推流使用`publish("record")`是吧？你拉流用的啥协议？

**Comment by hike2008** [comment]
rtmp协议

**Comment by begeekmyfriend** [comment]
服务器这边录制我也不是很清楚，你问一下`srs`作者
