### ISSUE TITLE
是否可以改变buff

### ISSUE THREAD

**Issue by Jack1103** [begeekmyfriend/yasea#192]
是够可以改变mic.read的buff大小，您的代码里是4096，我们需要更改为2048，但直接改的话，录制视频10秒就会快放为5秒了。

**Comment by begeekmyfriend** [comment]
这个缓存大小只是表明每次读取多少数据，怎么可能影响录制快慢？

**Comment by Jack1103** [comment]
现象是声音变声了，录制视频中声音变快了，不同轨了，视频10秒的话，5秒的时候声音就完了，声音也因此变了调。

**Comment by Jack1103** [comment]
请问一下我是不是不能只改4096为2048，相关的代码还需要更改呢？

**Comment by Jack1103** [comment]
虽然问题问得很低端，但这个问题我这真的存在

**Comment by Jack1103** [comment]
那我问一下，我直接把两个2048的byte合为一个byte[]为啥还是不行。

**Comment by Jack1103** [comment]
找到问题了，
        AudioRecord mic = new AudioRecord(MediaRecorder.AudioSource.DEFAULT,
                SrsEncoder.ASAMPLERATE, AudioFormat.CHANNEL_IN_STEREO,
                AudioFormat.ENCODING_PCM_16BIT, minBufferSize);

中的AudioFormat.CHANNEL_IN_STERE更改为AudioFormat.CHANNEL_IN_MONO后录制视频的时候声音变快了，这下能帮我解决一下问题吗？

**Comment by Jack1103** [comment]
改        int ach = aChannelConfig == AudioFormat.CHANNEL_IN_STEREO ? 2 : 1;
这个位置，视频声音卡顿。

**Comment by begeekmyfriend** [comment]
为何要改成MONO，手机录音设备原因？
