### ISSUE TITLE
Camera BackFace  

### ISSUE THREAD

**Issue by loidoan** [begeekmyfriend/yasea#193]
You can help me ? I want to start activity then camera backface defult?

**Comment by begeekmyfriend** [comment]
See [camera id](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/SrsCameraView.java#L21)

**Comment by loidoan** [comment]
Thank a lot. You can help me  problem other ! When start activity camera not show and theme black. I want to show camera review?
