### ISSUE TITLE
libyuv failure

### ISSUE THREAD

**Issue by veritas1** [begeekmyfriend/yasea#194]
Hey, Just trying out the sample app.

Camera is black to start. On switching camera, I get "libyuv failure" toast and camera freezes on first frame.

**Comment by begeekmyfriend** [comment]
Maybe some synchronization issue. I will keep track on it.

**Comment by begeekmyfriend** [comment]
Excuse me, could you retell your operations? When and how did you switch the camera?

**Comment by begeekmyfriend** [comment]
It also confuses me since some other users have also complained me about this issue. But it has not been reappearing on my phone and not all users have complained about it. So I am not sure whether it is a defect of my library or not.

**Comment by veritas1** [comment]
I found it only happened when using hardware encoders, switching to software encoders worked ok. But using hardware encoder setting, it happened every time.

**Comment by begeekmyfriend** [comment]
Every time? I am afraid it was the device issue.

**Comment by begeekmyfriend** [comment]
I apologize for my carelessness since it is really my fault. Now it is fixed https://github.com/begeekmyfriend/yasea/commit/42fd31eb5c6221e433ac1d1f9ce1abaa849a6f90
