### ISSUE TITLE
flvMuxer.writeSampleData 耗时很长，直播卡顿~

### ISSUE THREAD

**Issue by gzsll** [begeekmyfriend/yasea#195]
```
long start = System.currentTimeMillis();
flvMuxer.writeSampleData(videoFlvTrack, buffer, info);
Log.d(TAG, "writeSampleData:" + (System.currentTimeMillis() - start));
```

10-31 03:21:25.283 3568-4311/com.pursll.app D/SrsEncoder: writeSampleData:618
10-31 03:21:26.283 3568-4311/com.pursll.app D/SrsEncoder: writeSampleData:997
10-31 03:21:26.991 3568-4311/com.pursll.app D/SrsEncoder: writeSampleData:706
10-31 03:21:27.760 3568-4311/com.pursll.app D/SrsEncoder: writeSampleData:768
10-31 03:21:28.534 3568-4311/com.pursll.app D/SrsEncoder: writeSampleData:773
10-31 03:21:29.409 3568-4311/com.pursll.app D/SrsEncoder: writeSampleData:875
10-31 03:21:29.924 3568-4311/com.pursll.app D/SrsEncoder: writeSampleData:514
10-31 03:21:30.557 3568-4311/com.pursll.app D/SrsEncoder: writeSampleData:632
10-31 03:21:31.077 3568-4311/com.pursll.app D/SrsEncoder: writeSampleData:518
10-31 03:21:31.786 3568-4311/com.pursll.app D/SrsEncoder: writeSampleData:709
10-31 03:21:32.279 3568-4311/com.pursll.app D/SrsEncoder: writeSampleData:492
10-31 03:21:32.931 3568-4311/com.pursll.app D/SrsEncoder: writeSampleData:651
10-31 03:21:33.369 3568-4311/com.pursll.app D/SrsEncoder: writeSampleData:437

**Comment by begeekmyfriend** [comment]
Have you modified the original code? This function is non block.

**Comment by gzsll** [comment]
找到问题了，是用freeline编译出现的问题~删掉就好了
