### ISSUE TITLE
软编 花屏

### ISSUE THREAD

**Issue by ZhangGuangXin** [begeekmyfriend/yasea#197]
您好，我在自己的项目中集成您的这个库，我用的是自己的相机，对采集的数据做美颜之后，将数据转换为nv21格式的，然后调用您的编码和推流的功能，但是在服务器端看到的是一片花屏。请教一下，这是什么原因。我用的是软编

**Comment by ZhangGuangXin** [comment]
我是通过SrsEncoder.onGetYuvFrame(byte[] data)函数将nv21数据传入的

**Comment by begeekmyfriend** [comment]
这种集成可能涉及兼容的问题，我也没法帮你定位。而且图像处理的数据格式一般是rgba而不是NV21了。如果你需要美颜相机，请用[gpuimage](https://github.com/begeekmyfriend/yasea/tree/gpuimage)分支

**Comment by ZhangGuangXin** [comment]
谢谢你回复我的问题，问题找到了，是我们预览的分辨率和你SrsEncoder中的分辨率设置的不一样，都统一设置之后，问题就解决了。
再次感谢你。
