### ISSUE TITLE
arm64-v8a 编译出错

### ISSUE THREAD

**Issue by chinabigcat** [begeekmyfriend/yasea#198]
[arm64-v8a] SharedLibrary  : libenc.so
jni/lib/libx264.a: error adding symbols: File in wrong format
collect2.exe: error: ld returned 1 exit status
make: *** [obj/local/arm64-v8a/libenc.so] Error 1

64位手机无法正常使用么

**Comment by begeekmyfriend** [comment]
arm64-v8a NDK building for [libx264](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/libenc/jni/libx264/android_build_arm64_v8a.sh) and [libyuv](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/libenc/jni/libyuv/jni/Application.mk) are now both provided.

By the way, 64-bit mobile devices are always supporting 32-bit application. The reason why I do not provide so files is about GLES performance. See #177
