### ISSUE TITLE
  setSendAudioOnly(true) 没作用呢

### ISSUE THREAD

**Issue by liuzipei** [begeekmyfriend/yasea#199]
如题，求大神讲解哈我只想传音频  可是设置这个没什么效果呢

**Comment by begeekmyfriend** [comment]
在什么地方设置的？

**Comment by liuzipei** [comment]
mPublisher.setSendAudioOnly(true);
        mPublisher.startPublish(rtmpUrl);
如果是开启视频后 设置为true 就可以  ，但是我只想传音频

**Comment by begeekmyfriend** [comment]
你看logcat是否只传了audio packet，我之前测过是可以的。至于拉流端效果如何，要问服务器了

**Comment by liuzipei** [comment]
mPublisher.setSendAudioOnly(true);
mPublisher.startPublish(rtmpUrl);
如果只是这么设置  程序没有启动录音，我仔细分析了哈代码，发现必须先启动视频传输，创建“mFlvMuxer 成功后”才行：：：：
if (mFlvMuxer != null) {
            try {
                mFlvMuxer.start(rtmpUrl);
            } catch (IOException e) {
                e.printStackTrace();
                return;
            }
            mFlvMuxer.setVideoResolution(mEncoder.getOutputWidth(), mEncoder.getOutputHeight());

            startEncode();
        }

**Comment by begeekmyfriend** [comment]
嗯，那可能是audio的sequence header（第一帧）被漏掉了

**Comment by liuzipei** [comment]
可能 ，那就只能使用视频流的时候，然后关闭视频数据，只流音频。另外问哈 设置 mPublisher.setSurfaceView(null);为空，为什么发送不了视频呢，我只是不想预览，应该可以用啊！

**Comment by begeekmyfriend** [comment]
camera如果不绑定到surface也就不会有preview callback了，SDK就是这么用法

**Comment by liuzipei** [comment]
一语提醒梦中人！看代码看糊涂了，只开启音频提示：MP3Extractor: Unable to resync. Signalling end of stream
alsa_ucm: No valid device/modifier found with given identifier: None
可以有比较简单的解决方法吗

**Comment by begeekmyfriend** [comment]
不太明白你的logcat怎么来的

**Comment by liuzipei** [comment]
mPublisher.setSendAudioOnly(true);
mPublisher.startPublish(rtmpUrl);
只如此设置，点击开始开启mPublisher.startPublish(rtmpUrl);
然后就logcat：MP3Extractor: Unable to resync. Signalling end of stream

**Comment by begeekmyfriend** [comment]
没复现到你的情况

**Comment by liuzipei** [comment]
mPublisher.setSendAudioOnly(true);
mPublisher.startPublish(rtmpUrl);
那只设置这两个参数，你那边能传输出去吗？

**Comment by begeekmyfriend** [comment]
有logcat
