### ISSUE TITLE
Can this stream to any media Server with RTMP ingest capability or only SRS?

### ISSUE THREAD

**Issue by gouravd** [begeekmyfriend/yasea#2]
Can this stream to any media Server with RTMP ingest capability or only SRS?

**Comment by begeekmyfriend** [comment]
Servers which support FMLE (flash media live encoder) including SRS, FMS, nginx-rtmp and Red5 so on.

**Comment by begeekmyfriend** [comment]
A friend of mine found there is an unnecessary testing console log in your
Voola webpage scripts, may be in scripts.js? He is a brilliant front-end
engineer. You'd better remove it.😂



2016-04-26 15:46 GMT+08:00 das_vicky <notifications@github.com>:

**Comment by gouravd** [comment]
Will do :)
