### ISSUE TITLE
i  set  the  VFPS in  SrsEncoder.java,  but it  did'nt  work  to  change fps, could you  answer  me?  thans  inadvace~ 

### ISSUE THREAD

**Issue by lisnstatic** [begeekmyfriend/yasea#20]
could you tell me I can  change  fps  in  which  place , thank  you very  much,I  bothered by this question  for  some days

**Comment by lisnstatic** [comment]
I want to change  the value of  fps  bymyself ,  so I  modify the "public static final int VFPS = 15;" ,but  I  see  the  fps stil  can achieve  25,26,27.....

**Comment by begeekmyfriend** [comment]
It depends on your mobile manufacturers who may implement by themselves at low level and ignore the set method of FPS.

**Comment by lisnstatic** [comment]
it is to  say， I  can do nothing  about  the  frame  rate？  but  I  think  the  frame  rate  I  received  really  too  low， could  you  give  me  some suggestions？

**Comment by begeekmyfriend** [comment]
I am afraid that is the limitation of android device as known as lack of standard.

**Comment by begeekmyfriend** [comment]
你这么一说我想起来了，yasea视频前处理和UI在同一个线程里，计算量很大，的确是瓶颈

**Comment by begeekmyfriend** [comment]
It is the same after separating YUV processing from UI thread. That is still the issue of camera device.

**Comment by begeekmyfriend** [comment]
Nexus, son of Google, can assure that setting method.
