### ISSUE TITLE
Send only video ?- switch mute method not working ? 

### ISSUE THREAD

**Issue by oantajames** [begeekmyfriend/yasea#201]
Hi,
I am trying to set the streamer to send only video packets. I saw that there is a method in the SrsPublisher named "switchMute" 
`  public void switchMute() {
        AudioManager audioManager = (AudioManager) mCameraView.getContext().getSystemService(Context.AUDIO_SERVICE);
        int oldMode = audioManager.getMode();
        audioManager.setMode(AudioManager.MODE_IN_COMMUNICATION);
        boolean isMute = !audioManager.isMicrophoneMute();
        audioManager.setMicrophoneMute(isMute);
        audioManager.setMode(oldMode);
    }`

I have tried to use it, but still the audio packets are also sent, and the micrphone is not muted...
Any suggestions how to do this? 
Thanks in advance! #

**Comment by begeekmyfriend** [comment]
The simplest thing is not to pass PCM data through `onGetPcmFrame` callback.

**Comment by oantajames** [comment]
What is the point of the above method ? Could you please explain ? Is it related to this topic ? Thanks!

**Comment by oantajames** [comment]
@begeekmyfriend just resolved this with the helo of the above mentioned callback. 
For anyone trying to dot his --> 
` private void startAudio() {
        if (mic != null) {
            mic.startRecording();

            byte pcmBuffer[] = new byte[4096];
            while (aloop && !Thread.interrupted()) {
                int size = mic.read(pcmBuffer, 0, pcmBuffer.length);
                if (size <= 0) {
                    break;
                }
              #   if (!sendVideoOnly) {
                    mEncoder.onGetPcmFrame(pcmBuffer, size);
                }
            }
        }
    }`

I just added a flag in the class that can be set from the activity.

Thanks for the help @begeekmyfriend !
