### ISSUE TITLE
x86_64 compilation problem

### ISSUE THREAD

**Issue by RaulZhn** [begeekmyfriend/yasea#203]
I try to build libenc for x86_64 arch using ndk-build but the following error occurs:

/home/raul/Android/Sdk/ndk-bundle/toolchains/x86_64-4.9/prebuilt/linux-x86_64/lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: /home/raul/yasea/app/src/main/libenc/jni/lib/libx264.a(cabac-a.o): requires dynamic R_X86_64_PC32 reloc against 'x264_cabac_range_lps' which may overflow at runtime; recompile with -fPIC
/home/raul/Android/Sdk/ndk-bundle/toolchains/x86_64-4.9/prebuilt/linux-x86_64/lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: /home/raul/yasea/app/src/main/libenc/jni/lib/libx264.a(quant-a.o): requires dynamic R_X86_64_PC32 reloc against 'x264_decimate_table4' which may overflow at runtime; recompile with -fPIC
/home/raul/Android/Sdk/ndk-bundle/toolchains/x86_64-4.9/prebuilt/linux-x86_64/lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: /home/raul/yasea/app/src/main/libenc/jni/lib/libx264.a(dct-a.o): requires dynamic R_X86_64_PC32 reloc against 'x264_sub8x8_dct_sse2.skip_prologue' which may overflow at runtime; recompile with -fPIC
/home/raul/Android/Sdk/ndk-bundle/toolchains/x86_64-4.9/prebuilt/linux-x86_64/lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: /home/raul/yasea/app/src/main/libenc/jni/lib/libx264.a(trellis-64.o): requires dynamic R_X86_64_PC32 reloc against 'x264_cabac_entropy' which may overflow at runtime; recompile with -fPIC
/home/raul/Android/Sdk/ndk-bundle/toolchains/x86_64-4.9/prebuilt/linux-x86_64/lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: warning: shared library text segment is not shareable
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/home/raul/yasea/app/src/main/libenc/obj/local/x86_64/libenc.so] Error 1

**Comment by begeekmyfriend** [comment]
x86 native for [libx264](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/libenc/jni/libx264/android_build_x86.sh) and [libyuv](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/libenc/jni/libyuv/jni/Application.mk) are both provided. x86_64 are compatible.
