### ISSUE TITLE
What's the different between master and gpuimage branch?

### ISSUE THREAD

**Issue by gotounix** [begeekmyfriend/yasea#204]

**Comment by begeekmyfriend** [comment]
For Android system if which integrates OpenGL ES libraries or not.

**Comment by begeekmyfriend** [comment]
For Android system if which integrates OpenGL ES libraries or not.

**Comment by gouravd** [comment]
I think the video filters should be part of the the main branch as well. How about merging the feature to the main branch?

**Comment by begeekmyfriend** [comment]
@gouravd Because some people would apply yasea to android development boards for security monitoring and control business which do not integrate OpenGL ES libraries.

**Comment by gouravd** [comment]
Got it! So its a difficult job to keep both the branches upto date
