### ISSUE TITLE
红米note 1S 报错

### ISSUE THREAD

**Issue by JakeRed** [begeekmyfriend/yasea#205]
Hi，Begeekmyfriend：

    使用Yasea在红米note 1S，android版本5.1.使用软件编码是切换横竖屏的时候报错。
    错误信息：
     android.media.MediaCodec.native_stop(Native Method)
     android.media.MediaCodec.stop(MediaCodec.java:631)
     net.ossrs.yasea.SrsEncoder.stop(SrsEncoder.java:206)
     net.ossrs.yasea.SrsPublisher.stopEncode(SrsPublisher.java:118)
总的来说就是MediaCodec的stop方法报错：vencoder.stop();
如果您之前有遇到过希望能告诉下解决方案。

**Comment by begeekmyfriend** [comment]
No such device for me...

**Comment by JakeRed** [comment]
Today, Generate a bug in red HongMi Phone，The log is as follows: 
 java.lang.IllegalArgumentException Bad limit (capacity 1453): 1513
java.nio.Buffer.limit(Buffer.java:298)
net.ossrs.yasea.SrsMp4Muxer.writeSampleData(SrsMp4Muxer.java:940)
net.ossrs.yasea.SrsMp4Muxer.access$400(SrsMp4Muxer.java:65)
net.ossrs.yasea.SrsMp4Muxer$1.run(SrsMp4Muxer.java:166)
java.lang.Thread.run(Thread.java:818)

error code:
byteBuf.limit(bi.offset + bi.size);

**Comment by begeekmyfriend** [comment]
Have you modified the original code?

**Comment by JakeRed** [comment]
no

**Comment by JakeRed** [comment]
Only appears in red this phone，Do you help me？

**Comment by begeekmyfriend** [comment]
Have you upgraded to the latest version?

> net.ossrs.yasea.SrsMp4Muxer.writeSampleData(SrsMp4Muxer.java:940)

**Comment by JakeRed** [comment]
I used Yasea2.0.   I just add a note in the source.

**Comment by begeekmyfriend** [comment]
It is hard for me to locate the line of the code if we have different versions.

**Comment by JakeRed** [comment]
![Uploading QQ图片20161108104538.png…]()
this line.

**Comment by JakeRed** [comment]
![image](https://cloud.githubusercontent.com/assets/21214880/20084948/a163b9f4-a5a0-11e6-8d45-d2c38e5794e5.png)
this line.

**Comment by JakeRed** [comment]
in SrsMp4Muxer.java

**Comment by begeekmyfriend** [comment]
Then comment out this line and see the effect.

**Comment by JakeRed** [comment]
Let me try

**Comment by begeekmyfriend** [comment]
If it does not work, then comment out both two lines,

>     byteBuf.position(bi.offset + (isAudio ? 0 : 4));
        byteBuf.limit(bi.offset + bi.size);
