### ISSUE TITLE
Optimization Proposal

### ISSUE THREAD

**Issue by blueseaandsky** [begeekmyfriend/yasea#206]
在帧率比较低的时候（我这里是30fps），使用ffplay.exe拉流，ffplay总是输出下面的信息，请问下楼主，有什么优化的建议，非常感谢！！

还有一个问题，为什么更低帧率的时候，是音频先出问题呢，很疑惑！

Input #0, flv, from 'rtmp://192.168.0.1/oflaDemo/live1 live=1':/0
  Metadata:
    length          : 10
  Duration: 00:00:00.00, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (Constrained Baseline), yuv420p, 640x384, 33.33 fps
, 33 tbr, 1k tbn, 66 tbc
    Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp
[aac @ 0000006450d45900] channel element 0.0 is not allocated=0/0
[aac @ 0000006450d45900] channel element 0.0 is not allocated=0/0
[aac @ 0000006450d45900] channel element 0.0 is not allocated=0/0
    Last message repeated 1 times
[aac @ 0000006450d45900] channel element 0.0 is not allocated=0/0

**Comment by begeekmyfriend** [comment]
没遇到你的问题，也许该问问服务器

**Comment by begeekmyfriend** [comment]
没遇到你的问题，可能跟你网络环境（服务器），或者手机设备有关
