### ISSUE TITLE
ADTS问题

### ISSUE THREAD

**Issue by KeaneQian** [begeekmyfriend/yasea#208]
楼主，我发现有时候有些手机录制的流不带ADTS头，我看里面有一点ADTS的东西，但是没有用，这个ADTS的适配有计划修一下么？

**Comment by begeekmyfriend** [comment]
ADTS对于流媒体来说没必要

**Comment by KeaneQian** [comment]
哦哦，谢谢哈，这么快回复了。RTMP里面应该都带了ADTS的吧？我们有些手机推流的时候发现有些播放端放不了，然后存文件发现没有ADTS的头
或者
传了两个文件，vlc-output_no_adts.ts是无法播放的，vlc-output_adts.ts可以播放，帮我分析下是什么原因呀，这个支持可以付费哈

**Comment by begeekmyfriend** [comment]
Added https://github.com/begeekmyfriend/yasea/commit/676fd9cce9f5809de20de7f1ab3e486770ee2838

**Comment by KeaneQian** [comment]
哈哈，感谢楼主哈，真的太感谢了。
楼主能给个捐献的方式么？或者加下我QQ=492090511，略表感谢，知道支持开源不容易，特别是一直支持自己开源的内容的大神们。

**Comment by begeekmyfriend** [comment]
加个微信吧：begeekfriend
