### ISSUE TITLE
How to push RTMP live stream?

### ISSUE THREAD

**Issue by gotounix** [begeekmyfriend/yasea#209]
I test it for pushing HLS live stream with [nginx-rtmp-module](https://github.com/arut/nginx-rtmp-module), but failed to push RTMP live stream?
```
rtmp {
    server {
        listen 8899;
        application live {
            live on;
            record off;
        }
}
```
Does it support the application of RTMP server or just support HLS ?
Thanks!

**Comment by begeekmyfriend** [comment]
The port number should be 1935.
