### ISSUE TITLE
How to change the resolution of the push?

### ISSUE THREAD

**Issue by tz-xiaomage** [begeekmyfriend/yasea#21]
How to change the resolution of the push?
Can be compatible with the resolution of the different mobile phone support, and to set the size of the preview, frame deformation

**Comment by begeekmyfriend** [comment]
You may query `getSupportedPictureSizes()` or `getSupportedPreviewSizes()` camera paremeter method to select one.

**Comment by tz-xiaomage** [comment]
@begeekmyfriend 
![image](https://cloud.githubusercontent.com/assets/12270504/15455035/e39a31f0-207a-11e6-8688-dd6060d73607.png)
If I modify the VWIDTH=1280 and VHEIGHT=720, VCROP_WIDTH and VCROP_HEIGHT need to be modified?
This VCROP_WIDTH with VCROP_HEIGHT is pushed to the server of the real size it?
And VWIDTH and VHEIGHT are just the size of the preview?

**Comment by begeekmyfriend** [comment]
Crop resolution is defined by yourself only if the size is less than the preview one.

**Comment by banketree** [comment]
List<Camera.Size> previewSizes = params.getSupportedPreviewSizes();
			List<Camera.Size> pictureSizes = params.getSupportedPictureSizes();
			sPreviewSizes.clear();
			for (int i = 0; i < previewSizes.size(); i++) {
				float pFloat = (float) (previewSizes.get(i).width * 1.00 / previewSizes
						.get(i).height);
				if (pFloat > 1.7)//16：9
					sPreviewSizes.add(previewSizes.get(i));
			}

**Comment by lisnstatic** [comment]
@tz-xiaomage 
do  you  resolve  the question？I  set  the  resolution ，but  I  received  the flash  screen 。are you  Chinese ？

**Comment by begeekmyfriend** [comment]
Setting the surface view as full screen might be the solution. See #19

**Comment by begeekmyfriend** [comment]
I have changed UI layout as full screen mode https://github.com/begeekmyfriend/yasea/commit/25ab6f385f315afd9634266ec91283e044ad42b1
