### ISSUE TITLE
Android仅仅使用推流部分

### ISSUE THREAD

**Issue by ZhangGuangXin** [begeekmyfriend/yasea#210]
您好，我在做一个项目，我们有自己的视频采集和美颜处理，硬编也是我们自己实现。我们想用到您的推流的那部分。但是各种尝试之后，一直没有成功。
      我们将自己硬编的数据传进SrsEncoder的onGetYuvFrame(byte[] data)中，然后对onGetYuvFrame(byte[] data)函数做了如下修改：
            if (useSoftEncoder) {
                if (mOrientation == Configuration.ORIENTATION_PORTRAIT) {
                    swPortraitYuvFrame(data, pts);
                } else {
                    swLandscapeYuvFrame(data, pts);
                }
            } else {
                byte[] processedData = data;
//                        mOrientation == Configuration.ORIENTATION_PORTRAIT ?
//                        hwPortraitYuvFrame(data) : hwLandscapeYuvFrame(data);
                if (processedData != null) {
                    onProcessedYuvFrame(processedData, pts);
                } else {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(),
                            new IllegalArgumentException("libyuv failure"));
                }
            }
       也就是说我直接把数据传进onProcessedYuvFrame( )函数中，而没有经过之前的颜色转换。然后在服务器端看到的是一片黑屏。
         我的理解是我自己硬编的数据是h.264，而且你的onProcessedYuvFrame( )函数应该就是做推流的事情，理论上是可以的呀。
         其实我也尝试过，不注释那两行代码，但是在服务器上看到的是花屏。

**Comment by begeekmyfriend** [comment]
The data passed down to `onProcessedYuvFrame` is the YUV data that has been pre-processed but not encoded and to be sent into the encoder.  Try `onEncodedAnnexbFrame` function for encoded stream.

**Comment by ZhangGuangXin** [comment]
private void onProcessedYuvFrame(byte[] yuvFrame, long pts) {
        ByteBuffer frameBuffer = ByteBuffer.wrap(yuvFrame);
        onEncodedAnnexbFrame(frameBuffer, vebi);
    }
我把onProcessedYuvFrame改成这样，可以吗？同时我把onGetYuvFrame()函数中的如下一段代码去掉了。
                byte[] processedData = mOrientation == Configuration.ORIENTATION_PORTRAIT ?
                        hwPortraitYuvFrame(data) : hwLandscapeYuvFrame(data);

刚才试了一下，还是不行。

**Comment by begeekmyfriend** [comment]
横竖屏不是关键，我没弄明白你的数据到了哪个阶段，是YUV还是H.264？另外，分辨率对了吗？代码接口已经够明白了，就看你的参数是否匹配。

**Comment by ZhangGuangXin** [comment]
是h.264的。软编我们也用的是你这个库，分辨率应该是对的，因为软编情况下，一切正常。

**Comment by ZhangGuangXin** [comment]
软编部分我们是将nv21的数据传递到onGetYuvFrame()函数，硬编我们传递进来的是h.264

**Comment by begeekmyfriend** [comment]
H.264的就应该使用`onEncodedAnnexbFrame`，除非格式不是AnnexB
