### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Hassaram** [begeekmyfriend/yasea#213]
Hi. Was anyone able to get this along with the related project https://github.com/ossrs/srs/tree/2.0release to work?

I always get one of the following errors in the android project:
libyuv failure
Network weak
Connection to server-ip port 1935 timed out after 1935 s

Sometimes I get the error that the application has stopped working so basically an unexpected error occurred.

The server project does not get any error so far.

Thanks in advance.

**Comment by begeekmyfriend** [comment]
The "network weak" and "connection timeout" are your networking issues.

How does the "libyuv failure" happen?

By the way, SRS is not my project.
