### ISSUE TITLE
record MP4

### ISSUE THREAD

**Issue by JakeRed** [begeekmyfriend/yasea#217]
https://ipc.blob.core.chinacloudapi.cn/10056/4c0217e6-9ab9-4721-ae43-8223e660af3a.mp4?sv=2015-12-11&sr=c&sig=TNmpur6%2BudsQEh5GyQH1QyCJOQ3ptmGT%2BHl9rx%2FgDYE%3D&se=2016-11-20T09%3A50%3A18Z&sp=r
这是我用软编码录制的视频，您使用ie打开看一下，还有mac自带的浏览器。

**Comment by JakeRed** [comment]
花屏，但360浏览器，谷歌都是好用的。

**Comment by begeekmyfriend** [comment]
那就是解码器的问题了

**Comment by JakeRed** [comment]
我们需要分享视频功能，这至少要保证ios设备可播放。

**Comment by begeekmyfriend** [comment]
那就需要研究一下苹果的MP4格式有何异同，目前我自己到没这个需求

**Comment by JakeRed** [comment]
前辈，我想先试一下改codec，您看一下这地方都支持怎么改：
![image](https://cloud.githubusercontent.com/assets/21214880/20205801/a8d5ac38-a816-11e6-8f34-93bd3897a470.png)

**Comment by JakeRed** [comment]
![image](https://cloud.githubusercontent.com/assets/21214880/20205813/dbbf6d3c-a816-11e6-80df-72646ef81c72.png)
是这里的都可以吗？

**Comment by begeekmyfriend** [comment]
你在苹果的设备上去研究安卓codec？

**Comment by JakeRed** [comment]
去找一个都支持的codec，我先确定您的框架都支持这些codec？

**Comment by JakeRed** [comment]
问一下：video codec 和H264的关系，ios用avc1。

**Comment by JakeRed** [comment]
前辈，您好：

    对比了两个视频：
ios录制：
![ccb3 u2noo6idf3j 7fx c](https://cloud.githubusercontent.com/assets/21214880/20206978/2d59c43c-a81f-11e6-887b-660ba9ebb73c.png)

android录制：

![53ilel1 j f641 rx9cmy1](https://cloud.githubusercontent.com/assets/21214880/20206989/429cf260-a81f-11e6-9866-2c52988b934d.png)

麻烦您看一下，我们的codec都是一样的，我使用的软编码，然后出现了ie浏览器，ios自带浏览器不能播放。

**Comment by JakeRed** [comment]
![image](https://cloud.githubusercontent.com/assets/21214880/20207218/ae6c3a4a-a820-11e6-8bc4-deb235b98975.png)
这个值ze怎么设置呢？

**Comment by JakeRed** [comment]
我的问题就是您在软编码情况下录制的视频windows 自带的播放器播放不了，这个问题也应该算问题。

**Comment by begeekmyfriend** [comment]
没复现到你所说的，你用的win10？还是改了代码？

**Comment by JakeRed** [comment]
win10，代碼沒改動。

**Comment by JakeRed** [comment]
![image](https://cloud.githubusercontent.com/assets/21214880/20251937/a16dcdce-aa58-11e6-998b-c69f60d9bbe3.png)
圖上面是正常的硬編碼視頻，下面是軟件編碼視頻信息，就途中圈的部分不一樣，可否能指點一下，前輩，謝謝！

**Comment by begeekmyfriend** [comment]
你用了什么ffmpeg命令？试试ffplay.exe xxx.mp4

**Comment by JakeRed** [comment]
我用的 ffmpeg.exe -i xxx.mp4
得到的mp4信息，您看一下是不是baseline的事？

**Comment by JakeRed** [comment]
![image](https://cloud.githubusercontent.com/assets/21214880/20254019/8dd290c0-aa6b-11e6-9f41-953aac27b205.png)
這是不正常的軟編碼視頻信息。
![image](https://cloud.githubusercontent.com/assets/21214880/20254038/b71de9c0-aa6b-11e6-821c-1e4a9f1b596e.png)
這個是正常的硬編碼的mp4文件信息。

問題是出在win10情況下ie瀏覽器播放視頻花屏。

**Comment by JakeRed** [comment]
![image](https://cloud.githubusercontent.com/assets/21214880/20254090/0b79109e-aa6c-11e6-99f2-f2ea1c1806e7.png)

**Comment by JakeRed** [comment]
前輩您幫我看看有辦法將Constrained Baseline 改爲 Baseline  看看效果嗎？

**Comment by JakeRed** [comment]
除了改視頻分辨率我是真的什麽都沒改，大哥。

**Comment by JakeRed** [comment]
![image](https://cloud.githubusercontent.com/assets/21214880/20255948/75b72022-aa7b-11e6-8609-89f226e6b0b7.png)
下了最新的demo，軟件編碼，錄製視頻，結果用windows自帶的播放器是這個效果。

**Comment by begeekmyfriend** [comment]
x264的baseline profile本来就对应[Constrained Baseline](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/libenc/jni/libx264/encoder/encoder.c#L1712) ，由于是手机设备所以用了最节能的配置，yasea 不会更改它，但你可以在 libenc.cc 里自己指定profile，方法或接口网上自己查吧。

**Comment by JakeRed** [comment]
我的目的是想解決上述花屏的问题，BaseLine是最好的profile，但是如果花屏和这个有关系那就没办法必须要改了。

**Comment by JakeRed** [comment]
现在java层的代码不管怎么改，这个花屏总是不能解决。

**Comment by begeekmyfriend** [comment]
估计你还是给微软报bug更靠谱，何不在win7上试试呢？

**Comment by JakeRed** [comment]
迅雷看看，Safari，IE 好几个都是这个效果，但是用视频格式转换软件MP4格式转MP4格式后就好了，我觉得一定是mp4的头部信息或配置信息的问题吧。

**Comment by begeekmyfriend** [comment]
yasea本来就是流媒体的录制方式，不太可能做到像制作一个完整视频文件那样所有信息都收录进来。实际上，录制的逻辑是从[Telegram](https://github.com/DrKLO/Telegram/tree/master/TMessagesProj/src/main/java/org/telegram/messenger/video)脱胎而来的。

**Comment by JakeRed** [comment]
ffmpeg.exe -i 1.mp4 out.mp4之后，变为High了，这个out.mp4就支持ie之类的播放了。我想问一下BaseLine 和 那个Constrained Baseline 之间的关系是啥呀，因为硬件编码的是BaseLine，播放无障碍，那么我们是不是有可能按着这个想法来弄一下？

谢谢前辈。

**Comment by JakeRed** [comment]
Constrained Baseline转为BaseLine其实就好了，请问我应该怎么改呢？

**Comment by JakeRed** [comment]
恩，我试着去改一下prefile为High，这样是不是软件编码也会为High呢？

**Comment by JakeRed** [comment]
修改这里可以吗？ const char *profile = h->sps->i_profile_idc == PROFILE_BASELINE ? "Constrained Baseline" :
还是必须要去 libenc.cc 里自己指定profile，

**Comment by begeekmyfriend** [comment]
做过开发吗？
