### ISSUE TITLE
关于推流，画面移动时观看会模糊。类似于马赛克的感觉。

### ISSUE THREAD

**Issue by z2045217** [begeekmyfriend/yasea#219]
人物移动时推流端没有问题，但是接受数据观看的时候。会出现画面模糊的感觉。是因为 mPublisher.setPreviewResolution和 mPublisher.setOutputResolution()数值差别过大引起的吗？还是别的原因。

**Comment by begeekmyfriend** [comment]
网不太好，不一定是上行的网。当然你也可以降低分辨率来避免影响。

**Comment by blueseaandsky** [comment]
我这试过很多播放器，也有拉流移动视频不清楚的问题。
