### ISSUE TITLE
Push the picture in other mobile phone, color is not the same

### ISSUE THREAD

**Issue by tz-xiaomage** [begeekmyfriend/yasea#22]
Huawei mobile phone P6-4.4.2 T00 version, before using the camera push pictures in other mobile phones, is have off color

**Comment by begeekmyfriend** [comment]
Please show me the [logging](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/sea/SrsEncoder.java#L512)

**Comment by tz-xiaomage** [comment]
@begeekmyfriend 
I can not see what is wrong, there is no error, but push past the picture is the existence of color, I will send a photo

**Comment by banketree** [comment]
大部分Camera都是使用420，如果你的机子是442，你可以增加一个442的操作（442转到420 或 442 to h263）

**Comment by begeekmyfriend** [comment]
Now soft encoding is added into the latest version.
