### ISSUE TITLE
APK

### ISSUE THREAD

**Issue by breon** [begeekmyfriend/yasea#221]
Hi there!
I'm very interested in this project. I'm not an Android developer, but I know enough to install and run Android Studio. However, after a couple of hours of setting everything up, I'm still having issues building the project.

To make it easier to install on my phone, can you publish an APK when you cut a release? I would really appreciate it! :)

Thanks,
Breon

**Comment by begeekmyfriend** [comment]
https://github.com/begeekmyfriend/yasea-apk

Note: Not include the latest code.
