### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by HuuThang91** [begeekmyfriend/yasea#222]
I am running  your project in eclipsse and i got this error
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memclr4" referenced by "/data/app/net.ossrs.yasea.demo-1/lib/arm/libyuv.so"...
what should i do

**Comment by begeekmyfriend** [comment]
I have no idea about eclipse, I do use Android Studio.

**Comment by HuuThang91** [comment]
im sorry, in android studio 
first , my gradew is 2.4 , and i downgrade it to 2.1.4 .Then the error come up.

**Comment by begeekmyfriend** [comment]
Not yet reappear your issue cloning the whole project and running it. What is your architecture? armeabi-v7a or others? The `so` files are in the `/library/src/main/jniLibs/armeabi-v7a`

**Comment by kwey521** [comment]
i met the same issue when i clone the whole project. i use two phones(cpus are both arm64-v8a) , but only one is appeared.The big difference between the two is that the normal is OS-5.0 and the abnormal is OS-6.0. I wonder if the difference can affect that. thanks in advance.

**Comment by begeekmyfriend** [comment]
In fact my Nexus 5x with Android 7.0+ can both run under armeabi-v7a and arm64-v8a,. I am afraid I have no advice for you on this issue.

**Comment by begeekmyfriend** [comment]
By the way, I think you can build `so` files under arm64-v8a by yourself. The building scripts are provided as follows:
`/library/src/main/libenc/jni/libyuv/jni/Application.mk`
`/library/src/main/libenc/jni/libx264/android_build_arm64_v8a.sh`
`/library/src/main/libenc/jni/Application.mk`

**Comment by pcyan** [comment]
这是因为项目的targetSdkVersion低于ndk的编译对应的版本才会导致的，我降低了Application.mk中的版本到22后，就没有这个问题了

**Comment by begeekmyfriend** [comment]
That is why your phone is unsatisfied.

**Comment by kelmer44** [comment]
I also face the same problem with Samsung Galaxy S7. Only Nougat OS version is supported now "officially"?

**Comment by begeekmyfriend** [comment]
Sorry, My fault. Here is the fix https://github.com/begeekmyfriend/yasea/commit/2c4e21603edbae44b108ee3e384cd81e2e2e346f
