### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by JakeRed** [begeekmyfriend/yasea#223]
Hi，前辈：

    我想编译libyuv.so，然后装好了环境，因为我的目前是之前的想改profile，但是编译的时候mk文件看起来好像有问题。
ifeq ($(TARGET_ARCH_ABI),armeabi-v7a)
    LOCAL_SRC_FILES := libs/armeabi-v7a/libyuv.so
endif
   //这个位置我来的目的是编译so，一上来就一个等号，直接就报错了

请问一下我应该怎么编译呢。

谢谢您。

**Comment by JakeRed** [comment]
上图：
![image](https://cloud.githubusercontent.com/assets/21214880/20293729/c88c54bc-ab33-11e6-8185-8862fcdcc75c.png)

**Comment by JakeRed** [comment]
![image](https://cloud.githubusercontent.com/assets/21214880/20293841/8314c4cc-ab34-11e6-9bf9-e0189a84ff3e.png)
这里也编译了。

**Comment by JakeRed** [comment]
![image](https://cloud.githubusercontent.com/assets/21214880/20293929/4e21b026-ab35-11e6-9c29-0d9aec5eaf22.png)

**Comment by JakeRed** [comment]
前辈，指导一下吧，，十分感谢。

**Comment by begeekmyfriend** [comment]
ndk-build

**Comment by JakeRed** [comment]
![image](https://cloud.githubusercontent.com/assets/21214880/20294814/e6fd81ac-ab3b-11e6-9355-c9b1c8206e42.png)
我自己理解的意思是先去libyuv里ndk-build，
再去X264里编译.a文件，这里我遇到了问题，因为这里只有makefile，那么只能make，或者./android_arm......去编译.so，如果单编译so没问题，但是Makefile这里要是make的话那就会如上图找不到config.mak找不到。
第三步才去最外层ndk-nuild。
您觉得我自己的理解错在哪儿？

**Comment by JakeRed** [comment]
谢谢前辈

**Comment by JakeRed** [comment]
能否告诉我一下，要是一个简单的ndk-build解决问题我也不会来提问了。
谢谢前辈。

**Comment by JakeRed** [comment]
![image](https://cloud.githubusercontent.com/assets/21214880/20296594/c6437150-ab46-11e6-8e25-6810af616d2e.png)
不管我怎么改到头来还是这个错，当初pjsip我也编译过，没有这样的呀。

**Comment by begeekmyfriend** [comment]
你不看看`android_build_xxx.sh`里写了什么？

**Comment by JakeRed** [comment]
已经弄好了，就是时间不够又不确定是这个问题，这会证明和profile没关系。

**Comment by JakeRed** [comment]
但我觉得软编码录制那么多工具播放花屏应该算一个bug。

**Comment by JakeRed** [comment]
恩，前辈，有办法改prefile的level吗？在jni那边？

**Comment by JakeRed** [comment]
我再问一下：onSoftEncodedData()这个方法之前在SrsEncoder里的作用是什么？

**Comment by JakeRed** [comment]
问题已解决，软编码花屏的原因的确不是你的原因，是x264的原因，建议你更新一下libx264库。

**Comment by begeekmyfriend** [comment]
这样啊，谢谢告知~

**Comment by begeekmyfriend** [comment]
下了最新的x264也没见哪里差异了

**Comment by begeekmyfriend** [comment]
Fixed https://github.com/begeekmyfriend/yasea/commit/eb23c134c9b7d5b4175c10c452bd1296c38b2ae4

**Comment by JakeRed** [comment]
谢谢，我正在看x264改了啥。
