### ISSUE TITLE
config.mak: No such file or directory

### ISSUE THREAD

**Issue by Jack1103** [begeekmyfriend/yasea#224]
Hi,Begeekmyfriend:

    I do nik-build in linux 

Makefile:3: config.mak: No such file or directory
./configure
Found no assembler
Minimum version is yasm-1.2.0
If you really want to compile without asm, configure with --disable-asm.
Makefile:236: recipe for target 'config.mak' failed
make: *** [config.mak] Error 1

can you help me do it?

**Comment by begeekmyfriend** [comment]
Install yasm

**Comment by Jack1103** [comment]
Thanks，I have a new problem，Can you tell me How to determine whether the phone supports SoftEncoder？

**Comment by Jack1103** [comment]
It is all mobile phone support ？

**Comment by begeekmyfriend** [comment]
Typically it is.

**Comment by Jack1103** [comment]
for(int j = MediaCodecList.getCodecCount() - 1; j >= 0; j--){
                    MediaCodecInfo codecInfo = MediaCodecList.getCodecInfoAt(j);
                    String[] types = codecInfo.getSupportedTypes();
                    for (int i = 0; i < types.length; i++) {
                        if (types[i].equalsIgnoreCase("video/avc")) {
                            return true;
                        }
                    }

**Comment by Jack1103** [comment]
Thanks！
