### ISSUE TITLE
怎么获得一个帧从渲染缓存到发送到RTMP服务器的时间间隔？

### ISSUE THREAD

**Issue by blueseaandsky** [begeekmyfriend/yasea#226]
楼主，我想测试push的时间延迟，具体是获得一个帧从缓存渲染到发送到RTMP服务器之间的时间间隔。

我想通过frame.dts来得到渲染时间，但这个时间是从应用启动时间为零起点的一个逝去的时刻，所以即使可以获得但前的系统时间（System.nanoTime()），还是没办法计算延迟，因为我没法得到第一个帧渲染的系统时间。

请问楼主有办法么？感谢。

**Comment by begeekmyfriend** [comment]
何况渲染和发送不在同一个线程，你自己搞吧
