### ISSUE TITLE
前置摄像头画面左右翻转

### ISSUE THREAD

**Issue by zxnhl702** [begeekmyfriend/yasea#229]
你好  我希望能实现在只用前置摄像头推流的时候画面能够左右翻转一下  这样子vlc里看到的画面里的文字之类的可以变成正的 而不是像现在这样是反的  请问代码中可以修改什么地方来实现呢? 谢谢

**Comment by begeekmyfriend** [comment]
Switch [the boolean argument](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L532-L534)

**Comment by zxnhl702** [comment]
非常感谢 确实有用
