### ISSUE TITLE
Network weak

### ISSUE THREAD

**Issue by HuuThang91** [begeekmyfriend/yasea#230]
When i try running your sample app, i always receive  network weak althought my signal is strong.
My server still alive and address is  : rtmp://123.29.67.66:1935/live/kenh_9. Can you help me check it. Iam using elemental live

**Comment by begeekmyfriend** [comment]
Strong signal does not equal to good network.

**Comment by begeekmyfriend** [comment]
Strong signal does not equal to good bandwidth.

**Comment by HuuThang91** [comment]
so  the probleam is in my side or server side?
