### ISSUE TITLE
MediaCodec.native_dequeueInputBuffer的错误

### ISSUE THREAD

**Issue by JakeRed** [begeekmyfriend/yasea#233]
运行程序并产生数据，这一行报错退出：
int inBufferIndex = vencoder.dequeueInputBuffer(-1);

只捕捉到报错位置：

android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:983)
net.ossrs.yasea.SrsEncoder.onProcessedYuvFrame(SrsEncoder.java:315)
net.ossrs.yasea.SrsEncoder.onGetYuvFrame(SrsEncoder.java:418)
net.ossrs.yasea.SrsPublisher$1.onGetYuvFrame(SrsPublisher.java:86)
com.dragonfly.view.SrsCameraView.onPreviewFrame(SrsCameraView.java:187)
android.hardware.Camera$EventHandler.handleMessage(Camera.java:1160)

这里面的代码未改动，只是加了点log什么的。

如有时间请指点一下，谢谢！

**Comment by begeekmyfriend** [comment]
你提供这点信息我能看出什么？

**Comment by notedit** [comment]
哈哈  开源难做

**Comment by houshunwei** [comment]
需要给出：
0、具体错误；
1、是否稳定复现；
2、机型、系统版本；

此类问题一般是系统兼容性问题，源代码都有了调试下呗。
