### ISSUE TITLE
Upside down video

### ISSUE THREAD

**Issue by KyrychenkoOleksandr** [begeekmyfriend/yasea#237]
Video on Nexus 5x is playing upside down. I rotated preview with setPreviewRotation() method. But stream video is still upside down. Do you know how can I rotate video before sending it to a server?

**Comment by oantajames** [comment]
Facing the same issue on different device. Tested on Galaxy S3, Lg G2, Sony Xperia, Nexus 5x. When in reverse landscape - all the streamed video is upside down. The preview of the camera is not upside down only the streamed video is. I tried to fix it on the encoder part, but no luck. @begeekmyfriend any hints or ideas ? Thanks!

**Comment by begeekmyfriend** [comment]
I have tested on my Nexus 5x with Android N. It is OK now. https://github.com/begeekmyfriend/yasea/commit/d55ad9602bd284a6d0d55d54c4624e895bffcf57

**Comment by jtyang** [comment]
现在的代码应该还会有问题，至少在nexus6p上方向还是倒的，提供一段计算camera旋转方向的代码，切换前后摄像头的时候mPreviewRotation要重新赋值：
private int mPreviewRotation = 90;
    private int frontRotation;
    private int backRotation;
    private void initRotation() {
        int frontDirection, backDirection;
        Camera.CameraInfo cameraInfo = new Camera.CameraInfo();
        try {
            Camera.getCameraInfo(Camera.CameraInfo.CAMERA_FACING_BACK, cameraInfo);
            backDirection = cameraInfo.orientation;
            if (this.getResources().getConfiguration().orientation == Configuration.ORIENTATION_PORTRAIT) {
                backRotation = (backDirection == 90 ? 90 : 270);
            } else {
                backRotation = (backDirection == 90 ? 0 : 180);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            Camera.getCameraInfo(Camera.CameraInfo.CAMERA_FACING_FRONT, cameraInfo);
            frontDirection = cameraInfo.orientation;
            if (this.getResources().getConfiguration().orientation == Configuration.ORIENTATION_PORTRAIT) {
                frontRotation = (frontDirection == 90 ? 270 : 90);
            } else {
                frontRotation = (frontDirection == 90 ? 180 : 0);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        if(mCamId == Camera.CameraInfo.CAMERA_FACING_FRONT){
            mPreviewRotation = frontRotation;
        }else{
            mPreviewRotation = backRotation;
        }
    }

**Comment by begeekmyfriend** [comment]
@jtyang Please confirm this [condition](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsCameraView.java#L52) was triggered or not. 

One more thing please tell me in what is the camera face did your picture upside down and what SDK version is of your Nexus 6p.

**Comment by jtyang** [comment]
我的是android7.1系统，但是前置摄像头倒转，看你的代码处理的是后置摄像头。

**Comment by oantajames** [comment]
![15208011_604605983076044_2095927193_n](https://cloud.githubusercontent.com/assets/12069401/20619689/84c10854-b2fe-11e6-82b1-c343dfa64ffe.jpg)
Still the same issue here..

**Comment by begeekmyfriend** [comment]
@jtyang Please correct the code according to your requirement. I need more user feedback collection to make decision.

**Comment by KyrychenkoOleksandr** [comment]
Still the same issue on Nexus 5x android 7.0.
After this change on OnePlus android 6.0 appeared new issue. Back camera preview is upside down but on stream video everything is OK.
It seems like stream video don't depends on mPreviewRotation and  mCamera.setDisplayOrientation(mPreviewRotation) has no effect.
I used a following code for adjusting preview rotation and it worked for Nexus and OnePlus.

>  public static int getRotation(WindowManager windowManager, int cameraId) {
        Camera.CameraInfo info = new Camera.CameraInfo();
        Camera.getCameraInfo(cameraId, info);
        int rotation = windowManager.getDefaultDisplay().getRotation();
        int degrees = DEGREE_0;
        switch (rotation) {
            case Surface.ROTATION_0:
                degrees = DEGREE_0;
                break;
            case Surface.ROTATION_90:
                degrees = DEGREE_90;
                break;
            case Surface.ROTATION_180:
                degrees = DEGREE_180;
                break;
            case Surface.ROTATION_270:
                degrees = DEGREE_270;
                break;
        }
        if (info.facing == Camera.CameraInfo.CAMERA_FACING_FRONT) {
            int result = (info.orientation + degrees) % DEGREE_360;
            return (DEGREE_360 - result) % DEGREE_360;  // compensate the mirror
        } else {  // back-facing
            return (info.orientation - degrees + DEGREE_360) % DEGREE_360;
        }

**Comment by KyrychenkoOleksandr** [comment]
I found out that this is Nexus specific issue. Nexus 5X has reverse landscape camera sensor. https://www.reddit.com/r/Android/comments/3rjbo8/nexus5x_marshmallow_camera_problem/

setDisplayOrientation() method does not affect the order of byte array passed in onPreviewFrame(byte[], Camera).
https://developer.android.com/reference/android/hardware/Camera.html?hl=es#setDisplayOrientation(int)

**Comment by begeekmyfriend** [comment]
Not only Nexus 5x. According to @oantajames there are but also Galaxy S3, Lg G2 and Sony Xperia. So it is hard for compatibility.

`setDisplayOrientation()` does not affect the layout of byte array from the camera preview callback, but it does affect the preview picture display.

**Comment by anytimehh** [comment]
华为mate9，用后置摄像头，只有在typeC口在左边时，图像才是正的，否则是上下颠倒的。

**Comment by begeekmyfriend** [comment]
@anytimehh Ridiculous...

**Comment by yedidyak** [comment]
I have the same problem as @jtyang, also Nexus6P 7.1

**Comment by begeekmyfriend** [comment]
@yedidyak Android fragmentation is a headache problem。 I am afraid you have to modify `setPreviewOrientation` in `SrsCameraView.java` by yourself. Luckily it is not a tough job. Good luck.

**Comment by begeekmyfriend** [comment]
I am happy to inform all of you that this issue has been completely terminated https://github.com/begeekmyfriend/yasea/commit/5e039d6539e04879a09cf58d6227fefc513d628c

**Comment by jake22599** [comment]
i pull the latest build and it seems like the issue is still there. And there is a weird issue where the camera is showing in portrait when im in landscape upon app starts up. Until i rotate the application again, it gets updated.

**Comment by begeekmyfriend** [comment]
@jake22599 According to Yasea the default orientation for portrait is that the home button is at bottom while for landscape the home button at right. Otherwise all things are upside down.

**Comment by jake22599** [comment]
@begeekmyfriend Is there a way to change the orientation of the camera to based on the device current screen orientation? 
Example, if my screen is showing landscape (home button on the left), can the camera capture that as upright instead of upside down?

**Comment by begeekmyfriend** [comment]
@jake22599 [Here](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsCameraView.java#L198) is the function. But I am afraid you have to get the 4 rotations of the device (0, 90, 180 and 270) but not only landscape and portrait configuration to calculate the rotation of pictures.
