### ISSUE TITLE
运行就报错了，啥原因啊 ？

### ISSUE THREAD

**Issue by cdcdec** [begeekmyfriend/yasea#239]
dlopen("/data/app-lib/com.rtmpdemo-1/libenc.so") failed: Cannot load library: soinfo_relocate(linker.cpp:975): cannot locate symbol "stpcpy" referenced by "libenc.so"...

**Comment by begeekmyfriend** [comment]
Did you pull the latest code?
What is your phone model and Android SDK version?

**Comment by cdcdec** [comment]
下载的最新的;平板:p89mini(E2W6)---Android4.2.2;工程用android-23编译的。

**Comment by begeekmyfriend** [comment]
Delete directory: `/library/src/main/jniLibs/armeabi-v7a`

**Comment by cdcdec** [comment]
删掉/library/src/main/jniLibs/armeabi-v7a后还是会报同样的错误！

**Comment by begeekmyfriend** [comment]
I thought it had been working...Well, yasea is not aimed to surface but did you notice the `targetSdkVersion` in `build.gradle` and the Android platform version in `Applicatioin.mk` an libx264 building script?

**Comment by cdcdec** [comment]
我在已关闭的issues里面("Compiling Native Libraries(arm64-v8a ,armeabi,x86,x64...)")找到了vleonidov提供的so文件,这个文件可以使用，不报错。谢谢!
