### ISSUE TITLE
分辨率 清晰度的问题（模糊问题）

### ISSUE THREAD

**Issue by banketree** [begeekmyfriend/yasea#24]
你的分辨率固定如下：
    public static final int VWIDTH = 640;
    public static final int VHEIGHT = 480;
    public static final int VCROP_WIDTH = 384;
    public static final int VCROP_HEIGHT = 640;

    public static int vCropWidth = VCROP_WIDTH;   // Note: the stride of resolution must be set as 16x for hard encoding with some chip like MTK
    public static int vCropHeight = VCROP_HEIGHT;  // Since Y component is quadruple size as U and V component, the stride must be set as 32x

我的分辨率 根据机子类型进行设置，例如：
    public static final int VWIDTH = 864;
    public static final int VHEIGHT = 480;
    public static final int VCROP_WIDTH = 480; //16x
    public static final int VCROP_HEIGHT = 864; //32x

但画面就模糊了

**Comment by banketree** [comment]
![8dnuir wr de sb 0eu6f](https://cloud.githubusercontent.com/assets/4402896/15562681/f8d9347e-2333-11e6-86d3-65a710a81224.png)
Camera 放大后的效果图

**Comment by fly518420** [comment]
你的那边声音噪音大吗？

**Comment by banketree** [comment]
@fly518420 你可以手动调节声音，我这边噪音不大。

**Comment by fly518420** [comment]
你拿到 pcm 数据有进行降噪的处理吗？

**Comment by banketree** [comment]
![1](https://cloud.githubusercontent.com/assets/4402896/15564292/2c59ce76-2343-11e6-9cbe-cc8d6014f1c7.png)

Thanks,I solved it.

**Comment by banketree** [comment]
@fly518420  no

**Comment by crazyhl** [comment]
请问是如何解决的？

**Comment by lisnstatic** [comment]
@banketree 你好，推送分辨率宽大于高的流，你是怎么做到的，能分享一下吗

**Comment by begeekmyfriend** [comment]
@lisnstatic 现在可以支持横屏了

**Comment by fly518420** [comment]
@begeekmyfriend  横屏前置摄像头 YUV数据处理有问题

**Comment by fly518420** [comment]
@banketree 预览分辨率 大于了 推送的分辨率 如何对YUV数据进行按比例缩放呢？

**Comment by begeekmyfriend** [comment]
@fly518420 这个你有心可以用libyuv来做，好处是降低手机发热——这可能是纯Java的yasea唯一大量消耗性能的地方。

**Comment by banketree** [comment]
@begeekmyfriend  Good,You are great, learn from you.
