### ISSUE TITLE
camera flash

### ISSUE THREAD

**Issue by farisjameel** [begeekmyfriend/yasea#241]
how to turn on or off flash during recording?

**Comment by begeekmyfriend** [comment]
What do you mean?

**Comment by farisjameel** [comment]
I want to turn on camera torch while recording or streaming a video but there is no method available for this in your library please let me know how could I add this functionality into my app.

**Comment by begeekmyfriend** [comment]
> <uses-permission android:name="android.permission.FLASHLIGHT" />  
camera.getParameters().setFlashMode(Parameters.FLASH_MODE_TORCH);

**Comment by 386405828** [comment]
这样不能手动控制吧？

**Comment by begeekmyfriend** [comment]
@386405828 Write a method with switch parameter.

**Comment by 386405828** [comment]
恩恩，好了，刚搞定

**Comment by huangjingqiang** [comment]
@begeekmyfriend   不能同时开camera和flash

**Comment by begeekmyfriend** [comment]
@huangjingqiang Try to add this piece of script into `AndroidManifest.xml` under `app` directory.

> <uses-permission android:name="android.permission.FLASHLIGHT"/>

**Comment by huangjingqiang** [comment]
好的，🙏

**Comment by begeekmyfriend** [comment]
Commit https://github.com/begeekmyfriend/yasea/commit/3b5892e8698f7872af8a3b7e4b75c286df0d898c
