### ISSUE TITLE
How to do RTMP camera stream from background service?

### ISSUE THREAD

**Issue by laalex** [begeekmyfriend/yasea#243]
Hey there, is there any possibility to do RTMP camera stream from background service / without having the camera shown?

Also it seems that `Camera` object is deprecated in api level 23 and this doesn't work :(

**Comment by begeekmyfriend** [comment]
Please set `targetSdkVersion` property to 22 in `build.gradle`. Or substitute `Camera2` class library by yourself.

**Comment by laalex** [comment]
Good. I did that and it now works. I only have a single problem for the moment: How can I change the RTSP protocolo to RTMP to do the stream from the camera? Would you like to work on this with you and add RTMP capability to the lib
