### ISSUE TITLE
x264_config.h file not found

### ISSUE THREAD

**Issue by KyrychenkoOleksandr** [begeekmyfriend/yasea#249]
I got this error when I tried to build libs for different architectures

> yasea-master/library/src/main/libenc/jni/libx264\x264.h:46:10: fatal error:
'x264_config.h' file not found
#include "x264_config.h"
1 error generated.
make: *** [C:/Users/okyrychenko/Downloads/yasea-master/yasea-master/library/src/main/libenc/obj/local/armeabi-v7a/objs/enc/libenc.o] Error 1

Could you provide me with this file?

**Comment by begeekmyfriend** [comment]
Never happens to me. Clone the repository and try again please.

**Comment by kwangjaeyoo** [comment]
hi 

where is 'x264_config.h'  ??

same error~ 

check again plz~

**Comment by begeekmyfriend** [comment]
@kwangjaeyoo Didn't you see my last response?

**Comment by kwangjaeyoo** [comment]
i saw.

But I can not compile.

**Comment by begeekmyfriend** [comment]
`library/src/main/libenc/jni/libx264/android_build_armeabi_v7a.sh`

**Comment by kwangjaeyoo** [comment]
Thank you very mush!

**Comment by nirvana777** [comment]
我遇到了同样的问题，重新下载还是提示这个错误，但是我没看明白怎么修改才能编译通过，请教一下
