### ISSUE TITLE
Under the condition of the network in general, it is easy to disconnect

### ISSUE THREAD

**Issue by tz-xiaomage** [begeekmyfriend/yasea#25]
Connection error problem is very easy to appear, I try to set the connection time out to 10 seconds, but it is still very easy to appear connection failure, I tried the other push flow tool can be successful, the server is no problem
![image](https://cloud.githubusercontent.com/assets/12270504/15570730/1789b354-236a-11e6-9746-5cb998ab8df2.png)

**Comment by begeekmyfriend** [comment]
What is your server?
What is your connection logging?
What is your wireshark capture?

**Comment by tz-xiaomage** [comment]
05-27 11:38:16.565 31808-31808/com.live.demo D/AbsListView: unregisterIRListener() is called 
05-27 11:38:16.985 31808-31808/com.live.demo I/SrsMuxer: annexb multiple match ok, pts=837
05-27 11:38:16.985 31808-31808/com.live.demo I/SrsMuxer: 000-015: 0x0 0x0 0x0 0x1 0x67 0x42 0x80 0x1e 0xe9 0x3 0x0 0xa3 0x20 0x0 0x0 0x0 
05-27 11:38:16.985 31808-31808/com.live.demo I/SrsMuxer: 000-015: 0x0 0x0 0x0 0x1 0x68 0xce 0x6 0xe2 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 
05-27 11:38:16.985 31808-31808/com.live.demo I/SrsMuxer: annexb demux 21B, pts=837, frame=9B, nalu=7
05-27 11:38:16.985 31808-31808/com.live.demo I/SrsMuxer: annexb demux 21B, pts=837, frame=4B, nalu=8
05-27 11:38:16.990 31808-8910/com.live.demo I/SrsMuxer: worker: connecting to RTMP server by url=rtmp://192.168.1.234/mic/68?key=lC2LuoTkx3aP4rx4
05-27 11:38:16.990 31808-8910/com.live.demo D/RtmpConnection: connect() called. Host: 192.168.1.234, port: 1935, appName: mic, publishPath: 68?key=lC2LuoTkx3aP4rx4
05-27 11:38:17.015 31808-8910/com.live.demo D/RtmpConnection: connect(): socket connection established, doing handhake...
05-27 11:38:17.015 31808-8910/com.live.demo D/Handshake: writeC0
05-27 11:38:17.015 31808-8910/com.live.demo D/Handshake: writeC1
05-27 11:38:17.015 31808-8910/com.live.demo D/Handshake: writeC1(): Calculating digest offset
05-27 11:38:17.015 31808-8910/com.live.demo D/Handshake: writeC1(): (real value of) digestOffset: 697
05-27 11:38:17.015 31808-8910/com.live.demo D/Handshake: writeC1(): recalculated digestOffset: 1473
05-27 11:38:17.015 31808-8910/com.live.demo D/Handshake: writeC1(): digestOffsetBytes: 00BBFFFF
05-27 11:38:17.015 31808-8910/com.live.demo D/Handshake: partBeforeDigest(): size: 1473
05-27 11:38:17.015 31808-8910/com.live.demo D/Handshake: writeC1(): Writing timestamp and Flash Player version
05-27 11:38:17.020 31808-8910/com.live.demo D/Handshake: partAfterDigest(): size: 31
05-27 11:38:17.020 31808-8910/com.live.demo D/Handshake: copying digest offset bytes in partBeforeDigest
05-27 11:38:17.020 31808-8910/com.live.demo D/Handshake: writeC1(): Calculating digest
05-27 11:38:17.020 31808-8910/com.live.demo D/Handshake: writeC1(): writing C1 packet
05-27 11:38:17.020 31808-8910/com.live.demo D/Handshake: readS0
05-27 11:38:17.045 31808-8910/com.live.demo D/Handshake: readS1
05-27 11:38:17.050 31808-8910/com.live.demo D/Handshake: readS1(): S1 total bytes read OK
05-27 11:38:17.050 31808-8910/com.live.demo D/Handshake: readC2
05-27 11:38:17.050 31808-8910/com.live.demo D/Handshake: readS2
05-27 11:38:17.050 31808-8910/com.live.demo D/Handshake: readS2(): S2 total bytes read OK
05-27 11:38:17.050 31808-8910/com.live.demo D/RtmpConnection: connect(): handshake done
05-27 11:38:17.055 31808-8953/com.live.demo D/RtmpConnection: starting main rx handler loop
05-27 11:38:17.055 31808-8910/com.live.demo D/RtmpConnection: rtmpConnect(): Building 'connect' invoke packet
05-27 11:38:17.110 31808-8951/com.live.demo D/RtmpDecoder: readPacket(): header.messageType: WINDOW_ACKNOWLEDGEMENT_SIZE
05-27 11:38:17.110 31808-8953/com.live.demo D/RtmpConnection: handleRxPacketLoop(): Setting acknowledgement window size: 5000000
05-27 11:38:17.155 31808-8910/com.live.demo W/dalvikvm: threadid=16: thread exiting with uncaught exception (group=0x416fe960)
05-27 11:38:17.200 31808-31808/com.live.demo I/PLVideoViewActivity: stop audio worker thread
05-27 11:38:17.200 31808-8951/com.live.demo D/RtmpDecoder: readPacket(): header.messageType: SET_PEER_BANDWIDTH
05-27 11:38:17.200 31808-8951/com.live.demo D/RtmpDecoder: readPacket(): header.messageType: SET_CHUNK_SIZE
05-27 11:38:17.200 31808-8953/com.live.demo D/RtmpConnection: handleRxPacketLoop(): Send acknowledgement window size: 5000000
05-27 11:38:17.200 31808-8951/com.live.demo D/RtmpDecoder: readPacket(): Setting chunk size to: 4096
05-27 11:38:17.200 31808-8951/com.live.demo D/RtmpDecoder: readPacket(): header.messageType: COMMAND_AMF0
05-27 11:38:17.200 31808-8953/com.live.demo D/RtmpConnection: handleRxInvoke: Got result for invoked method: connect
05-27 11:38:17.485 31808-31808/com.live.demo I/SrsEncoder: stop aencoder
05-27 11:38:17.490 31808-31808/com.live.demo I/SrsEncoder: stop vencoder
05-27 11:38:17.505 31808-31808/com.live.demo I/SrsEncoder: stop muxer to SRS over RTMP
05-27 11:38:17.505 31808-31808/com.live.demo D/ReadThread: Stopping
05-27 11:38:17.505 31808-31808/com.live.demo D/WriteThread: Stopping
05-27 11:38:17.505 31808-8952/com.live.demo D/WriteThread: exit
05-27 11:38:17.505 31808-8951/com.live.demo I/ReadThread: exit
05-27 11:38:17.505 31808-31808/com.live.demo D/RtmpConnection: socket closed
05-27 11:38:17.515 31808-31808/com.live.demo I/SrsMuxer: worker: disconnect SRS ok.
05-27 11:38:17.515 31808-31808/com.live.demo I/SrsMuxer: SrsMuxer closed

提示了   ------>   Not connected to RTMP server

我试了多部手机都有一样的情况，就是我打开应用，然后点击推流，第一次几乎是百分之百是推送失败的，错误都是Not connected to RTMP server，在点击多次后，有时候是第二次，有时候是两次以上，就会推送成功

**Comment by tz-xiaomage** [comment]
第一次推送失败的原因找到了，是因为我将SurfaceView设置为  android:visibility="gone"
然而依旧是有个比较不好的体验，那就是在网络不稳定的时候，就会立马断开连接，而不会尝试重连

**Comment by begeekmyfriend** [comment]
The "network weak" process can be self defined.

**Comment by tz-xiaomage** [comment]
不知道可不可以弄个demo？

**Comment by begeekmyfriend** [comment]
You may use [this code](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/sea/SrsEncoder.java#L257) as condition and do whatever you want to do.

**Comment by tz-xiaomage** [comment]
thank
