### ISSUE TITLE
About record video 

### ISSUE THREAD

**Issue by Jack1103** [begeekmyfriend/yasea#251]
Hi,begeekmyfriend:
     I had a problem while I was recording the video,May be because of lost frames.Can you help me look at this video.
      https://ipc.blob.core.chinacloudapi.cn/10001/291c53d8-44bb-4e7d-8ae3-a7b61b6b1e1f.mp4?sv=2015-12-11&sr=c&sig=30ukaqSnVjMqqLSL7c%2Fj%2F4Ehe%2ByyKu%2FzFtA%2F8FZkfeQ%3D&se=2016-12-10T01%3A03%3A40Z&sp=r

**Comment by Jack1103** [comment]
Thanks！

**Comment by begeekmyfriend** [comment]
Did you modify the original code?

**Comment by Jack1103** [comment]
I modified the recorded code as follows: 
 private void writeSampleData(ByteBuffer byteBuf, MediaCodec.BufferInfo bi, boolean isAudio) throws IOException,IllegalArgumentException {
        int trackIndex = isAudio ? AUDIO_TRACK : VIDEO_TRACK;
        if (!mp4Movie.getTracks().containsKey(trackIndex)) {
            return;
        }

        if (mdat.first) {
            mdat.setContentSize(0);
            mdat.getBox(fc);
            mdatOffset = recFileSize;
            recFileSize += mdat.getHeaderSize();
            mdat.first = false;
        }

        mp4Movie.addSample(trackIndex, recFileSize, bi);
        try{
            byteBuf.position(bi.offset + (isAudio ? 0 : 4));
            byteBuf.limit(bi.offset + bi.size);
        }catch (IllegalArgumentException e){
            e.printStackTrace();
        }
        if (!isAudio) {
            ByteBuffer size = ByteBuffer.allocateDirect(4);
            size.position(0);
            size.putInt(bi.size - 4);
            size.position(0);
            recFileSize += fc.write(size);
        }
        int writeBytes = fc.write(byteBuf);

        recFileSize += writeBytes;
        flushBytes += writeBytes;
        if (flushBytes > 64 * 1024) {
            fos.flush();
            flushBytes = 0;
        }
    }
  
and

public void record(File outputFile) throws IOException {
        mRecFile = outputFile;
        isbRecordingtime = true;
        createMovie(mRecFile);
        mHandler.onRecordStarted(mRecFile.getPath());

        if (!spsList.isEmpty() && !ppsList.isEmpty()) {
            mp4Movie.addTrack(videoFormat, false);
        }
        mp4Movie.addTrack(audioFormat, true);

        worker = new Thread(new Runnable() {
            @Override
            public void run() {
                bRecording = true;
                while (bRecording) {
                    // Keep at least one audio and video frame in cache to ensure monotonically increasing.
                    while (!frameCache.isEmpty()) {
                        SrsEsFrame frame = frameCache.poll();
                        try {
                            if(isbRecordingtime){
                                recordtime = System.currentTimeMillis();
                                isbRecordingtime = false;
                            }
                            writeSampleData(frame.bb, frame.bi, frame.is_audio());
                        } catch (IOException e) {
                            e.printStackTrace();
                        }catch (IllegalArgumentException e2){
                            e2.printStackTrace();
                        }catch (NullPointerException e3){
                            e3.printStackTrace();
                            StringBuffer stringBuffer = new StringBuffer();
                            StackTraceElement[] se = e3.getStackTrace();
                            stringBuffer.append("ERROR_txt_length:"+se.length+"\n");
                            stringBuffer.append("contextTotal:" + e3.getMessage()+"\n");
                            for (int i = 0; i < se.length; i++) {
                                stringBuffer.append(se[i].toString()+"\n");
                            }
                            Util.saveFile(stringBuffer.toString());
                        }
                    }
                    // Waiting for next frame
                    synchronized (writeLock) {
                        try {
                            // isEmpty() may take some time, so we set timeout to detect next frame
                            if(bRecording){
                                writeLock.wait(500);
                            }
                        } catch (InterruptedException ie) {
                            worker.interrupt();
                        }
                    }
                }
            }
        });
        worker.start();
    }

Just change this. 

thanks！

**Comment by Jack1103** [comment]
Small probability event，Appeared once in two months 。

**Comment by Jack1103** [comment]
Repetition of the question is too difficult, but the existence of this problem .

**Comment by begeekmyfriend** [comment]
But your test was based on your modification.
