### ISSUE TITLE
如何优化 samplerExternalOES 类型纹理在高斯模糊算法中的性能？

### ISSUE THREAD

**Issue by jinyunfeng** [begeekmyfriend/yasea#252]
我看到了你的这个帖子，有没有开源这个方法

**Comment by begeekmyfriend** [comment]
Reduce camera preview resolution (i.e. 480p).
Draw to FBO texture.
Draw to screen (window surface) with higher resolution from FBO texture.
Therefore we need two shader programs. [loadExternalSamplerShader](https://github.com/begeekmyfriend/yasea/blob/gpuimage/library/src/main/java/com/seu/magicfilter/base/gpuimage/GPUImageFilter.java#L140) for `samplerExternalOES` to draw to FBO texture and [loadInternalSamplerShader](https://github.com/begeekmyfriend/yasea/blob/gpuimage/library/src/main/java/com/seu/magicfilter/base/gpuimage/GPUImageFilter.java#L149) for `sampler2D` to draw to the screen.

**Comment by jinyunfeng** [comment]
我也是这样做的，不过现在效果并不是很理想，帧率依然很低，所以先看一看你实现的具体过程

**Comment by begeekmyfriend** [comment]
The real FPS is dominated by your camera sampling FPS.

**Comment by jinyunfeng** [comment]
加个q吧，最近在做这方面的，也要填坑，945811353

**Comment by begeekmyfriend** [comment]
wechat: begeekmyfriend

**Comment by begeekmyfriend** [comment]
Simplified https://github.com/begeekmyfriend/yasea/commit/0f9e5f0589498b40c5aa4788ba983d3ffc104f28
