### ISSUE TITLE
Cant not send data streaming to Elemental Server

### ISSUE THREAD

**Issue by HuuThang91** [begeekmyfriend/yasea#255]
Hi, im using your lib to streaming to Elemental Server but its seem like my server cant get any data eventhought the signal is good. RTMP in my elemental server build base on Adobe Flash Media Server . Is it    
make the diffenence and how can i fix it?
Thanks

**Comment by begeekmyfriend** [comment]
You might have built your server wrong. Try [SRS](https://github.com/ossrs/srs/tree/2.0release)

**Comment by HuuThang91** [comment]
MyRTMP implementation is based on Adobe Flash Media Server, i cant change it,it is in hardware. Please help me, how can i change th rtmp protocol in your libs . My RTMP is still alive in rtmp://123.29.67.66/live/kenh_10

**Comment by begeekmyfriend** [comment]
Yasea has been used for FMS by some Github users. But I have never built FMS myself...

**Comment by HuuThang91** [comment]
how can i change bitrate before streaming :)

**Comment by HuuThang91** [comment]
How can i set camera auto focus and zoom like 
Camera.Parameters params = c.getParameters();
params.setFocusMode(Camera.Parameters.FOCUS_MODE_CONTINUOUS_PICTURE);

**Comment by begeekmyfriend** [comment]
Please check whether your camera [supports](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsCameraView.java#L109) automatic focus mode or not.

**Comment by HuuThang91** [comment]
i try three device, sony z5, sam sung s7, j7 and  supported Focus Modes  is only fixed . Is that because of device ?

**Comment by begeekmyfriend** [comment]
Sure.

**Comment by HuuThang91** [comment]
thanks a lot :)
