### ISSUE TITLE
Network weak

### ISSUE THREAD

**Issue by kwangjaeyoo** [begeekmyfriend/yasea#256]
Test with phones on the same network

Note 3 continues "Network weak"
Note 4 is operating normally.

How can you solve this?

**Comment by begeekmyfriend** [comment]
It does nothing with the phones.

**Comment by kwangjaeyoo** [comment]
How do I resolve the "weak network" issue?

**Comment by begeekmyfriend** [comment]
It happens when there are more than 48 video ES frames in the FLV cache which are not yet sent through the socket. It is your network issue. Maybe by the phone side or maybe by the server side.

**Comment by kwangjaeyoo** [comment]
thanks you ~ anyway
