### ISSUE TITLE
怎么直接推h264的byte[] 数据

### ISSUE THREAD

**Issue by liuchenx** [begeekmyfriend/yasea#259]

**Comment by begeekmyfriend** [comment]
你不打包？

**Comment by liuchenx** [comment]
不好意思 我描述的不太清楚， 是这样的， 因为我这边有个需求是想将自己获取的h264的byte[]字节流通过这个库推流到远程服务器， 这这边需要对这个库做什么更改呢， 因为对视频编解码这一块不了解

**Comment by begeekmyfriend** [comment]
See #257

**Comment by liuchenx** [comment]
是要现将h264解码成yuv才能用吗

**Comment by begeekmyfriend** [comment]
camera -> yuv or rgba -> h264 -> flv frame -> rtmp packet.

**Comment by liuchenx** [comment]
多谢

**Comment by TomYang1985** [comment]
@liuchenx 你解决了吗，我也是已经有了H264的data字节数据了。SrsFlvMuxer.java类里面没有直接取H264的数据转成flv frame的方法。不知道你怎么实现的。 @begeekmyfriend   writeVideoSample这个方法只能用从编码器编码出来的数据，能再提供一个方法出来吗，不需要编码的数据转成flv frame？

**Comment by begeekmyfriend** [comment]
@TomYang1985 `writeVideoSample`的参数还需要`BufferInfo`对象，是对`ByteBuffer`的状态信息，不复杂，你可以调试一下自己造一个，看看匹配得上。

**Comment by TomYang1985** [comment]
@begeekmyfriend 谢谢，我试试。

**Comment by hike2008** [comment]
@TomYang1985 请问你解决了直接推H264的字节数据了吗
