### ISSUE TITLE
 Video preview problem

### ISSUE THREAD

**Issue by tz-xiaomage** [begeekmyfriend/yasea#26]
Can not push the case, can also open the video？

**Comment by begeekmyfriend** [comment]
Excuse me, I do not get your point.

**Comment by tz-xiaomage** [comment]
能不能只推送音频，不推送视频

**Comment by tz-xiaomage** [comment]
就是不推送的情况下， 能不能进行视频的预览，也就是打开视频，但是不推送

**Comment by notedit** [comment]
都是可以自己控制的  可以的话读一下代码

**Comment by tz-xiaomage** [comment]
感谢

**Comment by begeekmyfriend** [comment]
What you need to do is just open the camera and NOT to send AV frames to the encoder.
