### ISSUE TITLE
请问美颜效果怎么设置？

### ISSUE THREAD

**Issue by huangsai** [begeekmyfriend/yasea#260]

**Comment by begeekmyfriend** [comment]
你是不会用还是怎么？

**Comment by huangsai** [comment]
不会用 可以直接调用gpuimage吗？

**Comment by begeekmyfriend** [comment]
在UI上直接点右上角，接口调用[在此](https://github.com/begeekmyfriend/yasea/blob/gpuimage/app/src/main/java/net/ossrs/yasea/demo/MainActivity.java#L168)

**Comment by huangsai** [comment]
请问你这个可以设置镜像吗？

**Comment by begeekmyfriend** [comment]
没有接口，不过可以手动改[布尔变量](https://github.com/begeekmyfriend/yasea/blob/gpuimage/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L476-L478)，或者自己写一个接口，调用它

**Comment by huangsai** [comment]
是哪一个布尔变量？

**Comment by notedit** [comment]
@huangsai  不是告诉你了么  

你不会花一秒钟看一眼?

**Comment by huangsai** [comment]
我在忙着接水印 不好意思啊
