### ISSUE TITLE
如何不预览直接用SrsPublisher推流

### ISSUE THREAD

**Issue by nirvana777** [begeekmyfriend/yasea#261]
我现在想在一个界面播放视频的同时推流摄像头图像到服务器。
我在onCreate方法中将**mPublisher = new SrsPublisher((SrsCameraView) findViewById(R.id.preview))**改为**mPublisher = new SrsPublisher(new SrsCameraView(this))**后，服务器接收到的图像是黑屏，但是有声音，我看了SrsCameraView这个类，但是没搞明白到底是为啥，不知道有解决这个问题的没

**Comment by begeekmyfriend** [comment]
没有`SurfaceView`怎么采集图像？

**Comment by nirvana777** [comment]
我查阅了Camera的资料获知从camera读取到的预览（preview）图像流一定要输出到一个可见的（Visible）SurfaceView上，看来我只能尝试覆盖SurfaceView实现了
