### ISSUE TITLE
Does not sure how can I convert 'Image' from 'ImageReader' to 'yuv frame'

### ISSUE THREAD

**Issue by insthync** [begeekmyfriend/yasea#262]
Hi, Now I'm developing broadcasting app which users can broadcast their screen to another users

I have try to creating new class called 'SrsScreenView' which is based on 'SrsCameraView'

I try to recording the screen by following codes

    private void startRecording() {
        Log.d(TAG, "startRecording()");

        DisplayMetrics metrics = getResources().getDisplayMetrics();
        int density = metrics.densityDpi;

        if (mHandlerLoop == null)
        {
            mHandlerLoop = new Thread() {
                @Override
                public void run() {
                    Looper.prepare();
                    mHandler = new Handler();
                    Looper.loop();
                }
            };
            mHandlerLoop.start();
        }

        // Start the video input.
        mImageReader = ImageReader.newInstance(mPreviewWidth, mPreviewHeight, PixelFormat.RGBA_8888, 2);

        mVirtualDisplay = mMediaProjection.createVirtualDisplay("Recording Display", mPreviewWidth, mPreviewHeight, density, 0 /* flags */, mImageReader.getSurface(), null /* callback */, mHandler);

        mImageReader.setOnImageAvailableListener(new ImageAvailableListener(), mHandler);
    }

    private class ImageAvailableListener implements ImageReader.OnImageAvailableListener {
        @Override
        public void onImageAvailable(ImageReader reader) {
            Image image = null;
            FileOutputStream fos = null;
            Bitmap bitmap = null;

            ByteArrayOutputStream stream = null;

            try {
                image = mImageReader.acquireLatestImage();
                if (image != null) {
                    Image.Plane[] planes = image.getPlanes();
                    ByteBuffer buffer = planes[0].getBuffer();
                    int pixelStride = planes[0].getPixelStride();
                    int rowStride = planes[0].getRowStride();
                    int rowPadding = rowStride - pixelStride * mPreviewWidth;

                    // create bitmap
                    bitmap = Bitmap.createBitmap(mPreviewWidth + rowPadding / pixelStride, mPreviewHeight, Bitmap.Config.ARGB_8888);
                    bitmap.copyPixelsFromBuffer(buffer);

                    final Bitmap finalBitmap = bitmap;
                    mActivity.runOnUiThread(new Runnable() {
                        @Override
                        public void run() {
                            if (testBitmap != null)
                                testBitmap.setImageBitmap(finalBitmap);
                        }
                    });
                    // TODO: Have to convert bitmap/image to yuv frame
                    //if (mPrevCb != null)
                    //    mPrevCb.onGetYuvFrame(mYuvPreviewFrame);
                }

            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                if (fos != null) {
                    try {
                        fos.close();
                    } catch (IOException ioe) {
                        ioe.printStackTrace();
                    }
                }

                if (stream != null) {
                    try {
                        stream.close();
                    } catch (IOException ioe) {
                        ioe.printStackTrace();
                    }
                }

                if (bitmap != null) {
                    //bitmap.recycle();
                }

                if (image != null) {
                    image.close();
                }
            }
        }
    }

I struck at where I placed todo comment, I don't know how can I convert 'Image' or 'Bitmap' to 'yuv frame', I've tested the bitmap, it's work well.

**Comment by begeekmyfriend** [comment]
No no no. See #248

**Comment by insthync** [comment]
Does not sure what I have to do. I have following the codes that you share, Now I've change surface input to the surface view. But I don't where should I calling `mPrevCb.onGetYuvFrame(data);`

**Comment by begeekmyfriend** [comment]
Use `MediaProjection` for screen recording which yasea does not support currently

**Comment by insthync** [comment]
Okay, I see

**Comment by AndroidDeveloperLB** [comment]
The image I got from this has black frames around it. Here's a StackOverflow question I wrote about it:
http://stackoverflow.com/q/43705756/878126
