### ISSUE TITLE
有几个问题，想问一下。

### ISSUE THREAD

**Issue by lyx32** [begeekmyfriend/yasea#264]
你好，我想问下，
1.这个程序是只实现了发布视频信息出去吗？如果想在其他android手机获取是否需要用 [#232](https://github.com/begeekmyfriend/yasea/issues/232) 去获取。
2.我在app左上角有一个url，哪个是用来干嘛的？是用来接收发布的视频信息的吗？
3.假如我想实现视频聊天这种功能，这个程序可以实现吗？还缺少什么？

**Comment by begeekmyfriend** [comment]
1. yasea是推流，#232 是拉流
2. 你需要一台rtmp服务器
3. 视频聊天是另外一回事

**Comment by lyx32** [comment]
关于第一个和第二个问题我这么理解你看对吗？
yasea是发布视频信息到一台rtmp服务器上去。然后用#232去获取rtmp服务器上保存的某个视频信息。
对吗？

**Comment by begeekmyfriend** [comment]
基本正确

**Comment by lyx32** [comment]
ok，非常感谢。

**Comment by notedit** [comment]
视频聊天可以看  https://dot.cc

**Comment by lyx32** [comment]
好的，非常感谢。我之前一直没做过这一块。就一直想试试，一直不知道该怎么入手。
