### ISSUE TITLE
Can not just push the sound?

### ISSUE THREAD

**Issue by tz-xiaomage** [begeekmyfriend/yasea#27]
Do not push the video, just push the sound?

**Comment by begeekmyfriend** [comment]
Just comment out [onGetYuvFrame](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/sea/SrsEncoder.java#L254) to not encode YUV frames.

**Comment by hezhubo** [comment]
@begeekmyfriend It doesn't work.Actually, I had comment out onGetYuvFrame, but it can't to play.

**Comment by begeekmyfriend** [comment]
What I mean is you do not need to send **YUV frames to the encoder**. That is it.

**Comment by hezhubo** [comment]
Thank you very much!
