### ISSUE TITLE
Camera shows upside down on Nexus6

### ISSUE THREAD

**Issue by jutikorn** [begeekmyfriend/yasea#271]
I ran an example app on Motorola Nexus6 and found that the camera shows upside down

**Comment by begeekmyfriend** [comment]
Set a break point to see if this [line](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsCameraView.java#L52) is to be passed through or not?

**Comment by jutikorn** [comment]
That line was passed if I **switch to back camera**, rotate device from **portrait** to **landscape** and **again back to portrait**. I am assuming that `Publisher.setScreenOrientation(newConfig.orientation);` is basically called at `onConfigurationChanged()` so the orientation isn't set at first.

**Comment by begeekmyfriend** [comment]
Which camera face did you open at first?

**Comment by jutikorn** [comment]
Front camera will be first usually.
