### ISSUE TITLE
Network bandwidth check functionality

### ISSUE THREAD

**Issue by davidarchi** [begeekmyfriend/yasea#272]
Hello,
Actually, I facing the issue:
When I change network bandwidth from low to high (500kb to 1.6Mb)
But onNetworkResume was not called. How can I resolve this ?
As I checked I see that videoFrameCacheNumber in SrsEncoder.onGetRgbaFrame always get value 48.
Could you tell me why? We cannot send any frame to server right ?

and additional, Live streaming works fine with hight bandwidth.
Thank you

**Comment by begeekmyfriend** [comment]
`onNetworkResume` will be only invoked after `onNetworkWeak`.

The value of `videoFrameCacheNumber` is set according to the relation between GOP and FPS.

**Comment by davidarchi** [comment]
> onNetworkResume will be only invoked after onNetworkWeak.

my problem is when onNetworkWeak is called, after that I will increas network bandwitdth,
but onNetworkResume is not called, videoFrameCacheNumber  also get value > 48
I want to know, the lib work fine or not in the case : bandwitdth is very low to high ?

**Comment by begeekmyfriend** [comment]
When on network weak notification, it means the circumstance of your network is not good. It is useless to increase the bit rate in this situation.

**Comment by davidarchi** [comment]
what should I do when on network weak be called ?
and when on network resume be called ?
Can you guide me
?

**Comment by begeekmyfriend** [comment]
Ask your ISP...

**Comment by davidarchi** [comment]
How can I change bitrate when onNetwork weak be called ?

**Comment by begeekmyfriend** [comment]
I am afraid what you can do is only to reduce the bit rate for your bandwidth was not available enough support such large stream.

 You may try `FFmpeg` or some third-party utils to stream to check your bandwidth.

**Comment by davidarchi** [comment]
I see the function `setVideoSmoothMode()` 
Can I use this function to reduce bitrate when onNetworkWeak be called while connecting ?
is this work fine ?

**Comment by begeekmyfriend** [comment]
Yes, you may. But it is not guaranteed.

**Comment by davidarchi** [comment]
how can I check the network bandwidth with your lib ?

**Comment by begeekmyfriend** [comment]
Not provided yet...

**Comment by davidarchi** [comment]
What is your way to calculator frame drop ?

**Comment by begeekmyfriend** [comment]
Take video frame as an example. The drop calculation can be set [here](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L373)
