### ISSUE TITLE
Hard Encoder doesn't work on Kitkat device

### ISSUE THREAD

**Issue by jutikorn** [begeekmyfriend/yasea#273]
Here is the logs
12-15 18:20:57.604 11237-15563/net.ossrs.yasea.demo W/System.err: java.net.SocketTimeoutException: failed to connect to ossrs.net/182.92.80.26 (port 1935) after 3000ms
12-15 18:20:57.604 11237-15563/net.ossrs.yasea.demo W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:159)
12-15 18:20:57.604 11237-15563/net.ossrs.yasea.demo W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:112)
12-15 18:20:57.604 11237-15563/net.ossrs.yasea.demo W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
12-15 18:20:57.604 11237-15563/net.ossrs.yasea.demo W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:460)
12-15 18:20:57.604 11237-15563/net.ossrs.yasea.demo W/System.err:     at java.net.Socket.connect(Socket.java:833)
12-15 18:20:57.604 11237-15563/net.ossrs.yasea.demo W/System.err:     at com.github.faucamp.simplertmp.io.RtmpConnection.connect(RtmpConnection.java:125)
12-15 18:20:57.604 11237-15563/net.ossrs.yasea.demo W/System.err:     at com.github.faucamp.simplertmp.DefaultRtmpPublisher.connect(DefaultRtmpPublisher.java:23)
12-15 18:20:57.604 11237-15563/net.ossrs.yasea.demo W/System.err:     at net.ossrs.yasea.SrsFlvMuxer.connect(SrsFlvMuxer.java:122)
12-15 18:20:57.604 11237-15563/net.ossrs.yasea.demo W/System.err:     at net.ossrs.yasea.SrsFlvMuxer.access$000(SrsFlvMuxer.java:47)
12-15 18:20:57.604 11237-15563/net.ossrs.yasea.demo W/System.err:     at net.ossrs.yasea.SrsFlvMuxer$1.run(SrsFlvMuxer.java:155)
12-15 18:20:57.604 11237-15563/net.ossrs.yasea.demo W/System.err:     at java.lang.Thread.run(Thread.java:841)

12-15 18:20:59.484 11237-11237/net.ossrs.yasea.demo I/SrsFlvMuxer: SrsFlvMuxer closed
12-15 18:20:59.484 11237-11237/net.ossrs.yasea.demo I/SrsMp4Muxer: SrsMp4Muxer closed
12-15 18:20:59.484 11237-15700/net.ossrs.yasea.demo W/System.err: java.net.SocketException: Socket is not connected
12-15 18:20:59.484 11237-15700/net.ossrs.yasea.demo W/System.err:     at java.net.Socket.checkOpenAndCreate(Socket.java:646)
12-15 18:20:59.484 11237-15700/net.ossrs.yasea.demo W/System.err:     at java.net.Socket.shutdownInput(Socket.java:609)
12-15 18:20:59.484 11237-15700/net.ossrs.yasea.demo W/System.err:     at com.github.faucamp.simplertmp.io.RtmpConnection.shutdown(RtmpConnection.java:340)
12-15 18:20:59.484 11237-15700/net.ossrs.yasea.demo W/System.err:     at com.github.faucamp.simplertmp.io.RtmpConnection.close(RtmpConnection.java:311)
12-15 18:20:59.484 11237-15700/net.ossrs.yasea.demo W/System.err:     at com.github.faucamp.simplertmp.DefaultRtmpPublisher.close(DefaultRtmpPublisher.java:33)
12-15 18:20:59.484 11237-15700/net.ossrs.yasea.demo W/System.err:     at net.ossrs.yasea.SrsFlvMuxer.disconnect(SrsFlvMuxer.java:109)
12-15 18:20:59.484 11237-15700/net.ossrs.yasea.demo W/System.err:     at net.ossrs.yasea.SrsFlvMuxer.access$700(SrsFlvMuxer.java:47)
12-15 18:20:59.484 11237-15700/net.ossrs.yasea.demo W/System.err:     at net.ossrs.yasea.SrsFlvMuxer$2.run(SrsFlvMuxer.java:215)
12-15 18:20:59.484 11237-15700/net.ossrs.yasea.demo W/System.err:     at java.lang.Thread.run(Thread.java:841)
12-15 18:20:59.484 11237-15700/net.ossrs.yasea.demo D/RtmpConnection: socket closed
12-15 18:20:59.484 11237-15700/net.ossrs.yasea.demo I/SrsFlvMuxer: worker: disconnect ok.
12-15 18:20:59.534 11237-11237/net.ossrs.yasea.demo I/SrsFlvMuxer: SrsFlvMuxer closed
12-15 18:20:59.534 11237-11237/net.ossrs.yasea.demo I/SrsMp4Muxer: SrsMp4Muxer closed

Samsung SM-G7102 firmware 4.4.2 CPU ARM Cortex-A7

**Comment by begeekmyfriend** [comment]
It seemed socket connection did nothing with the encoder.
