### ISSUE TITLE
Set Preview Size depend on Screen Size

### ISSUE THREAD

**Issue by HuuThang91** [begeekmyfriend/yasea#275]
How can i set mPublisher.setPreviewResolution depend on Screen Size, because if i fix preview resolution ,for example mPublisher.setPreviewResolution(640, 480), It s work fine for most device but it make app's crash for some device

**Comment by begeekmyfriend** [comment]
`setPreviewResolution` eventually depends on [getSupportedPreviewSizes](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsCameraView.java#L337) not your screen size.

**Comment by HuuThang91** [comment]
so, can you help me ., how can i set Previcew Resolution automaticly , not manualy?

**Comment by begeekmyfriend** [comment]
No, you have to specify one and the [adaptPreviewResolution](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsCameraView.java#L333) method will help adapt to the most proper size, or use the default presetting.
