### ISSUE TITLE
mediacodec 

### ISSUE THREAD

**Issue by fly518420** [begeekmyfriend/yasea#277]
硬编码有的手机码率设置不生效，并且会超级的大。

**Comment by begeekmyfriend** [comment]
什么叫“超级的大”？

**Comment by fly518420** [comment]
比如我设置的是500的码率，实际监控到的码率有1.4M这样

**Comment by begeekmyfriend** [comment]
I cannot explain it...

**Comment by fly518420** [comment]
还有一个问题就是 如果我推1.5M的码率 和 我推一个500的码率， 在网络不好的时候进行观看会对观看的马赛克有影响吗

**Comment by begeekmyfriend** [comment]
Higher bit rate, more loss.
