### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Jan31** [begeekmyfriend/yasea#278]
Hi,
I have imported project but getting following error...
Error:(1, 0) Cause: com/android/build/gradle/AppPlugin : Unsupported major.minor version 52.0
Open File

Please Help

**Comment by begeekmyfriend** [comment]
Only support Android Studio

**Comment by Jan31** [comment]
Its working now.
I want to know does this example support rtmp/rtsp mp3 live streaming. I have wawza urls and want to play audio in my project

**Comment by begeekmyfriend** [comment]
Yasea only serves AAC for audio encoding.

**Comment by begeekmyfriend** [comment]
By the way, AAC possess higher quality than MP3 with more compression.
