### ISSUE TITLE
RTMP stream to Wowza server getting crash

### ISSUE THREAD

**Issue by nikhilkilivayil** [begeekmyfriend/yasea#279]
Hardware encoder is using, getting crash

crash log:

12-23 18:05:25.270 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:25.719 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:25.757 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:25.798 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:25.837 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:25.882 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:25.926 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:25.964 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:26.008 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:26.052 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:26.089 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:26.133 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:26.174 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:26.214 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:26.257 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:26.296 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:26.338 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:26.381 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:26.422 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:26.464 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:26.514 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:26.551 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:26.594 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:26.630 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:26.671 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:26.713 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:26.754 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:26.795 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:26.842 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:26.879 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:26.923 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:26.964 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:27.006 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:27.050 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:27.091 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:27.137 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:27.170 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:27.216 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:27.257 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:27.304 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:27.347 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:27.387 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:27.422 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:27.460 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:27.511 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:27.552 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:27.596 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:27.644 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:27.682 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:27.721 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:27.764 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:27.806 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:27.845 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:27.889 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:27.931 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:27.974 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:28.015 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:28.063 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:28.094 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:28.136 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:28.182 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:28.228 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:28.258 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:28.301 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:28.340 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:28.383 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:28.427 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:28.465 21021-21180/net.ossrs.yasea.demo E/libenc: I420Scale failure
12-23 18:05:28.511 21021-21314/net.ossrs.yasea.demo I/SrsFlvMuxer: worker: connecting to RTMP server by url=rtmp://192.168.1.125:1935/rtmpsample/myStream
12-23 18:05:28.511 21021-21314/net.ossrs.yasea.demo D/RtmpConnection: connect() called. Host: 192.168.1.125, port: 1935, appName: rtmpsample, publishPath: myStream
12-23 18:05:28.515 21021-21180/net.ossrs.yasea.demo A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x5d8 in tid 21180 (Thread-4446)
12-23 18:05:28.560 21021-21324/net.ossrs.yasea.demo I/OMXClient: Using client-side OMX mux.
12-23 18:05:28.565 21021-21324/net.ossrs.yasea.demo I/ACodec: sampleRate=44100 channels=2 bits=16
12-23 18:05:28.567 21021-21328/net.ossrs.yasea.demo I/OMXClient: Using client-side OMX mux.

**Comment by begeekmyfriend** [comment]
Did you modify the original code? Or what is your device?

**Comment by nikhilkilivayil** [comment]
I didn't modify anything. Three devices I tested. : Zuk z1(arm7), vivo v5(arm8), Micromax p701(arm8)

**Comment by begeekmyfriend** [comment]
See #293

**Comment by heaveninfosoft** [comment]
i have same issue when i try to using to live usb camera

**Comment by begeekmyfriend** [comment]
Please check if there is IDR frame tag in [SrsFlvMuxer.java](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsFlvMuxer.java#L875) using external camera. If not you might check your code of adaption especially for [ByteBuffer and BufferInfo](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L348).

**Comment by heaveninfosoft** [comment]
@begeekmyfriend    error E/libenc: I420Scale failureerror
 eror come at below line
https://github.com/begeekmyfriend/yasea/blob/38418392358070f2ed36c0580a6b29bf3499695b/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L427

**Comment by begeekmyfriend** [comment]
Hope this history [issue](https://github.com/begeekmyfriend/yasea/issues/723) can help you. And you can search more relevant issues with question label. I am unavailable for Android development currently.
