### ISSUE TITLE
有点卡，播放不平滑

### ISSUE THREAD

**Issue by cndacai** [begeekmyfriend/yasea#28]
推流到srs服务器， 用VLC播放，将android端移动，VLC播放不是十分流畅，画面不平滑。但是用srs-sea推流，VLC播放则要平滑许多，请问是不是哪里参数没有调整好，应该怎么解决这个问题？

**Comment by begeekmyfriend** [comment]
请使用公网播放器[srs_player](http://www.ossrs.net/players/srs_player.html)，并将对比播放器下面展示的参数（帧率、码率等）。

**Comment by begeekmyfriend** [comment]
你这么一说我想起来了，yasea视频前处理和UI在同一个线程里，计算量很大，的确是瓶颈，srs-sea是没有前处理的，谢谢告知！

**Comment by begeekmyfriend** [comment]
最新版优化了一下YUV前处理，分离线程，效果差不多。

播放平滑与否，跟帧率(fps)关系最大。用手机对比测试，由于不同手机摄像头设备接口不一样，比如Nexus可以自己设置fps=24，三星Galaxy Note2摄像头不支持fps，而是固定fps=10，自然Nexus推流播放平滑许多，三星Galaxy Note2略微卡顿。这不是软件能控制的。

而且还发现一个有趣现象，fps小的摄像头推流，手机不烫，烫的都是fps高的手机。我猜想是否考虑到这一点，某些厂商故意把fps底层写死。

既然你说srs-sea对比，具体我不知道什么情况，如果是同一台手机，那播放效果应该差不多，判别方法还是用公网那个srs-player看看播放参数（比如fps）对比是多少。
