### ISSUE TITLE
移动手机出现类似马赛克的问题

### ISSUE THREAD

**Issue by joelan** [begeekmyfriend/yasea#282]
推流端和拉流端和服务器都在同一个局域网，移动下手机会出现类似马赛克的问题？

**Comment by begeekmyfriend** [comment]
码率太少了，你确定你的网OK？

**Comment by joelan** [comment]
应该没问题吧？都在同一个局域网，速度应该都
很快吧？对了，还有，该怎么调整那个分辨率，我感觉推流端手机上显示的影像和拉流端影像都稍微有一点拉伸的感觉

**Comment by begeekmyfriend** [comment]
拉升是因为分辨率和手机尺寸不匹配，采样分辨率是480p，如果手机比这个还要长，就会出现拉升，没办法的，因为采样分辨率有枚举值，不能随便设置。你可以设置成720p采样，画面就扁一点，但美颜开启后可能会掉帧。

马赛克的问题，如果网络没有问题，提高推流码率

**Comment by joelan** [comment]
推流码率是srsEncoder里面的这个吗   public static final int ABITRATE ?

**Comment by begeekmyfriend** [comment]
对

**Comment by joelan** [comment]
vBitrate ？这个？已经是1200*1000了？还要大概要提高到多少

**Comment by begeekmyfriend** [comment]
所以我觉得你的马赛克是不是网络问题，你推流到`rtmp://ossrs.net/xxx/xxxx`试试
