### ISSUE TITLE
AAC audio

### ISSUE THREAD

**Issue by ntminh90** [begeekmyfriend/yasea#283]
Audio RTMP AAC output from phone maybe is distored and has noise floor.
When i retranscode this RTMP to another AAC proile i hear also clearly.
Thank you for supporting.

**Comment by begeekmyfriend** [comment]
Did your device support [AEC](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsPublisher.java#L76)

**Comment by ntminh90** [comment]
You mean my equipment which retransscode RTMP output from yasea application? Can it support AEC?

**Comment by begeekmyfriend** [comment]
Please check whether AEC was enabled.

**Comment by begeekmyfriend** [comment]
I am sorry it is somewhat late to inform you that I have expanded the audio record buffer to improve the AEC result. See commit https://github.com/begeekmyfriend/yasea/commit/f6f071a6b624decfa6169e1841627df78152724d which really solved audio noise on some devices.
