### ISSUE TITLE
Audio streaming with noise and drop package

### ISSUE THREAD

**Issue by davidarchi** [begeekmyfriend/yasea#284]
Hi,
Actually, I am facing the issue relate to audio quality,
This lib can working fine with FFMPEG server but when I tried with other kind of server (Elemental server: http://www.elemental.com/products/elemental-server),
audio quality has low quality (very much noise) and it seems that some package of audio was drop.
Addition, I also test with 3rd app (https://play.google.com/store/apps/details?id=com.bemytv.mycaster.free) with my server Elemantal, It also work fine without noise. 
Can you suggest me any solution to resolve this ?
Thanks

**Comment by begeekmyfriend** [comment]
I am afraid you need to contact Elemental staff to find the solution for yasea works fine on general RTMP server.

But before that you need to confirm that if [AEC](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsPublisher.java#L76) was enabled on your device.
