### ISSUE TITLE
您好！之前推流的时候是可以聚焦的，我更新了最新的之后感觉聚焦效果没以前那么明显了？

### ISSUE THREAD

**Issue by 386405828** [begeekmyfriend/yasea#285]

**Comment by begeekmyfriend** [comment]
Try removing this [line](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/AndroidManifest.xml#L9)

**Comment by begeekmyfriend** [comment]
I have deleted it in commit https://github.com/begeekmyfriend/yasea/commit/ad73ed43979fa3e20e7156cf5128f635aa0467d0#diff-c8cc2dd42271f2bf39c6aa81eb6a5529L9
