### ISSUE TITLE
手机推流画面很暗，log打印这个，是什么原因呢？

### ISSUE THREAD

**Issue by cat1024** [begeekmyfriend/yasea#292]
Camera[ERROR] asd_port_stats_done_callback: 174: asd_port_stats_done_callback:174  asd_port_stats_done_callback Done ASD STATS ACK back                                                                     
Camera[ERROR] aec_biz_set_debug_data_enable: 1487: aec_biz_set_debug_data_enable:1487  aec set param AEC_SET_PARAM_DEBUG_DATA_LEVEL failed with result 1
 Camera[ERROR] aec_process_calculate_current_luma: 2245: aec_process_calculate_current_luma:2245  aec_BG: bayer luma(10.966911), hybrid luma(10.991308)
Camera[ERROR] aec_process_calculate_current_luma_for_af: 2953: aec_process_calculate_current_luma_for_af:2953  max 44 min 6, avg 10
Camera[ERROR] aec_process_fast_smooth_convergence: 3636: aec_process_fast_smooth_convergence:3636  luma_avr: [10.963790] cur_luma : [10.966911] target : [50.000000] luma_settled_cnt : [5705]

**Comment by begeekmyfriend** [comment]
I have no idea about it. What about other phones?

**Comment by cat1024** [comment]
我试了两部6.0系统的手机分别是三星c7，小米4，画面很暗，尤其是开美颜效果之后，而一部4.4一部5.0系统的手机没有这样的问题

**Comment by cat1024** [comment]
非常感谢您的细心回答，美颜会加剧视频暗度，我想视频很暗根本原因不是美颜引起的，系统亮度的调整对整个视频的效果影响不大！我下了yasea最开始的版本，和最新版本的apk，都有这样的问题。

**Comment by begeekmyfriend** [comment]
Your log is so strange that there seems luma component deficiency in your camera device

**Comment by cat1024** [comment]
我这边测试到导致视频很暗的原因是在SrsCameraVie类中的
params.setPreviewFpsRange(range[0], range[1])；这行代码。当我注调这行代码，画面恢复常了；但是会引起拉流会面卡顿。。。
