### ISSUE TITLE
publishing to rtmp server getting crash

### ISSUE THREAD

**Issue by nikhilkilivayil** [begeekmyfriend/yasea#293]
01-06 12:00:09.307 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:09.352 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:09.390 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:09.435 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:09.474 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:09.514 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:09.560 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:09.600 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:09.642 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:09.692 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:09.731 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:09.774 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:09.814 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:09.851 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:09.896 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:09.935 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:09.976 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:10.021 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:10.059 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:10.108 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:10.148 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:10.185 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:10.227 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:10.271 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:10.314 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:10.354 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:10.396 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:10.434 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:10.478 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:10.519 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:10.555 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:10.600 5380-5903/net.ossrs.yasea.demo E/libenc: I420Scale failure
01-06 12:00:10.609 5380-6139/net.ossrs.yasea.demo I/SrsFlvMuxer: worker: connecting to RTMP server by url=rtmp://192.168.1.125:1935/rtmpsample/myStream
01-06 12:00:10.609 5380-6139/net.ossrs.yasea.demo D/RtmpConnection: connect() called. Host: 192.168.1.125, port: 1935, appName: rtmpsample, publishPath: myStream
01-06 12:00:10.664 5380-6150/net.ossrs.yasea.demo I/OMXClient: Using client-side OMX mux.
01-06 12:00:10.675 5380-6150/net.ossrs.yasea.demo I/ACodec: sampleRate=44100 channels=2 bits=16
01-06 12:00:10.679 5380-6154/net.ossrs.yasea.demo I/OMXClient: Using client-side OMX mux.
01-06 12:00:10.711 5380-6139/net.ossrs.yasea.demo D/RtmpConnection: connect(): socket connection established, doing handhake...
01-06 12:00:10.715 5380-6139/net.ossrs.yasea.demo D/Handshake: writeC0
01-06 12:00:10.715 5380-6139/net.ossrs.yasea.demo D/Handshake: writeC1
01-06 12:00:10.715 5380-6139/net.ossrs.yasea.demo D/Handshake: writeC1(): Calculating digest offset
01-06 12:00:10.716 5380-6139/net.ossrs.yasea.demo D/Handshake: writeC1(): (real value of) digestOffset: 661
01-06 12:00:10.716 5380-6139/net.ossrs.yasea.demo D/Handshake: writeC1(): recalculated digestOffset: 1437
01-06 12:00:10.719 5380-6139/net.ossrs.yasea.demo D/Handshake: writeC1(): digestOffsetBytes: 0097FFFF
01-06 12:00:10.719 5380-6139/net.ossrs.yasea.demo D/Handshake: partBeforeDigest(): size: 1437
01-06 12:00:10.719 5380-6139/net.ossrs.yasea.demo D/Handshake: writeC1(): Writing timestamp and Flash Player version
01-06 12:00:10.719 5380-6139/net.ossrs.yasea.demo D/Handshake: partAfterDigest(): size: 67
01-06 12:00:10.719 5380-6139/net.ossrs.yasea.demo D/Handshake: copying digest offset bytes in partBeforeDigest
01-06 12:00:10.719 5380-6139/net.ossrs.yasea.demo D/Handshake: writeC1(): Calculating digest
01-06 12:00:10.723 5380-6139/net.ossrs.yasea.demo D/Handshake: writeC1(): writing C1 packet
01-06 12:00:10.724 5380-6139/net.ossrs.yasea.demo D/Handshake: readS0
01-06 12:00:10.743 5380-6139/net.ossrs.yasea.demo D/Handshake: readS1
01-06 12:00:10.743 5380-6139/net.ossrs.yasea.demo D/Handshake: readS1(): S1 total bytes read OK
01-06 12:00:10.743 5380-6139/net.ossrs.yasea.demo D/Handshake: readC2
01-06 12:00:10.743 5380-6139/net.ossrs.yasea.demo D/Handshake: readS2
01-06 12:00:10.743 5380-6139/net.ossrs.yasea.demo D/Handshake: readS2(): S2 total bytes read OK
01-06 12:00:10.744 5380-6139/net.ossrs.yasea.demo D/RtmpConnection: connect(): handshake done
01-06 12:00:10.745 5380-6159/net.ossrs.yasea.demo D/RtmpConnection: starting main rx handler loop
01-06 12:00:10.746 5380-6139/net.ossrs.yasea.demo D/RtmpConnection: rtmpConnect(): Building 'connect' invoke packet
01-06 12:00:10.761 5380-6154/net.ossrs.yasea.demo E/ACodec: [OMX.qcom.video.encoder.avc] storeMetaDataInBuffers (output) failed w/ err -1010
01-06 12:00:10.762 5380-6154/net.ossrs.yasea.demo W/ACodec: do not know color format 0x7fa30c04 = 2141391876
01-06 12:00:10.762 5380-6154/net.ossrs.yasea.demo W/ACodec: do not know color format 0x7f000789 = 2130708361
01-06 12:00:10.767 5380-6139/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Command (command: connect, transaction ID: 1), size: 263
01-06 12:00:10.767 5380-6154/net.ossrs.yasea.demo I/ACodec: [OMX.qcom.video.encoder.avc] setupVideoEncoder succeeded
01-06 12:00:10.800 5380-6159/net.ossrs.yasea.demo D/RtmpConnection: handleRxPacketLoop(): Setting acknowledgement window size: 2500000
01-06 12:00:10.806 5380-6159/net.ossrs.yasea.demo D/RtmpConnection: handleRxPacketLoop(): Send acknowledgement window size: 2500000
01-06 12:00:10.806 5380-6159/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Window Acknowledgment Size, size: 4
01-06 12:00:10.814 5380-6159/net.ossrs.yasea.demo D/RtmpDecoder: readPacket(): Setting chunk size to: 4096
01-06 12:00:10.821 5380-6159/net.ossrs.yasea.demo D/RtmpConnection: handleRxInvoke: Got result for invoked method: connect
01-06 12:00:10.821 5380-6139/net.ossrs.yasea.demo D/RtmpConnection: createStream(): Sending releaseStream command...
01-06 12:00:10.823 5380-6139/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Command (command: releaseStream, transaction ID: 2), size: 37
01-06 12:00:10.823 5380-6139/net.ossrs.yasea.demo D/RtmpConnection: createStream(): Sending FCPublish command...
01-06 12:00:10.823 5380-6139/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Command (command: FCPublish, transaction ID: 3), size: 33
01-06 12:00:10.823 5380-6139/net.ossrs.yasea.demo D/RtmpConnection: createStream(): Sending createStream command...
01-06 12:00:10.823 5380-6139/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Command (command: createStream, transaction ID: 4), size: 25
01-06 12:00:10.853 5380-5903/net.ossrs.yasea.demo I/SrsFlvMuxer: annexb demux 652B, pts=0, frame=22B, nalu=7
01-06 12:00:10.854 5380-5903/net.ossrs.yasea.demo I/SrsFlvMuxer: annexb demux 652B, pts=0, frame=4B, nalu=8
01-06 12:00:10.856 5380-5903/net.ossrs.yasea.demo I/SrsFlvMuxer: flv: h264 sps/pps sent, sps=22B, pps=4B
01-06 12:00:10.864 5380-6159/net.ossrs.yasea.demo D/RtmpConnection: handleRxInvoke(): 'onFCPublish'
01-06 12:00:10.864 5380-6159/net.ossrs.yasea.demo D/RtmpConnection: handleRxInvoke: Got result for invoked method: createStream
01-06 12:00:10.864 5380-6159/net.ossrs.yasea.demo D/RtmpConnection: handleRxInvoke(): Stream ID to publish: 1
01-06 12:00:10.864 5380-6159/net.ossrs.yasea.demo D/RtmpConnection: fmlePublish(): Sending publish command...
01-06 12:00:10.864 5380-6159/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Command (command: publish, transaction ID: 0), size: 38
01-06 12:00:10.897 5380-5522/net.ossrs.yasea.demo V/RenderScript: Application requested CPU execution
01-06 12:00:10.904 5380-5522/net.ossrs.yasea.demo V/RenderScript: 0xa1189800 Launching thread(s), CPUs 4
01-06 12:00:10.915 5380-6159/net.ossrs.yasea.demo D/RtmpConnection: handleRxInvoke(): onStatus NetStream.Publish.Start
01-06 12:00:10.915 5380-6159/net.ossrs.yasea.demo D/RtmpConnection: onMetaData(): Sending empty onMetaData...
01-06 12:00:10.917 5380-6159/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: com.github.faucamp.simplertmp.packets.Data@1c9ec094, size: 238
01-06 12:00:10.920 5380-6139/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Video, size: 42
01-06 12:00:10.920 5380-6139/net.ossrs.yasea.demo I/SrsFlvMuxer: worker: send frame type=9, dts=0, size=42B
01-06 12:00:10.920 5380-6139/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Video, size: 624
01-06 12:00:10.927 5380-6139/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Video, size: 16968
01-06 12:00:10.928 5380-6139/net.ossrs.yasea.demo I/SrsFlvMuxer: worker: send frame type=9, dts=241, size=16968B
01-06 12:00:10.966 5380-6139/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Video, size: 1024
01-06 12:00:10.993 5380-6139/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Video, size: 6234
01-06 12:00:11.016 5380-6139/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Video, size: 3810
01-06 12:00:11.019 5380-6139/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 11
01-06 12:00:11.019 5380-6139/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 94
01-06 12:00:11.019 5380-6139/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 138
                                                                    
                                                                    --------- beginning of crash
01-06 12:00:11.019 5380-6165/net.ossrs.yasea.demo A/libc: common/frame.c:765: x264_frame_push_unused: assertion "frame->i_reference_count > 0" failed
01-06 12:00:11.020 5380-6165/net.ossrs.yasea.demo A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 6165 (Thread-484)

**Comment by nikhilkilivayil** [comment]
I got this error first 



emo D/RtmpConnection: createStream(): Sending releaseStream command...
01-06 12:35:40.756 10291-11890/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Command (command: releaseStream, transaction ID: 2), size: 34
01-06 12:35:40.756 10291-11890/net.ossrs.yasea.demo D/RtmpConnection: createStream(): Sending FCPublish command...
01-06 12:35:40.757 10291-11890/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Command (command: FCPublish, transaction ID: 3), size: 30
01-06 12:35:40.757 10291-11890/net.ossrs.yasea.demo D/RtmpConnection: createStream(): Sending createStream command...
01-06 12:35:40.757 10291-11890/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Command (command: createStream, transaction ID: 4), size: 25
01-06 12:35:40.759 10291-11904/net.ossrs.yasea.demo D/RtmpConnection: handleRxInvoke(): 'onBWDone'
01-06 12:35:40.785 10291-11903/net.ossrs.yasea.demo E/ACodec: [OMX.qcom.video.encoder.avc] storeMetaDataInBuffers (output) failed w/ err -1010
01-06 12:35:40.786 10291-11903/net.ossrs.yasea.demo W/ACodec: do not know color format 0x7fa30c04 = 2141391876
01-06 12:35:40.786 10291-11903/net.ossrs.yasea.demo W/ACodec: do not know color format 0x7f000789 = 2130708361
01-06 12:35:40.793 10291-11903/net.ossrs.yasea.demo I/ACodec: [OMX.qcom.video.encoder.avc] setupVideoEncoder succeeded
01-06 12:35:40.795 10291-11904/net.ossrs.yasea.demo E/RtmpConnection: handleRxInvoke(): Unknown/unhandled server invoke: RTMP Command (command: _error, transaction ID: 2)
01-06 12:35:40.795 10291-11904/net.ossrs.yasea.demo D/RtmpConnection: handleRxInvoke: Got result for invoked method: FCPublish
01-06 12:35:40.795 10291-11904/net.ossrs.yasea.demo D/RtmpConnection: handleRxInvoke(): 'FCPublish'
01-06 12:35:40.795 10291-11904/net.ossrs.yasea.demo D/RtmpConnection: handleRxInvoke(): 'onFCPublish'
01-06 12:35:40.795 10291-11904/net.ossrs.yasea.demo D/RtmpConnection: handleRxInvoke: Got result for invoked method: createStream
01-06 12:35:40.795 10291-11904/net.ossrs.yasea.demo D/RtmpConnection: handleRxInvoke(): Stream ID to publish: 1
01-06 12:35:40.795 10291-11904/net.ossrs.yasea.demo D/RtmpConnection: fmlePublish(): Sending publish command...
01-06 12:35:40.795 10291-11904/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Command (command: publish, transaction ID: 0), size: 35
01-06 12:35:40.802 10291-11904/net.ossrs.yasea.demo D/RtmpConnection: handleRxInvoke(): onStatus NetStream.Publish.Start
01-06 12:35:40.802 10291-11904/net.ossrs.yasea.demo D/RtmpConnection: onMetaData(): Sending empty onMetaData...
01-06 12:35:40.805 10291-11904/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: com.github.faucamp.simplertmp.packets.Data@4d57ce7, size: 238
01-06 12:35:40.861 10291-11788/net.ossrs.yasea.demo I/SrsFlvMuxer: annexb demux 652B, pts=0, frame=22B, nalu=7
01-06 12:35:40.861 10291-11788/net.ossrs.yasea.demo I/SrsFlvMuxer: annexb demux 652B, pts=0, frame=4B, nalu=8
01-06 12:35:40.865 10291-11890/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Video, size: 42
01-06 12:35:40.866 10291-11890/net.ossrs.yasea.demo I/SrsFlvMuxer: worker: send frame type=9, dts=0, size=42B
01-06 12:35:40.866 10291-11788/net.ossrs.yasea.demo I/SrsFlvMuxer: flv: h264 sps/pps sent, sps=22B, pps=4B
01-06 12:35:40.866 10291-11890/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Video, size: 624
01-06 12:35:40.897 10291-10557/net.ossrs.yasea.demo V/RenderScript: Application requested CPU execution
01-06 12:35:40.909 10291-10557/net.ossrs.yasea.demo V/RenderScript: 0x9b38d200 Launching thread(s), CPUs 4
01-06 12:35:40.937 10291-11890/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Video, size: 14248
01-06 12:35:40.937 10291-11890/net.ossrs.yasea.demo I/SrsFlvMuxer: worker: send frame type=9, dts=239, size=14248B
01-06 12:35:40.975 10291-11890/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Video, size: 2911
01-06 12:35:40.994 10291-11890/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Video, size: 3987
01-06 12:35:41.019 10291-11890/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 11
01-06 12:35:41.019 10291-11890/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 94
01-06 12:35:41.037 10291-11890/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 133
01-06 12:35:41.039 10291-11890/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Video, size: 4217
01-06 12:35:41.057 10291-11890/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 150
01-06 12:35:41.077 10291-11890/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Video, size: 4811
01-06 12:35:41.078 10291-11890/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 123
01-06 12:35:41.097 10291-11890/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 117
01-06 12:35:41.128 10291-11890/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Video, size: 5207
01-06 12:35:41.137 10291-11890/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 120
01-06 12:35:41.157 10291-11890/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 117
01-06 12:35:41.163 10291-11890/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Video, size: 5180
01-06 12:35:41.171 10291-11915/net.ossrs.yasea.demo E/AndroidRuntime: FATAL EXCEPTION: Thread-594
                                                                      Process: net.ossrs.yasea.demo, PID: 10291
                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'int[] java.nio.IntBuffer.array()' on a null object reference
                                                                          at net.ossrs.yasea.SrsCameraView$4.run(SrsCameraView.java:226)
                                                                          at java.lang.Thread.run(Thread.java:818)
01-06 12:35:41.178 10291-11890/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 107
01-06 12:35:41.178 10291-11890/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 113
01-06 12:35:41.211 10291-11890/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Video, size: 5550
01-06 12:35:41.218 10291-11890/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 108
01-06 12:35:41.237 10291-11890/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 99

**Comment by begeekmyfriend** [comment]
Were you using the latest version? What operation did you trigger the crash? And how long?

**Comment by nikhilkilivayil** [comment]
Yes. I am using latest version only(master branch- ad73ed43979fa3e20e7156cf5128f635aa0467d0). 


Softencoder not opening camera. So, I switched to hardencoder. Then I switched the camera, camera open now. Then I tried to publish to server. That time getting this issue.

**Comment by nikhilkilivayil** [comment]
Checked with srs server, Wowza server . Both getting the same issue.

**Comment by nikhilkilivayil** [comment]
From my post, second put log I am getting first. 

Inside that showing some null pointer exception : 

> Process: net.ossrs.yasea.demo, PID: 10291
> java.lang.NullPointerException: Attempt to invoke virtual method 'int[] java.nio.IntBuffer.array()' on a null object reference
> at net.ossrs.yasea.SrsCameraView$4.run(SrsCameraView.java:226)

So, I added one null condition checking that line SrsCameraView.java 


`  IntBuffer picture = mGLIntBufferCache.poll();

                            mGLPreviewBuffer.asIntBuffer().put(picture.array());
                            mPrevCb.onGetRgbaFrame(mGLPreviewBuffer.array(), mPreviewWidth, mPreviewHeight);`


this code I changed to 

`   IntBuffer picture = mGLIntBufferCache.poll();
                            if(picture!=null) {
                                mGLPreviewBuffer.asIntBuffer().put(picture.array());
                                mPrevCb.onGetRgbaFrame(mGLPreviewBuffer.array(), mPreviewWidth, mPreviewHeight);
                            }
`

Then getting first posted crash log.

**Comment by begeekmyfriend** [comment]
Fixed https://github.com/begeekmyfriend/yasea/commit/42fd31eb5c6221e433ac1d1f9ce1abaa849a6f90

**Comment by heaveninfosoft** [comment]
@nikhilkilivayil have you solved??
