### ISSUE TITLE
关于推流优化和美颜问题

### ISSUE THREAD

**Issue by decide15** [begeekmyfriend/yasea#294]
您好，我对比了您和restreaming，同样的分辨率无滤镜情况下，Yasea所需要的内存和CPU都非常高。同样的手机，restreaming的CPU使用率约 小于5%，Yasea的CPU 大于20% ，而且内存回收呈锯齿状。回收速度非常快，请问是不是有什么优化方向。
       还有美颜滤镜发现效果不是很好，亮度低了一点，能不能mix两个Filter呢？对openGL的知识一无所知。。
拜谢！

**Comment by notedit** [comment]
restreaming 是什么

**Comment by decide15** [comment]
[开源推流项目](https://github.com/lakeinchina/librestreaming)

**Comment by decide15** [comment]
另外，磨皮美颜算法在某些MTK CPU手机上有严重的掉帧情况，我手上这部魅蓝note3跑起来是慢动作。。

**Comment by begeekmyfriend** [comment]
的确yasea没有做缓存，每个new对象（FLV frame、RTMP packet）出队列拷贝后就直接GC了，触发内存回收，这的确会导致CPU飚上去。优化一点的做法是自己做缓存池啦~

调亮度的话见[这一行](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/res/raw/beauty.glsl#L110)，RGB同时加上（或减去）某个数值你应该知道是什么意思吧。

掉帧恐怕要看设备了，我默认设置fps=24，如果无滤镜都达不到的话，真的很难避免掉帧。两种方法：
- 使用`MagicCamera`的[轻度美颜](https://github.com/wuhaoyu1990/MagicCamera/blob/master/Project_eclipse_old/MagicFilter/res/raw/beautify_fragment_low.glsl)，当然作者也维护了一个[正常美颜](https://github.com/wuhaoyu1990/MagicCamera/blob/master/Project_eclipse_old/MagicFilter/res/raw/beautify_fragment.glsl)。
- 摄像头采样分辨率480p别提高了。

**Comment by begeekmyfriend** [comment]
另外`librestreaming `的磨皮算法浏览了一下，有个脸部的条件判断，个人觉得条件语句很可能会限制GPU的发挥，还不如考虑`MagicCamera`的轻度美颜

**Comment by decide15** [comment]
THX
