### ISSUE TITLE
Audio Problem

### ISSUE THREAD

**Issue by developeralp** [begeekmyfriend/yasea#296]
Hello,

Sometimes , i'm getting that error.

That error can not be catchable like other errors,(App not throws java.lang.Exception class)

How this error occurs ?

Start rtmp live stream -> connect stream from another device -> on another phone there is no audio from rtmp stream...

shortly ,  i cannot listen rtmp streams audio...

How can i solve that ?

**Comment by begeekmyfriend** [comment]
Sometimes? I think you had better ask server vendor to check the problem why there is no audio stream downloading.
