### ISSUE TITLE
Initially camera view not showing

### ISSUE THREAD

**Issue by nikhilkilivayil** [begeekmyfriend/yasea#298]
Initially camera view is not visible. Black screen is coming. After pressing publish button, it's showing. 
How to enable camera screen intially?

**Comment by begeekmyfriend** [comment]
Move [publishing code](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/demo/MainActivity.java#L80-L95) into `onCreate` method.

**Comment by nikhilkilivayil** [comment]
No. That time publishing will also start while opening screen. I need to open camera view without publishing the view. Publish need to start same like as it is after pressing publish button.

**Comment by begeekmyfriend** [comment]
I do not catch your point... Does yasea not make it?

**Comment by nikhilkilivayil** [comment]
No. In Yasia initially black screen is coming . Whenever user pressing publish button, camera will open. This is how yasia now working. I need to open camera view instead of that black screen.

**Comment by begeekmyfriend** [comment]
I am afraid you do not understand some usage of Android UI components. The current practice is that the camera view has already been set in XML file in `res/layout` directory.  And then call  `(SrsCameraView) findViewById(R.id.glsurfaceview_camera)` to reference it in `onCreate` method.

**Comment by nikhilkilivayil** [comment]
Yes. I got that point. But, how visibility enable for camera view. Initially camera in closed state. Because of that black color only showing while starting. Openglview draw starting only after calling `startPublish()` method. I need to display camera content before publish starting.

**Comment by begeekmyfriend** [comment]
Just call `startCamera`.

**Comment by PangMing** [comment]
Could you please tell me the details on how to display the camera view without click Publish button.
I tried to call the startCamere method but failed, maybe I'm doing in a wrong way.

**Comment by begeekmyfriend** [comment]
In my option, the camera view is to be displayed at the `MainActivity` launch for it has been set in [res/layout/activity_main.xml](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/res/layout/activity_main.xml#L8-L17)
