### ISSUE TITLE
没声音的问题

### ISSUE THREAD

**Issue by tz-xiaomage** [begeekmyfriend/yasea#30]
情境：
A手机在在同个页面进行先播放rtmp流 然后打开 yasea推流，发现推过去的流是没有声音的。
请问是不是因为播放rtmp流的播放器占用了音频，所以推流拿不到声音？
我使用的播放器是：[PLDroidPlayer](https://github.com/pili-engineering/PLDroidPlayer)

**Comment by begeekmyfriend** [comment]
如果你没有改动代码，而且能看到视频，肯定同时发送音频，除非你播放器设置有问题

**Comment by tz-xiaomage** [comment]
我刚刚尝试了将PLDroidPlayer的音频播放改成共享
![image](https://cloud.githubusercontent.com/assets/12270504/15742250/538fef9a-28f0-11e6-9a88-7e1cbc404da7.png)
这样能解决先推流的情况的再播放流，不会出现抢占的情况，也就是两个声音都有了，
然而如果是先播放 再 推流的话，就会把播放的声音给抢了，这样就造成播放的没有声音
不知道能不能把推流这一边也改成共享的？

**Comment by begeekmyfriend** [comment]
不明白这个东西，yasea又不是专门针对PLDroidPlayer的，我一般用VLC。而且我也不知道哪个配置或代码能把推流改成共享的。

**Comment by notedit** [comment]
这是 android 的音频焦点抢占问题    android 的限制

**Comment by tz-xiaomage** [comment]
@notedit 就是焦点抢占的问题，就是不知道yasea有没有可以设置的地方

**Comment by tz-xiaomage** [comment]
@notedit 因为yasea是音频输入的，所以确实不知道哪个地方设置

**Comment by notedit** [comment]
设置也不管用的 android 的问题

**Comment by notedit** [comment]
共享使用会导致   推流的时候声音很小   基本没方案解决

**Comment by tz-xiaomage** [comment]
@notedit 声音小也好过没声音，有吗？

**Comment by tz-xiaomage** [comment]
因为我是发现一个app是能这样做的，而且没问题，叫kk世界说，就是两个人对讲的

**Comment by notedit** [comment]
实现机制不一样   你去搜一下  腾讯互动直播

**Comment by notedit** [comment]
rtmp 做不到

**Comment by tz-xiaomage** [comment]
@notedit 感谢，我试试看

**Comment by kyserCool** [comment]
@tz-xiaomage 
@begeekmyfriend 
我也发现这个问题，我是播着音乐，然后推的流是没声音的

**Comment by tz-xiaomage** [comment]
@begeekmyfriend 实在是不好意思，我反复多次测试后，发现不是因为抢占的问题，是只有小米 MI NOTE LTE 6.0.1会录不到声音
![image](https://cloud.githubusercontent.com/assets/12270504/15766746/9f4f91e0-2974-11e6-93a1-3dcdd84af1db.png)


![image](https://cloud.githubusercontent.com/assets/12270504/15766842/832fb89a-2975-11e6-841e-dc800ec8649e.png)

权限上面，我是百分之百有授权可以录音的

![image](https://cloud.githubusercontent.com/assets/12270504/15766900/e6bb0d6a-2975-11e6-8ec9-647c2a5461af.png)

**Comment by tz-xiaomage** [comment]
@begeekmyfriend 尝试了重新开机发现确实是我这边的问题，手机有程序占用的麦克风，关闭所有程序都不行，重新开机了才可以，实在是不好意思

**Comment by begeekmyfriend** [comment]
@tz-xiaomage @kyserCool 你俩被流氓软件搞了

**Comment by notedit** [comment]
你们还会遇到这种问题的 用 rtmp 做互动是不 ok 的  

我们测试了  声网的音视频通话  + rtmp直播    会有音频抢占的问题

**Comment by tz-xiaomage** [comment]
@notedit 你的情景是多个视频通话还是两方而已？
如果不使用rtmp，那使用什么才能达到互动的效果啊？

**Comment by notedit** [comment]
webrtc
