### ISSUE TITLE
Hard Encoder and Soft Encoder?

### ISSUE THREAD

**Issue by davidarchi** [begeekmyfriend/yasea#300]
what is diffrient between Hard Encoder and Soft Encoder?
Could you explain?
Thank you

**Comment by begeekmyfriend** [comment]
Hard encoder saves CPU. Consider it first.

**Comment by davidarchi** [comment]
Could uou tell in details ?

**Comment by begeekmyfriend** [comment]
Though for me in English:-P

**Comment by davidarchi** [comment]
Could you tell me in details about hard encoder and soft encoder
Hard encoder use hardware to encode
Soft encoder use software to encode, right?
Which is best for the performance?

**Comment by begeekmyfriend** [comment]
I said that hard encoding performs better.

**Comment by begeekmyfriend** [comment]
I said that hard encoding performs better since the soft one consumes CPU.

**Comment by notedit** [comment]
最好增加一个自动切换的机制   如果硬编失败 动态切换成软编   webrtc里面是这么做的

**Comment by begeekmyfriend** [comment]
@notedit That can be done in `MediaCodec` exception handler written in `SrsEncodeHandler.java`, but I have no such device for test.
