### ISSUE TITLE
关于效率优化等问题

### ISSUE THREAD

**Issue by decide15** [begeekmyfriend/yasea#302]
您好，在研究您项目的过程中，发现一些难以解决的问题，希望您在版本更新的时候，能解决并更新。
1、如上次 #294 问题，我也尝试做了一些优化，但还是时间精力有限且阅读这方面代码能力不足，我自己做的优化始终不能让我比较满意。
2、魅蓝note3 flyme 5.1.11.1A是一个神奇的手机，我尝试过很多RTMP的开源项目，对这个手机的兼容性，不是这里有问题，就是那里有问题，本身期配置还不算太低，但就是各种问题，我觉得如果能搞定它的适配，基本上所有手机都没啥问题了。。
      拜谢！我本身对于这块属于新手，想要好好学习，但是时间不是很允许，加上C/C++和图形算法底子薄弱，希望能多得到您的指点。

**Comment by begeekmyfriend** [comment]
你是指美颜吗？你需要了解shader语法，推荐《OpenGL ES 3.0编程指南》和《OpenGL ES应用开发实践指南 Android卷》两本书参考。

时间紧的话，你可以参考`MagicCamera`项目里的[beautify_fragment.glsl](https://github.com/wuhaoyu1990/MagicCamera/blob/master/Project_eclipse_old/MagicFilter/res/raw/beautify_fragment.glsl)和[beautify_fragment_low.glsl](https://github.com/wuhaoyu1990/MagicCamera/blob/master/Project_eclipse_old/MagicFilter/res/raw/beautify_fragment_low.glsl)两种程度美颜，应该说后者适用于低配，磨皮层数少。高斯模糊算法不懂没关系，关键是输入输出参数的含义，比如`sampler2D`表示二维纹理，从Java的GLES接口来看，绑定到哪个object上，顺藤摸瓜，渐渐就可一目了然了。
