### ISSUE TITLE
画面拉伸问题

### ISSUE THREAD

**Issue by cat1024** [begeekmyfriend/yasea#303]
直播画面拉伸明显，改如何设置？

**Comment by begeekmyfriend** [comment]
这是屏幕比例适配的问题，只能调整采样分辨率，但美颜的话不建议改太大，否则处理不过来容易卡顿，480p是市面上通用的经验值（七牛等）。一般来说，显瘦总比较好~

**Comment by bingdow** [comment]
那如果只是調整畫面比例使其符合相機比例的話會有問題嗎？

**Comment by begeekmyfriend** [comment]
@bingdow 调整view size不影响

**Comment by bingdow** [comment]
好吧，我是想問如何調整採樣分辨率呢？

**Comment by begeekmyfriend** [comment]
@bingdow 前者是摄像头采样分辨率，后者是libyuv做scaling的

**Comment by begeekmyfriend** [comment]
最新版本把预览改成360p了
