### ISSUE TITLE
Dual Camera Preview Q&A

### ISSUE THREAD

**Issue by PangMing** [begeekmyfriend/yasea#304]
Is that any way to combine both camera view of Front and Rear camera in 1 layout and upload to my rtmp server. Example <a href="https://i.stack.imgur.com/6kuyv.jpg">picture</a>

**Comment by begeekmyfriend** [comment]
I recommend [t_rtf_camera](https://github.com/fortdam/t_rtf_camera). Try it.

**Comment by begeekmyfriend** [comment]
It shows multi-camera GL usage...
