### ISSUE TITLE
Q: See/Receive server specific error

### ISSUE THREAD

**Issue by oantajames** [begeekmyfriend/yasea#306]
The current RTMP client does not have an error method.
Like when I make a request and the server aborts the connection, is there a way to receive from it the cause of the abortion ?
Something like a status/notification/response. 

Thanks in advance!

**Comment by begeekmyfriend** [comment]
There are [RTMP handler with callbacks](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/demo/MainActivity.java#L340) in `MainAvtivity.java`. The handler would be passed down to `RtmpConnection.java` and capture the `SocketException` and emit the message.

**Comment by oantajames** [comment]
Oh! I didn't have the last version of your code. Thanks!
