### ISSUE TITLE
How to get video frame from live streaming after some time (e.g. 1 sec)?

### ISSUE THREAD

**Issue by mahmood4429** [begeekmyfriend/yasea#308]
i want to get video frame when publishing starts. please tell me how to do that using this library.

**Comment by begeekmyfriend** [comment]
For H.264 encoded stream: [here](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L331);
For FLV video frame: [here](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsFlvMuxer.java#L1051-L1058);
For RTMP video packet: [here](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L438-L442).

**Comment by mahmood4429** [comment]
i think i didn't explain my question correctly.
i need to get one video frame in bitmap/base64 after some time (e.g 1 sec) when publish started.

**Comment by begeekmyfriend** [comment]
I have told you the entry. You may do it yourself. By the way, the raw RGBA frames are [here](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsCameraView.java#L226)

**Comment by developeralp** [comment]
If you will do this for creating thumbnail to every live stream , you should do this from server side with ffmpeg.
