### ISSUE TITLE
Stream key

### ISSUE THREAD

**Issue by varumora-everywoah** [begeekmyfriend/yasea#309]
Hi, I'm trying to use YASEA to stream to a RTMP server made by another enterprise and they gave me an URL to stream to but also a Stream Key. Is there any way to set that key in code? (ther's no other authentification needed)

**Comment by begeekmyfriend** [comment]
Try to change the format of RTMP URL as `rtmp://host:port/app/stream?SomeKey=12345`. Communicate with the vendor.

**Comment by tmartins91** [comment]
Try `rtmp://host:port/app/your_stream_key`.
It works for me.

**Comment by varumora-everywoah** [comment]
@tmartins91 my URL is 'rtmp://host:port/app/stream' and then I have the 'key'. You're saying I should try 'rtmp://host:port/app/key' and forget about the 'stream' parameter?

**Comment by tmartins91** [comment]
Yes, try without the stream parameter.

**Comment by varumora-everywoah** [comment]
not working :/
