### ISSUE TITLE
调试程序报错了

### ISSUE THREAD

**Issue by 1309954466** [begeekmyfriend/yasea#312]
C:\Talk\yasea-master\library\src\main\java\net\ossrs\yasea\SrsCameraView.java
错误:(201, 80) 错误: 找不到符号
符号:   变量 N
位置: 类 VERSION_CODES
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: C:\PJ\Talk\yasea-master\library\src\main\java\com\coremedia\iso\PropertyBoxParserImpl.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
2 个错误
:library:compileReleaseJavaWithJavac FAILED
错误:Execution failed for task ':library:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by begeekmyfriend** [comment]
怪我咯？

**Comment by notedit** [comment]
就怪你

**Comment by begeekmyfriend** [comment]
请确认使用Android Studio

**Comment by 1309954466** [comment]
其实是targetSdkVersion 24的问题，我先的一个是23.谢谢啊。
