### ISSUE TITLE
problem in publishing video

### ISSUE THREAD

**Issue by mahmood4429** [begeekmyfriend/yasea#313]
sometimes its working fine but sometimes it's unable to publish video. it only shows toast "Network resume" and socket is closed. can you tell me what's the problem?

**Comment by mahmood4429** [comment]
its all going well...but problem remains same...
![screenshot from 2017-01-18 14-29-34](https://cloud.githubusercontent.com/assets/25079515/22058628/6aff512a-dd8b-11e6-81ca-eb1fe81d3e25.png)
  this log may help you.

**Comment by begeekmyfriend** [comment]
It was nothing but your unsteady network that made it.

**Comment by mahmood4429** [comment]
okay
