### ISSUE TITLE
ava.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/cn.droidlover.xdroidmvp.demo/files/instant-run/dex/slice-support-annotations-25.0.0_4a3da5e6a21abe9eb9673181bd04bbfeb0efb87d-classes.dex"

### ISSUE THREAD

**Issue by yzcheng90** [begeekmyfriend/yasea#315]
java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/cn.droidlover.xdroidmvp.demo/files/instant-run/dex/slice-support-annotations-25.0.0_4a3da5e6a21abe9eb9673181bd04bbfeb0efb87d-classes.dex", dex file "/data/data/cn.droidlover.xdroidmvp.demo/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/cn.droidlover.xdroidmvp.demo/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/cn.droidlover.xdroidmvp.demo/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/cn.droidlover.xdroidmvp.demo/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/cn.droidlover.xdroidmvp.demo/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/cn.droidlover.xdroidmvp.demo/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/cn.droidlover.xdroidmvp.demo/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/cn.droidlover.xdroidmvp.demo/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/cn.droidlover.xdroidmvp.demo/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/cn.droidlover.xdroidmvp.demo/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/cn.droidlover.xdroidmvp.demo/files/instant-run/dex/slice-rxlifecycle-1.0_312719db61004e01c00ed151ca12bd3fdb2265ba-classes.dex", dex file "/data/data/cn.droidlover.xdroidmvp.demo/files/instant-run/dex/slice-rxjava-1.2.1_aa891a92fd7005674dbfb16a988b401dae763c6b-classes.dex", dex file "/data/data/cn.droidlover.xdroidmvp.demo/files/instant-run/dex/slice-retrofit-2.1.0_02cdaa5f093e78b272a8b951b62057cb62740b8d-classes.dex", dex file "/data/data/cn.droidlover.xdroidmvp.demo/files/instant-run/dex/slice-okio-1.9.0_db0545b090bbd931e1cf6e43202e038727277a7d-classes.dex", dex file "/data/data/cn.droidlover.xdroidmvp.demo/files/instant-run/dex/slice-okhttp-3.4.2_ae3cdcc1e7c2a4a303ea293d52806fed01d405bf-classes.dex", dex file "/data/data/cn.droidlover.xdroidmvp.demo/files/instant-run/dex/slice-library-2.4.0_dd460f45d27a359687729c3c169358b1eda3100b-classes.dex", dex file "/data/data/cn.droidlover.xdroidmvp.demo/files/instant-run/dex/slice-jsr305-3.0.1_b629f06a974d8a52776eaf08b3d7e7de95a0263a-classes.dex", dex file "/data/data/cn.droidlover.xdroidmvp.demo/files/instant-run/dex/slice-json-lib-2.4_3ecbc313c4e2cf41fbe4c31b2fbe24d6005de670-classes.dex", dex file "/data/data/cn.droidlover.xdroidmvp.demo/files/instant-run/dex/slice-jpush-android-2.2.0_5edcd59ed183046a39576ec3970e89488cb21cc5-classes.dex", dex file "/data/data/cn.droidlover.xdroidmvp.demo/files/instant-run/dex/slice-io.reactivex-rxandroid-1.2.1_0ea83cce384ee48a8657047974adf863c080193c-classes.dex", dex file "/data/data/cn.droidlover.xdroidmvp.demo/files/instant-run/dex/slice-internal_impl-25.0.0_f94405d043c8406db7c0621c723b62b7eb3ea807-classes.dex", dex file "/data/data/cn.droidlover.xdroidmvp.demo/files/instant-run/dex/slice-internal_impl-25.0.0_f36b4f8059883dda30c167a6566a3a5082e44a1a-classes.dex", dex file "/data/data/cn.droidlover.xdroidmvp.demo/files/instant-run/dex/slice-internal_impl-25.0.0_3bdf3e5243e4f2e8cc6abb1ea10633c33529467f-classes.dex", dex file "/data/data/cn.droidlover.xdroidmvp.demo/files/instant-run/dex/slice-internal_impl-25.0.0_2baef248634ef5b2c775ef9e1e82a4ce92ef384a-classes.dex", dex file "/data/data/cn.droidlover.xdroidmvp.demo/files/instant-run/dex/slice-internal_impl-25.0.0_020a8640d7d98d9de18ed06a31b7a3415d0aa919-classes.dex", dex file "/data/data/cn.droidlover.xdroidmvp.demo/files/instant-run/dex/slice-gson-2.7_2e85dbf641c4a16c73925139bd4ff50ebb0450dd-classes.dex", dex file "/data/data/cn.droidlover.xdroidmvp.demo/files/instant-run/dex/slice-glide-3.7.0_1f3ddf859a86296da03fddcf50d19f29d652df81-classes.dex", dex file "/data/data/cn.droidlover.xdroidmvp.demo/files/instant-run/dex/slice-converter-gson-2.1.0_fc6d109c83c05cddded4b5ea732ed5dd7c938086-classes.dex", dex file "/data/data/cn.droidlover.xdroidmvp.demo/files/instant-run/dex/slice-co

这个问题是不是找不到SO  我已经是放到了jniLibs中  还有 libs 中也放过 还是报这个错 楼主知道什么问题吗

**Comment by begeekmyfriend** [comment]
Please upgrade to the latest version.

**Comment by yzcheng90** [comment]
谢谢，我已经找到问题了，是我项目中引用了高德地图的so，高徳地图他有arm64-v8a 的so 。 所以yasea的so会报找不到,我删除了arm64-v8a 这个文件夹 就可以了，楼主可以编译一个运行arm64-v8a 的so吗？

**Comment by begeekmyfriend** [comment]
`arm64-v8a` has been removed for some compatibility reasons. For instance, `arm64-v8a` has to be built with NDK platform above 18 level, yet it cannot be run on the devices whose platform is below 19. So I have to make decision to abandon that platform for the whole open project.

After all, you may build `arm64-v8a` by yourself from commit tree https://github.com/begeekmyfriend/yasea/tree/e38864abb117aeaa90d06b44458022e9600bfeed. Some scripts like [android_build_arm64_v8a.sh](https://github.com/begeekmyfriend/yasea/blob/e38864abb117aeaa90d06b44458022e9600bfeed/library/src/main/libenc/jni/libx264/android_build_arm64_v8a.sh) were provided there.
