### ISSUE TITLE
Camera gets freeze when orientation change

### ISSUE THREAD

**Issue by jamariya** [begeekmyfriend/yasea#317]
Hello, 

Using the latest code the camera preview get freeze when orientation change. I am checking with the Google nexus 5.

- I have seen that here some code that handling the orientation change:

@Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        mPublisher.stopEncode();
        mPublisher.stopRecord();
        btnRecord.setText("record");
        mPublisher.setScreenOrientation(newConfig.orientation);
        if (btnPublish.getText().toString().contentEquals("stop")) {
            mPublisher.startEncode();
        }
    }

Can you please help, what cause this issue?

Thanks in advance.

**Comment by begeekmyfriend** [comment]
Fixed https://github.com/begeekmyfriend/yasea/commit/3e0874b08014d9fb371845dd8a08107d104fa374
