### ISSUE TITLE
Connect with another device

### ISSUE THREAD

**Issue by JayasenaMS** [begeekmyfriend/yasea#318]
how can i use this app as a streaming camera and connect with another android device to view streaming video.

**Comment by begeekmyfriend** [comment]
That is P2P, you need WebRTC.

**Comment by JayasenaMS** [comment]
Thanx for the quick reply..
But I need to use android media player as a video payer. 
How can I use YASEA as that kind of situation.

**Comment by begeekmyfriend** [comment]
[ExoPlayer](https://github.com/google/ExoPlayer) or [ijkPlayer](https://github.com/Bilibili/ijkplayer).

**Comment by JayasenaMS** [comment]
Thanx.. I'll try it

**Comment by JayasenaMS** [comment]
Hey... #begeekmyfriend 
I want some few explanation..
Can YASEA will act as a RTMP server and wait for a client (vlc, ExoPlayer, ijkPlayer or what ever) to request a stream. if it possible how can i connect to the yasea to request stream.

Or it act only as a RTMP client, connect with Wowza or FFmpeg.

**Comment by begeekmyfriend** [comment]
It is possible and has been tried by someone. But soon be abandoned.

**Comment by begeekmyfriend** [comment]
If you want P2P, try WebRTC.
