### ISSUE TITLE
没画面的问题

### ISSUE THREAD

**Issue by tz-xiaomage** [begeekmyfriend/yasea#32]
操作步骤：
启动推流--->按home键回到桌面-->回去
画面黑屏，可是依旧有在推流，而且也有声音

**Comment by begeekmyfriend** [comment]
Fixed https://github.com/begeekmyfriend/yasea/commit/9607b4f34d1e8710b89949bb7da4f835abc64352

**Comment by tz-xiaomage** [comment]
我根据你标记的进行修改，发现依旧是会没画面，下载你最新的master也一样是会这种情况
