### ISSUE TITLE
Video Stream freezing but audio still works when switch camera

### ISSUE THREAD

**Issue by arrivaldwis** [begeekmyfriend/yasea#321]
Video freezing when switch the camera to back and vice versa, but the audio still works

**Comment by begeekmyfriend** [comment]
Switch the phone.

**Comment by arrivaldwis** [comment]
Still freezing in others phone

**Comment by begeekmyfriend** [comment]
Did you clone the latest version?

**Comment by arrivaldwis** [comment]
Yes

**Comment by laqr** [comment]
I have the same problem on my devices. I use this code, but hope that problem will be fixed:
```
	public void switchCamera(){
		instance.publisher.switchCameraFace((instance.publisher.getCameraId() + 1) % Camera.getNumberOfCameras());
		instance.stopPublish();
		instance.startPublish(instance.RTMPAddr);
	}
```

**Comment by begeekmyfriend** [comment]
@laqr That is not my code. See [switchCameraFace](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsPublisher.java#L212).

**Comment by laqr** [comment]
@begeekmyfriend It is wrapper for your code. I just restart stream after switching camera.

**Comment by begeekmyfriend** [comment]
Then you made it in wrong way.

**Comment by begeekmyfriend** [comment]
@laqr You made it in wrong way. It is the camera not the streaming that should be restarted in switching camera.

**Comment by laqr** [comment]
@begeekmyfriend Well, I mean that after plain call to switchCameraFace stream continues without video (only audio). Code that I posted above fixes such behavior.

**Comment by begeekmyfriend** [comment]
@laqr I am sorry for that. But would you please try [yasea v2.3](https://github.com/begeekmyfriend/yasea-apk) to see whether the issue would appear? It does not happen on my device.

**Comment by laqr** [comment]
@begeekmyfriend sorry for late answer. yasea v2.3 switches camera perfectly, but fails when switch screen orientation(from portrait to landscape). I have Meizu m3 note and I can not launch v2.3 in landscape mode, because it fails immediately, don't know why.

**Comment by begeekmyfriend** [comment]
Well, for the latest version, would you please check whether the [mCameraView.startCamera](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsPublisher.java#L221) returns OK or not

**Comment by begeekmyfriend** [comment]
Try this commit https://github.com/begeekmyfriend/yasea/commit/2cfb8336ab2624e44c654e05f766a0f4dd2326c0

**Comment by laqr** [comment]
@begeekmyfriend I try it, works fine on meizu m3 note. But i tested it on Sony Xperia X with SDK 24, and here it works only with hard encoder. When I use soft encoder phone displays normal picture, but when I try to play stream using ffplay, ffplay logs in console many times string like this 
`[h264 @ 0x7fe2e30e6e00] concealing 3015 DC, 3015 AC, 3015 MV errors in P frame `
 and display something strange. I think this is due to 64bit processor on this phone. Thank you.

**Comment by begeekmyfriend** [comment]
@laqr See https://github.com/begeekmyfriend/yasea/issues/315#issuecomment-273695543
