### ISSUE TITLE
Torch Light 

### ISSUE THREAD

**Issue by PangMing** [begeekmyfriend/yasea#322]
`private void turnOnFlash() {

           Camera.Parameters p = cam.getParameters();
            p = cam.getParameters();
            p.setFlashMode(Camera.Parameters.FLASH_MODE_TORCH);
            cam.setParameters(p);
            cam.startPreview();
    }`
If I want to add this Flashlight method where should I put. I want add a Button to turn on Flashlight while streaming.

**Comment by begeekmyfriend** [comment]
I have added [that](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/AndroidManifest.xml#L8) for you.
