### ISSUE TITLE
Q: when should I start the encoder ? 

### ISSUE THREAD

**Issue by oantajames** [begeekmyfriend/yasea#323]
Hi! 
I modified the RtmpConnection class so it supports wowza authentication and currently I am connecting to the end point successfully and can stream audio.
On the video part it I am curently struggling to understand what happens in order to make it work...
In order to connect to wowza, the connection will fail 2 times and only the third time the connection will be successfull.
From what I saw, you start the encoder in here : 
```java
public void startPublish(String rtmpUrl) {
    if (mFlvMuxer != null) {
        mFlvMuxer.start(rtmpUrl);
        mFlvMuxer.setVideoResolution(mEncoder.getOutputWidth(), mEncoder.getOutputHeight());
        startEncode();
    }
}
``` 
The problem is that the `SrsFlvMuxer` actually starts the connection to the server here : 
```java
public void start(final String rtmpUrl) {
    worker = new Thread(new Runnable() {
        @Override
        public void run() {
              if (!connect(rtmpUrl)) {
                    return;
                }
```

And here :
```java
public void onGetYuvFrame(byte[] data) {
        // Check video frame cache number to judge the networking situation.
        // Just cache GOP / FPS seconds data according to latency.
        AtomicInteger videoFrameCacheNumber = flvMuxer.getVideoFrameCacheNumber();
            if (videoFrameCacheNumber != null && videoFrameCacheNumber.get() < VGOP) {
                long pts = System.nanoTime() / 1000 - mPresentTimeUs;
                if (useSoftEncoder) {
                    if (mOrientation == Configuration.ORIENTATION_PORTRAIT) {
                        swPortraitYuvFrame(data, pts);
                    } else {
                        swLandscapeYuvFrame(data, pts);
                    }
                } else {
                    byte[] processedData = mOrientation == Configuration.ORIENTATION_PORTRAIT ?
                            hwPortraitYuvFrame(data) : hwLandscapeYuvFrame(data);
                    if (processedData != null) {
                        onProcessedYuvFrame(processedData, pts);
                    } else {
                        Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(),
                                new IllegalArgumentException("libyuv failure"));
                    }
                }

                if (networkWeakTriggered) {
                    networkWeakTriggered = false;
                    mHandler.onNetworkResume("Network resume");
                }
            } else if (videoFrameCacheNumber != null) {
                mHandler.onNetworkWeak("Network weak");
                networkWeakTriggered = true;
            }
}
```

According to the `videoFrameCacheNumber` you detect if there is a weak network.

But with my current logic, if I start the encoder and the connection fails 2 times and only the third time the connection is established the network weak will be triggered.

So I thought that the encoder should start only when the connection is made with the endpoint.
So in the publisher I am receiving when the connection is made and only then start the encoder.

```java
public void isConnected(boolean isConnected) {
    //Start the encoder only if the connection is successfully established
    if (isConnected) {
        this.isConnected = true;
        startEncode();
    } else {
        this.isConnected = false;
        Log.e(TAG, "Connection could not be established!");
    }
}
```
But doing so I get a very laggy video, and very big video packets...

Any hint when to start the encoder with this pattern ? 
Thanks in advance! 

P.s. Also I'm thinking that maybe decoupling the connection from the muxer maybe will be a good idea. What do you think?

**Comment by begeekmyfriend** [comment]
Well try this commit https://github.com/begeekmyfriend/yasea/commit/da863658e36a8fe399ee7deff9e91900b97bf486. I put camera open method after connection and encoder enabling.

I do not understand why it had to fail twice on each connection to `Wowza`. The RTMP connection packets do nothing with AV packets.
