### ISSUE TITLE
Low FPS and incorrect ratio

### ISSUE THREAD

**Issue by ngochuu90** [begeekmyfriend/yasea#326]
Hi @begeekmyfriend 

Your library is amazing. But I encountered a number of problems:

- FPS very low in My Phone (Xiaomi Redmi Note 2) `I/Yasea: Output Fps: 10.184596`
- Camera incorrect ratio
![device-2017-02-09-102321](https://cloud.githubusercontent.com/assets/9895294/22768050/0365d358-eeb2-11e6-8463-944e3c6b0e26.png)

**Comment by begeekmyfriend** [comment]
- Redmi Note 2 sucks for camera.
- Generally speaking, the camera sampling resolution does not match the screen's unless you change the size of view.
