### ISSUE TITLE
前攝像頭影像反轉問題

### ISSUE THREAD

**Issue by bingdow** [begeekmyfriend/yasea#327]
直播時若使用前攝像頭，輸出影像和預覽屏幕上一樣。
然而一般手機相機在拍照或錄影時，若使用前攝像頭則輸出影像會做水平翻轉處理？

**Comment by begeekmyfriend** [comment]
Switch the `flip` parameter of [methods](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L500-L502) in `SrsEncoder.java`.

**Comment by bingdow** [comment]
感謝！試了一下成功了！
