### ISSUE TITLE
A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.

### ISSUE THREAD

**Issue by lipeng365** [begeekmyfriend/yasea#328]
I run into this problem ：
LOG：A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.    
 in  Galaxy C9 Pro  and HUAWEI Mate 9，they  both are  Android 6+ OS。

**Comment by begeekmyfriend** [comment]
I think it is safe to ignore this https://github.com/intercom/intercom-android/issues/224

**Comment by DeadlySOHAM** [comment]
https://github.com/intercom/intercom-android/issues/224 (Not found)
