### ISSUE TITLE
我想实现rtsp推流，以降低延时，有什么好建议吗？

### ISSUE THREAD

**Issue by anytimehh** [begeekmyfriend/yasea#329]
如题

**Comment by begeekmyfriend** [comment]
I am afraid RTSP does nothing better in latency than RTMP does which is the universal adopted solution in live streaming industry.

The suggestion about latency has been given in https://github.com/begeekmyfriend/yasea/issues/325

**Comment by anytimehh** [comment]
thank you very much for your help
