### ISSUE TITLE
我测试4K分辨率，结果播放器花屏，但画面运动一下又正常，不动就花屏。

### ISSUE THREAD

**Issue by anytimehh** [begeekmyfriend/yasea#331]
请问这是什么原因呢？

**Comment by begeekmyfriend** [comment]
你的推流比特率是多少？

**Comment by anytimehh** [comment]
我提高比特率到30M也一样，测试是在局域网进行的，同一个路由器，网速应该没问题。

**Comment by begeekmyfriend** [comment]
你跑手机？

**Comment by anytimehh** [comment]
手机，刚才测试结果是，码率越大，花屏越严重，码率在20M左右就花屏，8-10M左右都正常。
保存到手机再观看也正常。

**Comment by anytimehh** [comment]
我在同一个5GWIFI路由器下测试，网速应该没问题的。

**Comment by begeekmyfriend** [comment]
说实话，我以为你是别的设备啥的，手机跑4K是否不太现实了，毕竟采样才480p。数字电视的信号和带宽得有怎样的指标才可能达到4K的高清效果，你可以提高采样分辨率，但尚未见过手机上像你这样的需求……

**Comment by anytimehh** [comment]
我用华为mate9，4K视频已经非常清晰了，反应速度也很快，1080p是完全没用压力，4K也比较轻松，想试试做视频会议看行不行。

**Comment by anytimehh** [comment]
还有，我把帧率改为60，但srsplayer观看好像还是30的。我看手机时支持60的。

**Comment by anytimehh** [comment]
我还测试了h265，但rtmp封装好像不对，可以调用海思的硬编码，但传不到服务器。

**Comment by begeekmyfriend** [comment]
FLV只支持AVC(H.264)，用H.265恐怕解码不兼容。至于服务器上传没试过。另外从你描述看，编码还得看手机，mate9已是顶配，不代表一般手机。至于帧率，安卓自带降频设置，一般不超过30，跟苹果不同。

**Comment by anytimehh** [comment]
谢谢，我再试试。
