### ISSUE TITLE
非推播的狀態下預覽

### ISSUE THREAD

**Issue by bingdow** [begeekmyfriend/yasea#332]
我嘗試在「非推播」的狀態下進行預覽，代碼如下
`mPublisher.startCamera();
mPublisher.startEncode();`

發現如此一來除了 weak connection 會被觸發以外，程序也很常出現 Starting a blocking GC Alloc 的訊息然後就 crash 了，後著比較困擾，請問正確來說要怎麼做？

**Comment by begeekmyfriend** [comment]
- 更新到最新版本
- 只需要`mPublisher.startCamera`不需要`mPublisher.startEncode`
