### ISSUE TITLE
新版的預覽 Callback 如何生成圖像？

### ISSUE THREAD

**Issue by bingdow** [begeekmyfriend/yasea#333]
在舊版裡可以透過 yuvImage 在 preview callback 中生成預覽圖像，然而新版 preview 是 rgba frame 我的代碼就失效了，請問如何在 onGetRgbaFrame 中生成 bitmap?

**Comment by begeekmyfriend** [comment]
新版使用GLES的渲染，默认格式就是RGBA；https://github.com/begeekmyfriend/yasea/tree/non-gpuimage分支保留了旧版yuv格式
