### ISSUE TITLE
apk stop

### ISSUE THREAD

**Issue by sovereign000** [begeekmyfriend/yasea#335]
安装了2.4，运行后提示“停止运行”！

**Comment by begeekmyfriend** [comment]
Click [Download apk](https://git.oschina.net/begeekmyfriend/yasea)

**Comment by begeekmyfriend** [comment]
Sorry, what about other version and what is the model of your phone?

**Comment by sovereign000** [comment]
android4.4.4
手机版本ch1-CL10 
华为

**Comment by begeekmyfriend** [comment]
Is there any exception like #334 ?

**Comment by sovereign000** [comment]
直接安装的apk文件，没有进行编译。看不到什么异常

**Comment by begeekmyfriend** [comment]
我在[yasea-apk](https://github.com/begeekmyfriend/yasea-apk)里提供了v2.4.3，用最新Android Studio编译的，你再试试看

**Comment by sovereign000** [comment]
好的

**Comment by begeekmyfriend** [comment]
如果还是不行恐怕可能是 #334 里的机型适配问题
