### ISSUE TITLE
旋转屏幕问题解决

### ISSUE THREAD

**Issue by anytimehh** [begeekmyfriend/yasea#337]
在华为mate9上测试OK。
在SrsCameraView.java 文件中修改函数：

    public void setPreviewOrientation(int orientation) {
        mPreviewOrientation = orientation;
        Camera.CameraInfo info = new Camera.CameraInfo();
        Camera.getCameraInfo(mCamId, info);

        int rotation = ((WindowManager)(getContext().getApplicationContext().getSystemService(Context.WINDOW_SERVICE))).getDefaultDisplay().getRotation();
        int degrees = 0;
        switch (rotation) {
            case Surface.ROTATION_0: degrees = 0; break;
            case Surface.ROTATION_90: degrees = 90; break;
            case Surface.ROTATION_180: degrees = 180; break;
            case Surface.ROTATION_270: degrees = 270; break;
        }
        if (info.facing == Camera.CameraInfo.CAMERA_FACING_BACK) {
            mPreviewRotation = (info.orientation - degrees + 360) % 360;

        } else if (info.facing == Camera.CameraInfo.CAMERA_FACING_FRONT) {
            mPreviewRotation = (info.orientation + degrees) % 360;
            mPreviewRotation = (360 - mPreviewRotation) % 360;
        }
    }

**Comment by begeekmyfriend** [comment]
感谢您的代码。但请将手机倒转180度后在恢复过来，图像仍是倒置的

**Comment by anytimehh** [comment]
嗯，这个问题我也发现了，只要90度旋转是没问题的，转慢点就ok，比之前好多了。

**Comment by begeekmyfriend** [comment]
等我有空再想想办法

**Comment by begeekmyfriend** [comment]
Fixed https://github.com/begeekmyfriend/yasea/commit/5e039d6539e04879a09cf58d6227fefc513d628c
