### ISSUE TITLE
推流到斗鱼，App Crash

### ISSUE THREAD

**Issue by longzhao** [begeekmyfriend/yasea#339]
/AndroidRuntime(30813): FATAL EXCEPTION: Thread-2062
E/AndroidRuntime(30813): Process: net.ossrs.yasea.demo, PID: 30813
E/AndroidRuntime(30813): java.lang.NullPointerException
E/AndroidRuntime(30813): 	at com.github.faucamp.simplertmp.amf.AmfString.writeTo(AmfString.java:60)
E/AndroidRuntime(30813): 	at com.github.faucamp.simplertmp.packets.VariableBodyRtmpPacket.writeVariableData(VariableBodyRtmpPacket.java:71)
E/AndroidRuntime(30813): 	at com.github.faucamp.simplertmp.packets.Command.writeBody(Command.java:74)
E/AndroidRuntime(30813): 	at com.github.faucamp.simplertmp.packets.RtmpPacket.writeTo(RtmpPacket.java:38)
E/AndroidRuntime(30813): 	at com.github.faucamp.simplertmp.io.RtmpConnection.sendRtmpPacket(RtmpConnection.java:486)
E/AndroidRuntime(30813): 	at com.github.faucamp.simplertmp.io.RtmpConnection.createStream(RtmpConnection.java:223)
E/AndroidRuntime(30813): 	at com.github.faucamp.simplertmp.io.RtmpConnection.publish(RtmpConnection.java:204)
E/AndroidRuntime(30813): 	at com.github.faucamp.simplertmp.DefaultRtmpPublisher.publish(DefaultRtmpPublisher.java:27)
E/AndroidRuntime(30813): 	at net.ossrs.yasea.SrsFlvMuxer.connect(SrsFlvMuxer.java:128)
E/AndroidRuntime(30813): 	at net.ossrs.yasea.SrsFlvMuxer.access$000(SrsFlvMuxer.java:46)
E/AndroidRuntime(30813): 	at net.ossrs.yasea.SrsFlvMuxer$1.run(SrsFlvMuxer.java:161)
E/AndroidRuntime(30813): 	at java.lang.Thread.run(Thread.java:841)

推流到斗鱼平台遇到Crash,推流地址是rtmp://send1a.douyu.com/live.
大神能不能写篇WIKI讲解下整个推流的流程，代码里没有什么注释，有时候理解起来真的还是比较困难的，万分感谢！

**Comment by begeekmyfriend** [comment]
你漏了stream，rtmp格式为
> rtmp://host[:1935]/app/stream

**Comment by longzhao** [comment]
@begeekmyfriend 我在斗鱼平台申请一个直播，斗鱼平台有一个获取推流地址，平台为我分配地址为rtmp://send1a.douyu.com/live  目前只支持rtmp://host[:1935]/app/stream 这样的地址吗？谢谢。

**Comment by begeekmyfriend** [comment]
`stream`应该可以替换为任意ascii字符，不试试怎么知道呢？

**Comment by longzhao** [comment]
@begeekmyfriend 我替换了地址 rtmp://send1a.douyu.com/live/livestream 依旧不行，这时候会提示NetWork weak。

**Comment by begeekmyfriend** [comment]
那你要问斗鱼了，通常`stream`后面还会加`?userId=123&token=456`之类，不然谁都能推

**Comment by longzhao** [comment]
@begeekmyfriend 好的，谢谢，大神有没有个人的博客之类的啊，学习这些代码有时候还是难以下嘴，再次感谢！

**Comment by begeekmyfriend** [comment]
源码解析没有，一般了解FLV和RTMP的规格大致上就可以，量不大。

**Comment by longzhao** [comment]
@begeekmyfriend 刚看了下地址后面应该有直播码，我并没有加上，不好意思，祝工作顺利，身体健康。
