### ISSUE TITLE
addTrack function in SrsFlvMuxer

### ISSUE THREAD

**Issue by gouravd** [begeekmyfriend/yasea#34]
if (format.getString(MediaFormat.KEY_MIME) == MediaFormat.MIMETYPE_VIDEO_AVC) {

should that be 

if (format.getString(MediaFormat.KEY_MIME).equalsTo(MediaFormat.MIMETYPE_VIDEO_AVC)) {

**Comment by begeekmyfriend** [comment]
Fixed https://github.com/begeekmyfriend/yasea/commit/2042e33305d1601338c4a363cfb7a2a4e6565da6
