### ISSUE TITLE
Stream liveview image broken using ijkplayer sdk

### ISSUE THREAD

**Issue by pizegg** [begeekmyfriend/yasea#341]
Hello !

@begeekmyfriend 
I am using your project to test '**MTK-6580** based' tablet for streaming.
It worked very well for recording in sdcard and display in local liveview.
But when I tried to push rtmp streaming to nginx, and used ijkplayer to play on another phone.
No matter how I tuned the resolution of source, I got very bad liveview on my phone (it was phone independent)

I can clear hear audio on ijkplayer but always can't see clear video.
The attached picture shows the broken image of ijkclient.
![image uploaded from ios-1](https://cloud.githubusercontent.com/assets/15872210/23063323/e49bd03c-f544-11e6-8fdb-2583ff285e37.jpg)

I also tried several other android devices for yasea, all of them worked very well.
Is there any limitation for MTK-6580, or can you give me some hint to tracing the problem.

Thanks.

**Comment by begeekmyfriend** [comment]
Try to uncomment this [line](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L102) and this [line](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L289).

**Comment by pizegg** [comment]
I tried, it didn't throw any error.

$ adb shell getprop ro.mediatek.platform
=> MT6580
So I think it might not be resolution issue?

I push the streaming to "rtmp://ossrs.net/hzf/6dslx", would you please help check what is the problem of the streaming.

Thanks.

**Comment by begeekmyfriend** [comment]
The sad thing is I have no such device at hand.

**Comment by begeekmyfriend** [comment]
It occurs to me that the colour format might be different between Android phone and tablet since the display of images are abnormal. In the master branch of yasea I have converted data source from RGBA to NV12 and I420 and then sent into the encoder. I guess that there might be other colour format for tablet encoder input.
