### ISSUE TITLE
RTMPS

### ISSUE THREAD

**Issue by webdeutschland** [begeekmyfriend/yasea#345]
Does this library support RTMPS ?

**Comment by begeekmyfriend** [comment]
No such plan at present. Modification to RTMP module can achieve it.

**Comment by webdeutschland** [comment]
@begeekmyfriend can you please consider it as i need it in my project. I will be thankful to you :-)

**Comment by begeekmyfriend** [comment]
But I have no such environment and spare resources and time to build it.

**Comment by webdeutschland** [comment]
I have RTMPS Server, if you want to send stream on that server i can
provide you URL.
