### ISSUE TITLE
Aspect Ratio wrong?

### ISSUE THREAD

**Issue by imtrobin** [begeekmyfriend/yasea#347]
Hi, did you notice the aspect ratio in portrait mode? For e.g when I hold a square item, in the broadcast camera, I see the item is no longer square.

Also, I'm connected to a broadcast rtmp wowza stream, when I change orientation to landscape/portrait, the stream will stop. I will need to restart

**Comment by begeekmyfriend** [comment]
You can change the camera preview resolution through `mPublisher.setPreviewResolution`. 

The current preview resolution is 480p, but note 720p might be tough for beauty filter with FPS drop.

As for the second question, did you sync the latest version?

**Comment by imtrobin** [comment]
Hi, it is not the resolution, it is the aspect ratio. A square item is stretched when captured. Do you need to send an picture?

Yes, I used 2.4.3

**Comment by begeekmyfriend** [comment]
I mean it is the resolution ratio that did not match the view size. You need to change it.

**Comment by begeekmyfriend** [comment]
I have changed the ratio of preview resolution as 16:9 https://github.com/begeekmyfriend/yasea/commit/1c528bf09f181bb888ed47965a47176483385330
