### ISSUE TITLE
opr9s 和华为mate2硬编码都花屏幕

### ISSUE THREAD

**Issue by kongdemingwang** [begeekmyfriend/yasea#349]

**Comment by begeekmyfriend** [comment]
mate2什么年代。。。估计[color format](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L500-L501)不匹配吧

**Comment by kongdemingwang** [comment]
可是录像文件都是不花的，直播就用ffplayer播放，硬编码全是花的，软编码有的手机不花屏

**Comment by kongdemingwang** [comment]
按理来说要是色彩空间不对，直播和录制都是花的才对

**Comment by begeekmyfriend** [comment]
那就奇了怪了，你用SRS服务器？

**Comment by kongdemingwang** [comment]
不是呀，网宿的服务器

**Comment by kongdemingwang** [comment]
谢谢您的回复，rtmp://pw.live.fangyantianxia.cn/fangyan/12345 测试服务器可以试一下

**Comment by begeekmyfriend** [comment]
试过了，我的手机好好的。硬编码全部花屏也太不可思议了，你把代码重新拉一下吧

**Comment by begeekmyfriend** [comment]
前不久fix了一下，再试试吧：https://github.com/begeekmyfriend/yasea/commit/ad45075ac17183ee379a726c941f806fdd159799
