### ISSUE TITLE
请问一下　怎么把ａｒｇｂ转为ｎｖ２１

### ISSUE THREAD

**Issue by aoyj** [begeekmyfriend/yasea#350]

**Comment by begeekmyfriend** [comment]
GLES输出是RGBA，颜色布局你可以在`libenc.cc`里面改，参见libyuv目录头文件`video_common.h`里的`FourCC`枚举值

**Comment by aoyj** [comment]
<img width="700" alt="2017-02-23 9 04 38" src="https://cloud.githubusercontent.com/assets/13014638/23260223/bd7d601c-fa0b-11e6-86a1-e0a3c36ed08b.png">
是这样子改吗

**Comment by aoyj** [comment]
这样子改好像只有320*240的输出 是正确的
![image](https://cloud.githubusercontent.com/assets/13014638/23287332/baadfe2a-fa77-11e6-85ba-d6c5d1afa1a0.png)
这个地方 需要xiu'gai修改吗

**Comment by begeekmyfriend** [comment]
我没你那中环境，所以不好评论，应该是可以搞定的。

**Comment by aoyj** [comment]
就是说 只要修改 FourCC为NV21的枚举值  其它地方都不要改变吗

**Comment by notedit** [comment]
为什么要nv12呢   android 上对nv21 支持最好

**Comment by aoyj** [comment]
我需要的就是 转成nv21

**Comment by aoyj** [comment]
!
![image](https://cloud.githubusercontent.com/assets/13014638/23291878/604f32a4-fa96-11e6-8d06-5ad3b4055bd6.png)按照我的理解  nv12和nv21只是 uv的排列顺序不同  ，按照博主 说的  只要把FOURCC_NV12改为FOURCC_NV21应该就可以了。
![Uploading image.png…]() 在设置  图片预览大小 和输出大小 就只能都设置为320*240 我这边才能解析正确

**Comment by notedit** [comment]
理论上是只改FOURCC_NV12就可以   你可以检查其他的地方有没有设置对

**Comment by begeekmyfriend** [comment]
安卓编码器可能不支持，只是猜想，当初选择NV12也是试出来的
