### ISSUE TITLE
HLS分发下半部分绿屏

### ISSUE THREAD

**Issue by anytimehh** [begeekmyfriend/yasea#351]
我用华为P9推流，使用SRS做RTMP和HLS分发，RTMP正常，HLS在android下观看正常，在苹果手机或者macbook air用safari下观看HLS就出现下半边屏幕绿屏现象。式过降低分辨率、横竖屏切换、前后摄像头切换都一样。
但使用华为mate9就都正常。

**Comment by anytimehh** [comment]
试过软编码和硬编码都一样。

**Comment by begeekmyfriend** [comment]
那要问SRS了

**Comment by begeekmyfriend** [comment]
我是说直接用yasea定位有点困难

**Comment by anytimehh** [comment]
我觉得不是SRS的问题，用android观看HLS正常，RTMP观看也正常。应该也不是编码问题，软、硬编码都一样，我感觉是yasea的RTMP推流的问题。

**Comment by begeekmyfriend** [comment]
RTMP推流跟苹果播放端有关系吗？只有从服务端着手

**Comment by anytimehh** [comment]
用SRS的SEA就不会绿屏，是不是flvmuxer的问题？

**Comment by begeekmyfriend** [comment]
我没有苹果，不知有何工具可以在播放端调试看看那些字段错误？

**Comment by begeekmyfriend** [comment]
前不久fix了一下，再试试吧：https://github.com/begeekmyfriend/yasea/commit/ad45075ac17183ee379a726c941f806fdd159799

**Comment by begeekmyfriend** [comment]
#454 关键是关闭`multi-slice`，如果华为P9硬编码默认打开，我也没办法了
