### ISSUE TITLE
如何降低Video bitrate和Audio bitrate的值?

### ISSUE THREAD

**Issue by cdcdec** [begeekmyfriend/yasea#354]
问题:在两个不同的设备上,Video bitrate,Audio bitrate的值相差很大,而且值较大的那个设备上推出的视频不能播放,怎样把这个(Video bitrate,Audio bitrate)值降低啊？
log:
(1)值大,不能播放
Output Fps=Output Fps: 30.534351
Video bitrate>0=Video bitrate: 510.707379 kbps
Audio bitrate: %f kbps>0=Audio bitrate: 1631.733333 kbps
Audio bitrate: %f kbps>0=Audio bitrate: 1813.037037 kbps
Audio bitrate: %f kbps>0=Audio bitrate: 1932.315789 kbps
Audio bitrate: %f kbps>0=Audio bitrate: 2011.726027 kbps
(2)值小,可以播放
Output Fps=Output Fps: 9.708738
Video bitrate>0=Video bitrate: 179.016181 kbps
Audio bitrate: %f kbps>0=Audio bitrate: 130.132861 kbps
Audio bitrate: %f kbps>0=Audio bitrate: 132.908597 kbps
Audio bitrate: %f kbps>0=Audio bitrate: 138.086629 kbps
Audio bitrate: %f kbps>0=Audio bitrate: 131.587444 kbps

**Comment by begeekmyfriend** [comment]
`SrsEncoder.java`

**Comment by cdcdec** [comment]
为什么mPublisher.setPreviewResolution(720, 1280);和mPublisher.getPreviewHeight()的值不一致？

**Comment by cdcdec** [comment]
在两个不同的设备上,Video bitrate,Audio bitrate的值相差很大,设备的那些方面会影响这两个值啊？

**Comment by cdcdec** [comment]
值降低了一些,推出的视频还是不能播放？？？

**Comment by begeekmyfriend** [comment]
我不太明白为啥会出现这种情况，把设备报上来

**Comment by cdcdec** [comment]
Changhong/长虹 100Q3LZP,Android版本5.1.1,内核版本:3.10.79

**Comment by cdcdec** [comment]
使用ffmpeg播放时会出现下面的错误提示:
[live_flv @ 0147d500] Could not find codec parameters for stream 0 (Video: none,
none): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options

但是我不知道在代码的什么地方可以设置'analyzeduration' and 'probesize'?

**Comment by begeekmyfriend** [comment]
没用（见）过这种国产机……

**Comment by cdcdec** [comment]
不是手机,是电视。Changhong/长虹 100Q3LZP 100吋超短焦全高清智能激光影院电视。

使用ffmpeg播放时会出现下面的错误提示:
[live_flv @ 0147d500] Could not find codec parameters for stream 0 (Video: none,
none): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options

但是我不知道在代码的什么地方可以设置'analyzeduration' and 'probesize'?

**Comment by begeekmyfriend** [comment]
这我就不知道了，估计长虹定制了安卓系统

**Comment by cdcdec** [comment]
哦,谢谢!
