### ISSUE TITLE
rtmp

### ISSUE THREAD

**Issue by surabhi1694** [begeekmyfriend/yasea#355]
hey i'm new at this, tell me if your code work with any rtmp server ? 
i'm having rtmp nginx server and my local url
and also tell me when i start to stream video do i have to change any thing on your code to send it to server 
please help .....

**Comment by begeekmyfriend** [comment]
Did you run it?

**Comment by surabhi1694** [comment]
yes i run it what i meant is i'm using nginx  rtmp server so for the connection between app and server do i have to change something other then url ?

**Comment by begeekmyfriend** [comment]
Absolutely. Input your server IP and go on.

**Comment by surabhi1694** [comment]
oh i know that ..haha..  i was not sure about whether to make other changes or not so... thanks.....
