### ISSUE TITLE
rtmp推流与http推流有什么优势？

### ISSUE THREAD

**Issue by anytimehh** [begeekmyfriend/yasea#356]
感觉好像rtmp更复杂。

**Comment by begeekmyfriend** [comment]
- 延迟低
- CDN标配
- http-flv不是CDN标配

**Comment by anytimehh** [comment]
感觉推流的话http延时也很低，应该差不多，而且http穿透性更好。

**Comment by anytimehh** [comment]
目前延时主要产生在播放器端，HLS延时很大，没法降低，rtmp延时比较小，在播放端rtmp延时比较有优势，但支持的终端又比HLS差。android下有好的rtmp播放器吗？

**Comment by begeekmyfriend** [comment]
目前各CDN厂商都是rtmp推流，http-flv播放。不为什么，所以没有必要考虑http推流和rtmp播放了。开源播放器可以考虑[ijkplayer](https://github.com/Bilibili/ijkplayer)
