### ISSUE TITLE
Inputstream closed in the handshake

### ISSUE THREAD

**Issue by Abbo44** [begeekmyfriend/yasea#358]
Hi @begeekmyfriend ,

I have an Issue with your application. When I'm using it with a Wowza server, during the handshake, I have this exception : 

```
D/RtmpConnection: connect(): socket connection established, doing handhake...
D/Handshake: writeC0
D/Handshake: writeC1
D/Handshake: writeC1(): Calculating digest offset
D/Handshake: writeC1(): (real value of) digestOffset: 257
D/Handshake: writeC1(): recalculated digestOffset: 1033
D/Handshake: writeC1(): digestOffsetBytes: 000002FF
D/Handshake: partBeforeDigest(): size: 1033
D/Handshake: writeC1(): Writing timestamp and Flash Player version
D/Handshake: partAfterDigest(): size: 471
D/Handshake: copying digest offset bytes in partBeforeDigest
D/Handshake: writeC1(): Calculating digest
D/Handshake: writeC1(): writing C1 packet
D/Handshake: readS0
W/System.err: java.io.IOException: InputStream closed
W/System.err:     at com.github.faucamp.simplertmp.packets.Handshake.readS0(Handshake.java:52)
W/System.err:     at com.github.faucamp.simplertmp.io.RtmpConnection.handshake(RtmpConnection.java:94)
W/System.err:     at com.github.faucamp.simplertmp.io.RtmpConnection.connect(RtmpConnection.java:129)
W/System.err:     at com.github.faucamp.simplertmp.DefaultRtmpPublisher.connect(DefaultRtmpPublisher.java:22)
W/System.err:     at net.ossrs.yasea.SrsFlvMuxer.connect(SrsFlvMuxer.java:127)
W/System.err:     at net.ossrs.yasea.SrsFlvMuxer.access$000(SrsFlvMuxer.java:46)
W/System.err:     at net.ossrs.yasea.SrsFlvMuxer$1.run(SrsFlvMuxer.java:161)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
I/SrsEncoder: stop aencoder
```

Have you an idea why the handshake doesn't work ? Is it a proxy or a firewall ?

Regards,

Abbo

**Comment by begeekmyfriend** [comment]
The reason cannot be detected in the session layer. Use tools like `Wireshark` for analyse. What yasea can do is just reconnect.

**Comment by Abbo44** [comment]
Because I'm using RTMPS

**Comment by begeekmyfriend** [comment]
Yasea did not implement RTMPS and I have no plan for it.

**Comment by begeekmyfriend** [comment]
[Crypto.java](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/com/github/faucamp/simplertmp/Crypto.java) is in this project but I do not use it yet.

**Comment by Abbo44** [comment]
Ok I will try to use SSL next time

**Comment by lomoya90** [comment]
@begeekmyfriend I have the same question, after connecting YouTube RTMP server. The server does not respond to Handshake. Why?

**Comment by begeekmyfriend** [comment]
@lomoya90 I suggest that you can install [SRS 2.0 release](https://github.com/ossrs/srs) on your Linux machine as a local host. The FLV streaming mode startup is as follows:
> cd /usr/local/srs
> sudo ./objs/srs -c conf/push.flv.conf

Then you can set the RTMP URL as `rtmp://ipaddr[:1935]/app/stream`. The `app` and `stream` can be set as you like.

**Comment by lomoya90** [comment]
@begeekmyfriend Thank you very much, but I need push stream to YouTube RTMP server.

**Comment by begeekmyfriend** [comment]
@lomoya90 What you need to know about is authentication. Many people told me different failure of connection were finally due to the same root cause.

**Comment by Abbo44** [comment]
Yes me it was because of an SSL certificate to have RTMPS. I needed to store this certificate on my device

Le 21 juin 2017 09:01, Leo Ma <notifications@github.com> a écrit :

@lomoya90<https://github.com/lomoya90> What you need to know about is authentication. Many people told me different failure of connection were finally due to the same root cause.

**Comment by lomoya90** [comment]
@Abbo44 But the YouTube is RTMP, no  S. Sorry, I could not understand why

**Comment by begeekmyfriend** [comment]
The authentication is usually shown as
> rtmp://host[:port]/app/stream?userId=begeekmyfriend&token=abcdefg

The `userId` and the `token` need to be applied for to Youtube.

**Comment by lomoya90** [comment]
@begeekmyfriend  Thank you very much! The previous problems were caused by ourInternet. Now it works, but I do not know whether the server receives the video stream.
