### ISSUE TITLE
yasea由竖屏转为横屏后，播放端花屏

### ISSUE THREAD

**Issue by lisnstatic** [begeekmyfriend/yasea#36]
yasea由竖屏转为横屏，播放器端仍然是竖屏而且花屏，退出重进后可以正常显示横屏。播放器用的是ijkplayer。srs的web在线播放不会出现花屏。但是客户端播放器不论是ijkplayer还是vlc都是花屏。

**Comment by begeekmyfriend** [comment]
Please comment out [onMetaData](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/rtmp/io/RtmpConnection.java#L518) and see the effect.

**Comment by begeekmyfriend** [comment]
测试了VLC，跟版本有关系，下一个最新的吧

**Comment by lisnstatic** [comment]
我用的是ijkplayer，那应该跟播放器有关吧，我的vlc确实不花屏
