### ISSUE TITLE
Compile Problem

### ISSUE THREAD

**Issue by azzahrah** [begeekmyfriend/yasea#368]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':library:transformNativeLibsWithStripDebugSymbolForRelease'.
> A problem occurred starting process 'command 'D:\Dev\Android\sdk\ndk-bundle\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-strip''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by begeekmyfriend** [comment]
The default NDK level for Yasea so files build is `android-19` due to compatibility. So if you use different level (mostly higher than 19) you'd better rebuild the whole so files including `libx264.a`, `libyuv.so` and `libenc.so`. Just modify the build scripts provided in `libenc` directory.

**Comment by azzahrah** [comment]
Thank you problem solve, but audio and video not syncronized

**Comment by begeekmyfriend** [comment]
You may compare the [PTS](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L324) between H.264 and AAC out of the AV encoder.

Or compare the [PTS](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L371) between RGBA and PCM raw data before sent into the encoders.

If the difference of PTS value are too big then you need to adjust your parameter of the encoders. If both of them are normal then there might be issues at the server or the player.

**Comment by begeekmyfriend** [comment]
Before you start to debug on PTS, I suggest using FFplay to watch the result.

**Comment by azzahrah** [comment]
I have try, result like this:

ffplay -probezie 32 rtmp://192.168.0.100/live/test    audio only 2 second, video not display
ffplay rtmp://192.168.0.100/live/test    audio/video more than 7 second  (syncronized)
using plashplayer audio 2 second, video 5 second (not syncronized)

**Comment by begeekmyfriend** [comment]
I am afraid that it is the issue of your server. Try [SRS-2.0 release](https://github.com/ossrs/srs) by contrast.
