### ISSUE TITLE
Can you use TextureView instead of GLSurfaceView ?

### ISSUE THREAD

**Issue by zondaOf2012** [begeekmyfriend/yasea#371]
Now, SrsCameraView is derive from GLSurfaceView

**Comment by begeekmyfriend** [comment]
Of course. But it will be difficult to use GLES shader to filter the pictures as `GLSurfaceView` does. If you want magic filters you have to write EGL thread by yourself in `TextureView` mode.

**Comment by zondaOf2012** [comment]
@begeekmyfriend Thank you !
