### ISSUE TITLE
How I can stream video from uvc usb camera?

### ISSUE THREAD

**Issue by bently93** [begeekmyfriend/yasea#373]

**Comment by begeekmyfriend** [comment]
As long as you can get the object reference of the external device. I am afraid it is hard to make it on SDK level

**Comment by bently93** [comment]
I get a frame byte buffer from uvc usb camera in pixel format PIXEL_FORMAT_RGB565. How i can stream video?

**Comment by begeekmyfriend** [comment]
Well, first you need to pass the raw frame to the `SrsEncoder` by `onGetRgbaFrame` callback in which the native `libyuv` will convert the color format into H.264. You should rebuild `libenc.so` by changing [SRC_COLOR_FMT](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/libenc/jni/libenc.cc#L49). Note that the camera device should be exclusive that you cannot open another in the process.

**Comment by bently93** [comment]
Thanks. I'll try

**Comment by ManojMMWWIndia** [comment]
any luck on this? I am trying to achieve same. Please help me on this
