### ISSUE TITLE
preview的比例似乎不对？

### ISSUE THREAD

**Issue by fengqi-wang** [begeekmyfriend/yasea#375]

**Comment by begeekmyfriend** [comment]
目前采样分辨率480p并全屏显示，屏幕宽高比例要比采样分辨率窄，解决方案有二：
- 改变采样分辨率，使其比例尽可能接近屏幕
- 改变View显示区，使其比例尽可能接近采样分辨率

**Comment by begeekmyfriend** [comment]
我把采样分辨率改成16:9了https://github.com/begeekmyfriend/yasea/commit/1c528bf09f181bb888ed47965a47176483385330
