### ISSUE TITLE
录像功能必须依赖于推流？

### ISSUE THREAD

**Issue by mabiao6166** [begeekmyfriend/yasea#377]
此项目在需要录像的时候，需开启推流功能。
想知道怎么单独录像。

**Comment by begeekmyfriend** [comment]
Just remove [FlvMuxer](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L331)

**Comment by mabiao6166** [comment]
但是也想使用推流功能，希望推流功能和录像功能无关联。

**Comment by begeekmyfriend** [comment]
还不简单，你做成两个接口啊，一个按钮控制一个

**Comment by mabiao6166** [comment]
是publisher.record()方法么，但是我用了之后，录制视频时录制大致5-7秒就断掉了，录制出来的文件大小是正确的，视频播放的时候只有7秒有数据，也很卡。是我的视频参数有问题么？frameInterval=36,frameRate=36,codeRate=130 * 1024 * 8。是这些数据不合适么？

**Comment by begeekmyfriend** [comment]
那是你自己的问题了，原本并不复杂，推流是`FlvMuxer`，录制是`Mp4Muxer`，两者本来就是解耦的

**Comment by mabiao6166** [comment]
您能制作一个推流和录像不干扰的demo么？
