### ISSUE TITLE
Broadcast Image

### ISSUE THREAD

**Issue by aarajput** [begeekmyfriend/yasea#378]
Hi,
I want to broadcast image.
Can you please help?
Thanks,

**Comment by begeekmyfriend** [comment]
[mEncoder.onGetRGBAFrame](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsPublisher.java#L43) is the entry of your bitmaps.

**Comment by aarajput** [comment]
So, I have to convert bitmap to byte and and pass it to mEncoder.onGetRgbaFrame ?

**Comment by begeekmyfriend** [comment]
Of course. By the way, you also need to change the input format in [libenc.cc](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/libenc/jni/libenc.cc#L49) to match your image.

**Comment by aarajput** [comment]
Hi,
Thanks for your help. I am able to send images.
But the issue is, when i am sending image, its squeezing.
I am trying to change setOutputResolution of mPublisher object, but its crashing inside C code.
Can you please help?
Thanks,

**Comment by begeekmyfriend** [comment]
I do not know what you have changed in `libenc.cc`. It does nothing with image publishing on output resolution. In `libenc.cc` video stream is images. So what you need to do is just change the [input color format](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/libenc/jni/libenc.cc#L49) to adapt the coming images with the output resolution remains unchanged.
