### ISSUE TITLE
publishing link change to 1 param

### ISSUE THREAD

**Issue by jake22599** [begeekmyfriend/yasea#385]
Hi, is there a way to change the url link input to accept 1 parameters instead of min 2.
rtmp://server:port/app/stream
rtmp://server:port/stream

I notice that the RtmpConnection is using a regex to check if the url string is vaild. It also stores the application string and stream string separately. Both variables are required respectively. Thus, is it possible to change to take in a 1 parameter url string instead.

**Comment by begeekmyfriend** [comment]
NOT compatible with all RTMP servers.
