### ISSUE TITLE
java.lang.IllegalArgumentException: annexb not match

### ISSUE THREAD

**Issue by jutikorn** [begeekmyfriend/yasea#388]
```
03-31 16:27:55.631 5740-5740/com.livepop.android.dev I/SrsFlvMuxer: 000-015: 0x0 0x0 0x0 0x1 0x41 0xe4 0x1 0x17 0xab 0x73 0x20 0x47 0xe6 0xed 0xf5 0x6f 
03-31 16:27:55.671 5740-5740/com.livepop.android.dev W/System.err: java.lang.IllegalArgumentException: annexb not match for 2515B, pos=25
03-31 16:27:55.681 5740-5740/com.livepop.android.dev W/System.err:     at net.ossrs.yasea.SrsFlvMuxer$SrsRawH264Stream.annexb_demux(SrsFlvMuxer.java:729)
03-31 16:27:55.681 5740-5740/com.livepop.android.dev W/System.err:     at net.ossrs.yasea.SrsFlvMuxer$SrsFlv.writeVideoSample(SrsFlvMuxer.java:942)
03-31 16:27:55.681 5740-5740/com.livepop.android.dev W/System.err:     at net.ossrs.yasea.SrsFlvMuxer.writeSampleData(SrsFlvMuxer.java:234)
03-31 16:27:55.681 5740-5740/com.livepop.android.dev W/System.err:     at net.ossrs.yasea.SrsEncoder.onEncodedAnnexbFrame(SrsEncoder.java:322)
03-31 16:27:55.681 5740-5740/com.livepop.android.dev W/System.err:     at net.ossrs.yasea.SrsEncoder.onProcessedYuvFrame(SrsEncoder.java:301)
03-31 16:27:55.681 5740-5740/com.livepop.android.dev W/System.err:     at net.ossrs.yasea.SrsEncoder.onGetYuvFrame(SrsEncoder.java:373)
03-31 16:27:55.681 5740-5740/com.livepop.android.dev W/System.err:     at net.ossrs.yasea.SrsPublisher$1.onGetYuvFrame(SrsPublisher.java:54)
03-31 16:27:55.681 5740-5740/com.livepop.android.dev W/System.err:     at net.ossrs.yasea.SrsCameraView.onPreviewFrame(SrsCameraView.java:278)
```

Happens on Samsung Galaxy Grand2 (SM-G7102 and Qualcomm Snapdragon 400 chipset)  with nginx server.

**Comment by begeekmyfriend** [comment]
It is wired. There are always something happen on Samsung devices...

**Comment by begeekmyfriend** [comment]
It is a f***ing pain in the ass https://github.com/begeekmyfriend/yasea/commit/81e1d9f29197ec35cd7fc25df95d3754013aa380.

**Comment by jutikorn** [comment]
@begeekmyfriend 
I forget to let you know thqat I modified something on the SrsEncoder.java to fix to rotation problem here:
https://github.com/jutikorn/yasea/blob/cam-rotation/library/src/main/java/net/ossrs/yasea/SrsCameraView.java#56
https://github.com/jutikorn/yasea/blob/cam-rotation/library/src/main/java/net/ossrs/yasea/SrsCameraView.java#133
https://github.com/jutikorn/yasea/blob/cam-rotation/library/src/main/java/net/ossrs/yasea/SrsCameraView.java#134
https://github.com/jutikorn/yasea/blob/cam-rotation/library/src/main/java/net/ossrs/yasea/SrsCameraView.java#225
https://github.com/jutikorn/yasea/blob/cam-rotation/library/src/main/java/net/ossrs/yasea/SrsCameraView.java#265

https://github.com/jutikorn/yasea/blob/cam-rotation/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L368
https://github.com/jutikorn/yasea/blob/cam-rotation/library/src/main/java/net/ossrs/yasea/SrsPublisher.java#42

The camera rotation has been fixed if it is running in specific `screenOrientation` but I think that it changed the rotate value that pass in native method (NV21SoftEncode) so it cause this problem.

Weird that it happens only some devices like Samsung Galaxy Grand2  but this works fine on Nexus6, Galaxy J7, HTC Desire816, Note4, Note5

**Comment by jutikorn** [comment]
@begeekmyfriend I just found that it happens only on the first frame.  So I fixed this problem by only comment these out:
```
 //mHandler.notifyRtmpIllegalArgumentException(new IllegalArgumentException(
//String.format("annexb not match for %dB, pos=%d", bi.size, bb.position())));
```

**Comment by begeekmyfriend** [comment]
But it is a dirty fix...

**Comment by jutikorn** [comment]
@begeekmyfriend yep it is. Need to make it done just for now.
