### ISSUE TITLE
hi ，作者，请教目前推流器是否有网络断开恢复重连的机制

### ISSUE THREAD

**Issue by g123x** [begeekmyfriend/yasea#39]

**Comment by g123x** [comment]
这个issue 其实是 这样的，我的android手机连接了我们自己的srs-server并通信一段时间以后，我把wifi关闭 再开启，程序检测到网络通的时候执行flvMuxer.stop();，但是这个时候抛出了异常如下，
java.net.SocketException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
at java.net.PlainSocketImpl.shutdownInput(PlainSocketImpl.java:369)
at java.net.Socket.shutdownInput(Socket.java:610)
此时srs服务器其实并没有关闭socket，请问您遇到过吗？

**Comment by begeekmyfriend** [comment]
是这样的，由于yasea无法同时满足所有二次开发者的需求，所以默认对所有异常采取关闭策略，但并不是说二次开发不能基于原有代码作修改，你可以自定义捕获异常的同时做重连接。

**Comment by g123x** [comment]
ok thanks
