### ISSUE TITLE
Possible bug in SrsEncoder

### ISSUE THREAD

**Issue by laqr** [begeekmyfriend/yasea#391]
Hi. 
I found in your code [this](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L100) line. Maybe this
`if (! useSoftEncoder && vOutWidth % 32 != 0 || vOutHeight % 32 != 0)`
 should be like this
`if (! useSoftEncoder && (vOutWidth % 32 != 0 || vOutHeight % 32 != 0))`
Am I wrong?

**Comment by begeekmyfriend** [comment]
Oh yes. Thank you for your reminder!https://github.com/begeekmyfriend/yasea/commit/6d92307149ddb0210b9cd406e0364e1c75b7feb2

**Comment by laqr** [comment]
[Again.](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L100) May be it is a feature? )

**Comment by begeekmyfriend** [comment]
Damn it! Fix again.
