### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by snapshahab** [begeekmyfriend/yasea#394]
when publishing it says "failed to connect to ossrs.net/SOME_ADDRESS/PORT after 3000ms:isConnected failed :ECONNREFUSED(connection refused).

**Comment by begeekmyfriend** [comment]
Did you have the permission?

**Comment by snapshahab** [comment]
yes i did

**Comment by begeekmyfriend** [comment]
Your connection were rejected. I am afraid that there should be some stream key #309

**Comment by snapshahab** [comment]
but im using server generated by the app.

**Comment by begeekmyfriend** [comment]
I see. The `ossrs.net` has been crashed for some time.

**Comment by snapshahab** [comment]
okay thank you for clearing that

**Comment by snapshahab** [comment]
is there any alternative to ossrs.net?

**Comment by begeekmyfriend** [comment]
[srs](https://github.com/ossrs/srs)

**Comment by snapshahab** [comment]
okay thank you for clearing that
