### ISSUE TITLE
Fail to create aencoder

### ISSUE THREAD

**Issue by laqr** [begeekmyfriend/yasea#395]
Hello!

I have an error on remote device. The only error info I know is 

` java.io.IOException Failed to allocate component instance`

It appears only on Sony XPERIA L C2105 with android 4.2.2 and no root at [this](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L127) line.
My code is equals to yours.

May be you have some ideas about how to fix it?

**Comment by begeekmyfriend** [comment]
Custom ROM is hard to be compatible with.
