### ISSUE TITLE
how to integrate my project

### ISSUE THREAD

**Issue by sarawutl** [begeekmyfriend/yasea#396]
having error java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/mypackage-1/lib/x86/libenc.so: has text relocations

**Comment by begeekmyfriend** [comment]
The NDK level may not be compatible with yours. Consider to rebuild the native code on your own.

**Comment by sarawutl** [comment]
I found error when sdk-23 but working with sdk-22

**Comment by imamhambali0221** [comment]
have you add permission camera for sdk-23 ? @sarawutl
