### ISSUE TITLE
疑惑:library/src/libenc目录

### ISSUE THREAD

**Issue by pdyw** [begeekmyfriend/yasea#400]
求大神解答一下: 我现在在androidstudio上开发，library/src/libenc是否要编译，它的作用是什么; 如要编译，但是在library/src/jniLibs,有一个libyuv.so会有命名冲突。

**Comment by begeekmyfriend** [comment]
`libenc`作用：
- `libyuv` 对原始图像数据做旋转、翻转、缩放等处理；
- `libx264`软编码。

至于命名冲突，没遇到过这种问题
