### ISSUE TITLE
画面一直在抖

### ISSUE THREAD

**Issue by montotone** [begeekmyfriend/yasea#403]
界面一直在抖，和原生的Camera 效果有差距，有没有什么好的解决方法？

**Comment by begeekmyfriend** [comment]
你这是定制的ROM吧，native层的bug我没办法

**Comment by montotone** [comment]
用的三星glaxy s6和 小米 4c测，画面没有原生的相机好。有什么解决办法

**Comment by begeekmyfriend** [comment]
投诉……

**Comment by montotone** [comment]
大神，https://github.com/montotone/LiveCamera.git
看一下这个效果。画面质量会稍微好一些

**Comment by begeekmyfriend** [comment]
没有你那样的手机，我也对比不出来呀
