### ISSUE TITLE
软件解码色彩红色变蓝色

### ISSUE THREAD

**Issue by 0406445** [begeekmyfriend/yasea#405]
使用小米5s软件解码，推送流，显示的色彩没问题，但是用定制的android一体机推送trmp流时，红色变成蓝色，本地录制的视频，颜色也是这么奇怪，但是预览的画面颜色没问题，请问这个与什么有关系？需要厂家定制吗，还是app本身可以修改

**Comment by 0406445** [comment]
视频录制问题
1.硬件编码，推送，颜色没有问题，但是保存本地的画面是花屏
2.软件编码，保存本地以及推送没有问题，但是颜色红变成蓝，蓝变成红

**Comment by begeekmyfriend** [comment]
定制的ROM色彩空间不一样，需要自己摸索，或者咨询相关厂商，本项目不负责解决此类问题

**Comment by 0406445** [comment]
谢谢，大概了解问题所在
