### ISSUE TITLE
native有錯誤?

### ISSUE THREAD

**Issue by oyfu** [begeekmyfriend/yasea#411]
作者你好，首先感謝作者的open source
想請教這個問題
我推流有成功，但是拉流卻沒畫面
原因是不是沒有native成功?
這是native 那部分顯示紅色跟警告http://imgur.com/a/WJYr7
我有裝ndk,我有看到你的jniLibs跟libenc/jni 底下的libs libx264 libyuv 我有去查ndk相關的建立方式，只是不知道怎麼修正，我該用什麼方法來修正這些?

**Comment by begeekmyfriend** [comment]
你用什么拉流的？服务器是什么？试试ffplay，一般来说不需要编译native就可以推流的

**Comment by oyfu** [comment]
rtmp拉流   服務器用facebook

**Comment by begeekmyfriend** [comment]
额，不负责解决翻墙问题……
你可以使用如下命令验证
> ffmpeg -re -i test.mp4 -vcodec libx264 -acodec libfaac -f flv rtmp://facebook.com/app/stream
