### ISSUE TITLE
当前Activity处于被覆盖状态或者后台不可见状态后，再次启动之后 黑屏 但是 音视频还在传输，怎么让画面 显示呢？

### ISSUE THREAD

**Issue by 18518756793** [begeekmyfriend/yasea#412]
当前Activity处于被覆盖状态或者后台不可见状态后，再次启动之后 黑屏 但是 音视频还在传输，怎么让画面 显示呢？

**Comment by begeekmyfriend** [comment]
不存在你说的问题呀，你的手机是什么？

**Comment by 18518756793** [comment]
用 pad 测试的 两种 pad 小窗口 去打开别的应用 ，在小窗打开这个 推流的界面 ，界面就黑屏。我在手机上侧是正常的。

**Comment by begeekmyfriend** [comment]
yasea不针对Pad，所以我也没法帮你解决
