### ISSUE TITLE
服务器端无法存流？

### ISSUE THREAD

**Issue by YinWeiLF** [begeekmyfriend/yasea#413]
很喜欢这个开源库，但是试了一下不能在服务器端存流，其它的一些可以，到底是哪的问题？我需要怎么修改才能在服务器端存流呢？

**Comment by begeekmyfriend** [comment]
一般RTMP有几个推流参数`live`, `record`, `append`，你可以试试[更改一下](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsFlvMuxer.java#L103)，但我不保证服务端是否支持，一般来说CDN转储不需要更改这个参数了
