### ISSUE TITLE
视频水平翻转的代码是在哪里？代码里注释不是很多。多谢了

### ISSUE THREAD

**Issue by Arroon** [begeekmyfriend/yasea#414]
视频水平翻转的代码是在哪里？代码里注释不是很多。多谢了

**Comment by begeekmyfriend** [comment]
[Here](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L498-L500) is the APIs.

**Comment by Arroon** [comment]
谢谢回复，我没有调用camera，从文件里读的h264流发送出去的，那几个native方面应该没有调用到。
直接调用SrsEncoder.onEncodedAnnexbFrame，写入h264数据。而播放端看到的是水平翻转的视频。

**Comment by Arroon** [comment]
不要意思，是我电脑的播放器调了水平翻转，太抱歉了。
