### ISSUE TITLE
手机摄像头转换问题

### ISSUE THREAD

**Issue by sunnymooni** [begeekmyfriend/yasea#416]
您好，在把手机强制设置为只有竖屏的情况下，我使遇到了个问题华为平板m3转换镜头为后置后，无论怎么旋转平板，影像都是一直倒的；华为honor8等多摄像头就是上下颠倒，但是通过旋转手机就可以实现了画面正面显示。我把摄像头默认设置为打开后面，但是一切换前后方向就又乱了。不知道代码中旋转角度为何用sdk去比较呢，
  if (orientation == Configuration.ORIENTATION_PORTRAIT) {
                mPreviewRotation = Build.VERSION.SDK_INT >= Build.VERSION_CODES.N ? 270 : 90;
            } else if (orientation == Configuration.ORIENTATION_LANDSCAPE) {
                mPreviewRotation = Build.VERSION.SDK_INT >= Build.VERSION_CODES.N ? 180 : 0;
            }

**Comment by begeekmyfriend** [comment]
代码已经更新了，不用去比较版本了

**Comment by sunnymooni** [comment]
哦，主要是不太明白是为甚么要比较

**Comment by begeekmyfriend** [comment]
我是说请你更新一下代码，之前的做法是无效的

**Comment by sunnymooni** [comment]
已经修改了，知道失效，只是不明白，为什么那样做比较，判断版本是因为api改变的原因么(￣▽￣)"

**Comment by begeekmyfriend** [comment]
只是找不到规律时的乱撞墙而已
