### ISSUE TITLE
如何直播图片+音频

### ISSUE THREAD

**Issue by GraphicSound** [begeekmyfriend/yasea#417]
我们不想用摄像头的数据，我们只想截取Android手机屏幕当中部分控件，所以我们不断地去截图这个控件，之后再和音频混编，推流，怎么做，望大神指导~

**Comment by begeekmyfriend** [comment]
你这是录屏吧？
https://github.com/yrom/ScreenRecorder
https://github.com/googlesamples/android-ScreenCapture
