### ISSUE TITLE
ZE552KL 无法运作与60FPS是否支持

### ISSUE THREAD

**Issue by Ladell-twitch** [begeekmyfriend/yasea#420]
感谢你编写了这个工具，可惜我的ZF3（ZE552KL ）安装2.5后执行不了，只好有机会用其他手机试试了
另外想因为还没成功运行，想请问是否支援60FPS直播，因为目前市面上有的都几乎是30FPS而已

**Comment by begeekmyfriend** [comment]
安卓手机自带降频功能，60fps谈何可能？
