### ISSUE TITLE
Is there any way to improve image quality ?

### ISSUE THREAD

**Issue by Doss12** [begeekmyfriend/yasea#422]

**Comment by begeekmyfriend** [comment]
- Use better camera device.
- Improve preview resolution.
- Shrink output resolution.
- Improve video bitrate.
- Reduce FPS.
- Reduce GOP.

**Comment by sabodh** [comment]
Hi could you please explain how we can achieve the followings in this code,

- Shrink output resolution.
- Improve video bitrate.
- Reduce FPS.
- Reduce GOP.
