### ISSUE TITLE
is that possible to change the stream output to black and white

### ISSUE THREAD

**Issue by PangMing** [begeekmyfriend/yasea#428]
I'm looking a way to make the video into black and white or grey. any ideas?

**Comment by begeekmyfriend** [comment]
It is [GLSL](https://github.com/begeekmyfriend/yasea/tree/master/library/src/main/res/raw) that can make it. But I have no idea about which one. So you have to find it yourself or even search on the Internet.

**Comment by begeekmyfriend** [comment]
Two ways:
- Use [GLSL](https://github.com/begeekmyfriend/yasea/tree/master/library/src/main/res/raw) to filter the raw picture. But I have no idea that which one should be. So I am afraid you have to find it yourself even search on the Internet.
- Modify the components of raw RGBA data from [getGLFboBuffer](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsCameraView.java#L127) method. But I think it is not as good as the first way.
