### ISSUE TITLE
Error:A problem occurred configuring project ':library'.

### ISSUE THREAD

**Issue by abhishekcharismatic** [begeekmyfriend/yasea#429]
Everytime I open this project, this error comes. Please fix it. After the CPP updates this issue is coming I guess. Before it was working like a charm.

**Comment by begeekmyfriend** [comment]
Did you clone it from scratch?
Would you please upgrade your Android Studio version?

**Comment by abhishekcharismatic** [comment]
I am using Android Studio 2.3.1.. I guess this is the latest version. I did clone it from the scratch..

**Comment by begeekmyfriend** [comment]
It seems you need to restart your IDEA and then it works. I will find it out as soon as possible...

**Comment by begeekmyfriend** [comment]
@penninghlhd It occurs after I merged your PR. The IDEA seems not build the project successfully on the first opening. Could you help have a look on this issue?

**Comment by penninghlhd** [comment]
Yes, but probably somewhere next week if that is ok with you.

**Comment by begeekmyfriend** [comment]
No problem. Thank you in advance!

**Comment by abhishekcharismatic** [comment]
When I changed my package name with mine. Then this error is coming. How to change the NDK build ??? Please help.. There was one issue regarding this but didn't got anything... 


Class "net/ossrs/yasea/SrsEncoder" not found
05-12 12:52:23.354 32258-32258/com.muvi.www.xmpe E/art: JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.ClassNotFoundException: Didn't find class "net.ossrs.yase

**Comment by begeekmyfriend** [comment]
On this [line](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/cpp/libenc/libenc.cc#L576)

**Comment by abhishekcharismatic** [comment]
E/libenc: Class "net/ossrs/yasea/SrsEncoder" not found
05-12 15:09:53.850 3499-3499/com.muvi.www.xmpe E/art: JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.ClassNotFoundException: Didn't find class "net.ossrs.yasea.SrsEncoder" on path: DexPathList[[zip file "/data/app/com.muvi.



Still getting this same error.... Please help

**Comment by begeekmyfriend** [comment]
Are you sure there is no spelling mistake?

**Comment by abhishekcharismatic** [comment]
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.muvi.www.xmpe-1/lib/arm/libenc.so" has no loadable segments


I did now this error is coming... Its very irritating..

**Comment by begeekmyfriend** [comment]
Calm down buddy. The latest version does not let you build the so files by hand. What you need to do is just downloading `ndk-bundle` through setting menu in Android Studio and run it.

**Comment by abhishekcharismatic** [comment]
I downloaded NDK Bundle but that also didnt worked.. I simply imported your library into my project and now it's working.. Actually .so file is creating issue. Well will look after this issue and share the solution with you after fixing it. Till then please fix CPP issue. Thank you..

**Comment by begeekmyfriend** [comment]
The so files are only under `armeabi-v7a` and `x86` with API 19. Please check whether they are compatible with your project.

**Comment by begeekmyfriend** [comment]
It seems to be OK now with AS upgraded.

**Comment by mastashake08** [comment]
This issue is happening again. Please fix!

**Comment by flusharcade** [comment]
I had the same issue, all you need to do is add the **ndk.dir** to the local.properties. Like this:

ndk.dir="path-to-ndk"

Hope this helps.

**Comment by rizwan321** [comment]
i am also getting A problem occurred configuring project ':library'. 
please suggest me the solution so i can work on it
i clone this library from scratch i already have latest android studio having latest NDK 
i did not change any thing.

**Comment by begeekmyfriend** [comment]
@rizwan321 My warning is "No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android"
Please try downloading [NDK r16b version](https://developer.android.com/ndk/downloads/?hl=zh-cn) and replace `C:\Users\leo.ma\AppData\Local\Android\Sdk\ndk-bundle` with it.

**Comment by aderinto05** [comment]
I got same issue "Error:A problem occurred configuring project ':library'." 
After I use this ndk as your suggestion from https://developer.android.com/ndk/downloads/?hl=zh-cn
I still got error this "Error:No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android"

Any suggestion @begeekmyfriend ?
