### ISSUE TITLE
rtmp推流失败

### ISSUE THREAD

**Issue by 0406445** [begeekmyfriend/yasea#430]
请问一定要先使用mPublisher.startPublish(CameraSerivceInfo.getRTMPURL());连接，再调用startEncode（）合成吗，我先调用startEncode，和startCamera，本地录制可以录制，再调用mPublisher.startPublish时，不能推流，服务器提示
onMetaData: 
 - framerate: 0
 - audiocodecid: 0
 - height: 240
 - videodatarate: 0
 - width: 320
 - profile: 
 - Server: NGINX RTMP (github.com/arut/nginx-rtmp-module)
 - level: 
 - displayHeight: 240
 - audiodatarate: 0
 - fps: 0
 - displayWidth: 320
 - duration: 0
 - videocodecid: 0
Aspect_num:1.3333333333333333 
_vid.width:360  _vid.height:270
NetStream event : NetStream.Buffer.Full
NetStream event : NetStream.Buffer.Full
NetStream event : NetStream.Buffer.Flush

**Comment by begeekmyfriend** [comment]
推流的第一帧必须是视频的关键帧，所以一般都是先连接，然后等编码器出第一帧
