### ISSUE TITLE
Android 6.0 不會送声音流

### ISSUE THREAD

**Issue by JSiLi** [begeekmyfriend/yasea#431]
你好

我下载了您的专案，想做一个直播的应用，并播到Youtube，但发现在 Android 7的手机上，完全正常没问题。但是，在Android 6的机子上，只会送影像流不会送声音流

我的环境是
Android Studio 2.3

手机 Sony X Performance (Android 7.0) --> 可正常使用
手机 Sony Z3 (Android 6.0.1) --> 有送影像流 没送声音流

请问这可能是什么原因?

**Comment by begeekmyfriend** [comment]
你看一下`AudioRecord`[采集](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsPublisher.java#L105)的返回值

**Comment by JSiLi** [comment]
刚刚追踪了一下 mPcmBuffer.length = 4096 , offsetInBytes = 0 , sizeInBytes = 4096

但是返回的 int size = 0

**Comment by begeekmyfriend** [comment]
很有可能你的设备录音采集坏了吧……

**Comment by lomoya90** [comment]
@JSiLi 你好，请问youtube的直播链接里面没有端口号，要怎么通过url format校验呢？
