### ISSUE TITLE
Camerapreview should only occupy Half screen??

### ISSUE THREAD

**Issue by abhishekcharismatic** [begeekmyfriend/yasea#432]
I want my surfaceview to occupy only half of the screen. How to set that?? When I did, my image get stretched vertically and horizontally...

**Comment by begeekmyfriend** [comment]
[activity_main.xml](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/res/layout/activity_main.xml#L8-L17)

**Comment by abhishekcharismatic** [comment]
Ok so now I have successful splited my surfaceview into half. But now the preview is stretched.. Vertically and horizontally... How to fix it again?? this stretching issue creating lots of tension.

**Comment by begeekmyfriend** [comment]
I am afraid you have to adjust your preview resolution to fit the size of view...

**Comment by abhishekcharismatic** [comment]
how to do that??????? Little bit hint?

**Comment by begeekmyfriend** [comment]
This [line](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/demo/MainActivity.java#L74).
