### ISSUE TITLE
Why there is no Downstreaming??

### ISSUE THREAD

**Issue by abhishekcharismatic** [begeekmyfriend/yasea#433]
Upstreaming and camera work is excellent. No doubt this is the best thing on Github when it comes to Live Streaming using RTMP. I have a little request. Please show downstreaming also in a small player on the. Suppose two people are talking live.. So both can see eachother at the same time.

**Comment by begeekmyfriend** [comment]
[ExoPlayer](https://github.com/google/ExoPlayer) or [ijkplayer](https://github.com/Bilibili/ijkplayer). Both of them are BIG projects!
