### ISSUE TITLE
Not able to play audio while streaming

### ISSUE THREAD

**Issue by avinash7074** [begeekmyfriend/yasea#436]
Hi,
Thanks for just a great library.
When i am streaming then audio is not playing it just showing the video.
Can you help me out where I am making mistake.

Thank you

**Comment by begeekmyfriend** [comment]
See your logcat. If there are RTMP audio packets then it is the issue in the server or player.

**Comment by begeekmyfriend** [comment]
Or you need to fetch the latest version.

**Comment by avinash7074** [comment]
Thanks for the help I have fetch the latest version and it works
