### ISSUE TITLE
Disable Preview?

### ISSUE THREAD

**Issue by ugiacoman** [begeekmyfriend/yasea#437]
Is there any way to disable preview?

**Comment by begeekmyfriend** [comment]
Do not call `startCamera`

**Comment by ugiacoman** [comment]
It seems that the preview it tightly coupled to all other methods. Even if I don't call startCamera, I can't set the encoder's orientation without changing the preview orientation.

**Comment by begeekmyfriend** [comment]
I see. Just comment out this [line](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/com/seu/magicfilter/base/gpuimage/GPUImageFilter.java#L277).
