### ISSUE TITLE
这个可以支持的硬编机型有哪些啊？

### ISSUE THREAD

**Issue by MrZhangYang** [begeekmyfriend/yasea#44]
硬编我这边测试了好几个机型，魅族的，努比亚的等一些，发现魅族推流，我拉到的流fps只有5fps左右，能说说它支持哪些机型吗？

**Comment by begeekmyfriend** [comment]
只能一个个试了，设备厂商的问题不是我能控制的

**Comment by begeekmyfriend** [comment]
现在有[软编码](https://github.com/begeekmyfriend/yasea/commit/035637d9f7d2a23fc65540c40d018fdec21a41a3)了，参数还在调试中
