### ISSUE TITLE
Down-streaming is extremely Slow..

### ISSUE THREAD

**Issue by abhishekcharismatic** [begeekmyfriend/yasea#440]
Whenever I click on Publish button.. It first show toast "Conntecting..." and then show "Netwrok Weak" and the Downstreaming is extreamly Slow. The time period between Upstream and Downstream is almost 1 min. Why it is??? And the Network Weak toast never gets disappear...

**Comment by begeekmyfriend** [comment]
It is the network issue.

**Comment by abhishekcharismatic** [comment]
I am using 4G network... Even if I am using Wifi I still face same problem....,

**Comment by abhishekcharismatic** [comment]
And there is one more issue... After clicking on publish... When my slow down streaming starts.. My camera stops working and it gets pause,...

**Comment by begeekmyfriend** [comment]
Did it happen on all of your devices?

**Comment by abhishekcharismatic** [comment]
Yes facing this problem in every device....

**Comment by begeekmyfriend** [comment]
I still doubt that it is your network issue. Did you clone the latest version?

**Comment by abhishekcharismatic** [comment]
Yes I have clone the latest version and still the downstreaming is very slow... and I am this error sometimes.. Attempt to invoke virtual method 'int com.github.faucamp.simplertmp.amf.AmfType.ordinal()' on a null object reference

**Comment by begeekmyfriend** [comment]
The format of RTMP url must be as follows:
> rtmp://host/app/stream

**Comment by abhishekcharismatic** [comment]
Attempt to invoke virtual method 'int com.github.faucamp.simplertmp.amf.AmfType.ordinal()' on a null object reference..

My app is crashing after clicking publish button

**Comment by abhishekcharismatic** [comment]
I am using your server only that you have mentioned in the above code.... But still the streaming is very slow..

**Comment by begeekmyfriend** [comment]
Did you mean [SRS](https://github.com/ossrs/srs)?

**Comment by abhishekcharismatic** [comment]
public void onClick(View v) {
                if (btnPublish.getText().toString().contentEquals("publish")) {
                    //rtmpUrl = efu.getText().toString();
                    SharedPreferences.Editor editor = sp.edit();
                    editor.putString("rtmpUrl", rtmpUrl);
                    editor.apply();

                    mPublisher.startPublish(rtmpUrl);
                    mPublisher.startCamera();


                } else if (btnPublish.getText().toString().contentEquals("stop")) {
                    mPublisher.stopPublish();
                    mPublisher.stopRecord();

                }
            }
        });


Here  I want to use image instead of getText and setText... how to do that??

**Comment by begeekmyfriend** [comment]
None of business of the SDK.
