### ISSUE TITLE
Device getting heat while broadcasting.

### ISSUE THREAD

**Issue by nikhilkilivayil** [begeekmyfriend/yasea#441]
Device getting heat while broadcasting.

**Comment by begeekmyfriend** [comment]
It is inevitable especially using magic filters.

**Comment by nikhilkilivayil** [comment]
I will try to remove magic filter then. I don't want magic filter effect.

**Comment by begeekmyfriend** [comment]
Then try this branch [non-gpuimage](https://github.com/begeekmyfriend/yasea/tree/non-gpuimage)
