### ISSUE TITLE
Can not live to RTMP sever

### ISSUE THREAD

**Issue by tranlongbkhn** [begeekmyfriend/yasea#442]
Hello, 
with my RTMP sever link : 
[rtmp://0_8lfju1v0.p.kpublish.kaltura.com:1935/kLive?t=da26c70f](url)

I cannot live streaming to this sever
The error is: this link is not properly format.
How can I fix this issue?
Because I have tested with other RTMP encoder app(https://play.google.com/store/apps/details?id=com.miv.rtmpcamera&hl=vi) it works fine, I can live streaming with this app

Thank you so much

**Comment by begeekmyfriend** [comment]
The URL format must be as follows:
> rtmp://host[:1935]/app/stream?xxx=xxx
The `stream` above might be defined by yourself.

**Comment by tranlongbkhn** [comment]
Due to my url is fixed, I can not change the url format link.
can I make exception in the source for above link ?

**Comment by begeekmyfriend** [comment]
You may remove this [condition](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L118-L122) but there would be still `NullPointException` later. So I am afraid that you have to do it on your own.

**Comment by tranlongbkhn** [comment]
Can this project live streaming to youtube ?

**Comment by begeekmyfriend** [comment]
It can stream to all RTMP server with authentication and permission.

**Comment by tranlongbkhn** [comment]
sorry for disturb you so much.
But can you guide me how to streaming to youtube in code

**Comment by begeekmyfriend** [comment]
Just a RTMP URL with **authentication**.

**Comment by lomoya90** [comment]
@begeekmyfriend There is no port in the RTMP URL of YouTube live streaming:rtmp://a.youtube.com/live2/[streamId]

**Comment by begeekmyfriend** [comment]
@lomoya90 The default port of RTMP is 1935 that can be omitted. Otherwise you have to specify the port in the URL explicitly.

**Comment by lomoya90** [comment]
@begeekmyfriend  OK, thank you very much, I will try it.

**Comment by lomoya90** [comment]
@begeekmyfriend Sorry, it does not run on some mobile phones.

**Comment by begeekmyfriend** [comment]
@lomoya90 What do you mean? Did the app not run normally or not connect the server? Try `FFmpeg` command line to testify it:
> ffmpeg -re -i test.mp4 -vcodec libx264 -acodec libfdk-aac -f flv rtmp://host[:port]/app/stream

**Comment by lomoya90** [comment]
@begeekmyfriend Sorry, I don't have a clear description.  The app could not run on my Nexus 5, Android 6.0.1.  It is blocked in the onCreate method.

**Comment by begeekmyfriend** [comment]
@lomoya90 What was the logcat? Did it have any error tips?

**Comment by lomoya90** [comment]
@begeekmyfriend  Sorry, it's ok now after I restart my Nexus 5. But what's the function of the package CPP in the library?

**Comment by begeekmyfriend** [comment]
@lomoya90 Under package CPP there are `libyuv` for image processing and `libx264` for soft encoding.

**Comment by lomoya90** [comment]
@begeekmyfriend  I tried to connect rtmp://a.rtmp.youtube.com:1935/ , but it throws SocketTimeoutEexception:
 **java.net.SocketTimeoutException: failed to connect to a.rtmp.youtube.com/8.7.198.45 (port 1935) after 10000ms**

**Comment by begeekmyfriend** [comment]
@lomoya90 Because you do not have the authentication which appearing as parameters behind the RTMP URL, please contact Youtube staff for inquiry or application.

**Comment by lomoya90** [comment]
@begeekmyfriend You mean, the FFMPEG command line also could not work, as follow:
`ffmpeg -re -i test.mp4 -vcodec libx264 -acodec libfdk-aac -f flv rtmp://host[:port]/app/stream`

**Comment by begeekmyfriend** [comment]
I am afraid you do not understand what is AUTHENTICATION.

**Comment by lomoya90** [comment]
@begeekmyfriend  `java.net.SocketTimeoutException: failed to connect to a.rtmp.youtube.com/8.7.198.45 (port 1935) after 10000ms` this error occurred `socket.connect(socketAddress, 10000);`, it is not the certification question that you said. It is ok when I use VPN. Sorry, I describe not clear

**Comment by begeekmyfriend** [comment]
Well, the connection was **refused** by Youtube. I suggest that you can stream to other RTMP servers. If successful, you would know what I mean about authentication.
