### ISSUE TITLE
Switch mirroring

### ISSUE THREAD

**Issue by xdeop** [begeekmyfriend/yasea#443]
Hi,
I would like to switch mirror on / off to the camera preview and the video sent to the rtmp server using the hardware encoder.
How could it be done?
I imagine that it should be done in the onDrawFrame of the SrsCameraView class and also apply it to the magicFilter... Am I correct? How could I apply a mirroring transformation matrix (scale -1,1) to the preview frames and the sent frames?

Thanks in advance.

**Comment by begeekmyfriend** [comment]
Just switch the [flip](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L616-L617) argument.

**Comment by xdeop** [comment]
Hi,
Ok, I'll give it a try!!

Thanks.

**Comment by xdeop** [comment]
Hi,
As I undestand, the flip arguments flips de sent video horizontally (mirror), but it doesn't flip de camera preview... How could I accomplish that?

Thanks.

**Comment by begeekmyfriend** [comment]
Then you need to learn something about OpenGL ES.

**Comment by xdeop** [comment]
I've accomplished it by adding the following code in SrsCameraView:

surfaceTexture.getTransformMatrix(mSurfaceMatrix);
+// mirror frames
+Matrix.scaleM(mSurfaceMatrix, 0, -1, 1, 1);
+Matrix.translateM(mSurfaceMatrix, 0, -1, 0, 0);

And then there's no need using the flip argument.
Thanks for your help.

**Comment by begeekmyfriend** [comment]
You are excellent!
