### ISSUE TITLE
rtmp推流播放端阻塞

### ISSUE THREAD

**Issue by xinghua** [begeekmyfriend/yasea#444]
您好，我在使用demo进行rtmp推流时，使用html5播放器flowplayer在网页中进行rtmp流播放，发现有如下问题：

1 如果使用hard encoder,  持续推流的情况下，如果刷新网页，播放器需要阻塞很长一段时间才能播放，显示“seems something is blocking flash from running”.
2 如果断流，重新推流，网页播放器中会立刻开始播放
3 如果使用soft encoder，不存在这样的情况，持续推流的情况下，频繁刷新网页播放器，仍然可以立刻开始播放

请问这可能是什么原因引起的呢，非常感谢

**Comment by begeekmyfriend** [comment]
如果硬编码出现这样的问题，很有可能是你的手机ROM定制原因。播放器迟迟不出画面，是因为找不到关键帧，而yasea的硬编码配置GOP（I帧间隔）是2秒，所以正常情况下是不会出现的，请换个手机试一试

**Comment by xinghua** [comment]
@begeekmyfriend 我是在模拟器中进行测试的，是不是这里的GOP设置是无效的？

**Comment by begeekmyfriend** [comment]
晕死，请用真机。。。

**Comment by xinghua** [comment]
@begeekmyfriend 想请教一下，如果在模拟器上运行的话，貌似不是用硬编码的，是不是mediacodec的很多设置都是无效的，非常感谢

**Comment by begeekmyfriend** [comment]
这个问题没有意义
