### ISSUE TITLE
关于rtmp协议解析播放的问题

### ISSUE THREAD

**Issue by ButterRhopa** [begeekmyfriend/yasea#445]
您好！

之前看到您在google exoplayer下提出的[PR](https://github.com/google/ExoPlayer/pull/2590)中提到过关于纯java代码解析rtmp协议视频的问题，我随后去到[这个库](https://github.com/begeekmyfriend/ExoPlayer/tree/dev-v2)中把rtmp解析相关的类拷贝出来放到了我自己app依赖的exoplayer库中。测试和上线使用后发现效果的确很好，但是，在使用了一段时间后发现其对于某些rtmp直播流的解析出现了问题，具体表现在画面严重卡顿上，基本是1-2秒才能播放一帧，而声音却没有任何问题。

不知您在开发过程中有没有遇到过类似的问题，还请解答一下，谢谢！

**Comment by begeekmyfriend** [comment]
这个部分应该由Google来维护吧，何况ExoPlayer已经比我提交PR时更新过，何不重新merge一下试试？

**Comment by ButterRhopa** [comment]
重新合并过，还是存在问题，毕竟关于rtmp的部分是使用的你写的那一部分，所以感觉和ExoPlayer更新问题不大......看起来只能使用ffmpeg了。

**Comment by begeekmyfriend** [comment]
FLV的解析部分是ExoPlayer的模块，如果遇上卡顿问题，除非是RTMP输送出现断续，一般来说都是FLV解析。你可以在`RtmpDataSource`的read接口加上打印，如果没有遇上传输，那只能定位到FLV及其后面的部分。

你也明白实际上RTMP模块就是基于yasea更改的，如果有问题的话，作为一个推流模块早就被很多人所诟病了

**Comment by ButterRhopa** [comment]
嗯......也就是说，rtmp协议的直播流是使用的FLV解析？(原谅我是关于视频播放的新手)

**Comment by begeekmyfriend** [comment]
这个自然啊

**Comment by ButterRhopa** [comment]
好的，我再研究一下。感谢解答！
