### ISSUE TITLE
Low fps rate streaming to Facebook

### ISSUE THREAD

**Issue by schimini** [begeekmyfriend/yasea#447]
Hi there, 

First of all congrats on the amazaing work. 
I'm developing an app that should stream from the tablet camera to a facebook rtmp server. 

Although i'm getting super low fps (like 1 or 2) and i have no clue what may be te cause to this problem.

Thanks in advance

**Comment by begeekmyfriend** [comment]
I am afraid the ROM of your tablet has been customized so that the `MediaCodec` library did not work effectively.

**Comment by schimini** [comment]
So how should i proceed? I haven't made any hardware/software modifications on the tablet. It is a Samsung Active Tab (android lollipop)

**Comment by begeekmyfriend** [comment]
Another Samsung... I suggest you getting an authentic Android device (even just Android phone i.e. Nexux, Pixel) for testing.

**Comment by zzugyl** [comment]
same performance in my android devices .
i try getSupportedPreviewFpsRange() ,and get range [5,30].
but preview and send rtmp fps only get 5~7 fps.
same way ,using OpenCamere can get 30fps.

**Comment by schimini** [comment]
@zzugyl How are you using OpenCamera ? Can you give me some kind of intel on that?

**Comment by zzugyl** [comment]
@schimini I try opencamera debug in my android device. not integrate into yasea. 
https://sourceforge.net/projects/opencamera

**Comment by schimini** [comment]
@zzugyl  ahhh ok i get it thanks. 

@begeekmyfriend  so there's no hope for Samsung devices?

**Comment by begeekmyfriend** [comment]
Samsung sucksfor me.

**Comment by schimini** [comment]
Ok i'll try another device and eventually tell you how it went. 
Thanks for the support

**Comment by begeekmyfriend** [comment]
@zzugyl Well I have tested your recommended project. It is the back camera opened for preview with high FPS. If you switch to the front camera, the FPS would drop as well.
