### ISSUE TITLE
Native libraries

### ISSUE THREAD

**Issue by ltpquang** [begeekmyfriend/yasea#448]
Hi there,

Thank you for this awesome library. I'm quite interesting in the native parts of the library, including `libenc`, `libx264`, and `libyuv`. May I know where are they come from, since I really wanna deep dive into the native encoding process?

**Comment by begeekmyfriend** [comment]
The native encoding is just soft encoding. The `libx264` and `libyuv` are third-part open source projects and in `libenc` it invokes the APIs of those libraries and combines them together.

**Comment by AliceDinh** [comment]
Where the libenc.cc file and libenc.so file come from?

**Comment by begeekmyfriend** [comment]
It would be built with `ndk-bundle`.

**Comment by AliceDinh** [comment]
But libenc.cc file, sir?

**Comment by begeekmyfriend** [comment]
@AliceDinh I wrote it for `libyuv` and `libx264` API calling.

**Comment by AliceDinh** [comment]
That's reason why I couldnot file any documentation related to it on the Internet. Thank you.

**Comment by AliceDinh** [comment]
What will be the original problem when I run the program (Yasea) and it raises the error: Fail to open x264 encoder!
I dig into the code and found the error comes from libenc.cc file. Please advise me how to fix this error sir.
x264_ctx.encoder = x264_encoder_open(&x264_ctx.params);
    if (x264_ctx.encoder == NULL) {
        LIBENC_LOGE("Fail to open x264 encoder!");
        return JNI_FALSE;
    }

**Comment by begeekmyfriend** [comment]
@AliceDinh Did you modify something from the original code?

**Comment by AliceDinh** [comment]
Nope sir

**Comment by begeekmyfriend** [comment]
Did you use the latest version?

**Comment by AliceDinh** [comment]
I am using version 2.3.1

**Comment by begeekmyfriend** [comment]
Or please upgrade your Android Studio to the latest version.

**Comment by AliceDinh** [comment]
You mean yasea version 2.6?

**Comment by begeekmyfriend** [comment]
Yep.

**Comment by AliceDinh** [comment]
Okie, I will do it now. Thanks for your patience

**Comment by AliceDinh** [comment]
Thanks sir, it works
