### ISSUE TITLE
推流时晃动马赛克非常严重

### ISSUE THREAD

**Issue by lisnstatic** [begeekmyfriend/yasea#45]
提高了码率，到1M了但是推流时马赛克还是比较严重，而且实际推流码率肯定不能是1M，所以作者有关注到这个问题吗？加了这个属性：
videoFormat.setInteger(MediaFormat.KEY_PROFILE,MediaCodecInfo.CodecProfileLevel.AVCProfileHigh10);
videoFormat.setInteger(MediaFormat.KEY_LEVEL, MediaCodecInfo.CodecProfileLevel.AVCLevel11 );
没管用

**Comment by begeekmyfriend** [comment]
对某些厂商而言，profile和level都是默认不可更改的，如果你真要试，还是谷歌亲儿子Nexus保险
