### ISSUE TITLE
Undeclared Identifier 

### ISSUE THREAD

**Issue by RazmigPapissian** [begeekmyfriend/yasea#451]
![screen shot 2017-06-14 at 12 01 25 pm](https://user-images.githubusercontent.com/18104322/27142543-52494e24-50f9-11e7-84a1-c797d2a9b588.png)

I am having an issue with running gradle, seems like these functions are undeclared. Help please! :

**Comment by begeekmyfriend** [comment]
You need to install Android NDK through Android Studio menu: File > settings > Appearance & Behavior > System settings > Android SDK > SDK tools > NDK.

**Comment by sarawutl** [comment]
[error](https://ufile.io/rytak)

**Comment by sarawutl** [comment]
http://imgur.com/a/53T9t

how to fix, help me please

**Comment by begeekmyfriend** [comment]
@sarawutl I do not use Mac OS but I guess there is some problems on program linking.

**Comment by begeekmyfriend** [comment]
@sarawutl Damn it. It happened to me just now after I upgraded the NDK to r15. NDK r14 is good for me.

**Comment by sarawutl** [comment]
how to downgrade

**Comment by pedroSG94** [comment]
Add #include <string.h> to libenc.cc
https://stackoverflow.com/questions/44495668/ndk-use-of-undeclared-identifier-memcpy

**Comment by begeekmyfriend** [comment]
Fixed https://github.com/begeekmyfriend/yasea/commit/1e5c7c167552276328275ea4da797720a0687be7. Thank you!
