### ISSUE TITLE
Can use this for viewer

### ISSUE THREAD

**Issue by sarawutl** [begeekmyfriend/yasea#452]
this only use for sender?

**Comment by begeekmyfriend** [comment]
Of course it can only if you remove `SrsEncoder.java`.

**Comment by sarawutl** [comment]
show me example please

**Comment by begeekmyfriend** [comment]
Just keep `SrsCameraView.java`.

**Comment by sarawutl** [comment]
<blockquote class="imgur-embed-pub" lang="en" data-id="a/37GDl"><a href="//imgur.com/37GDl"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

Impact other file, Please help

**Comment by begeekmyfriend** [comment]
Just comment out these code.

**Comment by sarawutl** [comment]
not working 😭

**Comment by begeekmyfriend** [comment]
What you need are these [APIs](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/demo/MainActivity.java#L70-L77). Just keep them in the project.
