### ISSUE TITLE
软编码录制的视频在Mac或者iPhone上面播放都是绿屏

### ISSUE THREAD

**Issue by tbruceyu** [begeekmyfriend/yasea#454]
如图：
<img width="410" alt="dingtalk20170620183920" src="https://user-images.githubusercontent.com/1342575/27329370-eddae882-55e7-11e7-9f4b-1d668a2f552f.png">
但是在Android或者ffmpeg播放出来没有这个问题。

**Comment by begeekmyfriend** [comment]
很遗憾这是个遗留问题一直没解决，最大的问题是我不是果粉。。。

**Comment by zenghuakun** [comment]
iphone, mac解码问题。 x264编码出一帧会有多个00 00 01 这样的nal，但是iphone,mac只能一次解码一个nal, 放入多个nal就会绿屏(已验证过)

**Comment by begeekmyfriend** [comment]
@zenghuakun 如果是真的，那真的感谢您提供参考！

**Comment by jtyang** [comment]
[我android改用mediamuxer来存mp4，在部分机器也会出现这样的绿屏情况，看到ijk那也有个类似的问题分析[#2124](https://github.com/Bilibili/ijkplayer/issues/2124)]

**Comment by zenghuakun** [comment]
问题已经确定了，确实是由于1帧由多个nal造成。原计划在x264编码完成后，手动拆分1帧中的nal为多帧，但是显示出来有问题。经过楼上反馈说用mediamuxer也有这个问题，怀疑是x264编码问题。 网上查找了一下x264的参数，调试很久最终锁定到b_sliced_threads 参数。 

b_sliced_threads 默认只true。 为true时，编码时有几个线程，1帧会生成几个NAL，false时只会生成1个NAL.

本人设置为false时，ios下播放没有绿屏。 设置为false时，是否对性能有影响还不确定。

**Comment by begeekmyfriend** [comment]
@zenghuakun @jtyang 多谢你们提供的线索好验证！我打算把项目的x264的`b_sliced_threads`关闭，由于直播`profile`是`baseline`，所以性能就先不考虑了

**Comment by begeekmyfriend** [comment]
Fixed https://github.com/begeekmyfriend/yasea/commit/88dd496f1a411cf52b1247b0bd87e59e7398a96b

**Comment by jtyang** [comment]
android正常播放ios绿屏这个问题其实硬编码也会，我开始测试 “软编码+mp4parser ”存的视频在ios必现绿屏，后来就改用“硬编码+mp4parser”保存视频，发现线上还有部分机型录的到ios会绿屏，再后来又改成“硬编码+android mediamuxer”存mp4，发现还是有机器录的会有问题。不知道是否有人对硬编码这块有啥好办法么？

另外还想和大家交流下的是，在已经有会绿屏的MP4视频文件的情况下，是否有工具或啥办法分析是哪里出的问题呢？

**Comment by jinyunfeng** [comment]
@jtyang mediacodec硬编码出现的这种问题有好的解决方案吗
