### ISSUE TITLE
请问我想拍照片需要如何操作？

### ISSUE THREAD

**Issue by asswc204** [begeekmyfriend/yasea#456]

**Comment by begeekmyfriend** [comment]
```java
    Camera.PictureCallback mPictureCallback = new Camera.PictureCallback() {
        @Override
        public void onPictureTaken(byte[] data, Camera camera) {
            FileOutputStream fos = null;
            String mFilePath = Environment.getExternalStorageDirectory().getPath() + File.separator + "tt001.png";
            //文件
            File tempFile = new File(mFilePath);
            try {
                //
                fos = new FileOutputStream(tempFile);
                fos.write(data);

            } catch (FileNotFoundException e) {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            } finally {
                //实现连续拍多张的效果
//                mCamera.startPreview();
                if (fos != null) {
                    try {
                        fos.close();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
            }

        }
    };
```

**Comment by asswc204** [comment]
这样保存的图片是原来的照片没有了滤镜效果，怎么样才能把带有滤镜效果的照片保存呢

**Comment by begeekmyfriend** [comment]
那你只有从显存读取的[RGBA数据](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsCameraView.java#L231)保存为bitmap

**Comment by asswc204** [comment]
好的我试试，感谢

**Comment by asswc204** [comment]
我获取RGBA拍照时的argb数据保存为bitmap的时候为什么颜色色调会改变了。
            bitmap = Bitmap.createBitmap(mPreviewWidth, mPreviewHeight, Bitmap.Config.ARGB_8888);
            bitmap.copyPixelsFromBuffer(ByteBuffer.wrap(mGLPreviewBuffer.array()));

**Comment by begeekmyfriend** [comment]
GLES默认颜色空间格式是RGBA8888的，而bitmap默认的ARGB8888正相反，利用libyuv转换一下可以解决，你可以修改[libenc.cc](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/cpp/libenc/libenc.cc)中的`FOURCC_XXXX`；
另一种变通的方法是，本地录制，然后从中提取一帧出来

**Comment by asswc204** [comment]
感谢您的回复。最后是通过视频提取帧实现

**Comment by asswc204** [comment]
请问可以支持离线录制吗，每次录制publish都需要连接RTMPserver,不然录制的就是黑屏。

**Comment by begeekmyfriend** [comment]
可以的，你把[mFlvMuxer.start](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsPublisher.java#L165)去掉试试，总之整个`SrsFlvMuxer`都去掉也可以

**Comment by asswc204** [comment]
我尝试了去掉mFlvMuxer.start，和整个SrsFlvMuxer去掉，结果都是可以录制，但是每次录制的视频都是固定大小并且黑屏没有画面的。

**Comment by begeekmyfriend** [comment]
那就是你自己定制的事情了

**Comment by asswc204** [comment]
嗯，前面由于删除SrsFlvMuxer，导致onGetRgbaFrame中条件不满足没有执行导致录制黑屏，去掉判断后加上方法体后能实现本地录制，感谢大神的无私奉献~已把工程完全移植到项目里
