### ISSUE TITLE
有的apk版本不能启动

### ISSUE THREAD

**Issue by wuxianlijiang** [begeekmyfriend/yasea#459]
机型：三星note4
问题：安装成功；启动时提示“yasea已停止”。
安装包来源：https://github.com/begeekmyfriend/yasea-apk
版本：yasea-v2.6.apk

求解，谢谢。

**Comment by begeekmyfriend** [comment]
这是我在谷歌手机上编译的

**Comment by begeekmyfriend** [comment]
It is OK now.
