### ISSUE TITLE
kFilterNone in libenc scaling

### ISSUE THREAD

**Issue by EitanGoldfrad** [begeekmyfriend/yasea#460]
Hey mate,

In libenc.cc I see you use KFilterNone, is there a reason not to use KFilterBox or KFilterBilinear ? 

Btw I really like your work , you did a great job here.

**Comment by EitanGoldfrad** [comment]
I'm asking this because i'm experiencing low frame rate and maybe by making the scaling process faster the framerate would be better

**Comment by begeekmyfriend** [comment]
Yasea does nothing with KFilterXXX.
You may try this commit https://github.com/begeekmyfriend/yasea/commit/a8c36e3b43a1fd4bb4dace538d7b46873dca68f9 but it I will not assure you that your device can afford it.

**Comment by begeekmyfriend** [comment]
Oh yes. `kFilterNone` is the fastest option for scaling. I think you can try the latest version for that it does not scale at all and see what the result would be for FPS.

**Comment by EitanGoldfrad** [comment]
Oh you're right.
Is there any other way to get higher FPS?
I'm trying to get to 30 FPS but i'm only getting around 17

**Comment by begeekmyfriend** [comment]
Unless your device is of original ROM.

**Comment by EitanGoldfrad** [comment]
It is LG3 original ROM.
With Wowza android sdk I get 25 fps but here i get around 17 fps

**Comment by begeekmyfriend** [comment]
How about [non-gpuimage](https://github.com/begeekmyfriend/yasea/tree/non-gpuimage)?

**Comment by EitanGoldfrad** [comment]
I tried this branch and i'm trying to stream 854x480 but I get only 10 fps.
Any idea what I can do to get 24 fps at this resolution?

**Comment by begeekmyfriend** [comment]
Did you use front or back camera for Wowza SDK on preview?

**Comment by EitanGoldfrad** [comment]
I use back camera for both apps

**Comment by begeekmyfriend** [comment]
Why not try front camera for Wowza SDK? The major block point is on [glReadPixels](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/com/seu/magicfilter/base/gpuimage/GPUImageFilter.java#L273) which would fetch raw image data from GPU memory. Comment out this line and see what would happen.

**Comment by EitanGoldfrad** [comment]
I mostly use back camera in my app.
Why not use `onPreviewFrame` from Camera.PreviewCallback and get the frame in nv21 or yv12 format instead of rgba?

**Comment by begeekmyfriend** [comment]
In the [non-gpuimage](https://github.com/begeekmyfriend/yasea/blob/non-gpuimage/library/src/main/java/net/ossrs/yasea/SrsCameraView.java#L231) it does. But you said it still did not work well... How about comment out `mPrevCb.onGetYuvFrame(data)` statement?

**Comment by EitanGoldfrad** [comment]
Doesn't seem to work.
I manage to get 20 fps using [rtmp-rtsp-stream-client-java](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java)
Maybe you can use some of his methods

**Comment by begeekmyfriend** [comment]
Sorry to inform you so late. I forgot to add a thread to decouple preview callback and encoding and publishing. Now it works all right. https://github.com/begeekmyfriend/yasea/commit/0c404b273835ff24726c5028173076f074d3d30a
