### ISSUE TITLE
E/libenc: Fail to open x264 encoder!

### ISSUE THREAD

**Issue by AliceDinh** [begeekmyfriend/yasea#461]
Hi,
I got this error today:
06-28 14:14:39.171 6198-6198/net.ossrs.yasea.demo E/libenc: Fail to open x264 encoder!

I modified the path
FROM:
jclass clz = jenv->FindClass("net/ossrs/yasea/SrsEncoder");
 if (clz == NULL) {
        LIBENC_LOGE("Class \"net/ossrs/yasea/SrsEncoder\" not found");
        return JNI_ERR;
 }
TO:
jclass clz = jenv->FindClass("com/dinhnhan/encoder/video/VideoEncoderAVC");
  if (clz == NULL) {
       LIBENC_LOGE("Class \"com/dinhnhan/encoder/video/VideoEncoderAVC\" not found");
       return JNI_ERR;
   }
I don't think giving different path raising errors but it does, so please help. Thanks

**Comment by begeekmyfriend** [comment]
Did the logging show `Class XXX not found` or just show `Fail to open x264 encoder!`?
Please clone the latest version and try again.

**Comment by AliceDinh** [comment]
The latest version works fine, but I want to change the path of your class to my class's path.
