### ISSUE TITLE
flips mirror

### ISSUE THREAD

**Issue by visir-he** [begeekmyfriend/yasea#463]
Can you add a function that flips mirror when using the front camera?
Another problem is that when I run with an x86 architecture simulator, it goes awry. Here's the log:
java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/code.gongzhuzhibo-1/lib/x86/libenc.so: has text relocations
                                                                     at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                     at java.lang.System.loadLibrary(System.java:1076)

**Comment by begeekmyfriend** [comment]
See [flip](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L621-L629) parameter.

Yasea cannot run on simulator since it needs hard encoding.

**Comment by visir-he** [comment]
I didn't look at the parameters carefully. Thank you, Sir. I like this project very much

**Comment by visir-he** [comment]
Sir,
When I tried to run this project on huawei's mate 9 and use the device to push the stream, the screen became blurry when playing, whether it was playing on android, ios or VLC.

**Comment by begeekmyfriend** [comment]
It seems custom ROM on Huawei's mate 9. Unfortunately I have no such device for debugging...
