### ISSUE TITLE
RGBAToI420() and RGBAToNV12() functions

### ISSUE THREAD

**Issue by AliceDinh** [begeekmyfriend/yasea#465]
Hi,
As I know that because you use opengl with a glreadpixel, therefore you get RGBA format. You wrote RGBAToI420() and RGBAToNV12() functions to convert them into I420 and NV12. 
Please share why you choose I420 and NV12 to convert to and why not convert to YUV420?
Thanks

**Comment by begeekmyfriend** [comment]
Because I would send the raw images into Android hard encoder that just to be fit by such format.

**Comment by AliceDinh** [comment]
Hi,

If I don't want to use opengl, I want to send raw data from camera to encoder, I will receive NV21, what changes I have to make to make it work with soft coding?

**Comment by begeekmyfriend** [comment]
[non-gpuimage](https://github.com/begeekmyfriend/yasea/tree/non-gpuimage)

**Comment by AliceDinh** [comment]
I modified libenc.cc by this:
`static jint libenc_NV21SoftEncode(JNIEnv *env, jobject thiz, jbyteArray frame, jint src_width,
                                  jint src_height, jboolean need_flip, jint rotate_degree,
                                  jlong pts) {
    jbyte *nv21_frame = env->GetByteArrayElements(frame, NULL);

    if (!convert_to_i420((uint8_t *) nv21_frame, src_width, src_height, need_flip, rotate_degree,
                         FOURCC_NV21)) {
        return JNI_ERR;
    }

    int es_len = x264_ctx.global_nal_header ? encode_global_nal_header() : x264_encode(
            &i420_scaled_frame, pts);
    if (es_len <= 0) {
        LIBENC_LOGE("Fail to encode nalu");
        return JNI_ERR;
    }

    jbyteArray outputFrame = env->NewByteArray(es_len);
    env->SetByteArrayRegion(outputFrame, 0, es_len, (jbyte *) h264_es);

    jclass clz = env->GetObjectClass(thiz);
    jmethodID mid = env->GetMethodID(clz, "onSoftEncodedNV21Data", "([BJZ)V");
    env->CallVoidMethod(thiz, mid, outputFrame, x264_ctx.pts, x264_ctx.is_key_frame);

    env->ReleaseByteArrayElements(frame, nv21_frame, JNI_ABORT);
    return JNI_OK;
}`
and in the SrsEncoder, I had:
`  private void swYuvFrame(byte[] data, int width, int height, long pts) {
    NV21SoftEncode(data, width, height, true, 180, pts);
  }`
but then I don't know from where I can modify the input of encoder with no OpenGL support. Please help me.
Thanks

**Comment by AliceDinh** [comment]
non-gpuimage: How to do that sir?

**Comment by AliceDinh** [comment]
What does this function mean, sir?
I understand that you convert NV21 to I420 but what Scaled means? and the crop_x, crop_y, crop_with, crop_height?

`static jbyteArray
libenc_NV21ToI420Scaled(JNIEnv *env, jobject thiz, jbyteArray frame, jint src_width,
                        jint src_height, jboolean need_flip, jint rotate_degree,
                        jint crop_x, jint crop_y, jint crop_width, jint crop_height) {
    jbyte *argb_frame = env->GetByteArrayElements(frame, NULL);

    if (!convert_to_i420_with_crop_scale((uint8_t *) argb_frame, src_width, src_height,
                                         crop_x, crop_y, crop_width, crop_height,
                                         need_flip, rotate_degree, FOURCC_NV21)) {
        return NULL;
    }

    int y_size = i420_scaled_frame.width * i420_scaled_frame.height;
    jbyteArray i420Frame = env->NewByteArray(y_size * 3 / 2);
    env->SetByteArrayRegion(i420Frame, 0, y_size * 3 / 2, (jbyte *) i420_scaled_frame.data);

    env->ReleaseByteArrayElements(frame, argb_frame, JNI_ABORT);
    return i420Frame;
}`

**Comment by begeekmyfriend** [comment]
Please read [header files](https://github.com/begeekmyfriend/yasea/tree/master/library/src/main/cpp/libyuv/include/libyuv) of `libyuv` and be acquainted with its APIs.

**Comment by AliceDinh** [comment]
Thanks
