### ISSUE TITLE
录制视频时，只能在推流时录制嘛？

### ISSUE THREAD

**Issue by Yeecz** [begeekmyfriend/yasea#468]
录制视频只有在推流时才能录制，是有这个情况吗？
能不能改成只要启动录制就录制。

**Comment by begeekmyfriend** [comment]
只要[startEncode](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsPublisher.java#L167)就可以

**Comment by Yeecz** [comment]
@begeekmyfriend 
按照您的指示，先startEncode然后再startRecord，停止时调用先stopRecord再stopEncode。录制期间一直有onNetworkWeak()回调执行。当我第一次停止录制时没有保存完成提示，再次开启录制之后再停止，会有保存完成的提示，不过检查文件只有十几KB大小。

我把demo中录制按钮点击事件更改了一下。
`if (btnRecord.getText().toString().contentEquals("record")) {`
                    `mPublisher.startEncode();`
                    `if (mPublisher.startRecord(recPath)) {`
                        `btnRecord.setText("stop");`
                    `}`
                `} else if (btnRecord.getText().toString().contentEquals("stop")){`
                   ` mPublisher.stopRecord();`
                   ` mPublisher.stopEncode();`
                   ` btnRecord.setText("record");`
               ` }`

**Comment by begeekmyfriend** [comment]
你能不能继续深入把`SrsEncoder.java`里有关`FlvMuxer`相关的东西移除呢？这样对你的需求更干净，因为你不需要推流，这些本来就是你应该自己去做的事情啊（你应该了解自己在干什么，才能做好定制）

**Comment by Yeecz** [comment]
@begeekmyfriend 
我的需求是这样的，服务端发送推流命令或者录像命令，客户端进行响应操作。由于原生MediaRecorder不能使用，正好您的这个编码解码符合要求。本来还是个小白，如果可以多点提示，谢谢您了。

**Comment by Yeecz** [comment]
public void onGetRgbaFrame(byte[] data, int width, int height) {
        // Check video frame cache number to judge the networking situation.
        // Just cache GOP / FPS seconds data according to latency.
        AtomicInteger videoFrameCacheNumber = flvMuxer.getVideoFrameCacheNumber();
        if (videoFrameCacheNumber != null && videoFrameCacheNumber.get() < VGOP) {
            long pts = System.nanoTime() / 1000 - mPresentTimeUs;
            if (useSoftEncoder) {
                swRgbaFrame(data, width, height, pts);
            } else {
                byte[] processedData = hwRgbaFrame(data, width, height);
                if (processedData != null) {
                    onProcessedYuvFrame(processedData, pts);
                } else {
                    mHandler.notifyEncodeIllegalArgumentException(new IllegalArgumentException("libyuv failure"));
                }
            }

            if (networkWeakTriggered) {
                networkWeakTriggered = false;
                mHandler.notifyNetworkResume();
            }
        } else {
            mHandler.notifyNetworkWeak();
            networkWeakTriggered = true;
        }
    }


那我是不是可以直接进行编码判断然后数据发送就行了，去除videoFrameCacheNumber的判断

**Comment by begeekmyfriend** [comment]
如果你要实现某个需求，就按照这个需求去专门定制，然后再考虑整个项目的整合。比如你的需求是不推流情况下的录制，那么你就应该考虑将推流的逻辑（比如`FlvMuxer`）**全部**去掉，先实现单纯录制以后，再进行下一步，不然逻辑混在一起，你也搞不明白，我也帮不了你。

**Comment by Yeecz** [comment]
现在去除以后，录制下来只有声音没有视频。推流时视频资源从哪里获取的？是从SrsFlvMuxer里面获取的嘛？

**Comment by begeekmyfriend** [comment]
你必须收集到SPS和PPS才能加入[视频轨道](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsMp4Muxer.java#L124)

**Comment by Yeecz** [comment]
sps和pps都是从[PreviewCallback.onGetRgbaFrame](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsPublisher.java#L37)中获取，[SrsCameraView中的enableEncoding](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsCameraView.java#L224)执行回调，在onDrawFrame中添加[mGLIntBufferCache的值](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsCameraView.java#L115)。是这样嘛？

**Comment by begeekmyfriend** [comment]
很遗憾看来你连最基本的概念都没弄懂，为了促使你学习，我建议你自己去搜SPS和PPS是什么，我不会在这里回答你了

**Comment by Yeecz** [comment]
@begeekmyfriend 我解决了直接开启录制只有声音没有画面的问题了。由于startEncode() 会去获取cache，但是之前我都是开始startEncode()之后立即进行startRecord()导致SrsMp4Muxer中sps和pps里面为空没有进行视频资源的addTrack。所以只要开始startEncode() 之后延时1秒左右，再启动录制就可以了。谢谢您的耐心指导。

**Comment by begeekmyfriend** [comment]
但是你脑中的基本概念还是错的，如果顺其自然请随意

**Comment by Yeecz** [comment]
如果我理解没错的话，从SrsCameraView的worker线程中执行PreviewCallback.onGetRgbaFrame，SrsPublisher中实现PreviewCallback.onGetRgbaFrame，把byte数组data传递给SrsEncoder的onGetRgbaFrame，SrsEncoder中硬解成Yuvframe然后传递给Muxer的writeSampleData，录制SrsMp4Muxer的writeVideoSample区分sps和pps各自list中。对于sps、pps以及其他（硬软解，cpp之类的很多）不理解，但是我现在比较着急解决这个录制问题，所以向您请求帮助，您也愿意答复，我十分感谢。

**Comment by begeekmyfriend** [comment]
> SrsEncoder中硬解成Yuvframe
建议你多读书

**Comment by Yeecz** [comment]
能具体说明什么内容吗？比如书名，我该搜索的关键词
