### ISSUE TITLE
First recorder is only audio file

### ISSUE THREAD

**Issue by ii085** [begeekmyfriend/yasea#469]
h264_sps and h264_pps are null in the first record so the video track is not added. In a second recorder I got a video file.

**Comment by begeekmyfriend** [comment]
If sps and pps are not collected, how can live stream work? Did you modify the original code or did you run the latest version?

**Comment by ii085** [comment]
I'm using the last version

**Comment by begeekmyfriend** [comment]
Did it run through this [line](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsMp4Muxer.java#L292)? And what about other devices?

**Comment by ii085** [comment]
yes but "addTrack(MediaFormat format, boolean isAudio)" was called just one time with isAudio=true

**Comment by begeekmyfriend** [comment]
Well, these two [tracks](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsMp4Muxer.java#L690-L694) should be both added into `Mp4Muxer` at one time.

**Comment by ii085** [comment]
sorry i didn't understand you 
[L124:](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsMp4Muxer.java#L124) !spsList.isEmpty() && !ppsList.isEmpty() = false

**Comment by ii085** [comment]
when i stop the live and start one other without closing the app the video track is added and a video file is created.

**Comment by begeekmyfriend** [comment]
The video track should not be added until the SPS and PPS are collected.
