### ISSUE TITLE
Streaming without preview

### ISSUE THREAD

**Issue by deeepakpatil** [begeekmyfriend/yasea#472]
Hi,
Could you please implement streaming without preview ?
A radio button / check box can be added to toggle On/OFF preview.

A] Intent is to start streaming on boot, with locked screen (i.e. without preview).
B] Something like linux watchdog can be used to restart the app at regular interval if not running.
C] Idea is to make it remote streaming device, which can run without supervision.

This feature will significantly boost the utility of this app.

**Comment by begeekmyfriend** [comment]
Comment out this [line](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/com/seu/magicfilter/base/gpuimage/GPUImageFilter.java#L277).

**Comment by deeepakpatil** [comment]
Hi,
Thanks for quick reply.
I am using "non-gpuimage" branch. Please suggest me modification.

**Comment by begeekmyfriend** [comment]
That branch enables preview by default and can not cancel.

**Comment by begeekmyfriend** [comment]
You can see in `non-gpuimage` branch, the parameter of camera preview setting is a [surface holder](https://github.com/begeekmyfriend/yasea/blob/non-gpuimage/library/src/main/java/net/ossrs/yasea/SrsCameraView.java#L149) which would pass the native surface into camera grapic pipe and draw automatically on opening. While in master branch, we just pass a [SurfaceTexture](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsCameraView.java#L312) object which means you have to draw the image as external texture from camera on the surface by hand.
