### ISSUE TITLE
weak problem

### ISSUE THREAD

**Issue by go2av** [begeekmyfriend/yasea#474]
@begeekmyfriend 
### three class 
1. [SrsEncodeHandler](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncodeHandler.java#L21)

2. [SrsRecordHandler](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsRecordHandler.java#L26)

3. [RtmpHandler](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/com/github/faucamp/simplertmp/RtmpHandler.java#L34)

### fix
 [demo](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/demo/MainActivity.java)中的传递对象 是this,也就是跟着activity走，这个不会出现问题
 当传递的listener对象是实例时，而且是在方法内实例会被释放掉,这个持有地方

**Comment by begeekmyfriend** [comment]
我已经在`handleMessage`里做了检测，一旦Activity释放，这些消息自然就无用而丢弃，并不存在资源泄露

**Comment by go2av** [comment]
@begeekmyfriend 
不是泄漏，我这里传递的是个静态内部类，初始化在方法快里面，非全局变量
但是我在打印和d的时候 发现 weak.get 返回值为空，也就是这个对象被释放了，
我打印的时候，弱引用的时候对象很快就被释放了，

**Comment by begeekmyfriend** [comment]
具体情况我就不清楚了，静态类生命周期一般来说不会因为代码块的范围而结束，是不是您的逻辑有点问题？

**Comment by go2av** [comment]
我是直接去掉弱引用了:smile:
