### ISSUE TITLE
 ANR when I call SrsPublisher#stop()

### ISSUE THREAD

**Issue by lomoya90** [begeekmyfriend/yasea#477]
SrsFlvMuxer#stop():
```java
    /**
     * stop the muxer, disconnect RTMP connection.
     */
    public void stop() {
        mFlvTagCache.clear();
        if (worker != null) {
            worker.interrupt();
            try {
                **worker.join();**
            } catch (InterruptedException e) {
                e.printStackTrace();
                worker.interrupt();
            }
            worker = null;
        }
        flv.reset();
        needToFindKeyFrame = true;
        Log.i(TAG, "SrsFlvMuxer closed");

        new Thread(new Runnable() {
            @Override
            public void run() {
                disconnect();
            }
        }).start();
    }
```
ANR when I call Thread#join() .

**Comment by begeekmyfriend** [comment]
Did you modify the SDK code? Pull the latest version and try again

**Comment by lomoya90** [comment]
我用的是最近的代码，看起来好像是sendFlvTag 导致的anr，sendRtmpPacket会导致阻塞吗？

**Comment by begeekmyfriend** [comment]
Show me your logcat

**Comment by lomoya90** [comment]
###"main" prio=5 tid=1 Waiting
  | group="main" sCount=1 dsCount=0 obj=0x885c7f60 self=0x7fa10a6000
  | sysTid=8865 nice=0 cgrp=bg_non_interactive sched=0/0 handle=0x7fa50e7e30
  | state=S schedstat=( 0 0 0 ) utm=1736 stm=516 core=4 HZ=100
  | stack=0x7fe6c40000-0x7fe6c42000 stackSize=8MB
  | held mutexes=
  at java.lang.Object.wait!(Native method)
  - waiting on <0x1b1a2e06> (a java.lang.Object)
  at java.lang.Thread.join(Thread.java:724)
  - locked <0x1b1a2e06> (a java.lang.Object)
  at main.live.f.f.b(SrsFlvMuxer.java:182)
 
  - locked <@addr=0x133be310> (a main.live.f.i)
  at android.view.View.performClick(View.java:5254)
  at android.view.View$PerformClick.run(View.java:21179)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:145)
  at android.app.ActivityThread.main(ActivityThread.java:6837)
  at java.lang.reflect.Method.invoke!(Native method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by begeekmyfriend** [comment]
These were too little for me, can you show me more? What you point out is not the true ANR point.

**Comment by lomoya90** [comment]
@begeekmyfriend 点击停止的时候，有时就会ANR，没有更多的日志了。

**Comment by begeekmyfriend** [comment]
你可以在这个[线程](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsFlvMuxer.java#L140)里面加打印，看看哪里会卡住

**Comment by lomoya90** [comment]
private ConcurrentLinkedQueue<SrsFlvFrame> mFlvTagCache 这个变量没有大小限制处理，容易导致内存溢出，不知道您有没有发现这个问题。

**Comment by begeekmyfriend** [comment]
FLV队列会有个[计数](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L375)，一旦超过说明网络差，是不会送往编码器的，所以你确定溢出了？

**Comment by WillyWLLu** [comment]
您好, 我目前也有測試出這個問題
在[線程](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsFlvMuxer.java#L153) 153卡住的

發生問題時我有持續收到onNetworkWeak()的callback訊息, 但我當前網路狀況是良好的

**Comment by begeekmyfriend** [comment]
`onNetworkWeak`说明RTMP包发不出去了，你自以为网络良好，但事实就是发不出去，发包的代码在[这里](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L497)，你可以自己加打印判断。

**Comment by begeekmyfriend** [comment]
@WillyWLLu 你还可以使用`ffmpeg`命令来诊断能否推流（不过那是PC的网络）
> ffmpeg -re -i test.mp4 -vcodec libx264 -acodec copy -f flv rtmp://host[:port]/app/stream

**Comment by WillyWLLu** [comment]
@begeekmyfriend 您好, 我再測試看看, 感謝您的回覆

**Comment by begeekmyfriend** [comment]
@WillyWLLu 好久没回复，我一直没复现，最新版是否存在问题？
