### ISSUE TITLE
画面边缘锯齿严重

### ISSUE THREAD

**Issue by yaooort** [begeekmyfriend/yasea#478]
请问画面的边缘锯齿是怎么回事？

**Comment by begeekmyfriend** [comment]
这恐怕跟编码器有关吧，报一下手机型号？，另外软编码试试？

**Comment by yaooort** [comment]
三星s6 ,软编码也是一样的。
![](https://github.com/yaooort/Readme/blob/master/device-2017-07-21-103025.png)

**Comment by begeekmyfriend** [comment]
其它手机，同样的服务器和播放器，也有锯齿么？

**Comment by yaooort** [comment]
我试了小米5 也是有锯齿，我是用你的Demo直接跑的，就改成软编码，其他的没动。

**Comment by yaooort** [comment]
请教个问题，这个项目如果改为librtmp推流，从哪里入手？

**Comment by begeekmyfriend** [comment]
FLV tag出口（与RTMP交接部分）在[这里](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsFlvMuxer.java#L121-L125)

至于锯齿，真的怀疑你的server和player是不是有问题，这个项目开源一年多了，还没接到这样的反馈，你再clone一把最新的试试……

**Comment by yaooort** [comment]
谢谢
