### ISSUE TITLE
使用PLDroidPlayer播放器sdk播放时只有视频没有声音

### ISSUE THREAD

**Issue by xml4cn** [begeekmyfriend/yasea#48]
测试设备：台电Android平板
服务器使用nginx-rtmp
yasea：16-07-05  master的版本
使用七牛的播放器sdk Android版本：https://github.com/pili-engineering/PLDroidPlayer     1.3.0
1. 测试PLDroidPlayer是不是不能播放声音：
播放  rtmp://live.hkstv.hk.lxdns.com/live/hks 是有视频和声音，播放yasea推送的内容没有声音。
2. 测试yasea是不是采集的声音有问题：
在pc上使用flash提供的rtmp播放器播放yasea推送的视频，有声音。在Android上使用PLDroidPlayer播放没声音。
现在怀疑yasea推送的数据格式跟PLDroidPlayer的实现有冲突的地方。

**Comment by begeekmyfriend** [comment]
这个锅恐怕得PLDroidPlayer来背，因为flash播放器还有VLC播放器都是正常的，你可以向pili团队提交issue

**Comment by zzzlq** [comment]
请问yasea有实现拉流部分么？

**Comment by begeekmyfriend** [comment]
@zzzlq 没有

**Comment by begeekmyfriend** [comment]
Maybe fixed https://github.com/begeekmyfriend/yasea/commit/ad6eadefca7fa5c0fb8082f4c685b83128577992 and https://github.com/begeekmyfriend/yasea/commit/be200b1bc61376dc22ba8c69acbb2ac4c4a17a6d
