### ISSUE TITLE
网络是没有问题的，但是偶尔播一段时间就会有马赛克，有优化方案吗 

### ISSUE THREAD

**Issue by WangShuo1143368701** [begeekmyfriend/yasea#481]

**Comment by begeekmyfriend** [comment]
你确定你的网络是稳定的，所以马赛克是推流端的问题？

**Comment by WangShuo1143368701** [comment]
每过6秒左右会出现一帧马赛克画面之后又好了，然后6秒后又出现一帧。  百兆光纤，应该是稳定的

**Comment by begeekmyfriend** [comment]
换成软编码试试，另外其它手机都是这个现象吗？

**Comment by WangShuo1143368701** [comment]
这个现象是偶现的，不过一旦偶现出来这个现象，就必然会6秒左右出现一帧马赛克。  另外发现在推流端（比如主播）晃动的时候，这个马赛克会更明显   之前一直硬编码，我只后用软编试试
