### ISSUE TITLE
Publish Record

### ISSUE THREAD

**Issue by Marcrazyness** [begeekmyfriend/yasea#482]
Hello,

I am new to rtmp and I would like to record the stream to the server. If possible to do with this library, would you please guide me in doing so?

Thanks,
Marcos

**Comment by begeekmyfriend** [comment]
You may replace ["live"](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsFlvMuxer.java#L103) with "record" if the server supports this field. See [this](https://www.wowza.com/community/questions/1374/publishing-stream-using-quotlivequot-quotrecordquo.html).

**Comment by Marcrazyness** [comment]
Awesome thanks! 

It looks like it is recording but the file isn't readable. Is there a configuration I am missing? The file size for each failed attempt is the same.

> ffmpeg -i filename.flv
> ffmpeg version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2000-2017 the FFmpeg developers
>   built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
>   configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
>   libavutil      54. 31.100 / 54. 31.100
>   libavcodec     56. 60.100 / 56. 60.100
>   libavformat    56. 40.101 / 56. 40.101
>   libavdevice    56.  4.100 / 56.  4.100
>   libavfilter     5. 40.101 /  5. 40.101
>   libavresample   2.  1.  0 /  2.  1.  0
>   libswscale      3.  1.101 /  3.  1.101
>   libswresample   1.  2.101 /  1.  2.101
>   libpostproc    53.  3.100 / 53.  3.100
> filename.flv: could not find codec parameters

Thanks,
Marcos

**Comment by Marcrazyness** [comment]
Just read that FMS doesn't support H264 flv.

> https://viveklakhanpal.wordpress.com/tag/screensharing-in-flash/
> Using H264 you can’t reocrd flv file on server you can only create mp4 files

> https://forums.adobe.com/message/3953605#3953605
> "...does not support H.264/AVC in an FLV container."

Added prefix mp4 to path and now receiving the message below:

> ffmpeg version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2000-2017 the FFmpeg developers
>   built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
>   configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
>   libavutil      54. 31.100 / 54. 31.100
>   libavcodec     56. 60.100 / 56. 60.100
>   libavformat    56. 40.101 / 56. 40.101
>   libavdevice    56.  4.100 / 56.  4.100
>   libavfilter     5. 40.101 /  5. 40.101
>   libavresample   2.  1.  0 /  2.  1.  0
>   libswscale      3.  1.101 /  3.  1.101
>   libswresample   1.  2.101 /  1.  2.101
>   libpostproc    53.  3.100 / 53.  3.100
> [mov,mp4,m4a,3gp,3g2,mj2 @ 0xc04fe0] Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), none, 480x320): unspecified pixel format
> Consider increasing the value for the 'analyzeduration' and 'probesize' options
> [mov,mp4,m4a,3gp,3g2,mj2 @ 0xc04fe0] Could not find codec parameters for stream 1 (Audio: none, 1000 Hz, 0 channels): unknown codec
> Consider increasing the value for the 'analyzeduration' and 'probesize' options
> Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'androidtest_12':
>   Metadata:
>     major_brand     : f4v 
>     minor_version   : 0
>     compatible_brands: isommp42m4v 
>     creation_time   : 2022-11-14 13:59:00
>   Duration: N/A, bitrate: N/A
>     Stream #0:0(eng): Video: h264 (avc1 / 0x31637661), none, 480x320, SAR 8:9 DAR 4:3, 1k tbr, 1k tbn, 2k tbc (default)
>     Metadata:
>       creation_time   : 2022-11-14 13:59:00
>       handler_name    : MainConcept
>       encoder         : AVC Coding
>     Stream #0:1(eng): Audio: none, 1000 Hz, 0 channels (default)
>     Metadata:
>       creation_time   : 2022-11-14 13:59:00
>       handler_name    : Mainconcept MP4 Sound Media Handler
>     Stream #0:2(eng): Data: none (amf0 / 0x30666D61) (default)
>     Metadata:
>       creation_time   : 2022-11-14 13:59:00
>       handler_name    : Timed Metadata Handler
> At least one output file must be specified

**Comment by begeekmyfriend** [comment]
Maybe it was the configuration of FMS. Unfortunately I am not familiar with that. I suggest you may try [SRS](https://github.com/ossrs/srs) as local RTMP server and the author can help you with that.

**Comment by Marcrazyness** [comment]
Thanks for your help @begeekmyfriend!
