### ISSUE TITLE
Error:A problem occurred configuring project ':library'.

### ISSUE THREAD

**Issue by mastashake08** [begeekmyfriend/yasea#484]
Just checkout out your project into Android Studio I have NDK installed but this happens when I try to sync the build. I haven't touched the code this is fresh clone.

**Comment by begeekmyfriend** [comment]
- Clone to the latest version.
- Upgrade Android Studio.
- Download `ndk-bundle` (in setting menu).

**Comment by zameelpichen** [comment]
Iam having a problem with library configuration. 

....
...
...
JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.NoSuchMethodError: no static or non-static method "Lnet/ossrs/yasea/SrsEncoder;.ARGBToI420Scaled([IIIZIIIII)[B"
 A/art: art/runtime/java_vm_ext.cc:470]   at java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.String) (Runtime.java:-2)
 A/art: art/runtime/java_vm_ext.cc:470]   at java.lang.String java.lang.Runtime.doLoad(java.lang.String, java.lang.ClassLoader) (Runtime.java:1072)
 A/art: art/runtime/java_vm_ext.cc:470]   at void java.lang.Runtime.loadLibrary0(java.lang.ClassLoader, java.lang.String) (Runtime.java:987)
 A/art: art/runtime/java_vm_ext.cc:470]   at void java.lang.System.loadLibrary(java.lang.String) (System.java:1530)
 A/art: art/runtime/java_vm_ext.cc:470]   at void net.ossrs.yasea.SrsEncoder.<clinit>() (SrsEncoder.java:508)
 A/art: art/runtime/java_vm_ext.cc:470]   at void net.ossrs.yasea.SrsPublisher.setEncodeHandler(net.ossrs.yasea.SrsEncodeHandler) (SrsPublisher.java:281)
 A/art: art/runtime/java_vm_ext.cc:470]   at void net.ossrs.yasea.demo.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:78)
 A/art: art/runtime/java_vm_ext.cc:470]   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6679)
 A/art: art/runtime/java_vm_ext.cc:470]   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentatio........

what to do? the full error that is shown in logcat (as red) is huge.
SrsEncoder.java:508
SrsPublisher.java:281
MainActivity.java:80
these lines have been shown three times as error.

i am compiling yasea as a library under my project. also, yasea by default is compiling 'library' as its library.
I have checked for android studio build error possibilities, which i could not find so far.
andrecently, there was some issue with creating the R file for itemsOptionsMenu items values in mainactivity. so, after cleaning and rebuilding many times, i had to comment those lines out.

Is this fixable?

**Comment by begeekmyfriend** [comment]
@zameelpichen That was because you had failed to load the library (so files). Look at my response on the 2nd floor and try again...

**Comment by zameelpichen** [comment]
but i have installed the ndk.

**Comment by begeekmyfriend** [comment]
Did you modify the original project?

**Comment by zameelpichen** [comment]
no, but i made it into a library in the gradle.

is it saying i have to make any function static?

**Comment by zameelpichen** [comment]
myapp <- yasea (library) <- (library

this is my setup. is this an issue?

**Comment by begeekmyfriend** [comment]
@zameelpichen I suggest you need to find out which [line](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/cpp/libenc/libenc.cc#L581) did the NDK fail loading library.

**Comment by zameelpichen** [comment]
CheckJNI: method to register "ARGBToI420Scaled" not in the given class. This is slow, consider changing your RegisterNatives calls.
 E/art: Failed to register native method net.ossrs.yasea.SrsEncoder.ARGBToI420Scaled([IIIZIIIII)[B in /data/app/com.example.app.myapp-2/split_lib_dependencies_apk.apk:classes17.dex
08-21 07:34:52.245 15761-15761/com.example.app.myapp E/art: ----- class 'Lnet/ossrs/yasea/SrsEncoder;' cl=0x12cd8310 -----
 E/art:   objectSize=352 (180 from super)
 E/art:   access=0x0008.0001
 E/art:   super='java.lang.Class<java.lang.Object>' (cl=0x0)


this was the begining of the error.
-------------------------------------------------------
srsencoder
```
   private byte[] hwArgbFrameScaled(int[] data, int width, int height, Rect boundingBox) {
        switch (mVideoColorFormat) {
            case MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420Planar:
->(this line)                return ARGBToI420Scaled(data, width, height, false, 0, boundingBox.left, boundingBox.top, boundingBox.width(), boundingBox.height());
            case MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420SemiPlanar:
                return ARGBToNV12Scaled(data, width, height, false, 0, boundingBox.left, boundingBox.top, boundingBox.width(), boundingBox.height());
            default:
                throw new IllegalStateException("Unsupported color format!");
        }
    }
```
--------------------------------------------------
srspublisher
`   public void switchCameraFace(int id) {
        mCameraView.stopCamera();
        mCameraView.setCameraId(id);
        if (id == 0) {
            mEncoder.setCameraBackFace();
        } else {
->(this line)            mEncoder.setCameraFrontFace();
        }
        if (mEncoder != null && mEncoder.isEnabled()) {
            mCameraView.enableEncoding();
        }
        mCameraView.startCamera();
    }
`
---------------------------------------------------
mainactivity - yasea
`        mPublisher.setEncodeHandler(new SrsEncodeHandler(this));
`

**Comment by zameelpichen** [comment]
libenc.cc shows this

"Class \"net/ossrs/yasea/SrsEncoder\" not found"

**Comment by begeekmyfriend** [comment]
@zameelpichen Then you need to find the package

**Comment by zameelpichen** [comment]
i will get back in 8 hrs. can you briefly elaborate what i have to do? by finding package you mean....

where do i have to update?

**Comment by begeekmyfriend** [comment]
> "Class "net/ossrs/yasea/SrsEncoder" not found"

**Comment by zameelpichen** [comment]
thing is, srsencoder is within the -  package net.ossrs.yasea;
then what is wrong here...? Thanks a lot for the quick replies.

**Comment by zameelpichen** [comment]
i made some changes and it is working now.
