### ISSUE TITLE
Text relocations in libenc.so

### ISSUE THREAD

**Issue by Khalitzer** [begeekmyfriend/yasea#485]
According to
https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md
there can be no text relocations in compiled files if you want to use target SDK >= 23.
https://www.akkadia.org/drepper/textrelocs.html
`/lib/x86/libenc.so has text relocations.`
```
0x00000016 (TEXTREL)         0x0
0x0000001e (FLAGS)           TEXTREL BIND_NOW
```

**Comment by begeekmyfriend** [comment]
`grep -r "android-19"` and replace all of the results with `android-21`.

**Comment by Khalitzer** [comment]
Does not resolve the underlying issue. Recompiling native libraries still results in TEXTREL, no matter which android version I target in ndk-built files.

**Comment by begeekmyfriend** [comment]
Did you rebuild `libx264.a` manually in this [directory](https://github.com/begeekmyfriend/yasea/tree/master/library/src/main/cpp/libx264/libs)?

**Comment by Khalitzer** [comment]
I have tried doing that. No luck, the linker gives me exit code 1 when I try to build the app with rebuilt libx264.a.

**Comment by begeekmyfriend** [comment]
Oh, did you mean `x86`? How about `armeabi-v7a`?

**Comment by Khalitzer** [comment]
Still the same error while trying to build the app.

**Comment by begeekmyfriend** [comment]
I am curious about the model of your device. I tried changing target SDK version today and everything was OK for me.
