### ISSUE TITLE
Output stream aspect ratio.

### ISSUE THREAD

**Issue by AntonZorin** [begeekmyfriend/yasea#486]
Hi, is it possible to stream   ##output video in 4:3 aspect ratio? (640:480 for example)

**Comment by begeekmyfriend** [comment]
You may change the [parameters](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/demo/MainActivity.java#L75)

**Comment by AntonZorin** [comment]
If I set resolution exactly 640:480 and my camera support this resolution. Can yasea stream such resolution or will throw error?

**Comment by begeekmyfriend** [comment]
Why not have a try?
