### ISSUE TITLE
美颜

### ISSUE THREAD

**Issue by fly518420** [begeekmyfriend/yasea#49]
我想在推流的时候对数据进行美颜，可以直接对数据进行操作吗？如何绘制到预览界面呢？还是绘制到预览界面需要使用GLSurfaceView 这类的呢？

**Comment by begeekmyfriend** [comment]
有人也提及过GLSurfaceView，但我没用过，也没做过美颜。

**Comment by begeekmyfriend** [comment]
See [here](https://github.com/wuhaoyu1990/MagicCamera/issues/8).

**Comment by fly518420** [comment]
看到了 多谢

**Comment by begeekmyfriend** [comment]
Done [gpuimage](https://github.com/begeekmyfriend/yasea/tree/gpuimage)
