### ISSUE TITLE
最新版的DEMO无法录制视频

### ISSUE THREAD

**Issue by ecol0408** [begeekmyfriend/yasea#491]
最新版的DEMO无法录制视频，修改代码之后，录制的文件只有声音（断断续续）。

**Comment by begeekmyfriend** [comment]
确认吗？我试过，请重新clone一下试试

**Comment by ecol0408** [comment]
直接点击DEMO的录制按钮是无效的   ，但是推流那个按键是有效的。

**Comment by begeekmyfriend** [comment]
你这是需要自己定制的，不过简单，只要知道什么时候[启动编码器](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsPublisher.java#L167)即可

**Comment by ecol0408** [comment]
好的  谢谢
