### ISSUE TITLE
引入library出错

### ISSUE THREAD

**Issue by yaooort** [begeekmyfriend/yasea#494]
请问这个问题是什么导致的？我哪里配置错误？
java.lang.UnsatisfiedLinkError: No implementation found for void net.ossrs.yasea.SrsEncoder.setEncoderResolution(int, int) (tried Java_net_ossrs_yasea_SrsEncoder_setEncoderResolution and Java_net_ossrs_yasea_SrsEncoder_setEncoderResolution__II)

**Comment by begeekmyfriend** [comment]
你clone最新的repo试试？另外参考https://github.com/begeekmyfriend/yasea/issues/484

**Comment by yaooort** [comment]
还是不行，会不会是因为我项目cpp有两份导致的

**Comment by begeekmyfriend** [comment]
那你需要自己整合了，这个[地方](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/cpp/libenc/libenc.cc#L579)注意了吗？

**Comment by yaooort** [comment]
好的 。谢谢！我再看看
