### ISSUE TITLE
yasea有瘦脸功能吗?

### ISSUE THREAD

**Issue by Zziv** [begeekmyfriend/yasea#497]

**Comment by begeekmyfriend** [comment]
太高端了。。。

**Comment by Zziv** [comment]
@begeekmyfriend 首先，谢谢作者的回答，我还有些疑问，我把demo运行起来了，调起相机时为什么把我的脸照得拉伸的感觉。。。？这里有设置吗？

**Comment by begeekmyfriend** [comment]
采样分辨率设置，目前是360p，跟屏幕比例不一样，但必须是相机支持的，所以只能接近，不能相等，但是推流（输出）分辨率可以调整的
