### ISSUE TITLE
[Question] How to prevent CameraView frozen when start publishing?

### ISSUE THREAD

**Issue by hnvn** [begeekmyfriend/yasea#498]
When I start publishing a stream, CameraView is frozen in a second. I think it's not good for user experience. Is there any way to prevent it?

**Comment by begeekmyfriend** [comment]
Are you sure that this would happen on all devices?

**Comment by hnvn** [comment]
I'm not sure. I just tested on my Sony Z5.

**Comment by begeekmyfriend** [comment]
Not happen to me.

**Comment by hnvn** [comment]
It seems weird. I will examine it deeply and get back to you.
