### ISSUE TITLE
Can we add the ability to record video to phone while streaming

### ISSUE THREAD

**Issue by gouravd** [begeekmyfriend/yasea#5]
Is this possible? Where to start?

**Comment by begeekmyfriend** [comment]
Which kind of file format? h.264 or FLV?

**Comment by gouravd** [comment]
Ideally h.264 in mp4 format

**Comment by begeekmyfriend** [comment]
MP4...that is a great job...

**Comment by gouravd** [comment]
how about flv...would that be easier?

**Comment by begeekmyfriend** [comment]
Well [MP4Parser](https://github.com/sannies/mp4parser) is really a useful toolkit. It is worth a try.

**Comment by gouravd** [comment]
Will you give it a try, it will be a great feature missing from almost all other opensource rtmp streaming solution.

**Comment by begeekmyfriend** [comment]
This weekend, Labor Day. A new branch.

**Comment by gouravd** [comment]
Awesome...

On API 18+, we may encode with MediaMuxer,. On API 16, wrap H.264 as .mp4 using MP4Parser

This brings another point.. Is this library supposed to work reliably below 4.3 due to limitations of MediaCodec in Android below 4.3?

**Comment by gouravd** [comment]
Also Jcodec looks promising - its a pure java implementation as well

https://github.com/jcodec/jcodec

**Comment by begeekmyfriend** [comment]
Hey, the research on MP4 is in progress. I want to know that you want an MP4 file containing both AV track or only video track? If only video track needed, the implementation would be more easier because the lightweight [jcodec](https://github.com/jcodec/jcodec) will work around. If both AV tracks needed, the (mp4parser)[https://github.com/sannies/mp4parser] project is something heavy and hard to be cropped. I expect your final choice.

**Comment by gouravd** [comment]
The final locally saved file should have both the Video & Audio tracks. Because just the video or audio tracks would be useful.

The idea of having locally saved file is that if users are streaming some important moments of their life and the internet snaps or the server crashes, their moment is atleast saved locally, which they can upload later. This is very important for developing countries like in India with low internet penetration quality of internet.

**Comment by begeekmyfriend** [comment]
Hey I have found a Google official git site containing many external modules like [mp4parser](https://android.googlesource.com/platform/external/mp4parser) or [mp4v2](https://android.googlesource.com/platform/external/mp4v2) which both have good portability on Android and maintained by Google official staff. Actually they are the most reusable modules for Android.

However I have no idea which tag fits your project. If you cannot wait long time for yasea, you can DIY. Do not get me wrong, I just do not want to drag your project. By the way, any pull request are welcome.

**Comment by begeekmyfriend** [comment]
I have opened a new branch to support this [feature](https://github.com/begeekmyfriend/yasea/commit/b086328590148e6935cd6633337aedb5fd58b40c). It is written in complete Java and now has good performance and small size except that -- the recorded file can still not be played:P Anyway, there are signs that it begin to accommodate some capacities.

**Comment by begeekmyfriend** [comment]
The new [branch](https://github.com/begeekmyfriend/yasea/tree/mp4-storage) seems to work, though it is now only for recording and not have been merged into the master branch yet. And some MP4 parameters still need to be fixed that not every time it is playable. I will continue to work on it.

**Comment by begeekmyfriend** [comment]
One month since your requirement and now [I have really made it](https://github.com/begeekmyfriend/yasea/commit/c278d6e50feeb271bba276b8bb7aca481916bc38). Now it can record to MP4 at any time while streaming. And it can even support pause and resume function to complete an MP4 file which is playable, both on video and audio.

**Comment by gouravd** [comment]
A big thanks to you. Appreciate the great work.

I just integrated to a test app of mine. 

However I am facing an issue. I already have com.googlecode.mp4parser:isoparser 1.1.18. The structure for Boxes is different than the code used in this project. So there are few conflicts.

Since com.googlecode.mp4parser.isoparser is widely used can we use that as a base instead of the ones used in this project.

With some review I found that the problem lies in 

public class InterleaveChunkMdat implements Box

Class Box is very different in both the libraries.

**Comment by begeekmyfriend** [comment]
In fact I borrowed the code from [Telegram](https://github.com/DrKLO/Telegram/blob/master/TMessagesProj/src/main/java/org/telegram/messenger/video/MP4Builder.java#L167) whose implementation is reliable for instant recording.

**Comment by begeekmyfriend** [comment]
I advice you'd better change file `SrsMp4Muxer.java` to adapt your `mp4parser` library version. It will not be big job.

**Comment by gouravd** [comment]
Actually I also realized that. and it makes sense to use this. I would rather move out the isoparser.

BTW the addTrack function uses MediaFormat.MIMETYPE_VIDEO_AVC which is not available before API 21. 

This will make yasea incompatible with API 16-20. Could you please take a look if it can be adapted for API 16

**Comment by gouravd** [comment]
Can we also reopen this issue for better tracking. Assuming you will look into the API 16 compatibility part.

**Comment by begeekmyfriend** [comment]
In fact it is all right for API 18 in my test, but I have no API 16 device in hand.

**Comment by gouravd** [comment]
I am slightly confused - as per https://developer.android.com/reference/android/media/MediaFormat.html#KEY_MIME that constant MIMETYPE_VIDEO_AVC is not available below API 21

But as you correctly said, I also checked the CTS tests - https://android.googlesource.com/platform/cts/+/3661c33/tests/tests/media/src/android/media/cts/EncodeDecodeTest.java 

They are infact available for API 18. Not sure if they are for API 16.

We can add a condition that disables Recording below API18

**Comment by begeekmyfriend** [comment]
**SDK does not equal to API.** See [build.gradle](https://github.com/begeekmyfriend/yasea/blob/master/app/build.gradle), `compileSdkVersion` and `buildToolsVersion` are both 23+ which means Android Studio uses SDK 23 to compile and build the project and thus can be run in any compatible SDK device.

**Comment by gouravd** [comment]
From http://stackoverflow.com/questions/26694108/what-is-the-difference-between-compilesdkversion-and-targetsdkversion

compileSdkVersion

The compileSdkVersion is the version of the API the app is compiled against. This means you can use Android API features included in that version of the API (as well as all previous versions, obviously). If you try and use API 16 features but set compileSdkVersion to 15, you will get a compilation error. If you set compileSdkVersion to 16 you can still run the app on a API 15 device as long as your app's execution paths do not attempt to invoke any APIs specific to API 16.

So it means if you include API 21 specific code, it will compile well and run fine on API 21, 22, 23. It will also run fine on < API 21 as long as that piece of code is not called. 

I also checked the source of MediaFormat.java for Lollipop and Kitkat. i can see that MIMETYPE_VIDEO_AVC  is present in Lollipop but not in Kitkat.

https://github.com/android/platform_frameworks_base 

I believe the case for MediaFormat is different because this KEY MIMETYPE_VIDEO_AVC is simply a constant "video/avc" which is available since Android 3.0. The explicit mapping was made available in API 21.

**Comment by begeekmyfriend** [comment]
Well it seems that is really an issue for `KEY_MIMETYPE_VIDEO_AVC` in API 16, thought it is 'lucky' enough not crash on running...I would replace it with primitive string "video/avc".

**Comment by gouravd** [comment]
So it means video/avc and audio/mp4a-latm for MIMETYPE_VIDEO_AVC and MIMETYPE_AUDIO_AAC respectively

**Comment by begeekmyfriend** [comment]
Done https://github.com/begeekmyfriend/yasea/commit/e5179d4a312a3777a1d236b7115b209130321343
