### ISSUE TITLE
libyuv bug

### ISSUE THREAD

**Issue by tomerhatav** [begeekmyfriend/yasea#50]
Hi Leo,
Thanks again for an awesome library,
I just tested the new libyuv jni library on Nexus 5 and I think there's a small bug on the output frames.
A stripe of pixels on the left side of the frame that shows the right part of the frame.
Attached image below.
I marked the stripe in RED border

![yuvbug](https://cloud.githubusercontent.com/assets/12594464/16787493/59a35afa-48a5-11e6-8f51-c58fd8b4b2bc.jpg)

**Comment by begeekmyfriend** [comment]
That is strange. I have never found this phenomenon on other Android phone but Nexus. And that had never happened on Nexus until libyuv was added. I will continue to follow up this issue.

**Comment by begeekmyfriend** [comment]
Fixed https://github.com/begeekmyfriend/yasea/commit/f7f52cef57b492151d15dda5235fb63baac3db47
