### ISSUE TITLE
Lets create a wiki

### ISSUE THREAD

**Issue by zameelpichen** [begeekmyfriend/yasea#502]
I am interested in developing this project further by adding a wiki and a nicer ui, so that many programmers can have a ready-made version.

Waiting to know what you think.

Thanks.

**Comment by begeekmyfriend** [comment]
It is just a simple SDK and I do not think the amounts of features are enough create a Wiki. If you want to do more work on the project, any PR is welcome and to build your own fork is also a good job.

**Comment by zameelpichen** [comment]
ok, i guess, soon (in a week maybe) i will be coming with a PR.
