### ISSUE TITLE
Back camera upside down

### ISSUE THREAD

**Issue by zameelpichen** [begeekmyfriend/yasea#503]
1.Is there any way to solve this? which file could be the cause?

also, one more issue,
2.getting this error for now, when i click publish button
```

 No implementation found for void net.ossrs.yasea.SrsEncoder.setEncoderResolution(int, int) (tried Java_net_ossrs_yasea_SrsEncoder_setEncoderResolution and Java_net_ossrs_yasea_SrsEncoder_setEncoderResolution__II)
                                                                                     at net.ossrs.yasea.SrsEncoder.setEncoderResolution(Native Method)
```

**Comment by begeekmyfriend** [comment]
Sorry for late response. Did you clone the latest version. If it still does not work. Then I am afraid your device is with custom ROM and hard to be compatible with.

**Comment by zameelpichen** [comment]
Yes, it was a custom ROM issue.

Sorry, Its been so long. but this repo is still one of the main ones i forked....though i havent made a pull request.

**Comment by begeekmyfriend** [comment]
Thank you all the same...
