### ISSUE TITLE
re publishing to only audion data send..

### ISSUE THREAD

**Issue by dongmin2** [begeekmyfriend/yasea#505]
1. publish  : audio, video  send 
2. stop 
3. public : audio send 

why  republish after only audio packets are sent??

sorry i'm github use first 
i  don't know ...ㅜㅜ how submit  issue  
i'm how showing info you??

[first_publish.txt](https://github.com/begeekmyfriend/yasea/files/1247731/first_publish.txt)
[second_publish.txt](https://github.com/begeekmyfriend/yasea/files/1247732/second_publish.txt)

**Comment by begeekmyfriend** [comment]
Does it happen every time?

**Comment by dongmin2** [comment]
Yeah
It will work when you first publish it.
From the second publishing, however, only audio data is transmitted.

**Comment by dongmin2** [comment]
i'm One way to find

change sw / hw before publishing, it works.

ex) 
not work : first - publishing - stop - publishing  (only audio )
work : first - publishing -stop - change encoder - publishing (audio,video)

**Comment by dongmin2** [comment]
What I changed from source  fix to SCREEN_ORIENTATION_LANDSCAPE 

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);

**Comment by begeekmyfriend** [comment]
Fixed https://github.com/begeekmyfriend/yasea/commit/5ad694f61d81a5e2b6e600bfa1c8c8954c129d84
