### ISSUE TITLE
YUV image messed up

### ISSUE THREAD

**Issue by tomerhatav** [begeekmyfriend/yasea#51]
On nexus 5 libyuv
![bug](https://cloud.githubusercontent.com/assets/12594464/16808507/73550ab8-4925-11e6-8a32-652430fef04e.jpg)
 is working fine now, but on various other devices I get this frames

**Comment by begeekmyfriend** [comment]
Which devices?

**Comment by begeekmyfriend** [comment]
[Here](https://github.com/begeekmyfriend/yasea-apk) is the record of two versions of apk for test while v1.0 is out of libyuv. You may try it to see whether your devices are OK or not.

**Comment by tomerhatav** [comment]
Those are some of the devices that get those corrupted frames:
GT-I9505
LG Leon LTE
Samsung Galaxy J7 SM-J700M
Samsung Galaxy Grand Prime

**Comment by begeekmyfriend** [comment]
Do they work good with v1.0?

**Comment by tomerhatav** [comment]
You mean the version without libyuv? if so then yes, they all work fine with the PURE JAVA version.

**Comment by begeekmyfriend** [comment]
I see, the colour format may be quite different on these chips, Code in `SrsEncoder.java`

```java
switch (mVideoColorFormat) {
    case MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420Planar:
        return NV21ToI420(data, VPREV_WIDTH, VPREV_HEIGHT, true, 270);
    case MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420SemiPlanar:
        return NV21ToNV12(data, VPREV_WIDTH, VPREV_HEIGHT, true, 270);
    default:
        throw new IllegalStateException("Unsupported color format!");
    }
```

I have not tested `NV21ToI420` yet. It may be wrong process. I need some time to pick up a phone whose chip is like these above. Maybe on next Monday.

**Comment by begeekmyfriend** [comment]
Try this [commit](https://github.com/begeekmyfriend/yasea/commit/f876d486879e3d963721200861b79fe3c430fa37)

**Comment by tomerhatav** [comment]
Hi Leo,
I tried the latest commit.
It works fine with Nexus 5, and Galaxy S5.
That's the only pyhsical devices that I have, the other ones belongs to users that is using my live streaming platform.

on user with SAMSUNG GALAXY J2 has good result when using the BACK camera, but when switching to FRONT the result is this:
![bug](https://cloud.githubusercontent.com/assets/12594464/16891953/5e47ce1a-4b0c-11e6-8cd3-a9af9eefe0d1.jpg)

**Comment by begeekmyfriend** [comment]
Then try this [branch](https://github.com/begeekmyfriend/yasea/tree/nv12).

**Comment by tomerhatav** [comment]
maybe it has something to do with that?
// Note: the stride of resolution must be set as 16x for hard encoding with some chip like MTK

**Comment by begeekmyfriend** [comment]
Did you change the resolution? On MTK the resolution must be in 32x stride for the UV components are half of  the Y component.

**Comment by tomerhatav** [comment]
The resolution right now is height = 640 width = 360, but with the version without libyuv it was width = 384.

**Comment by begeekmyfriend** [comment]
Oh I see. I forgot that. It should be 384(32 * 12) or 352(32 * 11) for MTK while 352:640 is closer to 9:16.

**Comment by begeekmyfriend** [comment]
BTW, do not forget the latest [commit](https://github.com/begeekmyfriend/yasea/commit/9e13c6e2bc0f435cfb14e74e2c099baa42132d7e)

**Comment by tomerhatav** [comment]
Everything works fine now, the problem was with the width,
I set it to 352 instead of 360 and now it's good even on MTK chips.
So do you suggest that I'll use the master branch libyuv? or the yv12

**Comment by begeekmyfriend** [comment]
Of course the master branch for I have added soft encoding feature with x264 into it and the bug has been fixed.

**Comment by tomerhatav** [comment]
What is better soft encoding or hard encoding? what should I use?

**Comment by begeekmyfriend** [comment]
You can switch these two optional modes on UI as you like. Different phones have different effects.

**Comment by tomerhatav** [comment]
I have experience with JAVACV - FFmpegRecorder, I've used it before, and I think soft encoding is using too much cpu.
I liked more the PURE Java approach of your library.

**Comment by begeekmyfriend** [comment]
Just try the **pure x264** solution under which the CPU usage is down to 10% on ordinary phones in my test.

**Comment by tomerhatav** [comment]
Ok, I will try, but first I need to build it for more architectures.
armeabi armeabi-v7a x86 arm64-v8a
it seems like to integrated libyuv.cc inside libenc.cc, and when I'm trying to build it with NDK I get this error: 
![compile](https://cloud.githubusercontent.com/assets/12594464/16915499/7b14676a-4d00-11e6-8aa7-eff23f79a821.jpg)

**Comment by begeekmyfriend** [comment]
[commit](https://github.com/begeekmyfriend/yasea/commit/b87bc2d616620692ba0991c8bd4b729784ab0779) added.

**Comment by begeekmyfriend** [comment]
BTW, yasea currently only support `armeabi-v7a` so you should change such files below:
https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/libenc/jni/libx264/android_build.sh
https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/libenc/jni/libyuv/jni/Application.mk
https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/libenc/jni/Application.mk

**Comment by tomerhatav** [comment]
I changed the Application.mk files, but the build.sh is out of my scope, can you guide me how to add architectures to this file?

**Comment by begeekmyfriend** [comment]
Ah, the libx264 should be built on linux while the running host machine is windows.

**Comment by tomerhatav** [comment]
Ok thanks for the help, but I still get this bug when using your builds

"JNI ERROR (app bug): expected jboolean (0/1) but got value of -1611290112 as argument 3 to void net.ossrs.yasea.SrsEncoder.onSoftEncodedData(byte[], long, boolean)

**Comment by begeekmyfriend** [comment]
That is strange. the `is_key_frame` is a `bool` variable and only [assigned ](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/libenc/jni/libenc.cc#L240) by encoder. It must be `true` or `false` here.
