### ISSUE TITLE
always push stream a while,then stop itself(it confused me 2 days,help me,thanks)

### ISSUE THREAD

**Issue by lidanqing** [begeekmyfriend/yasea#510]
when it stopped,logcat like this:

E/RtmpConnection: Caught SocketException during write loop, shutting down: sendto failed: EPIPE (Broken pipe)
12-26 15:26:07.872 27527-27759/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 184
12-26 15:26:07.873 27527-27759/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 183
12-26 15:26:07.873 27527-27759/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Video, size: 2644
12-26 15:26:07.874 27527-27759/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 199
12-26 15:26:07.874 27527-27759/net.ossrs.yasea.demo D/RtmpConnection: wrote packet: RTMP Audio, size: 184
12-26 15:26:07.879 27527-27759/net.ossrs.yasea.demo I/SrsFlvMuxer: worker: send frame type=9, dts=83894, size=131072B
12-26 15:26:07.996 27527-27527/net.ossrs.yasea.demo I/SrsEncoder: stop aencoder
12-26 15:26:08.008 27527-27527/net.ossrs.yasea.demo I/SrsEncoder: stop vencoder
12-26 15:26:08.022 27527-27527/net.ossrs.yasea.demo I/SrsFlvMuxer: SrsFlvMuxer closed
12-26 15:26:08.025 27527-27527/net.ossrs.yasea.demo I/SrsMp4Muxer: SrsMp4Muxer closed
12-26 15:26:08.034 27527-9908/net.ossrs.yasea.demo D/RtmpConnection: closeStream(): setting current stream ID to 0
12-26 15:26:08.036 27527-9908/net.ossrs.yasea.demo W/System.err: java.net.SocketException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
12-26 15:26:08.058 27527-9908/net.ossrs.yasea.demo W/System.err:     at java.net.PlainSocketImpl.shutdownInput(PlainSocketImpl.java:365)
12-26 15:26:08.058 27527-9908/net.ossrs.yasea.demo W/System.err:     at java.net.Socket.shutdownInput(Socket.java:633)
12-26 15:26:08.058 27527-9908/net.ossrs.yasea.demo W/System.err:     at com.github.faucamp.simplertmp.io.RtmpConnection.shutdown(RtmpConnection.java:346)
12-26 15:26:08.058 27527-9908/net.ossrs.yasea.demo W/System.err:     at com.github.faucamp.simplertmp.io.RtmpConnection.close(RtmpConnection.java:317)
12-26 15:26:08.058 27527-9908/net.ossrs.yasea.demo W/System.err:     at com.github.faucamp.simplertmp.DefaultRtmpPublisher.close(DefaultRtmpPublisher.java:32)
12-26 15:26:08.058 27527-9908/net.ossrs.yasea.demo W/System.err:     at net.ossrs.yasea.SrsFlvMuxer.disconnect(SrsFlvMuxer.java:89)
12-26 15:26:08.058 27527-9908/net.ossrs.yasea.demo W/System.err:     at net.ossrs.yasea.SrsFlvMuxer.access$700(SrsFlvMuxer.java:21)
12-26 15:26:08.058 27527-9908/net.ossrs.yasea.demo W/System.err:     at net.ossrs.yasea.SrsFlvMuxer$2.run(SrsFlvMuxer.java:196)
12-26 15:26:08.058 27527-9908/net.ossrs.yasea.demo W/System.err:     at java.lang.Thread.run(Thread.java:818)
12-26 15:26:08.059 27527-9908/net.ossrs.yasea.demo W/System.err: Caused by: android.system.ErrnoException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
12-26 15:26:08.059 27527-9908/net.ossrs.yasea.demo W/System.err:     at libcore.io.Posix.shutdown(Native Method)
12-26 15:26:08.059 27527-9908/net.ossrs.yasea.demo W/System.err:     at libcore.io.ForwardingOs.shutdown(ForwardingOs.java:149)
12-26 15:26:08.059 27527-9908/net.ossrs.yasea.demo W/System.err:     at java.net.PlainSocketImpl.shutdownInput(PlainSocketImpl.java:363)
12-26 15:26:08.059 27527-9908/net.ossrs.yasea.demo W/System.err: 	... 8 more
12-26 15:26:08.060 27527-9908/net.ossrs.yasea.demo D/RtmpConnection: socket closed
12-26 15:26:08.060 27527-9908/net.ossrs.yasea.demo I/SrsFlvMuxer: worker: disconnect ok.

**Comment by begeekmyfriend** [comment]
This is the server end that cut off the connection. You may stream to public domain to verify yasea is all right.
> rtmp://ossrs.net/xxx/xxxxx

**Comment by lidanqing** [comment]
thanks, I'm testing a public domain.
But there was no operation on the server, why did this happen? 
Is it because of the weak network environment?

**Comment by lidanqing** [comment]
I just used "rtmp://ossrs.net/live/vczz" to test my demo, and the same error occurred.
Do you have any good Suggestions?thanks

**Comment by lidanqing** [comment]
It seems that when the network environment is good, the probability of this happening is smaller.

**Comment by begeekmyfriend** [comment]
Then it might be of that.

**Comment by lidanqing** [comment]
Is there a solution to this problem caused by poor network environment?thanks

**Comment by lidanqing** [comment]
where should I add a "reconnect" function? thanks

**Comment by begeekmyfriend** [comment]
`MainActivity.java` serves as the all kinds of exception listener and it also implements `SocketException` [handler](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/demo/MainActivity.java#L344) in which you can do your own reconnection funtion.

**Comment by lidanqing** [comment]
我在onRtmpSocketException中这样重连，似乎没有用，我直接把开启的流程放进来了。麻烦帮忙看下，谢谢！

@Override
    public void onRtmpSocketException(SocketException e) {
        if (isNetworkAvailable())
        {
            Toast.makeText(getApplicationContext(), "当前有可用网络！", Toast.LENGTH_LONG).show();
            mPublisher = new SrsPublisher(bgSurfaceView);
            mPublisher.setEncodeHandler(new SrsEncodeHandler(this));        //编码状态回调
            mPublisher.setRtmpHandler(new RtmpHandler(this));               //rtmp推流状态回调
            mPublisher.setRecordHandler(new SrsRecordHandler(this));
            mPublisher.setPreviewResolution(320, 240);
            mPublisher.setOutputResolution(240, 320);
            mPublisher.setVideoSmoothMode();
            mPublisher.startCamera();
            rtmpUrl = "rtmp://ossrs.net/live/vczz";
            mPublisher.startPublish(rtmpUrl);
            mPublisher.startCamera();
        }
        else
        {
            handleException(e);
            Toast.makeText(getApplicationContext(), "当前没有可用网络！", Toast.LENGTH_LONG).show();
        }
    }

**Comment by begeekmyfriend** [comment]
为什么要重新构造`mPublisher`？

**Comment by lidanqing** [comment]
这样处理呢，谢谢

@override
public void onRtmpSocketException(SocketException e) {
if (isNetworkAvailable())
{
Toast.makeText(getApplicationContext(), "当前有可用网络！", Toast.LENGTH_LONG).show();
rtmpUrl = "rtmp://ossrs.net/live/vczz";
mPublisher.startPublish(rtmpUrl);
mPublisher.startCamera();
}
else
{
handleException(e);
Toast.makeText(getApplicationContext(), "当前没有可用网络！", Toast.LENGTH_LONG).show();
}
}

**Comment by begeekmyfriend** [comment]
```java
mPublisher.stopPublish();
mPublisher.stopRecord();
```

**Comment by lidanqing** [comment]
谢谢
我要做的操作是：在网络环境差的时候产生socketException，然后判断当前是否有网络，如果有就进行重连，没有网络就执行handleException(e)。
您的意思是要先stopPublish()和stopRecord()后，再执行mPublisher.startPublish(rtmpUrl)和mPublisher.startCamera()吗

**Comment by begeekmyfriend** [comment]
网络有两个异常
一个是RTMP那边引发的`SocketException`，表示服务器断开了，这样的话重新推流即可；
还有是`SrsEncoder.java`那边引发的[onNetworkWeak](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/demo/MainActivity.java#L398)，这时需要你手动断开，你是否清楚你的情况属于哪种？

**Comment by lidanqing** [comment]
谢谢，应该是NetworkWeak导致的，服务端没有主动断开，而且用其他播放器还可以接收到服务端的流。
在网络环境很差的时候才会发生：E/RtmpConnection: Caught SocketException during write loop, shutting down: sendto failed: EPIPE (Broken pipe)
