### ISSUE TITLE
Request update 2.5 to 2.5.x

### ISSUE THREAD

**Issue by mcxycross** [begeekmyfriend/yasea#511]
Hi, thanks for the library.
Could you please update the library of version 2.5 with the all new changes?
I know there's the new version 2.6, but you provided the sources file of the libs instead of the .so file. The problem is that I worked in team and if I use the version 2.6, some of my teammate are not able to run the project because of the `ndk` problem. 
So, could you please update the version 2.5? or Is it possible just to copy the updated files from version to 2.6 to the version 2.5?

**Comment by begeekmyfriend** [comment]
What is the platform of NDK do your team use? In Yasea, I use `android-19`.
