### ISSUE TITLE
Android7.1的系统，wifi关掉后，直播还在继续，没有停止

### ISSUE THREAD

**Issue by lomoya90** [begeekmyfriend/yasea#517]
Android7.1的系统，wifi关掉后，直播还在继续，直至通道塞满后也不会自动关闭，而是要等到系统底层tcp协议栈自己实现的超时时间后，才会停止，有什么版本能够在这种情况下，自动停止直播吗？

**Comment by begeekmyfriend** [comment]
我把这个问题交给demo实现，方便你们自己定制，你可以在`MainActivity.java`中收到网络不佳的消息。

**Comment by lomoya90** [comment]
@begeekmyfriend 最终，用当前正在发送的帧时间戳和当前正在编码的这一帧时间戳差值大于30s，认定为网络异常，自动断开直播

**Comment by begeekmyfriend** [comment]
这也是一种方法

**Comment by lomoya90** [comment]
@begeekmyfriend 能用非阻塞socket来替换当前的阻塞socket实现吗？

**Comment by begeekmyfriend** [comment]
那你必须要用异步的库，而不是原生的IO了，但我要警告你，这会增大缓存导致延迟
