### ISSUE TITLE
Cannot live streaming audio only

### ISSUE THREAD

**Issue by euchael** [begeekmyfriend/yasea#524]
Using this :
mPublisher = new SrsPublisher((SrsCameraView) findViewById(R.id.glsurfaceview_camera));
mPublisher.setEncodeHandler(new SrsEncodeHandler(this));
mPublisher.setRtmpHandler(new RtmpHandler(this));
mPublisher.setRecordHandler(new SrsRecordHandler(this));
mPublisher.setSendAudioOnly(true);
mPublisher.startAudio();

got error : 

java.lang.NullPointerException: Attempt to invoke virtual method 'java.nio.ByteBuffer[] android.media.MediaCodec.getInputBuffers()' on a null object reference
                                                                           at net.ossrs.yasea.SrsEncoder.onGetPcmFrame(SrsEncoder.java:347)
                                                                            at net.ossrs.yasea.SrsPublisher$2.run(SrsPublisher.java:107)

working fine if i use  mPublisher.startcamera(); but i need live streaming audio only .

pls help . Thx

**Comment by begeekmyfriend** [comment]
Start encoder please...

**Comment by euchael** [comment]
thx for the response. i already add  mPublisher.startEncode(); 

but get another error : 

 java.lang.NullPointerException: Attempt to invoke virtual method 'java.nio.IntBuffer java.nio.ByteBuffer.asIntBuffer()' on a null object reference
                                                                             at net.ossrs.yasea.SrsCameraView$4.run(SrsCameraView.java:231)

can i live streaming audio only without using camera?

thx

**Comment by begeekmyfriend** [comment]
Do not call `mCameraView.enableEncoding` method if you want to send audio only. By the way, I hope you can read `SrsPublisher.java` before you start to customize on your own.

**Comment by llxxhm** [comment]
@begeekmyfriend 感谢作者，非常感谢，特别好用

**Comment by llxxhm** [comment]
@begeekmyfriend 　中国的骄傲
