### ISSUE TITLE
Simple questions

### ISSUE THREAD

**Issue by st4ycool** [begeekmyfriend/yasea#527]
1. Have you tested yasea on android emulator (API 19, 21, 22)? 
  1.1. I can't use hard encoder when streaming from emulator lower than api 23.
  1.2. I have video lag when recording my stream to the storage: video lags for about 1.5 seconds. But, on the remote stream there are no lag. It's happening because I click "record" few secs after start streaming?
2. If I need exactly H.264 ![level 4.1](https://user-images.githubusercontent.com/17159323/30648978-005f6414-9e28-11e7-988d-f4bd58d4d47f.jpg) settings stream, how can I check if every parameter is compatible and right?
3. My stream has audio lags and interrupts, how can i check that my audio is exactly 44.1 kHz and 128 kbps?

Thank you

**Comment by begeekmyfriend** [comment]
Do NOT test AV codec on emulator!

**Comment by st4ycool** [comment]
why closed? there are 2 more questions not about emulator.

**Comment by begeekmyfriend** [comment]
I do not answer testing on emulator.

**Comment by st4ycool** [comment]
It was only 1.1 and 1.2 about emulator.
Other two questions are about testing on devices.

**Comment by st4ycool** [comment]
It was only 1.1 and 1.2 about emulator.
Other two questions are about testing on devices.

**Comment by begeekmyfriend** [comment]
Sorry...

2. On most Android (I mean below Android 7.0) it only support baseline profile and there is no parameter for setting.

3. Unfortunately there is no guarantee for real setting on Android device layer even though there is interfaces provided. It is very likely that the codec does not support such parameters. As for your problem I suggest you can build local media server with SRS and play with FFplay to check whether it is issue of the server or the player end.
