### ISSUE TITLE
package名字改动？

### ISSUE THREAD

**Issue by ywj7931** [begeekmyfriend/yasea#53]
请问下我改动pacakage的名字的时候 报错（通过refactor）
JNI NewGlobalRef called with pending exception java.lang.ClassNotFoundException: Didn't find class "net.ossrs.yasea.SrsEncoder"
该怎么解决呢？

**Comment by begeekmyfriend** [comment]
手动改“net.ossrs.yasea.SrsEncoder”的前缀包名

**Comment by ywj7931** [comment]
@begeekmyfriend 谢谢回复 关键是找不到net.ossrs.yasea.SrsEncoder在哪里，找了全项目都没。

**Comment by begeekmyfriend** [comment]
[yuv.cc](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/libyuv/jni/yuv.cc) 只能手动改，没法传递，因为还没初始化。

**Comment by ywj7931** [comment]
@begeekmyfriend  我修改了好像没生效？我rebuild了也没生效
显示：
this file has been added after last project sync with gradle. please sync the project again for the NDK support to work properly.
NDK support is an experimental feature and all use cases are not yet supported

这是要用ndk重新编译c么

**Comment by begeekmyfriend** [comment]
是的，编译脚本（在Linux下）
```shell
#!/bin/sh
ndk-build
cp -rf libs/armeabi-v7a ../jniLibs
```
NDK推荐选r10

**Comment by Ashion-AS** [comment]
你好，我也是修改了包名导致报错，怎么修改下，需要重新编译吗？现在的版本好像没有yuv.cc了。03-13 10:18:39.887 28357-28357/com.focusdream.camera E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.focusdream.camera, PID: 28357
    java.lang.UnsatisfiedLinkError: No implementation found for void net.ossrs.camera.SrsEncoder.setEncoderResolution(int, int) (tried Java_net_ossrs_camera_SrsEncoder_setEncoderResolution and Java_net_ossrs_camera_SrsEncoder_setEncoderResolution__II)
        at net.ossrs.camera.SrsEncoder.setEncoderResolution(Native Method)
        at net.ossrs.camera.SrsEncoder.start(SrsEncoder.java:114)
        at net.ossrs.camera.SrsPublisher.startEncode(SrsPublisher.java:174)
        at net.ossrs.camera.SrsPublisher.startPublish(SrsPublisher.java:194)
        at com.focusdream.camera.MainActivity.LiveControl(MainActivity.java:494)
        at com.focusdream.camera.MainActivity.ParseIntent(MainActivity.java:324)
        at com.focusdream.camera.MainActivity.onNewIntent(MainActivity.java:219)

**Comment by begeekmyfriend** [comment]
Please notice this [line](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/cpp/libenc/libenc.cc#L579)

**Comment by begeekmyfriend** [comment]
Please notice this [line](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/cpp/libenc/libenc.cc#L579)

**Comment by Ashion-AS** [comment]
谢谢哦，那我用自己的包名，是不是得把库的包名改成我那个com/focusdream/camera。保持统一？

**Comment by Ashion-AS** [comment]
改包名后。重新rebuild。make project。可以了……，没有JNI经验，谢谢作者回复。
