### ISSUE TITLE
Can't connect to AzureMedia Live Streaming

### ISSUE THREAD

**Issue by ahmadtahirpk** [begeekmyfriend/yasea#532]
Hello everyone,

Has anybody been successfully able to connect using this awesome library to the Azure Media Services Live Streaming? I am always getting the "Network is weak" toast, even though it never even got connected to the server (The network is fine also).

Debugging allowed me to find out that input stream is always empty in the file RtmpHeader.java on line 231.

    `private void readHeaderImpl(InputStream in, RtmpSessionInfo rtmpSessionInfo) throws IOException {

        int basicHeaderByte = in.read();
        if (basicHeaderByte == -1) {
            throw new EOFException("Unexpected EOF while reading RTMP packet basic header");
        }`

But this does not happen on any other RTMP server. The AzureMedia live streaming also works fine on other apps. Is there any reason why is that?

Thank you very much.

**Comment by begeekmyfriend** [comment]
You may test it with `FFmpeg` to check your network connection
> ffmpeg -re -i test.mp4 -vcodec libx264 -acodec copy -f flv rtmp://host[:port]/app/stream

Node: be sure that you have got the authentication.
