### ISSUE TITLE
publisher layout hides

### ISSUE THREAD

**Issue by wedevelopyou** [begeekmyfriend/yasea#535]
Hi,

i am using yasea library for publishing a rtmp stream it is working fine . on the other hand i am using exoplayer at the same screen where my app is publishing stream as well as playing rtmp stream on exoplayer . but when stream is loaded in the player publisher screen hides in fact other widgets on the screen are visible as well as publisher container is visible but it does not show my preview . any suggestions what should i do . exoplayer extends frame layout .its urgent kindly review my problem

**Comment by begeekmyfriend** [comment]
UI widgets are not part of stream...
