### ISSUE TITLE
重连后，视频上传到YouTube，但是YouTube显示正在直播，视频数据一直不变

### ISSUE THREAD

**Issue by lomoya90** [begeekmyfriend/yasea#538]

**Comment by begeekmyfriend** [comment]
你不看logcat？

**Comment by lomoya90** [comment]
@begeekmyfriend 看了，一切正常，后来发现是youtube，每次重连成功后，必须发送sps数据和aac sequence header数据。针对Broken pipe错误，您有好的处理方法吗？

**Comment by begeekmyfriend** [comment]
sequence header的问题请重启编码器解决

**Comment by lomoya90** [comment]
@begeekmyfriend 重连后数据不变是因为每次重连后，都是重新开始的直播流程；那么aac的序列头中AudioSpecificConfig， 必须使用第一帧数据。而之前不是用的首帧数据，那么ytb服务器虽然收到了数据，但是处理不了。

**Comment by begeekmyfriend** [comment]
那可能是服务器那边没有完全断开，我不在现场也无法帮你调试
