### ISSUE TITLE
请问推流成功了但是没有音频是怎么回事？

### ISSUE THREAD

**Issue by ZhengwuFan** [begeekmyfriend/yasea#539]
请问推流成功了但是没有音频是怎么回事？

**Comment by begeekmyfriend** [comment]
你看一下logcat有没有Audio出来，如果有，那是播放器的事情，如果没有，你的AudioRecord可能被其它应用独占了

**Comment by ZhengwuFan** [comment]
您好，logcat是有Audio出来的，您说的播放器是指我播放流的播放器吗？可是相同的代码我在别的手机上是没问题的，只是在一款比较小众的机器上有这个问题。

**Comment by begeekmyfriend** [comment]
试着改变Audio参数，比如声道，注意采样率44.1KHz不要变

**Comment by ZhengwuFan** [comment]
大佬，我试过了改变参数这些，试了好多还不行，后来发现应该是降噪处理的问题，把SrsPublisher里的相关代码注释了就可以了。反馈一下，应该是我的这个测试机不支持降噪。
`        if (AcousticEchoCanceler.isAvailable()) {
            aec = AcousticEchoCanceler.create(mic.getAudioSessionId());
            if (aec != null) {
                aec.setEnabled(true);
            }
        }

        if (AutomaticGainControl.isAvailable()) {
            agc = AutomaticGainControl.create(mic.getAudioSessionId());
            if (agc != null) {
                agc.setEnabled(true);
            }
        }`

**Comment by begeekmyfriend** [comment]
安卓都是坑……
