### ISSUE TITLE
Help to compile only.

### ISSUE THREAD

**Issue by alejandroguille** [begeekmyfriend/yasea#540]
What are the steps to compile it?
Android studio does not let me compile it.
Thank you very much, sorry for my bad english.

**Comment by begeekmyfriend** [comment]
Try to fetch the latest Android Studio version.

**Comment by UbuntuLover** [comment]
如何编译这个库呢

**Comment by UbuntuLover** [comment]
我的最新的稳定版的AS

**Comment by begeekmyfriend** [comment]
@UbuntuLover Just load under the root directory with AS and run it.

**Comment by UbuntuLover** [comment]
@begeekmyfriend 谢谢。可以用NDK r13b编译吗

**Comment by begeekmyfriend** [comment]
应该可以

**Comment by UbuntuLover** [comment]
hi, really thanks your help. :+1: but when i import this project with Android Studio using "open an existing Android Studio project", then I append my NDK path to the file local.properties and click sync. But there are lots of errors like 


Error:(37) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Spinner.Underlined'.
Error:(36) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.RatingBar.Small'.
Error:(35) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.RatingBar.Indicator'.
Error:(34) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionBar.Menu'.
Error:(33) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Borderless.Colored'.
Error:(37) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Spinner.Underlined'.
Error:(36) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.RatingBar.Small'.
Error:(35) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.RatingBar.Indicator'.
Error:(34) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionBar.Menu'.
Error:(33) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Borderless.Colored'.
E:\GitHubOpenSources\yasea\library\build\intermediates\res\merged\debug\values-v23\values-v23.xml

**Comment by UbuntuLover** [comment]
I think I missed somewhere. Can you give some hints to compile this library? I think i can help to make a tutorial file about telling people how to compile this library and use it. (Especially for the beginners :) )

**Comment by UbuntuLover** [comment]
okay，problem solved. I should make the compile sdk version in build.gradle same as the root build.gradle Anyway, thanks a lot!

**Comment by alejandroguille** [comment]
Thank you very much, I was able to compile it with the latest version of android studio.

**Comment by UbuntuLover** [comment]
Android Studio 3.0 released yesterday. Glad to try it!
