### ISSUE TITLE
jni 编译报错

### ISSUE THREAD

**Issue by ICECHN** [begeekmyfriend/yasea#542]
$ $NDK/ndk-build
[armeabi-v7a] Cygwin         : Generating dependency file converter script
[armeabi-v7a] Compile++ thumb: enc <= libenc.cc
[armeabi-v7a] Compile++ thumb: yuv <= compare.cc
[armeabi-v7a] Compile++ thumb: yuv <= compare_common.cc
[armeabi-v7a] Compile++ thumb: yuv <= convert.cc
[armeabi-v7a] Compile++ thumb: yuv <= convert_argb.cc
[armeabi-v7a] Compile++ thumb: yuv <= convert_from.cc
[armeabi-v7a] Compile++ thumb: yuv <= convert_from_argb.cc
[armeabi-v7a] Compile++ thumb: yuv <= convert_to_argb.cc
[armeabi-v7a] Compile++ thumb: yuv <= convert_to_i420.cc
[armeabi-v7a] Compile++ thumb: yuv <= cpu_id.cc
[armeabi-v7a] Compile++ thumb: yuv <= planar_functions.cc
[armeabi-v7a] Compile++ thumb: yuv <= rotate.cc
[armeabi-v7a] Compile++ thumb: yuv <= rotate_any.cc
[armeabi-v7a] Compile++ thumb: yuv <= rotate_argb.cc
[armeabi-v7a] Compile++ thumb: yuv <= rotate_common.cc
[armeabi-v7a] Compile++ thumb: yuv <= row_any.cc
[armeabi-v7a] Compile++ thumb: yuv <= row_common.cc
jni/libyuv/source/row_common.cc: In function 'void libyuv::YuvPixel(uint8, uint8                                                                                                                           , uint8, uint8*, uint8*, uint8*, const libyuv::YuvConstants*)':
jni/libyuv/source/row_common.cc:1247:36: error: invalid types 'const uvec8 {aka                                                                                                                            __vector(16) unsigned char const}[int]' for array subscript
jni/libyuv/source/row_common.cc:1248:34: error: invalid types 'const uvec8 {aka                                                                                                                            __vector(16) unsigned char const}[int]' for array subscript
jni/libyuv/source/row_common.cc:1249:34: error: invalid types 'const uvec8 {aka                                                                                                                            __vector(16) unsigned char const}[int]' for array subscript
jni/libyuv/source/row_common.cc:1250:36: error: invalid types 'const uvec8 {aka                                                                                                                            __vector(16) unsigned char const}[int]' for array subscript
jni/libyuv/source/row_common.cc:1251:38: error: invalid types 'const vec16 {aka                                                                                                                            __vector(8) short int const}[int]' for array subscript
jni/libyuv/source/row_common.cc:1252:38: error: invalid types 'const vec16 {aka                                                                                                                            __vector(8) short int const}[int]' for array subscript
jni/libyuv/source/row_common.cc:1253:38: error: invalid types 'const vec16 {aka                                                                                                                            __vector(8) short int const}[int]' for array subscript
jni/libyuv/source/row_common.cc:1254:35: error: invalid types 'const vec32 {aka                                                                                                                            __vector(4) int const}[int]' for array subscript
/cygdrive/d/work/android/android-ndk-r10c/build/core/build-binary.mk:449: recipe                                                                                                                            for target 'obj/local/armeabi-v7a/objs/yuv/source/row_common.o' failed
make: *** [obj/local/armeabi-v7a/objs/yuv/source/row_common.o] Error 1

编译jni是报错，如上。
具体修改：
1、把cpp放到library根目录
2、删除 library gradle中
     //    externalNativeBuild {
//        ndkBuild {
//            path 'src/main/cpp/Android.mk'
//        }
//    }    

3、library目录下ndk-build

环境：
1、as 2.3
2、ndk r10c

**Comment by begeekmyfriend** [comment]
现在的版本一律使用ndk-bundle编译的，请用AS设置里面下载
