### ISSUE TITLE
运行Demo，JNI编译问题

### ISSUE THREAD

**Issue by SuperKung** [begeekmyfriend/yasea#544]
Error:FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':library:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process C:\Users\Huobull\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\AndroidProject\yasea\library\src\main\cpp\Android.mk NDK_APPLICATION_MK=D:\AndroidProject\yasea\library\src\main\cpp\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-21 NDK_OUT=D:/AndroidProject/yasea/library/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=D:\AndroidProject\yasea\library\build\intermediates\ndkBuild\debug\lib D:/AndroidProject/yasea/library/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/libenc.so}
  [armeabi-v7a] "Compile++ thumb": "enc <= libenc.cc"
  process_begin: CreateProcess(NULL, C:/Users/Huobull/AppData/Local/Android/Sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -MMD -MP -MF D:/AndroidProject/yasea/library/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/objs-debug/enc/libenc.o.d -gcc-toolchain C:/Users/Huobull/AppData/Local/Android/Sdk/ndk-bundle/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -g -target armv7-none-linux-androideabi21 -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-exceptions -fno-rtti -mthumb -O0 -UNDEBUG -fno-limit-debug-info -ID:/AndroidProject/yasea/library/src/main/cpp/libenc/../libyuv/include -ID:/AndroidProject/yasea/library/src/main/cpp/libenc/../libx264 -ID:/AndroidProject/yasea/library/src/main/cpp/libyuv/include -IC:/Users/Huobull/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/cxx-stl/system/include -ID:/AndroidProject/yasea/library/src/main/cpp/libenc -DANDROID -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security --sysroot C:/Users/Huobull/AppData/Local/Android/Sdk/ndk-bundle/build//../sysroot -isystem C:/Users/Huobull/AppData/Local/Android/Sdk/ndk-bundle/build//../sysroot/usr/include/arm-linux-androideabi -c D:/AndroidProject/yasea/library/src/main/cpp/libenc/libenc.cc -o D:/AndroidProject/yasea/library/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/objs-debug/enc/libenc.o, ...) failed.
  make (e=2): ?????????????????
  make: *** [D:/AndroidProject/yasea/library/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/objs-debug/enc/libenc.o] Error 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

**Comment by begeekmyfriend** [comment]
please use ndk-bundle through AS setting menu.

**Comment by SuperKung** [comment]
ndk已经安装了啊

**Comment by begeekmyfriend** [comment]
把AS升级到3.0，`ndk-bundle`也升级一下

**Comment by SuperKung** [comment]
都是最新的了

**Comment by begeekmyfriend** [comment]
重新clone一下repo

**Comment by SuperKung** [comment]
可能是我这里环境问题，怎么也编译不了，能帮忙提供一下编译好的so文件吗？用so文件应该也是可以用的吧？
