### ISSUE TITLE
Youtube

### ISSUE THREAD

**Issue by NasinLin** [begeekmyfriend/yasea#546]
請問rtmp server 可以使用 Youtube 的直播 (rtmp) 去代替server嗎 >

**Comment by begeekmyfriend** [comment]
当然可以，只要RTMP URL正确即可（得到许可），你也可以用ffmpeg推流验证

ffmpeg -re -i test.mp4 -vcodec libx264 -acodec libfdk-aac -f flv
rtmp://host[:port]/app/stream[?xx=xx;xx=xxx]

2017-11-10 9:14 GMT+08:00 NasinLin <notifications@github.com>:

**Comment by NasinLin** [comment]
請問大神，compile 的版本 (buildToolsVersion) 一定要使用到26 版本嗎

**Comment by begeekmyfriend** [comment]
没有必要，只要适配你自己的环境就好，但API必须>=21

这个项目还有个android-21的分支，针对旧NDK编译的native代码，不支持arm64

2017-11-10 10:23 GMT+08:00 NasinLin <notifications@github.com>:

**Comment by NasinLin** [comment]
版主，我有編譯成功，然後我搭建的server 為 red5 ，我ip也設相同路徑，手機顯示狀況為 connecting -> connected ，但是red5 無法看到即時串流，請問您有發生過此狀況嗎 ?

**Comment by begeekmyfriend** [comment]
see your logcat. If any, then it is the issue of your server or player.
