### ISSUE TITLE
推流一段时间后   很短  自动退出推流界面了  并且没有显示异常

### ISSUE THREAD

**Issue by cdcdec** [begeekmyfriend/yasea#549]
推流一段时间后（视频） 调用了Connecting  Connected   视频画面不动   过一会后  自动退出推流界面了  并且没有显示异常

**Comment by begeekmyfriend** [comment]
你跑的什么版本？logcat有推流显示吗？

**Comment by cdcdec** [comment]
11-11 11:29:17.574 17968-18033/net.ossrs.yasea.demo D/Surface: Surface::setBuffersDimensions(this=0x7f99a08600,w=800,h=1280)
11-11 11:29:18.069 17968-17968/net.ossrs.yasea.demo I/SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = net.ossrs.yasea.SrsCameraView{613beb9 V.E..... ........ 0,0-800,1143 #7f070037 app:id/glsurfaceview_camera}
11-11 11:29:18.072 17968-18033/net.ossrs.yasea.demo D/Surface: Surface::setBuffersDimensions(this=0x7f99a08600,w=800,h=1280)
11-11 11:29:18.582 17968-17968/net.ossrs.yasea.demo I/SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = net.ossrs.yasea.SrsCameraView{613beb9 V.E..... ........ 0,0-800,1143 #7f070037 app:id/glsurfaceview_camera}
11-11 11:29:18.585 17968-18033/net.ossrs.yasea.demo D/Surface: Surface::setBuffersDimensions(this=0x7f99a08600,w=800,h=1280)
11-11 11:29:18.700 17968-18072/net.ossrs.yasea.demo D/ACodec: [OMX.MTK.VIDEO.ENCODER.AVC] onOutputBufferDrained ID f50da880
11-11 11:29:18.700 17968-18072/net.ossrs.yasea.demo D/ACodec: [OMX.MTK.VIDEO.ENCODER.AVC] onInputBufferFilled ID 0xf52a0100 w/ time 686053 eos 0 mode 1 err 0
11-11 11:29:18.707 17968-18082/net.ossrs.yasea.demo D/AudioTrackShared: front(0x24bf), mIsOut 0, avail 941, mFrameCount 8192, filled 941
11-11 11:29:18.708 17968-18068/net.ossrs.yasea.demo D/ACodec: [OMX.google.aac.encoder] onInputBufferFilled ID 0xf52a02e0 w/ time 13537067 eos 0 mode 1 err 0
11-11 11:29:18.748 17968-18068/net.ossrs.yasea.demo E/IOMX: binder transaction failed: -32
11-11 11:29:18.748 17968-18068/net.ossrs.yasea.demo A/ACodec: frameworks/av/media/libstagefright/ACodec.cpp:6923 CHECK_EQ( mCodec->mOMX->emptyBuffer( mCodec->mNode, bufferID, 0, buffer->size(), flags, timeUs),(status_t)OK) failed: -32 vs. 0
11-11 11:29:18.748 17968-18068/net.ossrs.yasea.demo A/libc: Fatal signal 5 (SIGTRAP), code 1 in tid 18068 (MediaCodec_loop)
11-11 11:29:18.749 17968-17987/net.ossrs.yasea.demo W/CameraBase: mediaserver's remote binder Camera object died
11-11 11:29:18.749 17968-18059/net.ossrs.yasea.demo D/AudioTrackShared: front(0x2800), mIsOut 0, binderDied() FUTEX_WAKE
11-11 11:29:18.750 17968-18059/net.ossrs.yasea.demo I/BufferQueueProducer: [unnamed-17968-0](this:0x7f8f302000,id:0,api:4,p:-1,c:17968) disconnect(P): api 4
11-11 11:29:18.750 17968-18059/net.ossrs.yasea.demo I/BufferQueueConsumer: [unnamed-17968-0](this:0x7f8f302000,id:0,api:4,p:-1,c:17968) getReleasedBuffers: returning mask 0xffffffffffffffff
11-11 11:29:18.750 17968-18059/net.ossrs.yasea.demo D/GraphicBuffer: unregister, handle(0x7f93b74160) (w:960 h:540 s:960 f:0x32315659 u:0x000102)
11-11 11:29:18.759 17968-17987/net.ossrs.yasea.demo W/CameraBase: Camera service died!
11-11 11:29:18.760 17968-17987/net.ossrs.yasea.demo W/AudioSystem: AudioPolicyService server died!
11-11 11:29:18.760 17968-17987/net.ossrs.yasea.demo W/AudioEffect: IEffect died
11-11 11:29:18.760 17968-17968/net.ossrs.yasea.demo I/CameraFramework: handleMessage: 1
11-11 11:29:18.760 17968-17987/net.ossrs.yasea.demo W/AudioEffects-JNI: EVENT_ERROR
11-11 11:29:18.760 17968-18072/net.ossrs.yasea.demo E/ACodec: OMX/mediaserver died, signalling error!
11-11 11:29:18.760 17968-18072/net.ossrs.yasea.demo E/ACodec: signalError(omxError 0x8000100d, internalError -32)
11-11 11:29:18.760 17968-17987/net.ossrs.yasea.demo W/AudioEffect: IEffect died
11-11 11:29:18.760 17968-17987/net.ossrs.yasea.demo W/AudioEffects-JNI: EVENT_ERROR
11-11 11:29:18.760 17968-17968/net.ossrs.yasea.demo E/CameraFramework: Error 100
11-11 11:29:18.760 17968-18071/net.ossrs.yasea.demo E/MediaCodec: Codec reported err 0xffffffe0, actionCode 0, while in state 6
11-11 11:29:18.760 17968-18072/net.ossrs.yasea.demo D/ACodec: [OMX.MTK.VIDEO.ENCODER.AVC] onInputBufferFilled ID 0xf50da280 w/ time -1 eos 0 mode 0 err 0
11-11 11:29:18.761 17968-18072/net.ossrs.yasea.demo D/ACodec: [OMX.MTK.VIDEO.ENCODER.AVC] onInputBufferFilled ID 0xf40268e0 w/ time -1 eos 0 mode 0 err 0
11-11 11:29:18.761 17968-18072/net.ossrs.yasea.demo D/ACodec: [OMX.MTK.VIDEO.ENCODER.AVC] onInputBufferFilled ID 0xf50da400 w/ time -1 eos 0 mode 0 err 0
11-11 11:29:18.761 17968-18072/net.ossrs.yasea.demo D/ACodec: [OMX.MTK.VIDEO.ENCODER.AVC] onInputBufferFilled ID 0xf52a0160 w/ time -1 eos 0 mode 0 err 0
11-11 11:29:18.761 17968-18072/net.ossrs.yasea.demo D/ACodec: [OMX.MTK.VIDEO.ENCODER.AVC] onInputBufferFilled ID 0xf4026880 w/ time -1 eos 0 mode 0 err 0
11-11 11:29:18.761 17968-18072/net.ossrs.yasea.demo D/ACodec: [OMX.MTK.VIDEO.ENCODER.AVC] onInputBufferFilled ID 0xf50da3a0 w/ time -1 eos 0 mode 0 err 0
11-11 11:29:18.761 17968-18072/net.ossrs.yasea.demo D/ACodec: [OMX.MTK.VIDEO.ENCODER.AVC] onInputBufferFilled ID 0xf50da640 w/ time -1 eos 0 mode 0 err 0
11-11 11:29:18.761 17968-18072/net.ossrs.yasea.demo D/ACodec: [OMX.MTK.VIDEO.ENCODER.AVC] onInputBufferFilled ID 0xf52a01c0 w/ time -1 eos 0 mode 0 err 0
11-11 11:29:18.763 17968-18059/net.ossrs.yasea.demo D/GraphicBuffer: unregister, handle(0x7f93b742a0) (w:960 h:540 s:960 f:0x32315659 u:0x000102)
11-11 11:29:18.764 17968-18059/net.ossrs.yasea.demo D/GraphicBuffer: unregister, handle(0x7f93b74340) (w:960 h:540 s:960 f:0x32315659 u:0x000102)
11-11 11:29:18.764 17968-18059/net.ossrs.yasea.demo D/GraphicBuffer: unregister, handle(0x7f8f0743e0) (w:960 h:540 s:960 f:0x32315659 u:0x000102)
11-11 11:29:18.766 17968-17986/net.ossrs.yasea.demo D/AudioSystem: CALL STACK : - binderDied
11-11 11:29:29.780 17968-18079/net.ossrs.yasea.demo W/AudioRecord: dead IAudioRecord, creating a new one from processAudioBuffer()
11-11 11:29:29.780 17968-18079/net.ossrs.yasea.demo D/AudioRecord: openRecord_l

刚下载你的demo

**Comment by cdcdec** [comment]
点击那个PUBLISH按钮后 ，会调用Connecting Connected   画面就卡住了 过一会后  程序退出

**Comment by cdcdec** [comment]
下载你提供的yasea-v2.6.1.apk也出现同样的问题：点击那个PUBLISH按钮后 ，画面就卡住了 过一会后 程序退出

**Comment by begeekmyfriend** [comment]
粗看感觉想`MediaCodec`安卓平台适配的问题，你自己编译过么？

**Comment by cdcdec** [comment]
直接把你的工程引入的

**Comment by begeekmyfriend** [comment]
个人判定是你手机（还是其它安卓设备）的ROM定制了，跟`MediaCodec`包不兼容

**Comment by begeekmyfriend** [comment]
demo是否正常运行？
