### ISSUE TITLE
Camera2 API

### ISSUE THREAD

**Issue by tomerhatav** [begeekmyfriend/yasea#55]
Hi Lee,
Any plans to add camera2 support?

**Comment by begeekmyfriend** [comment]
Yasea is aimed to Android mini API 16 which is below the mini API level of `Camera2`. So I think it will not developed on master branch.

**Comment by begeekmyfriend** [comment]
A compromise solution is to set `targetSdkVersion` to 22 in `build.gradle`. And then you can run the application on any device with `Camera` class library.
