### ISSUE TITLE
是否能在未开启直播时进行视频录制？

### ISSUE THREAD

**Issue by MissFang** [begeekmyfriend/yasea#551]
录制是本地高清录像，而直播时传输较低画质的视频，是否能做到呢？

**Comment by begeekmyfriend** [comment]
See #533

**Comment by MissFang** [comment]
对这方面了解不多，能否详细的说说具体该怎么去做？

**Comment by begeekmyfriend** [comment]
你要直播和录制同时进行，只能用同一种编码设置，除非你把采样图像拷贝一份，编码两次

**Comment by MissFang** [comment]
我也是那么想的，但是对视频这方面的不熟悉导致我出现很多的问题而解决不了，能否提供一个修改后的事例代码呢，万分感谢。

**Comment by MissFang** [comment]
还有一个问题，当调用stopPublish()后进入的是同步操作，如果网络不好的情况下整个程序就会卡死，这里能做成异步处理吗？

**Comment by begeekmyfriend** [comment]
断开明明是[异步](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsFlvMuxer.java#L192)

**Comment by MissFang** [comment]
可是运行Demo的时候断开确实是会有卡死的现象，能否查看一下是什么原因呢

**Comment by yiyunchong** [comment]
老师 连接FMS服务器的时候 publishType参数值传record或者append FMS服务器端为什么不录制呢
