### ISSUE TITLE
Unable to load NDK

### ISSUE THREAD

**Issue by Muvidevelopers** [begeekmyfriend/yasea#556]
When I tries to use the library in Android Studio it is showing error like this:
Error while executing process C:\Users\Muvi Guest\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\AndroidStudioProjects\Live-Stream\XPMETest-master\Xmpe\library\src\main\cpp\Android.mk NDK_APPLICATION_MK=D:\AndroidStudioProjects\Live-Stream\XPMETest-master\Xmpe\library\src\main\cpp\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-21 NDK_OUT=D:/AndroidStudioProjects/Live-Stream/XPMETest-master/Xmpe/library/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=D:\AndroidStudioProjects\Live-Stream\XPMETest-master\Xmpe\library\build\intermediates\ndkBuild\debug\lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}

**Comment by erwanlbp** [comment]
Hello, 
Did you solved the issue ? I got the same and I can't manage to solve it
