### ISSUE TITLE
Adaptive streaming

### ISSUE THREAD

**Issue by sdebasek** [begeekmyfriend/yasea#56]
I saw some code on SetPeerBandwidth.java. Is it possible to set any adaptive streaming with this library ie. change bitrate or resolution on the go?

**Comment by begeekmyfriend** [comment]
Sorry, there is no plan to design Yasea as SDK. I would like users to custom themselves.

**Comment by begeekmyfriend** [comment]
I have no plan to design Yasea as an SDK and I would rather users custom it by themselves.

**Comment by begeekmyfriend** [comment]
Now supported https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/MainActivity.java#L73
