### ISSUE TITLE
问题关于Acoustic echo cancellation and automatic gain control support.

### ISSUE THREAD

**Issue by autismbug92** [begeekmyfriend/yasea#567]
视频通话的场景，推流的音频输入中会带上扬声器中播放的声音。
这个属于回声消除的场景吗？
如果是，项目支持的回声消除要怎么使用，还是自动就处理了。

**Comment by begeekmyfriend** [comment]
[SrsPublisher.java](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsPublisher.java#L4-L5)

**Comment by autismbug92** [comment]
找到了，谢谢你
