### ISSUE TITLE
回调正常但是播放器没有图像

### ISSUE THREAD

**Issue by maxdylan** [begeekmyfriend/yasea#568]
我是源数据就是h264的，MediaCodec.BufferInfo不知道怎么初始化，因为涉及到帧类型不同，那个flags不太确定怎么设置，presentationTimeUs只是一个递增的时间，sps和pps数据是当做单独一帧数据喂给他的，不知道为什么，回调是正常的，但是用vlc播放器播放不出来，等了很长时间后播放出来一帧，卡在那里就不动了，不太确定是哪里的问题，能帮我简单分析一下么？万分感谢

01-04 17:51:27.598 D: yasea==onRtmpConnecting: Connecting
01-04 17:51:27.891 D: yasea==onRtmpConnected: Connected
01-04 17:51:28.037 D: yasea==onRtmpVideoStreaming // 这条log太多，没有全部粘贴过来
01-04 17:51:28.879 D: yasea==onRtmpVideoFpsChanged: 0.1317656876659081
01-04 17:51:28.879 D: yasea==onRtmpVideoBitrateChanged: 881.0073486822058
前面部分log是这样，后面会经常打这样的log
01-04 17:51:32.491 D: yasea==onRtmpVideoFpsChanged: 27.08803611738149
01-04 17:51:32.491 D: yasea==onRtmpVideoBitrateChanged: 233002.25733634311

**Comment by begeekmyfriend** [comment]
只能打印对比着看，比如硬编码或者x264出来的，`BufferInfo`对比着看一下，能否适配自己的数据。你可以用第三方ffplay拉流试试看，VLC坑很多。

**Comment by maxdylan** [comment]
我想问一下，onRtmpVideoStreaming这个回调是推流成功的时候的回调么？如果推流失败或出现其他问题的时候回调那几个exception的接口么？万分感谢

**Comment by begeekmyfriend** [comment]
走到这一步[mHandler.notifyRtmpVideoStreaming](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L451)说明正在推流，你的数据格式都没有问题。拉不到流就用ffplay验证。如果连接发生意外，可以看`mHandler`在`RtmpConnection.java`的其它通知
