### ISSUE TITLE
Audio mute and videoResolution

### ISSUE THREAD

**Issue by iSinch** [begeekmyfriend/yasea#57]
Hey,bro :)
Thanks for your project.
Could you tell me,please.
What about Audio mute ? How to set another video/camera resolution ?

**Comment by begeekmyfriend** [comment]
Audio mute: Do not send PCM data to encoder.
Video resolution: There is no SDK interface currently. You need to change theses [const values](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/SrsEncoder.java#L23-L26).
