### ISSUE TITLE
Echo cancellation in Yasea

### ISSUE THREAD

**Issue by gouravd** [begeekmyfriend/yasea#58]
I was testing yasea along with Nimble streamer for 1-1 chat. Everything works fine except that the voice echoes. Can we implement echo cancellation?

**Comment by begeekmyfriend** [comment]
You may try [sipdroid](http://sipdroid.org/) project. The echo cancellation module is called [speex](https://github.com/i-p-tel/sipdroid/tree/master/jni/speex-1.2rc1)

**Comment by begeekmyfriend** [comment]
Moreover the new version of flash player has integrated AEC(speex). See this [article](http://www.adobe.com/devnet/flashplayer/articles/acoustic-echo-cancellation.html) or this [sample code](http://mrbinitie.blogspot.sg/2011/03/implementing-acoustic-echo-suppression.html)

**Comment by begeekmyfriend** [comment]
All in all, it needs support from RTMP server and player, not one-sided publisher.

**Comment by begeekmyfriend** [comment]
Supported https://github.com/begeekmyfriend/yasea/commit/723c792d83ae87f05b7d8a9365bf44449cc0d9c6
