### ISSUE TITLE
当网络状况不好或断网后，有做类似重连的操作么？

### ISSUE THREAD

**Issue by maxdylan** [begeekmyfriend/yasea#580]
跟了源码跟了半天，只看到了socketException 和 IoException相关部分，是走了这两个异常之后，连接就断开了不会重连了么？我尝试了断网，然后再联网，播放器没有图像，还有一个小问题，ffplay播放rtmp的流直接执行 ffplay rtmp://ssssss  就行了么？多谢多谢

**Comment by begeekmyfriend** [comment]
你在哪里做的断开重连？`stopPublish`和`startPublish`。ffplay就是这样使用

**Comment by maxdylan** [comment]
我没有使用SrsPublisher这个类，也没有做断开重连的操作，只是断了一下无线网络，然后又开启了无线网络，刚才又看了一下您的demo，在handleException的时候就stopPublish了，也就是说断网重连（或是异常重连）这块需要我自己来实现，应该是这样吧？还有就是网络状态不好的时候也是会走这个handleException，也是和断网处理方式类似么？麻烦您了

**Comment by begeekmyfriend** [comment]
对的，demo里没有重连，你可以亲自试试

**Comment by maxdylan** [comment]
多谢
