### ISSUE TITLE
直播过程中延时越来越长

### ISSUE THREAD

**Issue by maxdylan** [begeekmyfriend/yasea#581]
我用rtmp协议直播，以前没有推audio数据，延时在5-7秒左右，比较稳定，后来加推了audio数据，延时以肉眼可见的速度增加，二十秒左右延时增加了大概一秒多，我想问一下sdk里面有没有类似控制的方法（比如丢掉一些包）？或者这个问题应该从哪个角度分析一下？多谢指教，万分感谢

**Comment by begeekmyfriend** [comment]
Yasea缓存是不会超过2s的，满了会在编码器之前就丢掉，见[这里](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L376)，你需要排查其它因素。

**Comment by maxdylan** [comment]
我是直接获取的h264数据，跳过了SrsPublisher，所以应该是没用到SrsEncoder

**Comment by begeekmyfriend** [comment]
那你就需要自己处理缓存队列了，`SrsFlvMuxer.java`里
