### ISSUE TITLE
想请教您一个问题，关于vlc和ffplay

### ISSUE THREAD

**Issue by maxdylan** [begeekmyfriend/yasea#582]
我在这个Issues也问了您很多问题了，承蒙指教，先行道谢。
最近测试发现同样的推流逻辑，用ffplay和vlc播放rtmp流表现不一样，ffplay播放的延时随时间推移越来越久，从最初的3秒左右延时涨到了10几秒20几秒还在继续增加，但是声音播放正常，不卡顿；用vlc播放的时候延时比较稳定，在3秒左右，但是声音听不完整，总是一卡一卡的，我是直接获取的h264流使用flvmuxer推流，音频也是直接推的，没有走publisher和encoder，您能帮忙指教一下是哪里的问题么？不胜感激

**Comment by begeekmyfriend** [comment]
这属于播放器内部逻辑，一般来说ffplay效果更好，vlc维护得不太好，具体没有研究过播放器的逻辑，也许ffplay内部维护了一个缓存导致延时。不过对于推流端来说，缓存维持在2s左右数据量，超过就会[丢弃编码](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L376)，所以不可能是延迟的源头。

**Comment by llxxhm** [comment]
那是ffplay把延迟的都累积下来了, 所以延时越来越大; 而VLC没累积, 丢弃了延迟的数据, 就显得一卡一卡的, 这是播放器的问题, 和推流没有关系
