### ISSUE TITLE
华为荣耀6 Android 4.4.2 切后置摄像头崩溃

### ISSUE THREAD

**Issue by xiongxianwei90** [begeekmyfriend/yasea#585]
用的 2.6.1 版本

01-24 18:38:18.110 10447-10447/net.ossrs.yasea.demo E/BufferQueue: [unnamed-10447-0] cancelBuffer: slot 4 is not owned by the client (state=3)
01-24 18:38:18.110 10447-10447/net.ossrs.yasea.demo E/BufferQueue: [unnamed-10447-0] cancelBuffer: slot 5 is not owned by the client (state=2)
01-24 18:38:18.110 10447-10447/net.ossrs.yasea.demo E/BufferQueue: [unnamed-10447-0] cancelBuffer: slot 0 is not owned by the client (state=0)
01-24 18:38:18.110 10447-10447/net.ossrs.yasea.demo E/BufferQueue: [unnamed-10447-0] cancelBuffer: slot 1 is not owned by the client (state=0)
01-24 18:38:18.110 10447-10447/net.ossrs.yasea.demo E/BufferQueue: [unnamed-10447-0] cancelBuffer: slot 2 is not owned by the client (state=0)
01-24 18:38:18.110 10447-10447/net.ossrs.yasea.demo E/BufferQueue: [unnamed-10447-0] cancelBuffer: slot 3 is not owned by the client (state=0)
01-24 18:38:18.110 10447-10447/net.ossrs.yasea.demo E/BufferQueue: [unnamed-10447-0] cancelBuffer: slot 4 is not owned by the client (state=3)
01-24 18:38:18.110 10447-10447/net.ossrs.yasea.demo E/BufferQueue: [unnamed-10447-0] cancelBuffer: slot 5 is not owned by the client (state=2)
01-24 18:38:18.110 10447-10447/net.ossrs.yasea.demo E/BufferQueue: [unnamed-10447-0] cancelBuffer: slot 6 is not owned by the client (state=0)
01-24 18:38:18.110 10447-10447/net.ossrs.yasea.demo E/BufferQueue: [unnamed-10447-0] cancelBuffer: slot 7 is not owned by the client (state=0)
01-24 18:38:18.770 10447-10447/net.ossrs.yasea.demo E/BufferQueue: [unnamed-10447-0] cancelBuffer: slot 2 is not owned by the client (state=3)
01-24 18:38:18.770 10447-10447/net.ossrs.yasea.demo E/BufferQueue: [unnamed-10447-0] cancelBuffer: slot 4 is not owned by the client (state=2)
01-24 18:38:18.770 10447-10447/net.ossrs.yasea.demo E/BufferQueue: [unnamed-10447-0] cancelBuffer: slot 0 is not owned by the client (state=0)
01-24 18:38:18.770 10447-10447/net.ossrs.yasea.demo E/BufferQueue: [unnamed-10447-0] cancelBuffer: slot 1 is not owned by the client (state=0)
01-24 18:38:18.770 10447-10447/net.ossrs.yasea.demo E/BufferQueue: [unnamed-10447-0] cancelBuffer: slot 2 is not owned by the client (state=3)
01-24 18:38:18.770 10447-10447/net.ossrs.yasea.demo E/BufferQueue: [unnamed-10447-0] cancelBuffer: slot 3 is not owned by the client (state=0)
01-24 18:38:18.770 10447-10447/net.ossrs.yasea.demo E/BufferQueue: [unnamed-10447-0] cancelBuffer: slot 4 is not owned by the client (state=2)
01-24 18:38:18.770 10447-10447/net.ossrs.yasea.demo E/BufferQueue: [unnamed-10447-0] cancelBuffer: slot 5 is not owned by the client (state=0)
01-24 18:38:18.770 10447-10447/net.ossrs.yasea.demo E/BufferQueue: [unnamed-10447-0] cancelBuffer: slot 6 is not owned by the client (state=0)
01-24 18:38:18.770 10447-10447/net.ossrs.yasea.demo E/BufferQueue: [unnamed-10447-0] cancelBuffer: slot 7 is not owned by the client (state=0)
01-24 18:38:26.540 10447-10447/net.ossrs.yasea.demo E/BufferQueue: [unnamed-10447-0] cancelBuffer: slot 2 is not owned by the client (state=3)
01-24 18:38:26.540 10447-10447/net.ossrs.yasea.demo E/BufferQueue: [unnamed-10447-0] cancelBuffer: slot 3 is not owned by the client (state=2)
01-24 18:38:26.540 10447-10447/net.ossrs.yasea.demo E/BufferQueue: [unnamed-10447-0] cancelBuffer: slot 0 is not owned by the client (state=0)
01-24 18:38:26.540 10447-10447/net.ossrs.yasea.demo E/BufferQueue: [unnamed-10447-0] cancelBuffer: slot 1 is not owned by the client (state=0)
01-24 18:38:26.540 10447-10447/net.ossrs.yasea.demo E/BufferQueue: [unnamed-10447-0] cancelBuffer: slot 2 is not owned by the client (state=3)
01-24 18:38:26.540 10447-10447/net.ossrs.yasea.demo E/BufferQueue: [unnamed-10447-0] cancelBuffer: slot 3 is not owned by the client (state=2)
01-24 18:38:26.540 10447-10447/net.ossrs.yasea.demo E/BufferQueue: [unnamed-10447-0] cancelBuffer: slot 4 is not owned by the client (state=0)
01-24 18:38:26.540 10447-10447/net.ossrs.yasea.demo E/BufferQueue: [unnamed-10447-0] cancelBuffer: slot 5 is not owned by the client (state=0)
01-24 18:38:26.540 10447-10447/net.ossrs.yasea.demo E/BufferQueue: [unnamed-10447-0] cancelBuffer: slot 6 is not owned by the client (state=0)
01-24 18:38:26.540 10447-10447/net.ossrs.yasea.demo E/BufferQueue: [unnamed-10447-0] cancelBuffer: slot 7 is not owned by the client (state=0)

**Comment by begeekmyfriend** [comment]
clone最新版本吗？是前置还是后置奔溃？

**Comment by xiongxianwei90** [comment]
大神，是2.6.1 的tag 
最新代码 ndk 编译不过总是报错“  error: undefined reference to 'stpcpy'”。
不过2.6.1 这个版本在华为荣耀6崩溃的原因我找到了。大概是后置摄像头设置 
mPublisher.setPreviewResolution(1280, 720); 会崩溃
mPublisher.setPreviewResolution(640, 480); 可以正常使用
明天我再追一下具体原因。

**Comment by begeekmyfriend** [comment]
那就是不支持这个分辨率。
至于stpcpy的问题，你可以搜“NDK stpcpy”找到合适的NDK版本，目前我是直接用AS设置中ndk-bundle最新版

**Comment by xiongxianwei90** [comment]
好的谢谢。
