### ISSUE TITLE
How can I improve the latency ?

### ISSUE THREAD

**Issue by zzzykf** [begeekmyfriend/yasea#587]
I've tried to use localhost to do the live stream and there is a 6 ~ 8sec latency,  is there any ways to improve it to be real time or approximate to real time ?

**Comment by zzzykf** [comment]
I've found the similar question, will close this issue, thank you :)

**Comment by zzzykf** [comment]
I m still not able to improve the latency, is there any ways to do it ?

**Comment by begeekmyfriend** [comment]
Build A local RTMP server, and use ffplay to see the latency, you will find it is not the issue of yasea.

**Comment by zzzykf** [comment]
I have tried this, and there is the same latency when using hard encoder and around 2sec latency when using soft encoder.
May I know what is the issue for this ? And is it 2 sec is the minimum latency ? Thank you for your reply

**Comment by zzzykf** [comment]
Okay, thank you for your information :)
