### ISSUE TITLE
No Audio in recorded file after mp4muxer.stop() unless flvmuxer.stop() called

### ISSUE THREAD

**Issue by long-greg-c** [begeekmyfriend/yasea#59]
Hi Leo, 
It is possible that a recorded mp4 file will have no audio if the mp4 muxer is stopped before the flv muxer. Example steps to reproduce.
OS: 6.0.1
Device: Nexus 5

1. Start publishing.
2. Start mp4 recording - mp4Muxer.record(fileName)
3. Stop mp4 recording - mp4Muxer.stop()
4. Stop publishing - flvMuxer.stop()

**Comment by begeekmyfriend** [comment]
#60

**Comment by long-greg-c** [comment]
Recording now has audio. Thank you.
