### ISSUE TITLE
How to adjust front camera mirroring?

### ISSUE THREAD

**Issue by ToysoftInc** [begeekmyfriend/yasea#595]
How do I adjust the front camera mirroring to show the opposite of what is displaying?
When the camera displays text "ABC" for example it shows "CBA" flipped.
I want to show exactly what is displaying like the back camera.
I have tried changing the orientation but it doesn't work
        mCamera.setDisplayOrientation(mPreviewRotation);

**Comment by begeekmyfriend** [comment]
You can switch the [flip](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L621-L628) argument.

**Comment by ToysoftInc** [comment]
Do you know which function to be more specific and what about the camera preview? how do I change that? thanks

**Comment by begeekmyfriend** [comment]
The boolean `flip` argument can be used to control the `libyuv` for image mirroring. You can assign `true` or `false` to it.
As for camera preview, I am afraid I do not provide the method for image mirroring. I think you can do it in [SrsCameraView.java](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsCameraView.java#L115) on your own.

**Comment by keeblebogdan** [comment]
Add these 2 lines in onDrawFrame after **getTransformMatrix** and before **multiplyMM**.

 // mirror frames
 Matrix.scaleM(mSurfaceMatrix, 0, -1, 1, 1);
 Matrix.translateM(mSurfaceMatrix, 0, -1, 0, 0);

**Comment by ToysoftInc** [comment]
Thanks.
