### ISSUE TITLE
Are there any callbacks for states like Connecting, Connected, Streaming, Disconnected etc.

### ISSUE THREAD

**Issue by gouravd** [begeekmyfriend/yasea#6]
Is there any existing callbacks for states like Connecting, Connected, Streaming, Disconnected so that the client app can add additional business logic based on these states

**Comment by begeekmyfriend** [comment]
How about exception state like networking error? Is it a standalone state or Are they multiple states? You'd better give me a clear complete state definition.

**Comment by gouravd** [comment]
Basically I am looking for callbacks with State information from the library/rtmp_publisher. Atleast single states like CONNECTING, CONNECTED, STREAMING/STOPPED_STREAMING, DISCONNECTED 

More states like EXCEPTION, NETWORK_ERROR, TIMEOUT, IO_ERROR are also welcome, but we can start with the basic ones

Expectation is that the Publisher calls the state callback with the following States
1) CONNECTING -> When the connection is being established with the rtmp endpoint
2) CONNECTED -> When the connection is established
3) STREAMING --> When the streaming actually starts and Audio/Video data is being written
4) STOPPED_STREAMING --> When the streaming stops
5) DISCONNECTED --> When the connection with the rtmp endpoint ends.

So CONNECTING and DISCONNECTED will always be the first and last state called respectively, in the Publisher lifecycle

My point of reference is https://github.com/pili-engineering/PLDroidCameraStreaming

**Comment by gouravd** [comment]
"help wanted" what is the tag for? I am willing to help

**Comment by begeekmyfriend** [comment]
https://github.com/begeekmyfriend/yasea/commit/04c831146d0323cb743cd4f09cbdfedc0de7fa0b

I have added an interface `EventHandler` for RTMP publisher which is implemented in `MainActivity` and constructed and passed as a parameter of `SrsEncoder`

```java
    /**
     * RTMP event handler.
     */
    interface EventHandler {

        void onRtmpConnecting(String msg);

        void onRtmpConnected(String msg);

        void onRtmpVideoStreaming(String msg);

        void onRtmpAudioStreaming(String msg);

        void onRtmpStopped(String msg);

        void onRtmpDisconnected(String msg);
    }
}
```

**Comment by gouravd** [comment]
WOW,, @begeekmyfriend this is too good. Great work and quite fast too. 

I will test sometime within the next 24 hours and let you know my observations. It looks great though.

**Comment by begeekmyfriend** [comment]
Sorry, an additional patch https://github.com/begeekmyfriend/yasea/commit/71a7e519409b273f358df29cdcfc85bc99c4b86d

**Comment by gouravd** [comment]
This works perfectly
