### ISSUE TITLE
Second recorded mp4 has no audio or video

### ISSUE THREAD

**Issue by long-greg-c** [begeekmyfriend/yasea#60]
Hi Leo, 
If a second recorded mp4 is created then the recording will have no audio or video. Example steps to reproduce.
OS: 6.0.1
Device: Nexus 5

1. Start publishing.
2. Start mp4 recording - mp4Muxer.record(fileName)
3. Stop mp4 recording - mp4Muxer.stop()
4. Start mp4 recording - mp4Muxer.record(newFileName)
5. Stop mp4 recording mp4Muxer.stop()
6. Stop publishing - flvMuxer.stop()

**Comment by begeekmyfriend** [comment]
Thank you for your reminding https://github.com/begeekmyfriend/yasea/commit/b2ec6c8e55e65c081a39d654661898365e4d4f33

**Comment by long-greg-c** [comment]
Changes fix the issue. Thank you.
