### ISSUE TITLE
海康摄像头推流

### ISSUE THREAD

**Issue by ivanlex** [begeekmyfriend/yasea#603]
请问可以使用海康威视的网络摄像头提供的SDK配合yasea进行推流吗？可否提供思路，谢谢!

**Comment by begeekmyfriend** [comment]
raw data可以送到[encoder.onGetRGBAFrame](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L372)，H.264可以送到[flvMuxer.writeSampleData](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L339)。
别忘了开一个线程，不然会堵塞。

**Comment by begeekmyfriend** [comment]
raw data可以送到[encoder.onGetRGBAFrame](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L372)，H.264可以送到[flvMuxer.writeSampleData](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L339)。
别忘了开一个线程，不然会堵塞。

**Comment by daniulive** [comment]
海康摄像头默认是拉取rtsp流，拿到之后，回调上来H.264和audio数据，publisher side开支持编码后的接口，传出去即可
