### ISSUE TITLE
大神 我在推流后按stop按钮会调用onRtmpDisconnected()

### ISSUE THREAD

**Issue by freedomqian** [begeekmyfriend/yasea#608]
我在推流后按stop按钮会调用onRtmpDisconnected()，TOASTDisconnected。

**Comment by begeekmyfriend** [comment]
建议检查网络环境与服务器

**Comment by freedomqian** [comment]
感谢大神 我这边用nginx服务器，PC端推手机端拉流播放倒是没问题。也是醉了。

**Comment by begeekmyfriend** [comment]
你可以推公网`rtmp://ossrs.net/app/stream`验证

**Comment by freedomqian** [comment]
好的我试试再次感谢

**Comment by begeekmyfriend** [comment]
这个版本应该不会有连接问题，建议检查网络。最新版本在repo上。

**Comment by freedomqian** [comment]
好的感谢大神
