### ISSUE TITLE
大神你好 请问我推拉流已经完成，但是请问能否做成双向的

### ISSUE THREAD

**Issue by freedomqian** [begeekmyfriend/yasea#609]
手机做分屏处理 左SrsCameraView，右videoview
先A 推RTMPURI /livea ——B拉
再B再推RTMPURI /liveb——A拉

**Comment by begeekmyfriend** [comment]
你这个属于P2P，协议上不一样，RTMP必须有对应的服务器

**Comment by freedomqian** [comment]
谢谢
