### ISSUE TITLE
画面翻转

### ISSUE THREAD

**Issue by microswind** [begeekmyfriend/yasea#610]
作者你好，我在一台800x480的定制机上运行的时候，拉流发现画面翻转了（上下倒转）；之前在普通竖屏手机上试都是没问题的。不知道如何解决这个问题。

**Comment by begeekmyfriend** [comment]
那是你定制机的问题，标准机上都是OK的对吧。你可以在[API](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L621-L629)上调整一下参数

**Comment by microswind** [comment]
改了下角度就可以了。非常感谢。

**Comment by liyangyang123** [comment]
怎么改参数？

**Comment by microswind** [comment]
@liyangyang123 你好，抱歉之前没留意到回复，我之前是在上面begeekmyfriend提供的链接中SrsEncoder类调整部分native调用的角度参数。因为我的是翻转，+-180度试一下就可以了。
