### ISSUE TITLE
When streaming audio only I can't record to local.

### ISSUE THREAD

**Issue by ToysoftInc** [begeekmyfriend/yasea#615]
I'm only streaming audio and I'm not able to record audio.
The .mp4 file is only 559 bytes.  

It works fine if I stream both video and audio.

I do this:

            mPublisher.setSendAudioOnly(true);
            mPublisher.startPublish(rtmpUrl);
            mPublisher.startCamera();

When connected to server I then start the recording.

Any suggestions? thanks

**Comment by begeekmyfriend** [comment]
Maybe the ROM of your phone is custom, change the device supporting complete SDK

**Comment by ToysoftInc** [comment]
I don't understand your question.  What does ROM have to do with recording?
I have tested on Samsung 4, 5 and 7 and when streaming just audio recording does not work.
Have you tried just streaming audio and record?

**Comment by begeekmyfriend** [comment]
Sorry I have mistaken your requirement.
The recording will not receive the frames till the video [key frame](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsMp4Muxer.java#L327) comes. I think you need to modify `SrsMp4Muxer.java` on your own.

**Comment by ToysoftInc** [comment]
Ok. Will try that. thanks
