### ISSUE TITLE
清晰度有设置吗

### ISSUE THREAD

**Issue by jw20082009** [begeekmyfriend/yasea#627]
我用硬编码，设置的帧率，码率，分辨率基本接近系统相机的参数，拍出来的效果相差甚远，项目中除了这几个参数，还有其他会影响清晰度的参数设置了吗？

**Comment by begeekmyfriend** [comment]
流媒体从压缩到传输到播放端本身就是一个画质不断损耗的过程

**Comment by jw20082009** [comment]
我把rtmp的库删掉了，只留了硬编和录制

**Comment by begeekmyfriend** [comment]
硬编码profile写死了baseline，安卓默认设置，我估计你得自己去调参[x264](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/cpp/libenc/libenc.cc#L516-L536)
