### ISSUE TITLE
ByteArray.allocateDirect 创建的ByteArray，使用array() 获取的数据有问题

### ISSUE THREAD

**Issue by ZengHK2018** [begeekmyfriend/yasea#629]
问题详情: https://github.com/begeekmyfriend/yasea/issues/415
因为我的小米5S 手机也在推流后观看出现左边有一条线。其他手机也出现过。

经过几天深入的研究终于发现并解决此Bug.
见: https://blog.csdn.net/ilittleone/article/details/46659183
**因allocateDirect 申请的内存有对齐问题，不能直接用 array() 作为数据传递.**

测试过程:
`
       
        int[] intArray = {1};
        IntBuffer intBuffer = IntBuffer.allocate(1);
        intBuffer.put(intArray);
        Log.i(TAG, "capacity:" + intBuffer.capacity() + " " + Arrays.toString(intBuffer.array()));
        //输出  capacity:1 [1]

        ByteBuffer byteBuffer = ByteBuffer.allocate(4);
        byteBuffer.asIntBuffer().put(intBuffer.array());
        Log.i(TAG, "capacity:" + byteBuffer.capacity() + " " + Arrays.toString(byteBuffer.array()));
        //输出  capacity:4 [0, 0, 0, 1]
        //正确结果.

        ByteBuffer byteDirectBuffer = ByteBuffer.allocateDirect(4);
        byteDirectBuffer.asIntBuffer().put(intBuffer.array());
        Log.i(TAG, "capacity:" + byteDirectBuffer.capacity() + " " + Arrays.toString(byteDirectBuffer.array()));
        //输出  capacity:4 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
        //错误结果.  因为allocateDirect 申请的内存空间有字节对齐，会有额外的数据.
`
问题定位:
https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsCameraView.java#L158

2种解决方式:
        1. allocateDirect() 改用 allocate()
        2. `

           byte[] output = new byte[byteDirectBuffer.capacity()];
           byteDirectBuffer.get(output);`
           使用output 替代 byteDirectBuffer.array()

**Comment by begeekmyfriend** [comment]
棒！这个问题你来提交PR吧，欢迎加入contributor！

**Comment by zenghuakun** [comment]
@begeekmyfriend 还是你来吧。哈哈，我要动手我自己都害怕！

**Comment by begeekmyfriend** [comment]
Fixed https://github.com/begeekmyfriend/yasea/commit/fea87c86f8fe1cd00dc34fc0e9566849cca17b41

**Comment by ZengHK2018** [comment]
nice!

**Comment by begeekmyfriend** [comment]
我试过`byteDirectBuffer.get`还是不行，恐怕这个方法跟`array`方法一样

**Comment by ZengHK2018** [comment]
可能跟手机厂商的优化有关系。
