### ISSUE TITLE
Front camera is mirror......

### ISSUE THREAD

**Issue by fifa1016** [begeekmyfriend/yasea#64]
Front camera's preview  is like a mirror,  it's right.  But in player,  a mirrored video is not acceptable.

所以前置镜头需要将画面翻转后再推流上去, 这个问题如何解决?

**Comment by begeekmyfriend** [comment]
Try to switch the boolean argument in this [method](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/SrsEncoder.java#L384).

The problem is multiple android models have different preview display and data content. It is hard to unify them.

**Comment by veritas1** [comment]
@begeekmyfriend Link is dead. Which method are you referring to? Line 384 of SrsEncoder.java is inside `public void onGetRgbaFrame(byte[] data, int width, int height)` now.

**Comment by begeekmyfriend** [comment]
In `SrsEncoder.java`,  the native APIs

**Comment by veritas1** [comment]
👍
