### ISSUE TITLE
第三方摄像头不通过录屏的方式

### ISSUE THREAD

**Issue by ivanlex** [begeekmyfriend/yasea#640]
你好，我这边用的不是设备自带的摄像头，而是使用的第三方网络摄像头，稍微研究了一下你的代码应该是需要通过录屏实现的。我想不通过录屏实现，请问应该怎么实现？

**Comment by begeekmyfriend** [comment]
本来就没有录屏啊，录频是`MediaProjectionManager `类库。你想要的是读取摄像头的图像数据吧
[这个](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsCameraView.java#L127)是主分支，是基于GLES的，将图像数据塞入队列里，队列另一端通过另一个线程送往编码器。
[这个](https://github.com/begeekmyfriend/yasea/blob/non-gpuimage/library/src/main/java/net/ossrs/yasea/SrsCameraView.java#L271)是除去GLES分支，同样是通过一个队列输送的。
所以你也需要构建一个队列，再用多线程摄像机的数据填入，另一端送往编码器即可

**Comment by ivanlex** [comment]
请教一下，这种思路可不可以。通过改写SrsCameraView，然后将网络摄像机的数据直接填入SrsCameraView的PreviewCallback的onGetRgbaFrame(byte[] data, int width, int height) 方法内

**Comment by ivanlex** [comment]
感谢老师，我成功了，使用的是no-gpuimage这个分支，之前说的方法是可行的,谢谢！
