### ISSUE TITLE
Pay $50: Anyone can inject audio to stream

### ISSUE THREAD

**Issue by ToysoftInc** [begeekmyfriend/yasea#650]
I will pay out $50 if you can add audio injection to the stream.

What i want is to inject a small mp3 or wav in the audio stream.
It must work on OS7 and higher.

**Comment by begeekmyfriend** [comment]
Sir,

Sorry that I am unavailable, not because the payment.

ToysoftInc <notifications@github.com> 于2018年8月30日周四 下午11:30写道：

**Comment by ToysoftInc** [comment]
OK. But I will pay anyone who can do this
