### ISSUE TITLE
双摄推流数据混乱的问题

### ISSUE THREAD

**Issue by zhangyuanlu** [begeekmyfriend/yasea#654]
你好，我尝试使用两个SrsPublisher将前后Camera的数据同时推流到两个Url地址，rtmp服务器接收到的图像出现数据混合（这一帧是前摄的数据，下一摄又是后摄的数据），这种情况可能是什么原因造成的呢？
            mPublisher1 = new SrsPublisher(srsCameraView1);
            srsPublisher(mPublisher1,url1);//SrsPublisher两个配置一样
            mPublisher2 = new SrsPublisher(srsCameraView2);
            srsPublisher(mPublisher2,url2);
我也怀疑过硬编码的并发问题，但是我将一个设置为软编，一个设置为硬编后还是一样的结果

**Comment by begeekmyfriend** [comment]
FYI https://github.com/begeekmyfriend/yasea/issues/593

**Comment by zhangyuanlu** [comment]
> FYI #593

这个我看到了，但是我一个用软编一个用硬编，mediacodec就是创建一次没错啊，在这种情况下为什么还会出现数据混乱的问题，我想不明白哎

**Comment by begeekmyfriend** [comment]
你这个业务需求有点复杂，我没验证过，我当初发布只是为了手机版，没想到这么多安卓开发板技术人员找上门，也是出乎意料，爱莫能助啊……

**Comment by zhangyuanlu** [comment]
> 你这个业务需求有点复杂，我没验证过，我当初发布只是为了手机版，没想到这么多安卓开发板技术人员找上门，也是出乎意料，爱莫能助啊……

关键我现在搞不明白哪里出的问题，两个推流对象分别在各自的线程中进行推流，数据也是各自的cameraview中拿到的，为什么会发生混乱呢？怎么都感觉不应该发生这种情况啊。我们这种需求也确实少见。除了我们这种奇葩需求，这个开源项目做的还是挺棒的。

**Comment by zhangyuanlu** [comment]
另外我这个也是手机，是支持同时开启两个camera进行预览的，预览界面还是很正常的。

**Comment by begeekmyfriend** [comment]
有一种调试方法是从`SrsCameraView.java`中的采集内容dump出来看一下是否有误，不过我没法帮你验证了。

**Comment by zhangyuanlu** [comment]
> 有一种调试方法是从`SrsCameraView.java`中的采集内容dump出来看一下是否有误，不过我没法帮你验证了。

感谢提供各种思路，我先试试，如果有其它可能的原因也可以说一下，十分谢谢

**Comment by zhangyuanlu** [comment]
应该不是图像采集的问题，感觉是多线程造成的。最后通过使用两个独立进程得以解决。

**Comment by begeekmyfriend** [comment]
嗯嗯，祝贺解决，我标记一下这个issue吧

**Comment by Macrow** [comment]
> 应该不是图像采集的问题，感觉是多线程造成的。最后通过使用两个独立进程得以解决。

今天也遇到这个需求，我尝试在一个Activity里面用两个service调用Publisher，结果还是出现错误，麻烦请问用两个独立进程是如何解决两个摄像头同时推流的，能否提供一个大概思路，谢谢了！

**Comment by wtbee** [comment]
> 应该不是图像采集的问题，感觉是多线程造成的。最后通过使用两个独立进程得以解决。

您好，可以将具体解决的方案详细说明一下吗？谢谢~
当前遇到了类似的问题，一个Activity里面要推两路摄像头的数据，怎么做到进程独立来解决这个问题~

**Comment by Naxiding** [comment]
我研究后发现native层使用c实现，出现静态变量存在多线程问题，可以在SrsEncode.java 中hwRgbaFrame方法内容使用类锁来包裹实现同步，已实现单进程双摄同时打开推流没问题
    private byte[] hwRgbaFrame(byte[] data, int width, int height) {
        synchronized (SrsEncoder.class) {
            switch (mVideoColorFormat) {
                case MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420Planar:
                    return RGBAToI420(data, width, height, true, 180);
                case MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420SemiPlanar:
                    return RGBAToNV12(data, width, height, true, 180);
                default:
                    throw new IllegalStateException("Unsupported color format!");
            }
        }
    }

**Comment by Naxiding** [comment]
native转码数据的时候有静态变量

**Comment by Naxiding** [comment]
> > 应该不是图像采集的问题，感觉是多线程造成的。最后通过使用两个独立进程得以解决。
> 
> 您好，可以将具体解决的方案详细说明一下吗？谢谢~ 当前遇到了类似的问题，一个Activity里面要推两路摄像头的数据，怎么做到进程独立来解决这个问题~

可以参考我的解决方案，或者使用其他的转码方式将rgba转码成yuv

**Comment by banmeng1** [comment]
> 我研究后发现native层使用c实现，出现静态变量存在多线程问题，可以在SrsEncode.java 中hwRgbaFrame方法内容使用类锁来包裹实现同步，已实现单进程双摄同时打开推流没问题 private byte[] hwRgbaFrame(byte[] data, int width, int height) { synchronized (SrsEncoder.class) { switch (mVideoColorFormat) { case MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420Planar: return RGBAToI420(data, width, height, true, 180); case MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420SemiPlanar: return RGBAToNV12(data, width, height, true, 180); default: throw new IllegalStateException("Unsupported color format!"); } } }

兄弟你好，重写了C层实现了视频同时推流但是推流是视频会有一些卡或者延迟有些高，您知道大概是什么原因引起的吗

**Comment by banmeng1** [comment]
@Naxiding 
开发板的前后摄像头同时推流 分辨率是1920*1080
