### ISSUE TITLE
使用第三方摄像头获取到了YUV420SP的流，怎么推流呢？

### ISSUE THREAD

**Issue by fingdo** [begeekmyfriend/yasea#656]
使用SrsPublisher的onGetYuvFrame(byte[] data)方法不行啊

**Comment by begeekmyfriend** [comment]
这个格式需要你自己做个适配了，具体可以参考一下`SrsEncoder.java`的接口，以及`libenc.cc`的实现，考虑色彩空间的转换

**Comment by fingdo** [comment]
如果对方的流改成了YUV420的话，能否直接用non-gpuimage分支的`SrsEncoder`中的`onGetYuvFrame(byte[] data)`推流呢？

**Comment by begeekmyfriend** [comment]
不清楚你的环境，你可以试试看

**Comment by wasdzy111** [comment]
@fingdo  你成功了吗

**Comment by fingdo** [comment]
@wasdzy111 这个库没有成功，我换了其他方式实现了
