### ISSUE TITLE
audio bitrate and video bitrate

### ISSUE THREAD

**Issue by huongtran84** [begeekmyfriend/yasea#657]
can anyone tell me how to change audio and video bitrate before streaming?

**Comment by begeekmyfriend** [comment]
`SrsEncoder.java`

**Comment by huongtran84** [comment]
Thank for suggesting .I use the library for live streaming youtube .but It alway slower realtime about 30 second from start time.any ideas?

**Comment by begeekmyfriend** [comment]
Maybe you need to refer to https://github.com/begeekmyfriend/yasea/issues/554
