### ISSUE TITLE
yasea remove video

### ISSUE THREAD

**Issue by wtchaos** [begeekmyfriend/yasea#66]
Excuse me,I want to ask a question. how to only send the audio when I use the yasea?

**Comment by begeekmyfriend** [comment]
Done https://github.com/begeekmyfriend/yasea/commit/65153631f74728a6f525b02f1260a0d0fc1438f0

**Comment by wtchaos** [comment]
I updated the code but useless

**Comment by begeekmyfriend** [comment]
Try to call `setSendAudioOnly(true)` and setSendAudioOnly(false)``  [here](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/MainActivity.java#L98)

Note do not call it on publish, the connection to the server need at least one key frame

**Comment by wtchaos** [comment]
Thank you.It works,but may I modify the key frame and send audio directly?

**Comment by begeekmyfriend** [comment]
You may [connect](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/SrsFlvMuxer.java#L162) to RTMP server at the beginning.

**Comment by wtchaos** [comment]
Thank you very much! I read your code and it helped me a lot.

**Comment by fifa1016** [comment]
GREAT WORK!
