### ISSUE TITLE
Youtube streaming

### ISSUE THREAD

**Issue by maniacs-engineerica** [begeekmyfriend/yasea#663]
Hi,

I can't integrate this with Youtube. Logcat isn't showing any warning or error and it seems the live streaming is working fine, but when I try to watch the streaming on Youtube it doesn't come up.

Thanks,
Matias.

**Comment by begeekmyfriend** [comment]
Please refer to https://github.com/begeekmyfriend/yasea/issues/554. In China I am not able to connect Youtube directly...
