### ISSUE TITLE
请问能推流mp3背景音乐吗

### ISSUE THREAD

**Issue by itbaixue** [begeekmyfriend/yasea#671]
mp3转成pcm后，不知道能否推流？

**Comment by begeekmyfriend** [comment]
可以的,你通过[SrsPublisher.java](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsPublisher.java#L105)提供数据源,去掉PCM头部

**Comment by itbaixue** [comment]
感谢反馈，我用ffmpeg命令把mp3转成pcm后，推流声音会有延迟卡顿现象，请教下什么地方出问题了

```shell
ffmpeg -i 201811050057.mp3 -f s16be -ar 44100 -ac 1 -acodec pcm_s16be 201811050057.pcm
```

```java
byte[] sourceReader = new byte[4096];
int sourceReadSize = pcmInputStream.read(sourceReader);
if (sourceReader.length > 0) {
    mEncoder.onGetPcmFrame(sourceReader, sourceReader.length);
}
```

**Comment by begeekmyfriend** [comment]
打开`setSendAudioOnly`方法，并且注意buffer里没有“杂质”（长度是否正确）

**Comment by itbaixue** [comment]
`setSendAudioOnly`打开之后是没有视频图像了吧，这边的场景需要摄像头 和 背景音乐 同时，在观众端出现的效果像放慢了3/4倍播放背景音乐（应该是这样）
