### ISSUE TITLE
错误: 可能尚未初始化变量camera

### ISSUE THREAD

**Issue by zhangnan1** [begeekmyfriend/yasea#702]
yasea-master/library/src/main/java/net/ossrs/yasea/SrsCameraView.java 在这个目录下报这个 错误: 可能尚未初始化变量camera

**Comment by begeekmyfriend** [comment]
@thegobot Please checkout your last PR, I am unavailable for Android development. Sorry about that.

**Comment by begeekmyfriend** [comment]
Have you solved this problem? Any fix required?
