### ISSUE TITLE
两个视频流上传的问题

### ISSUE THREAD

**Issue by XiaoXu09** [begeekmyfriend/yasea#703]
你好，我这边的业务需求是同时长传手机摄像头捕获的画面和智能眼镜捕获的画面同时上传。其中手机端包含图像和声音   智能眼镜端只上传画面。   智能眼镜由UVCCamera控制，可以直接获取byte[]。  现在我要将这些byte[]和手机摄像头的一起上传。请问，这种怎么实现？

**Comment by begeekmyfriend** [comment]
开两个连接，每个连接一个线程，每个线程一个队列(muxer)，将数据往相应的队列输送，可以试试，祝好运

**Comment by XiaoXu09** [comment]
你好，再问一下，我只想上传，不想预览。当我把srscameraview不继承surfaceview后，打印有流，但是另一端播放不了（打开不成功）。这个该怎么处理

**Comment by XiaoXu09** [comment]
又看了一下，只有音频，没有视频。

**Comment by begeekmyfriend** [comment]
什么叫“打印有流”，那只是无意义的字节而已。你没有surface。怎么渲染图像？

**Comment by XiaoXu09** [comment]
我手机端只需要上传，不需要渲染图像啊。  这个界面我不展示摄像头画面，可以做其他的展示。只是开启摄像头，然后上传即可。

**Comment by begeekmyfriend** [comment]
你根本没弄明白安卓音视频原理，这里没有义务向你科普。

**Comment by XiaoXu09** [comment]
好吧，我在学习一下吧。谢谢！
