### ISSUE TITLE
error: variable camera might not have been initialized

### ISSUE THREAD

**Issue by goelakansha006** [begeekmyfriend/yasea#709]
I am getting this error in /library/src/main/java/net/ossrs/yasea/SrsCameraView.java file. Please check.

**Comment by begeekmyfriend** [comment]
Could you show me the error logging here?

**Comment by goelakansha006** [comment]
![RTMP](https://user-images.githubusercontent.com/16938442/56910507-598e1d00-6ac8-11e9-9767-d6aa67fe0d13.PNG)

Please check.

**Comment by begeekmyfriend** [comment]
@thegobot Would you please checkout your last PR for I am unavailable for Android development currently.

**Comment by goelakansha006** [comment]
Any updates on this?
Will it take time to fix the issue?

**Comment by begeekmyfriend** [comment]
Unfortunately there is no Android IDE in my development platform. I am afraid you have to fix it on your own. Any PR is welcome. Sorry about it!

**Comment by deathemperor** [comment]
I've put a PR here https://github.com/begeekmyfriend/yasea/pull/724

**Comment by begeekmyfriend** [comment]
Thank you for your PR! @goelakansha006 please feel free to reopen it.
