### ISSUE TITLE
About setRecordEventHandler

### ISSUE THREAD

**Issue by pcyan** [begeekmyfriend/yasea#71]
我不得不去调用 `setRecordEventHandler` 去成功发布视频，就算我不需要录制功能

我在 `SrsEncoder.java` 看到这一句
```
if (flvMuxer == null || mp4Muxer == null) {
            return false;
}
```
感觉这样设计有点荒谬，录制应该是一个可选的功能才合理吧

**Comment by begeekmyfriend** [comment]
还在整合阶段，所以没有明确把`mp4Muxer`分离，后续会考虑重新设计SDK

**Comment by begeekmyfriend** [comment]
Done
