### ISSUE TITLE
混音

### ISSUE THREAD

**Issue by zzzlq** [begeekmyfriend/yasea#72]
我尝试将yasea与mp3或者wav之类的音频文件进行混音，但总是不能达到预想的效果？请问使用yasea可否实现混音效果？

**Comment by begeekmyfriend** [comment]
Yasea用于网络推流，音频编码默认是AAC，没想过mp3和wav及其混音

**Comment by begeekmyfriend** [comment]
另外混音需要播放器那边配合的，我没做过player

**Comment by zzzlq** [comment]
好的··谢谢··我这边把mp3转码成pcm，然后通过混音算法把mp3和麦克风的流混成pcm后推成功了，我看代码Yasea好像是推pcm的吧，Yasea可以将pcm编码成aac么？

**Comment by begeekmyfriend** [comment]
本来就是AAC编码啊，只不过从麦克风采样的PCM没经过处理，直接送到MediaCodec的
