### ISSUE TITLE
Yasea APP2.6版本推流音视频不同步

### ISSUE THREAD

**Issue by Believe-Myself** [begeekmyfriend/yasea#728]
您好！我使用下载的yasea2.6推流，使用flv.js播放出现画面早于声音两三秒左右的现象，但是使用OBS推流是正常的，请问是什么原因呢？感谢指点！

**Comment by Believe-Myself** [comment]
我将Nginx部署在了阿里云上，OBS推流+flv.js播放正常，yasea2.6推流+VLC播放正常，所以现在分不清是哪里的问题。

**Comment by begeekmyfriend** [comment]
目前已经不从事流媒体业务。但可以这样排查：
- 是否每次必现？还是偶现？
- 如果每次必现，用ffplay的方式拉流
- 如果ffplay没问题，则上报bug给`flv.js`

**Comment by Believe-Myself** [comment]
好的，感谢
