### ISSUE TITLE
Yasea can connect a video and an audio address to push the stream at the same time?

### ISSUE THREAD

**Issue by leepan** [begeekmyfriend/yasea#73]
Yasea can connect a video and an audio address to push the stream at the same time?

**Comment by begeekmyfriend** [comment]
The address can only be `rtmp://host/app/stream`

**Comment by leepan** [comment]
@begeekmyfriend Video address like this,rtmp://host/app/stream1  and audio address like this,rtmp://host/app/stream2. Connectting  a video and an audio address to push the stream at the same time.

**Comment by begeekmyfriend** [comment]
Then you may create a new socket with its input and output stream, a new `RtmpSessionInfo` and a reading and writing thread to receive and send RTMP packets. The key code is [here](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/rtmp/io/RtmpConnection.java#L110-L114).
