### ISSUE TITLE
Black screen when tap 'publish' button

### ISSUE THREAD

**Issue by iSinch** [begeekmyfriend/yasea#76]
I think it is connected somehow with libenc.so libyuv.so
In Log surface just waiting
![image](https://cloud.githubusercontent.com/assets/13470331/17690307/56752186-6396-11e6-9fc4-f0cd581f1adb.png)

**Comment by begeekmyfriend** [comment]
Please tell me your phone model. Does it happen on other machine?

**Comment by iSinch** [comment]
Lenovo tab2 and other models

**Comment by begeekmyfriend** [comment]
Under which camera face did it happen?

**Comment by iSinch** [comment]
Problem with frontal and main camera :(
I did an experiment . 
If i  create a new project and import your package and  .so, then camera not starting

**Comment by begeekmyfriend** [comment]
It did not occur on my machine. Did you clone the latest repository and run as a standalone demo? If so please help me count the phone models.

**Comment by iSinch** [comment]
Update my last message

**Comment by iSinch** [comment]
so may be problem with jniLibs ?
Thank you for your project and for answer my questions

**Comment by begeekmyfriend** [comment]
I just provide `arm_v7a` ABI. Maybe it is CPU architecture.
