### ISSUE TITLE
长时间推流问题

### ISSUE THREAD

**Issue by TBoyLi** [begeekmyfriend/yasea#763]
手机持续推送一个多小时之后提示网络差，然后就提示broken pipe 这是srs服务器的问题吗？如下图

![image](https://user-images.githubusercontent.com/14815341/83853740-4b3d1680-a748-11ea-99c0-de338037ecc7.png)

**Comment by begeekmyfriend** [comment]
是的，你可以查看SRS的日志，显示服务端主动关闭了连接，原因是弱网（网络没有响应）

**Comment by TBoyLi** [comment]
@begeekmyfriend 是服务器的问题。感谢
