### ISSUE TITLE
请问回声和噪音如何处理呢？

### ISSUE THREAD

**Issue by SunnyBoolean** [begeekmyfriend/yasea#77]
如题，求告知啊

**Comment by begeekmyfriend** [comment]
单独在推流端做没有意义，需要播放端配合解码的

**Comment by SunnyBoolean** [comment]
@begeekmyfriend 了解了，thx~

**Comment by SunnyBoolean** [comment]
@begeekmyfriend 我手机端用的Vitamio拉流视频，发现仍然有极大的噪音和间隔性的回音，是否需要在推流前进行编码处理？我是流媒体小白，请指点一二啊

**Comment by begeekmyfriend** [comment]
这个[项目](https://github.com/i-p-tel/sipdroid/blob/master/jni/speex_jni.cpp)你可以参考下，使用speex，需要解码端支持。不过我也没做过音效处理。

**Comment by JakeRed** [comment]
怎么更改为Speex

**Comment by begeekmyfriend** [comment]
Android SDK supports it https://github.com/begeekmyfriend/yasea/commit/2c4e21603edbae44b108ee3e384cd81e2e2e346f
