### ISSUE TITLE
hi,你好，谢谢之前你的解答，现在我调试没有推流就开始调用startEncoder，出现如下情况，望解答。

### ISSUE THREAD

**Issue by Wodner** [begeekmyfriend/yasea#770]
情况是这样的，页面预览起来之后，我就调用startEncoder,  并且这时候 没有往 flvmuxer 传数据， 然后点击推送按键，这时候往flvmuxer 传数据，

在SrsFlvMuxer中的public void writeVideoSample(final ByteBuffer bb, MediaCodec.BufferInfo bi)函数中，没有走如下的条件：

else if (nal_unit_type == SrsAvcNaluType.SPS || nal_unit_type == SrsAvcNaluType.PPS) {
 .......
              if (!frame_pps.data.equals(h264_pps)) {
                    byte[] pps = new byte[frame_pps.size];
                    frame_pps.data.get(pps);
                    h264_pps_changed = true;
                    h264_pps = ByteBuffer.wrap(pps);
                    writeH264SpsPps(dts, pts);
                }
 .......
}

按照demo 那个流程 就会首先进入上面 的条件分支，就能正常推送， 我这个情况是什么原因导致不走以上代码走的条件分支。
nal_unit_type 不对，

**Comment by begeekmyfriend** [comment]
一般视频第一帧sequence header包含SPS & PPS，说明你的数据格式不对，或者哪里错位了，请检查H.264的每一个NALU，从start code开始，你可以dump或者打断点调试

**Comment by Wodner** [comment]
> 一般视频第一帧sequence header包含SPS & PPS，说明你的数据格式不对，或者哪里错位了，请检查H.264的每一个NALU，从start code开始，你可以dump或者打断点调试

是的，找到问题了， 谢谢。
