### ISSUE TITLE
limit streaming to FPS

### ISSUE THREAD

**Issue by andreac** [begeekmyfriend/yasea#775]
Hi, thanks for your work

I see that the app is streaming at 30 fps, i have a server that receive stream and create an overlay, but it works well at 25 fps.

Is it possible to limit the streaming to 25 FPS?

thanks

**Comment by begeekmyfriend** [comment]
1. Adjust the value of [SrsEncoder.FPS](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsCameraView.java#L319) to check out the effect.
2. Switch to soft encoding and change SrsEncoder.FPS as well.

**Comment by andreac** [comment]
i set ` mPublisher.switchToSoftEncoder()` and `SrsEncoder.VFPS` to 24 but i always got 30 fps

**Comment by begeekmyfriend** [comment]
Maybe it is your device that make such situation. Is it pad or phone?

**Comment by andreac** [comment]
i'm using an huawei p30pro. But i was wrong, in app logs i saw 30fps, but ffmpeg server that receive stream told me 24fps.
So it's working!
