### ISSUE TITLE
No audio output for WebRTC to play

### ISSUE THREAD

**Issue by thuongtd** [begeekmyfriend/yasea#776]
Hi @begeekmyfriend,

I'm currently using your lib as a encoder to publish (RTMP) stream to Wowza.
It worked well at player side (we used WebRTC) except the audio.

As far as I know WebRTC prefer 48 kHz as the input sample rate for audio. But currently Yasea's using 44.1 kHz. Is Yasea support 48 kHz sample rate? Or could you guide me how to change this.

Note: I succeed in trying to publish RTMP source by using OBS Studio (with audio sample rate is 48 kHz) to Wowza and can have both video and audio at player using WebRTC.

Thanks,

**Comment by thuongtd** [comment]
Thank you for your info.
Btw, it's still not working when I change SrsEncoder.ASAMPLERATE to 48000. Is there anything else need to be changed?
The expected output is H.264+Opus codec.

**Comment by begeekmyfriend** [comment]
Excellent!
