### ISSUE TITLE
录屏后搭配EasyDarwin来使用

### ISSUE THREAD

**Issue by cl1069573062** [begeekmyfriend/yasea#78]
我希望在安卓上面去录屏，然后利用你开源的Yasea来推流，之后搭配EasyDarwin服务器来分发。EasyDarwin是支持Rtsp协议的，不知道能配合你的Yasea使用吗。或者使用什么流媒体服务器来搭配更合适

**Comment by begeekmyfriend** [comment]
Yasea是RTMP的，不支持RTSP，可用服务器包括Nginx-RTMP，SRS、Wowza、FMS、Red5以及各大CDN
