### ISSUE TITLE
推流地址格式问题

### ISSUE THREAD

**Issue by 1403851384** [begeekmyfriend/yasea#796]
你好，问一下推流地址的格式多加一个/  是不是不能需要在RtmpConnection里面修改
我在“rtmp://192.168.0.105:8003/channel/1”进行推流是能用srs拉到视频流，但是把地址修改为“rtmp://192.168.0.105:8003/channel/1/1” ，真机上虽然显示出推流成功的Toast，但是用srs拉流就拉不到。请问一下这个问题是在RtmpConnection里面的rtmpUrlPattern修改为自己需要的格式。

**Comment by begeekmyfriend** [comment]
是的，`SimpleRTMP`的URL解析做得太简单，你可以自行修改

**Comment by begeekmyfriend** [comment]
Fixed https://github.com/begeekmyfriend/yasea/commit/ae2c11406ad2c11147ebb65999e5c5ec36b41743
