### ISSUE TITLE
About plug flow state

### ISSUE THREAD

**Issue by fly518420** [begeekmyfriend/yasea#8]
When in use, I would like to know the status of plug flow such as connection, data is written and disconnection.

The publisher states can meet the situation that connection is successful but not successful writing data, causing the plug flow side is not consistent with player endpoint.

**Comment by gouravd** [comment]
is this similar to #6

**Comment by begeekmyfriend** [comment]
Commit https://github.com/begeekmyfriend/yasea/commit/04c831146d0323cb743cd4f09cbdfedc0de7fa0b

I have added an interface `EventHandler` for `RtmpPublisher` and it is implemented in `MainActivity` and constructed and passed as a parameter of `SrsEncoder`

```java
/**
 * RTMP event handler.
 */
public interface RtmpPublisher {
    
    interface EventHandler {

        void onRtmpConnecting(String msg);

        void onRtmpConnected(String msg);

        void onRtmpVideoStreaming(String msg);

        void onRtmpAudioStreaming(String msg);

        void onRtmpStopped(String msg);

        void onRtmpDisconnected(String msg);
    }
}
```
