### ISSUE TITLE
请问有手机播放器的开源apk么？

### ISSUE THREAD

**Issue by sankycui** [begeekmyfriend/yasea#80]
目前项目可以用手机编码，也可以通过服务器观看实时视频。
请问下，还有观看视频的播放器apk么？谢谢！

另外，我的手机是魅族 M1 metal，可以通过yasea将视频上传到服务器观看。

**Comment by begeekmyfriend** [comment]
http://www.videolan.org/

**Comment by sankycui** [comment]
好的，谢谢！
