### ISSUE TITLE
安卓推流，连接自己的rtmp（srs）服务器失败

### ISSUE THREAD

**Issue by yxh0714** [begeekmyfriend/yasea#807]
博主你好，我自己使用腾讯云服务器搭建了srs服务器，我在服务器上使用ffmpeg推流一个视频，安卓端拉流可以成功播放，我使用安卓端推流的时候，使用云服务器公网地址就会闪退，使用云服务器内网地址就会出现连接失败并弹出以下Toast "failed to connect to /10.0.0.15 (port1935) from /10.65.76.231 (port 49842)after 3000ms: isConnected failed:ECONNREFUSED (Connection refused)"
我服务器也开了1935端口的，请教一下是哪里出了问题呢

**Comment by begeekmyfriend** [comment]
估计你的URL里面没有鉴权吧，所以被拒绝了

**Comment by yxh0714** [comment]
![1245D36F9B11202EE114E90FA48ACD7E](https://user-images.githubusercontent.com/58198675/111740623-0988f100-88c0-11eb-8365-98060b1766c6.jpg)

**Comment by yxh0714** [comment]
我刚刚使用OBS推流也成功了，安卓端URL填写成rtmp://139.155.83.204:1935/live/livestream 时就会闪退，把live去掉或者改成数字就会出现上图所示了

**Comment by yxh0714** [comment]
问题已解决，RtmpConnection.java里面，serverId数据类型转换错误，初始化为AmfNumber,在onSrsServerInfo()方法，getServerId()方法中数据转换有问题。如下修改即可

**Comment by yxh0714** [comment]
![Uploading `]WE$%O]T`8IKHEZN]U9~SU.png…]()

**Comment by yxh0714** [comment]
![` WE$%O T`8IKHEZN U9~SU](https://user-images.githubusercontent.com/58198675/111766549-a2c7ff80-88e0-11eb-949a-497b37aff218.png)

**Comment by begeekmyfriend** [comment]
Fixed! Many thanks!
