### ISSUE TITLE
小白求助 已有已编码流 怎么把它推流出去

### ISSUE THREAD

**Issue by a354123417** [begeekmyfriend/yasea#814]
本人PHPer
已知有
`@Override
        public void onVideoFrame(ByteBuffer byteBuffer, MediaCodec.BufferInfo bufferInfo) {
//            Log.d(TAG, "Receive video frame" + System.currentTimeMillis());
        }

        @Override
        public void onAudioFrame(ByteBuffer byteBuffer, MediaCodec.BufferInfo bufferInfo) {
//            Log.d(TAG, "Receive audio frame");
        }`
我是这样推出去的：
mFlvMuxer = new SrsFlvMuxer(new RtmpHandler(this));
mFlvMuxer.start(rtmpUrl);
mFlvMuxer.writeSampleData(100, byteBuffer, bufferInfo);
遇到的问题：电脑端能看，手机端直接播放m3u8也能看，但是用videojs播放器播放10s左右才更新一次画面，请问问题可能出在什么地方？

**Comment by begeekmyfriend** [comment]
videojs我不熟啊

**Comment by a354123417** [comment]
好的 谢谢！
