### ISSUE TITLE
google在N上对.so库的加载进行了限制，限制了so库指从部分指定的路径进行加载

### ISSUE THREAD

**Issue by pengguanming** [begeekmyfriend/yasea#816]
java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/lib/libyuv.so" needed or dlopened by "/apex/com.android.art/lib/libnativeloader.so" is not accessible for the namespace "classloader-namespace"

**Comment by pengguanming** [comment]
是因为没有引入libyuv.so所导致

**Comment by begeekmyfriend** [comment]
[SrsEncoder.java](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L652)不是在静态加载的时候引入吗

**Comment by pengguanming** [comment]
是我自己没有在module项目依赖引入so文件，实在不好意思，打扰您了
