### ISSUE TITLE
只推音频的情况下，延迟比同时推音视频要高很多

### ISSUE THREAD

**Issue by hfutxqd** [begeekmyfriend/yasea#82]
为什么在只推音频的情况下，延迟比同时推音视频要高很多很多，能达到6~8秒

**Comment by begeekmyfriend** [comment]
你确定每次都是6~8秒？

**Comment by hfutxqd** [comment]
差不多每次都有这么长的延迟

**Comment by begeekmyfriend** [comment]
那你很可能改动有问题了，你把视频的preview callback里面的内容注释掉，或者`mCamera.setPreviewCallback(null)`试试

**Comment by hfutxqd** [comment]
是不是有一个缓冲区，只有缓冲区到了一定大小之后在进行推流操作？视频+音频比较大，单单音频的话比较小，所以延迟提高了？

**Comment by hfutxqd** [comment]
按照我打得Log来看，在我开始纯语音推流后，WriteThread就已经立即在发送了，但是就是有很长时间的延迟

**Comment by begeekmyfriend** [comment]
有音频就直接发的啊，不需要缓冲，还是排查一下服务器和播放端的问题吧

**Comment by zzzlq** [comment]
请问下服务器采用hls，如果我同时推视频和音频是正常的，但如果只推音频的话收听的时候会卡顿，请问是为什么啊

**Comment by begeekmyfriend** [comment]
这我就不清楚了

**Comment by begeekmyfriend** [comment]
See https://github.com/begeekmyfriend/yasea/commit/9339e9d5442281c84a5882a831ba675637348fcd
