### ISSUE TITLE
Is it possible to include a custom message in an RTMP packet header?

### ISSUE THREAD

**Issue by stefanjaspers** [begeekmyfriend/yasea#820]
I need to be able to send custom data along with an RTMP packet. I was wondering if the RTMP protocol supports a way to do this.

**Comment by begeekmyfriend** [comment]
You might check the [SimpleRTMP](https://github.com/begeekmyfriend/yasea/tree/master/library/src/main/java/com/github/faucamp/simplertmp) package source and try your own solution. I am no longer in Android development.
