### ISSUE TITLE
Network weak

### ISSUE THREAD

**Issue by DoubleCcc** [begeekmyfriend/yasea#831]
您好，请问为什么在AndroidStudio里或者安卓模拟器可以连接上nginx并推流成功，在手机上则显示Network weak，电脑与手机在同一个wifi，地址都为 rtmp://(nginx所在linux虚拟机ip):1935/mylive/xxx 
nginx.conf 部分配置：application mylive{
			live on;
			hls on;
			hls_path /usr/local/m3u8File;			
			hls_fragment 2s;
			hls_playlist_length 16s;
			recorder myRecord {
				record all manual;
				record_suffix _.flv;
				record_path /tmp/rec;
		}
	}
-----------------
listen       80;
        server_name	localhost;

**Comment by DoubleCcc** [comment]
我没有改代码，手机连接了电脑分享的wifi ，然后就能推流成功了 谢谢！

**Comment by begeekmyfriend** [comment]
是挺不容易的，祝好
