### ISSUE TITLE
关于终端播放延迟降低

### ISSUE THREAD

**Issue by cl1069573062** [begeekmyfriend/yasea#84]
我现在用yesea推流后，用nginx-rtmp来做服务器，用SRS的播放器做测试。硬编码大概有2秒左右的延迟，软编码的话延迟更加厉害。         延迟的影响是不是主要产生在在play端和server端，你有什么好的建议在server端和play端上做处理能更好的降低延迟。 server端的缓存怎么处理，能对延迟降低能有帮助。谢谢！

**Comment by begeekmyfriend** [comment]
Yasea的缓冲就是2s，如果网络通畅的话，一般不会积累缓存，所以个人倾向于认为是服务端和播放器导致的，但是我没深入接触过，所以无法提供专业建议。

**Comment by begeekmyfriend** [comment]
不好意思，see https://github.com/begeekmyfriend/yasea/commit/9339e9d5442281c84a5882a831ba675637348fcd
