### ISSUE TITLE
连接失败

### ISSUE THREAD

**Issue by sankycui** [begeekmyfriend/yasea#86]
今天我用yasea测试，显示如下：
failed to connect to ossars.net/182.92.80.26(port 1935) after 3000ms: is Connected failed: ECONNREFUSED(Connection refused).
服务器为什么会拒绝服务呢？

**Comment by begeekmyfriend** [comment]
这需要看服务器log了，公网时有故障的，一般都会几天内修复。如果你不放心可以自己搭建一个。

**Comment by sankycui** [comment]
好的，我还以为您加了什么权限限制了呢，谢谢您！

**Comment by begeekmyfriend** [comment]
ossrs.net不是我维护的

**Comment by sankycui** [comment]
哦哦，那我问下ossrs他们。
