### ISSUE TITLE
推流界面处于onpause状态时怎么让摄像头继续采集数据

### ISSUE THREAD

**Issue by FrankLove** [begeekmyfriend/yasea#861]
大佬，请问当打开摄像头推流界面开推流后，这时又打开了一个新的activity导致之前推流的界面处于onpause状态，摄像头数据采集也就停了，我想在这种情况下继续保持摄像头数据采集，有什么办法吗？我的想法是在打开B界面时把A界面里的SrsCameraView从布局里移除掉，然后添加到一个悬浮窗，但是添加到悬浮窗的SrsCameraView 无法正常预览。

**Comment by begeekmyfriend** [comment]
已经脱离安卓开发几年了，不好意思
