### ISSUE TITLE
推流的视频很糊

### ISSUE THREAD

**Issue by chen1986923** [begeekmyfriend/yasea#865]
推到后端的视频流包括本地录制的视频流都很糊， 但是系统自动的拍照应用录制视频很清晰。 请问排查这个问题需要查看哪块的代码逻辑？

**Comment by begeekmyfriend** [comment]
[SrsCameraView](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsCameraView.java)，另外这个项目已经很老了，可能SDK与你的机型不太匹配？你试着自己调试一下
