### ISSUE TITLE
yasea推流是不是只支持armeabi-v7a架构的手机

### ISSUE THREAD

**Issue by atlearn** [begeekmyfriend/yasea#87]
你好，请问一下，yasea推流是不是只支持armeabi-v7a架构的手机，我看jnilibs里面只有v7a的so文件。

**Comment by begeekmyfriend** [comment]
See #74

**Comment by atlearn** [comment]
嗯 看了 但还不是很明白，你的意思是把其他的so加进来之后，然后再修改Application.mk吗

**Comment by begeekmyfriend** [comment]
重新`ndk-build`

**Comment by atlearn** [comment]
好的 如果不重新ndk-build，是不是只支持armeabi-v7a架构的手机

**Comment by begeekmyfriend** [comment]
对

**Comment by shishuo365** [comment]
其他架构主要是 libx264 库的编译，可以参照这个，特意为yasea量身定作的扩展
https://github.com/shishuo365/libx264-android

**Comment by begeekmyfriend** [comment]
Fixed https://github.com/begeekmyfriend/yasea/commit/40ba529a717ae011d3f17a1e8eadf87057ad7c71
