### ISSUE TITLE
How is the flv muxed

### ISSUE THREAD

**Issue by gouravd** [begeekmyfriend/yasea#9]
I have a test server with Nginx and RTMP-Module. When I am trying to stream to the server I am not able to view the rtmp tream in VLC or any other player.

I am also trying a command like this

exec_push ffmpeg -i rtmp://127.0.0.1:1935/staging_live_v1/$name -map 0:a -map 0:v -c copy -b:v 512k -r 30 -movflags faststart /Videos_staging/staging_mp4/$name.mp4 2>>/Videos_staging/staging_mp4/$name-out.txt;

it is failing with the following

Input #0, flv, from 'rtmp://127.0.0.1:1935/staging_live_v1/tst':
  Duration: N/A, start: 26.979000, bitrate: N/A
    Stream #0:0: Audio: aac (LC), 44100 Hz, stereo, fltp
Stream map '0:v' matches no streams.

**Comment by begeekmyfriend** [comment]
Maybe in yasea, flv not include the header?
https://github.com/ossrs/srs-sea/blob/master/app/src/main/java/net/ossrs/sea/SrsHttpFlv.java#L284-L290

Or not include the previous tag size?
https://github.com/ossrs/srs-sea/blob/master/app/src/main/java/net/ossrs/sea/SrsHttpFlv.java#L406-L432

After all, I have modified the original file.

**Comment by gouravd** [comment]
Since I haven't seen the FLV specifications, not sure about the details of the headers. Would you happen to know what change needs to be done to get it working.

Or in other words is the FLV being sent has both Audio and Video streams in Stream 0? Or is the layout different? From the Nginx-RTMP  logs it looks different but not sure how it is muxed in Yasea

**Comment by begeekmyfriend** [comment]
I modified the FLV muxing file at that time because there is no proper meta data about the AV streams, and it got working well on servers such as SRS and FMS.

The HTTP-FLV needs the whole FLV structure to store in the cache of server as a file for video on demand (VOD) which is not supported by RTMP.

To know about the FLV structure, what you need is to download the `flvparse` tool and an FLV file. Actually it is much simpler than MP4.

I will try Nginx-RTMP someday though it is not the first choice in streaming industry.

**Comment by gouravd** [comment]
I thought Nginx-Rtmp was the most used opensource/free Media server.

Anyways since SRS is closed and I dont see much activity in the forks I find it risky to invest much without a large in-house development house for SRS.

I tried Nimble streamer and had better success with Yasea-Nimble streamer than Yasea-Nginx.

**Comment by begeekmyfriend** [comment]
Patch https://github.com/begeekmyfriend/yasea/commit/882ce15d3e2bd243d5b0fd0f247cc7840f86e92b has fixed it!

What fails to stream on nginx-rtmp is lack of [onMetaData](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/sea/rtmp/io/RtmpConnection.java#L495) function following `NetStream.Publish.Start` response and before AV streaming. And the metadata could be a null object if no proper metadata provided. **In fact, SRS and FMS choose to ignore `onMetaData` if not provided while nginx-rtmp does not.** I have learnt that from SRS sources which is really simpler and cleaner than that of nginx-rtmp:)

By the way, the first appearance of AV stream from nginx-rtmp at player peer, especially for VLC, is really a long time...

**Comment by gouravd** [comment]
"By the way, the first appearance of AV stream from nginx-rtmp at player peer, especially for VLC, is really a long time..." ---> You are spot on. 

"Moreover, the SRS project has been closed for business due to its outstanding performance. You may see the benchmark compared with nginx-rtmp." ---> No doubt SRS was one the great Streaming servers. We were seriously contemplating to replacing Nginx-Rtmp with it. Unfortunately the close of SRS forced us to rethink Nimble Streamer, Red5Pro and other similar servers likewise.

I will try the new commit soon

**Comment by gouravd** [comment]
I tried the new commit for this. But the problem continues. I tried ffplay and this is what I got

Metadata:  :  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0
  Server                NGINX RTMP (github.com/arut/nginx-rtmp-module)
  width                 0.00
  height                0.00
  displayWidth          0.00
  displayHeight         0.00
  duration              0.00
  framerate             0.00
  fps                   0.00
  videodatarate         0.00
  videocodecid          0.00
  audiodatarate         0.00
  audiocodecid          16.00
[live_flv @ 0000000004fbb440] Could not find codec parameters for stream 0 (Video: none, none): unknown
 codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, live_flv, from 'rtmp://streamingstaging.voola.me:1935/staging_live_v1/tst':
  Metadata:
    Server          : NGINX RTMP (github.com/arut/nginx-rtmp-module)
    displayWidth    : 0
    displayHeight   : 0
    fps             : 0
    profile         :
    level           :
  Duration: 00:00:00.00, start: 147.857000, bitrate: N/A
    Stream #0:0: Video: none, none, 1k tbr, 1k tbn, 1k tbcB f=0/0
    Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp
No codec could be found with id 0
 160.21 M-A:  0.000 fd=   0 aq=    1KB vq=    0KB sq=    0B f=0/0

As you can see, there is no Video, just audio

Also in the Nginx-Rtmp stats this is what is seen

tst	1	H264  	541 Kb/s	0x0	0	AAC LC	35 Kb/s	44100	2	2.96 MB	308 KB	577 Kb/s	57 Kb/s	active	45s 

BTW earlier the codec used to be H264 Baseline 3.0, now its just H264

**Comment by gouravd** [comment]
Actually with the patch 882ce15 even publishing to Nimble Streamer is not working properly. I just checked and found that there is no video data at the Nimble streaming server. Whereas in the logs I can see the Video Data is being sent.

**Comment by begeekmyfriend** [comment]
It seems nginx does not deal with video stream unless specific metadata has to be provided...

**Comment by gouravd** [comment]
Looks like the emptyMetaData() is causing the issue on Nimble Streamer as well.

**Comment by gouravd** [comment]
Since we will be anyways moving away from Nginx Rtmp, I will be doing most of the testing on Nimble Streamer which looks like the best Stream Server money can buy. Actually its free to install and use, the charge is for wmspanel for administration.

**Comment by begeekmyfriend** [comment]
I found the cause. It is nginx that lost the most number of video frames without metadata while the audio frame is all right. Yet sometimes they are both all right as I tested on afternoon. If you wait 20 minutes you will find there are still several number of video frame appear suddenly and then it comes still picture again. I watched it with VLC.

I guess Nimble Streamer run the same "strategy" as nginx does though I get no access to the source. There is no problem on SRS and FMS.

**Comment by begeekmyfriend** [comment]
By the way, there is business version for SRS called [BMS](https://github.com/ossrs/srs/wiki/BravoMediaServer) maintained by chnvideo where the author of SRS takes office.

**Comment by begeekmyfriend** [comment]
Hey, how about just commenting the `onMetaData()` in `RtmpConnection`?  As for me, it seems to work well on nginx-rtmp.

**Comment by begeekmyfriend** [comment]
Hey, how about just commenting the `onMetaData()` in `RtmpConnection`? As for me, it seems to work well on nginx-rtmp.

Here is my nginx configuration
```shell
rtmp {
    server {
        listen 1935;
        application app {
            live on;
        }
    }
}
```

**Comment by gouravd** [comment]
I am not sure I followed you correctly. Because I tried to comment out the onMetaData(); in handleRxInvoke function in RtmpConnection. But still video data is not read in Nginx-Rtmp

**Comment by begeekmyfriend** [comment]
I have decided to revert `onMetaData` on commit https://github.com/begeekmyfriend/yasea/commit/b5e39cb218520713b9316611433dda76c59cd694

@fly518420 who also uses nginx-rtmp said it is all right for him.
