### ISSUE TITLE
关于闪光灯

### ISSUE THREAD

**Issue by JakeRed** [begeekmyfriend/yasea#91]
闪光灯的设置为开时，程序ANR，确定已经给了相关的权限，只在代码的set里给予打开闪光灯。
还有一个问题您们的代码怎么改speex codec ，是不是需要重新编一份so？

**Comment by begeekmyfriend** [comment]
speex是native代码，肯定要重编so的，不过拉流端需要配合，不然声音无法解码。

**Comment by JakeRed** [comment]
播放端可以支持speex codec，但是我得到的代码不能自己去编写codec。
以前编译PJSIP，添加G729 codec，算是有这方面的经验。不过没有c文件，也做不了这事/

**Comment by begeekmyfriend** [comment]
yasea提供了jni源码的

**Comment by JakeRed** [comment]
谢谢！
