### ISSUE TITLE
横竖屏的问题

### ISSUE THREAD

**Issue by JakeRed** [begeekmyfriend/yasea#92]
横屏后推的流播放和我预览这边的图像不一样，推的流逆时针旋转90度才能和预览的一样，预览端显示正常。这是那个参数的问题呢，谢谢！

**Comment by begeekmyfriend** [comment]
[这一行](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/SrsEncoder.java#L401)最后一个参数就是旋转角度。

**Comment by JakeRed** [comment]
谢谢你，我找到了我的问题，是因为少了                    mEncoder.setScreenOrientation(Configuration.ORIENTATION_LANDSCAPE);
嗯，我想如果动态调节推流分辨率的话，对Camera对象进行setPictureSize(width, height)就好，还是去setVideoResolution呢？

**Comment by begeekmyfriend** [comment]
推流分辨率就是输出分辨率，调用`setVideoResolution`，摄像头是采集分辨率（预览）
