### ISSUE TITLE
Square aspect proportions

### ISSUE THREAD

**Issue by AntonZorin** [begeekmyfriend/yasea#93]
Hi, is there some way to set 1:1 or 4:3 aspect proportions on preview?

**Comment by begeekmyfriend** [comment]
Change the camera preview resolution constant value as supportable.

**Comment by begeekmyfriend** [comment]
In `MainActivity .java`
```java
mPublisher.setPreviewResolution(1280, 720);
```

**Comment by AntonZorin** [comment]
Thanks for your answer. I tried such config - mPublisher.setPreviewResolution(480, 480); I need square aspect proportions. But had no luck. Only black screen is displayed and debugger shows message: "VideoCapabilities: Unrecognized profile 2130706433 for video/avc". I know phone camera is support square resolution 713x713, but when i set it as preview resolution in mPublisher - black screen.

**Comment by begeekmyfriend** [comment]
```java
Camera.Size size = mCamera.new Size(mEncoder.getPreviewWidth(), mEncoder.getPreviewHeight());
if (!params.getSupportedPreviewSizes().contains(size) || !params.getSupportedPictureSizes().contains(size)) {
            Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(),
                    new IllegalArgumentException(String.format("Unsupported resolution %dx%d", size.width, size.height)));
}
```

**Comment by AntonZorin** [comment]
Thank you wery much, but I had no luck making video square that way. Could you help? I need crop video preview and output to make it square.  Where shoud I put keys ""crop-left"/"crop-right" to make crop rectangle?

**Comment by begeekmyfriend** [comment]
No way for preview but output resolution can be set as long as the player supports the display.
```java
mPublisher.setOutputResolution(713, 713);
```

**Comment by iSinch** [comment]
I set outputResolutions is SrsPublisher so  :
```
 private void getSupportedResolutions(Camera.Parameters params) {
        List<String> list = new ArrayList<>();
        SharedPreferences.Editor ed = sPref.edit();
        StringBuilder sb = new StringBuilder();

        List<Camera.Size> pictureSizes = params.getSupportedPreviewSizes();


        for (int i = 1; i < pictureSizes.size(); i++) {
            list.add(String.valueOf(pictureSizes.get(i).width) + "x" + String.valueOf(pictureSizes.get(i).height));


            if (pictureSizes.get(i).height % 32 != 0 && pictureSizes.get(i).width % 16 != 0) {
                saveNewResolutionsList(ed, sb, pictureSizes, i);
            } else {

               //  the stride must be set as 32x
                pictureSizes.get(i).height = pictureSizes.get(i).height - pictureSizes.get(i).height % 32;
                //stride of resolution must be set as 16x
                pictureSizes.get(i).width = pictureSizes.get(i).width - pictureSizes.get(i).width % 16;
                saveNewResolutionsList(ed, sb, pictureSizes, i);

            }
        }
    }

    private void saveNewResolutionsList(SharedPreferences.Editor ed, StringBuilder sb, List<Camera.Size> pictureSizes, int i) {
        sb.append(String.valueOf(pictureSizes.get(i).width) + "x" + String.valueOf(pictureSizes.get(i).height)).append(",");
        ed.putString("resolutions", sb.toString());
        ed.apply();
    }
```

It's true way ? )

**Comment by AntonZorin** [comment]
Not in my case :) I need somehow make video preview on surfaceView square. But its not trivial task.

**Comment by begeekmyfriend** [comment]
Use `TextureView`.

**Comment by iSinch** [comment]
@AntonZorin попробуй запихать в  surfaceView в `AspectRatioFrameLayout` и дальше как тебе нужно

**Comment by AntonZorin** [comment]
@begeekmyfriend because video inside surfaceview will be distorted. Its not a problev ajust surface by layout params. But I get stretched faces.

**Comment by AntonZorin** [comment]
@iSinch клиент упёрся в то, что превью должно быть квадратным и квадратом стримиться на сервак,  я мог бы менять высоту и ширину surfaceView, но морды то тянет. В камере есть квадратные аспект пропорции, но когда ставлю их (например mPublisher.setPreviewResolution(400, 400);) либа просто не работает. Выдаёт что не найден соответствующий профиль.

**Comment by iSinch** [comment]
У него много чего не работает )

**Comment by AntonZorin** [comment]
@iSinch Лучшего пока не нашел.
