### ISSUE TITLE
长时间推送自动停止的问题

### ISSUE THREAD

**Issue by studyzhxu** [begeekmyfriend/yasea#94]
在用手机推送大约40分钟的时候，推送自动停止，跟踪log发现，推送停止的时候SrsRtmpPublisher中的方法publishVideoData中的dts为负值，分析代码发现在正常推送的情况下SrsEncoder中的onGetYuvFrame()方法中的pts值和onSoftEncodedData()方法中的pts值是相等的。但是推送停止的时候发现两者不相等。因为onSoftEncodedData()方法是在JNI层被调用的，onGetYuvFrame()方法调用JNI层的NV21SoftEncode()，在JNI层调用Java层的onSoftEncodedData()方法。
在正常推送的时候NV21SoftEncode()方法中接收的参数pts和onSoftEncodedData()中的pts值相等，而onSoftEncodedData中的pts值是有JNI层中的NV21SoftEncode()方法经过处理传入的。处理部分代码如下int es_len = x264_ctx.global_nal_header ? encode_global_nal_header() : x264_encode(&i420_scaled_frame, pts);
正常情况下处理完后两者是相等的。
调用onSoftEncodeData()方法传入参数部分如下
jmethodID mid = env->GetMethodID(clz, "onSoftEncodedData", "([BJZ)V");
    env->CallVoidMethod(thiz, mid, outputFrame, x264_ctx.pts, x264_ctx.is_key_frame);
可以看到x264_ctx.pts就是传入的pts值，在失败的时候发现这个值为负值，正常情况下是为正值的，所以可以肯定推送失败是由负值引起的，所以为什么为负值呢？？？

为什么会出现负值呢？？？？？

**Comment by begeekmyfriend** [comment]
`x264_ctx.pts`是libx264输出的PTS值，估计有溢出导致高位置1，我也不知道x264里面对PTS做了什么处理，一种避免方式是使用送入x264之前打的pts，做法是在[这一行](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/SrsEncoder.java#L318)里的pts参数使用[这个值](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/SrsEncoder.java#L339)。

**Comment by begeekmyfriend** [comment]
估计x264的pts有溢出行为，我查了一下x264默认timebase毫秒级别，而Java层是以微秒单位，所以你在调用`NV21SoftEncode`可以试试pts/1000，然后在`onSoftEncodedData`中再讲pts*1000

**Comment by begeekmyfriend** [comment]
自己测了一小时，软编码模式，还是怀疑您的结论。我没有遇到过pts为负值的情况。你确定每次都是40分钟断开吗？

**Comment by studyzhxu** [comment]
谢谢解答
目前采用第一种方法测试推送1小时30分钟没有问题，只测试到1小时30分钟，没有测试更长时间，虽然不会出现推送自动停止的问题了，但是随着连续推送时间的增加，播放画面会越来越卡顿，
long pts = System.nanoTime() / 1000 - mPresentTimeUs;这个pts的值会越来越大。

接下来会测试第二种方法看看效果怎么样

**Comment by begeekmyfriend** [comment]
所以我怀疑断开是否由于时间戳引起的，你有异常记录吗？

**Comment by studyzhxu** [comment]
目前来看，断开确实是时间戳引起的，具体的异常记录在公司的电脑上，周一发上来

**Comment by studyzhxu** [comment]
08-25 16:19:10.921 2826-12791/net.ossrs.yasea D/WriteThread: WriteThread: wrote packet: RTMP Audio, size: 104
08-25 16:19:10.921 2826-12791/net.ossrs.yasea D/WriteThread: WriteThread: waiting...
08-25 16:19:11.197 2826-2826/net.ossrs.yasea I/libx264: frame :-416128224 Avg QP:-1294188789278876886633237509822411580023734510702186182064902350443774696017694217229640402938959380769274886689461167279947999554980644782124014970272345890638746637252773569789857359724544.00  size:-78024513713269669300735065493216204495354982665621633826069264698436395546116666091956798116071835605773257144921594789452129208311992695228407617590842328453973646680176507832930915522392351389651799372687340557067117681089193104513766549470898531970012060445981412594944603994299173407445310563990567387136
08-25 16:19:11.197 2826-2826/net.ossrs.yasea I/libx264: frame :-416128224 Avg QP:-1294188789278876886633237509822411580023734510702186182064902350443774696017694217229640402938959380769274886689461167279947999554980644782124014970272345890638746637252773569789857359724544.00  size:-78024513713269669300735065493216204495354982665621633826069264698436395546116666091956798116071835605773257144921594789452129208311992695228407617590842328453973646680176507832930915522392351389651799372687340557067117681089193104513766549470898531970012060445981412594944603994299173407445310563990567387136
08-25 16:19:11.198 2826-2826/net.ossrs.yasea I/libx264: mb I  8���e�l!�C@
08-25 16:19:11.198 2826-2826/net.ossrs.yasea I/libx264: mb P  8���9Ԯ��K@  P16..4:  0.0% -1294188789276629147944649935816869733112707957039146908364270537242635690963921967247872241330115545316430309896595703642028364880664619576692235215276160831181180632142747447444569981976576.0% -78024552429415053240739298772731118327084100498083805360440850200212470109388674021679720777810876644682705653322159552857762090899422862141681328196950141063535911513908442111653602856644009750057346215634376852192072481519063924042832925307624126369491289444613743558297116100592426680062791078853744787456.0%  0.0% -1377381035803980713416156270877081002383249966849273713283883303606131337258993130414731507274337558270846618140821546209061731719478610186500089418216155382651267656731675160759095412129792.0%    skip:-7803706764993892564819745610926504740247078887847761348988363395628096551880636693954729072004967274212504571086943563012742973907557409972023744806516800274484183637013134399052585228564959174715642443965091369091360534777353118932910334234658203340369097850370335267108
08-25 16:19:11.199 2826-2826/net.ossrs.yasea I/libx264: final ratefactor: -0.00
08-25 16:19:11.200 2826-2826/net.ossrs.yasea I/libx264: i16 v,h,dc,p:  0% -1294188540386643287522401861815991660742517185824591042802693958164989779027285429484050059090131122760734766313277949649658984149053184611333904732071529030354347819612929640597002003677184% -78024513741275739608994351528736990806684769529164644751776900721459269012388959545278313059260838468318329682461487658908144023924367619017903970428939749745302023833019297837028598974135274555257818568691512642645041822226889569598322729359272504645034074633835984726824725436953909131386448386980831035392%  0%
08-25 16:19:11.200 2826-2826/net.ossrs.yasea I/libx264: i-2373868 v,h,dc,ddl,ddr,vr,hd,vl,hu:  0% -1294188540386643287522401861815991660742517185824591042802693958164989779027285429484050059090131122760734766313277949649658984149053184611333904732071529030354347819612929640597002003677184% -78024513741275739608994351528736990806684769529164644751776900721459269012388959545278313059260838468318329682461487658908144023924367619017903970428939749745302023833019297837028598974135274555257818568691512642645041822226889569598322729359272504645034074633835984726824725436953909131386448386980831035392% -78052487331755288442497976427073631053547903197651483375080254315930036011315412751765091958782953978384181894650033347094671314755247272098747919531514102710230852988538272068872384445303798744508196549836349568467552867640532576829221951151360213242540595997245476397521076482317395557742313413162035052544% -138390765945971339485525540386373179737839702672709351668750717438817781026561937567073544263403986604954699146459353281120973650251902600442298790646644917557810855
08-25 16:19:11.201 2826-2826/net.ossrs.yasea I/libx264: i8c dc,h,v,p:  0% -1294188540386643287522401861815991660742517185824591042802693958164989779027285429484050059090131122760734766313277949649658984149053184611333904732071529030354347819612929640597002003677184% -78024513741275739608994351528736990806684769529164644751776900721459269012388959545278313059260838468318329682461487658908144023924367619017903970428939749745302023833019297837028598974135274555257818568691512642645041822226889569598322729359272504645034074633835984726824725436953909131386448386980831035392%  0%
08-25 16:19:11.201 2826-2826/net.ossrs.yasea I/libx264: kb/s:-2177133467358781997784451154537733179058293234467162490919395932383805635112812323174024933472500819811422479912087950125260139391062927967157691360278204861863717488620378933413780159201280.00
08-25 16:19:11.203 2826-2826/net.ossrs.yasea I/SrsEncoder: stop aencoder
08-25 16:19:11.218 2826-2826/net.ossrs.yasea I/SrsEncoder: stop vencoder

**Comment by begeekmyfriend** [comment]
我还是没复现到你描述的问题，请问你clone哪个版本？

**Comment by studyzhxu** [comment]
clone的最新版本，用的软编码，推送40分钟左右会出现停止的问题，如果直接换成你说的两个方案就没有这个问题

**Comment by studyzhxu** [comment]
还有就是每次执行到long pts = System.nanoTime() / 1000 - mPresentTimeUs;的时候，pts的值都会比之前的大，随着时间的推移的持续增长的

**Comment by begeekmyfriend** [comment]
PTS本来就是单调递增的

**Comment by studyzhxu** [comment]
对对，是我糊涂了

**Comment by begeekmyfriend** [comment]
Sorry for my carelessness https://github.com/begeekmyfriend/yasea/commit/03b2dbb1e4e789f1e8cbfb30f414cb93a17df039

**Comment by begeekmyfriend** [comment]
其实快速复现问题的方法就是`pts += 2147483647`
