### ISSUE TITLE
Trying to record video without broadcasting and it saves a movie without sound

### ISSUE THREAD

**Issue by jilagan** [begeekmyfriend/yasea#96]
Hi. I've been trying to get recording (without broadcasting) to work but the saved mp4 does not have audio. It's only when I try broadcasting and recording at the same time that there is sound.

Is there a way to include audio in the recorded file?

I checked previous issues and I couldn't find any solution.

**Comment by begeekmyfriend** [comment]
Please ensure [this line](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/SrsEncoder.java#L371) is accessible.

**Comment by jilagan** [comment]
The line is there, and there's no sound.

**Comment by begeekmyfriend** [comment]
I mean whether the program passes this line.
