### ISSUE TITLE
预览问题

### ISSUE THREAD

**Issue by JakeRed** [begeekmyfriend/yasea#97]
您好，我遇到一个简单的问题，但是我按着自己想法更改总是报错，我想更改您的程序为预览一直打开，一直能看到本地预览，推流的按钮按了直接推流，不去操作摄像头，但是我把摄像头一直开着，推流的时候不去操作它，Toast一直显示libyuv failure。

**Comment by begeekmyfriend** [comment]
能把问题描述清楚点吗，你改了什么地方

**Comment by JakeRed** [comment]
这样吧，我就想让预览一直打开，我应该改哪些代码呢？

**Comment by begeekmyfriend** [comment]
可以考虑直接把publish的代码写在`onCreate`里啊

**Comment by JakeRed** [comment]
我的版本是1.2，我把flvMuxer.start注释掉，因为我觉得它的作用是开始推流，flvMuxer.start放到了onclick方法，这样的结果是点击后就卡死程序。

**Comment by JakeRed** [comment]
我甚至想过做一个全局的标志位，预览的问题是解决了，但是真正想推流的时候却推不出去，我的标志位放在sendFlvTag和send都试了

**Comment by JakeRed** [comment]
我预览的问题解决了，但是用预览录制视频又陷入了僵局，开始录制视频后到结束的时候，程序VM卡死，如果您有空看到我的问题，还希望提一点建议。

**Comment by begeekmyfriend** [comment]
那是你自己改出来的啊，我怎么看？

**Comment by JakeRed** [comment]
也是，我还在改，只是希望少走点弯路，谢谢你，目前可以不推流录制，只是没有声音，我再看看，谢谢您的源码。

**Comment by wenjue** [comment]
@JakeRed 您好，我想问一下您是怎么解决预览问题的

**Comment by JakeRed** [comment]
预览问题jiu'h就是把如图这些方法放onCreate()；然后去推流的类里吧推流打断，设置标志位，通过set方法就好，当然这方法不一定是最优的，但能解决你的问题。
![image](https://cloud.githubusercontent.com/assets/21214880/18228667/fae65dd6-728a-11e6-8d50-2973f79182c9.png)

**Comment by JakeRed** [comment]
博主， @begeekmyfriend                     
 if (rtmpPacket instanceof Video) {
                publisher.getVideoFrameCacheNumber().getAndDecrement();
                calcFps();
            }
在线程里有这个方法，那问一下有没有对音频的该方法在某个线程里。

**Comment by JakeRed** [comment]
或者说怎么让推流不推，但数据流还是在队列了FIFO？看一天没找到。

**Comment by begeekmyfriend** [comment]
光预览不推流就不要送数据到编码器啊，比如怎么[只推流音频]（https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/SrsPublisher.java#L274）

**Comment by JakeRed** [comment]
如果没有数据流，那么录视频就完不成。

**Comment by begeekmyfriend** [comment]
See [it](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/SrsEncoder.java#L327)

**Comment by JakeRed** [comment]
嗯，谢谢你，只是新的问题是，录制视频后，程序推流无法推流了，可能是启动的问题，估计flv.start(Url)得重新开启一下。

**Comment by JakeRed** [comment]
录制视频后，程序推流无法推流了,当停止录制，推流马上才生效，这个解决方法貌似还是未解决我的问题，，

**Comment by JakeRed** [comment]
博主，录制视频的start里是和推流的某个位置冲突吗？为啥一进程序录视频后不停止录制视频的情况下推流推不出去，然后只要录制一结束马上推流了。谢谢。

**Comment by begeekmyfriend** [comment]
这是你自己改出来的，录制和推流在模块上是解耦的

**Comment by wenjue** [comment]
@JakeRed  哦哦，谢谢，我明天试一下

**Comment by JakeRed** [comment]
@wenjue 一起研究。

**Comment by JakeRed** [comment]
@begeekmyfriend 看代码我也觉得是解耦的，觉得两者没关系，但实际操作中，唯一意外的是，打开APP直接录制视频，然后视频录制中再推流，要么推流不被触发，待录制一结束推流才触发，估计就是我没发现这个小地方，我想到你给我说的方法我之前也试过，就是刚刚说的那个问题，但一直没找到解决办法，还在研究中，或许时间不够，我还需要好好理解理解。

**Comment by JakeRed** [comment]
按着解耦的逻辑，录音就会没声音。

**Comment by begeekmyfriend** [comment]
推流看`connect()`

**Comment by JakeRed** [comment]
start(url)便是connect()；然后我的问题呢其实和我改代码没关系，因为推流和录视频是解耦的，我将预览打开后，第一件事是录制视频，如果在录制视频的过程中不推流，那么录制视频好用，但是当在录制视频中点击推流，那么推流这件事进入了等待队列，当录制视频结束后，推流开始，我估摸这这是某个标志位或者流数据的问题，让其一直等待了。

**Comment by JakeRed** [comment]
并且，这种情况下推流已经走到了WriteThread这个线程，且帧数据并不为null。

**Comment by JakeRed** [comment]
frame.is_keyframe()这个管connect(),当录制视频时推理，frame.is_keyframe()一直为为false，那怕让connect强制连接，也不会推流。

**Comment by begeekmyfriend** [comment]
不可能连一个key frame都没有吧

**Comment by JakeRed** [comment]
我其实就改了            
mp4Muxer.writeSampleData(videoMp4Track, record, bi);
flvMuxer.writeSampleData(videoFlvTrack, es, bi);
这个位置，对flvMuxer.writeSampleData(videoFlvTrack, es, bi);用标志位判断是否write，但是当录制视频开始后，启动flvMuxer.writeSampleData(videoFlvTrack, es, bi)不能跑WriteThread线程，也不会产生key frame。

**Comment by JakeRed** [comment]
这一块改了好几天了，总觉得推流和录制是有关系的，不是完全解耦的，可能小弟才疏学浅。

**Comment by begeekmyfriend** [comment]
录制没有关键帧也是不可能成功播放出来的，你要确定关键帧是下来的

**Comment by JakeRed** [comment]
情况是录制播放没问题，但在flv.start()后的判断key frame返回false；我也觉得应该有关键帧，可是真没有，这种情况只会发生在一打开APP第一件事做录制，当第一件事是推流的时候，那么久不存在这个问题。我觉得很神奇。

**Comment by begeekmyfriend** [comment]
你推流用的es是duplicate出来的吗？

**Comment by JakeRed** [comment]
是呀。
![image](https://cloud.githubusercontent.com/assets/21214880/18237337/95c53160-7362-11e6-95cd-f340f9170400.png)

**Comment by begeekmyfriend** [comment]
你加断点看看es有没有进入`rtmp_write_packet`这个函数

**Comment by JakeRed** [comment]
录制视频的时候推流也会进入rtmp_write_packet，只是不推流，这里的ADD是走的。
![image](https://cloud.githubusercontent.com/assets/21214880/18237448/28d0489a-7364-11e6-990b-00e347b76815.png)
但是这里的frame_type的值为0.

**Comment by begeekmyfriend** [comment]
你就把从[这一行](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/SrsFlvMuxer.java#L911)开始前几个字节打印出来查查呗，别跟我说你不知道H.264基本的格式

**Comment by JakeRed** [comment]
第一次做视频，还真不知道H264基本格式，不过我不太了解，这里打印出来，都是写数据了，出了问题我也没法改呀，只能通过这个打印确定是write之前的错还是之后的错呗？

**Comment by begeekmyfriend** [comment]
**基本格式**不知道我就没法帮你排查了，做流媒体不能不懂这个，好自为之。。。

**Comment by JakeRed** [comment]
才接触，我可以去了解H264，可是我觉得这里的问题不在格式上，我不了解，但也能借助三方的demo写一个简单的demo，数据格式不了解没办法深层的开发应用，但不等于不能做，谢谢你对我的帮助，这个项目时间太紧我也没时间去做过多的了解，我再看看先出一款再好好研究H264.

**Comment by begeekmyfriend** [comment]
你不了解基本格式你就不理解什么叫关键帧，就没法调试，这么简单的道理你还不明白吗？

**Comment by JakeRed** [comment]
了解了一下H264，打印后我明白了我的问题，首先录制视频已经开始产生H264流，出现了I帧，随后便是基于I帧的P帧，然后在P帧的时候，我开始了推流，应该等待一个关键帧，这个时间其实不长，而且在SrsFlvMuxer的writeVideoSample方法里打印nal_unit_type，一秒内必定会有一个关键帧，但是到了SrsFlvMuxer的start方法里面frame.is_keyframe()却一直是false，因为在write写的时候一定是有关键帧的，所以我觉得start一定会有，您有时间帮我提提建议，我这边之前一直没做过这块。

**Comment by JakeRed** [comment]
关键帧不走这个方法是为什么呢？
rtmp_write_packet（）

**Comment by JakeRed** [comment]
将关键帧作为推流起始帧，进行推流，Log显示流已经推出去，不过播放却黑屏。

**Comment by begeekmyfriend** [comment]
其实我不用回答刚才的问题你不就自己解决了么，说到底还是你自己的问题

**Comment by JakeRed** [comment]
其实我不应该总问，但是最近新开这个项目，了解到这块，然后项目后台那边只管流转发，然后活压我这块了，我就总想少走弯路，却一次次弯着走。我以为把关键帧当起始帧就好了，然后打断点，然后都还是有思路的，但当我能够让正常推流和录制的时候推流都走一个流程了却一时没想法了，我再想想，你能给我点建议就好，就像你说我不懂H264就没法做，这话对我的帮助挺大的，我了解了知道怎么回事，我才敢去改代码。

**Comment by JakeRed** [comment]
这次了解了下RTMP组包，问题终于解决。谢谢！

**Comment by oantajames** [comment]
@JakeRed Hi! From what I have understood(with the help of google translate) you tried to start the camera preview when the activity is created, and start the streaming only when the button is pressed. 
I'm trying to do the same thing...but no luck. 
Could you please tell me what did you do to make it work  ? 
Thanks in advance!
Also great softwear @begeekmyfriend !!
