### ISSUE TITLE
null object references on Camera when start camera

### ISSUE THREAD

**Issue by HartzDev** [begeekmyfriend/yasea#99]
hai.,

i just debug my app,
and it said i invoke camera.setParameters() on null object references.

Thx.

**Comment by begeekmyfriend** [comment]
Camera not opened

**Comment by iSinch** [comment]
@HartzDev may be you have API >23 ?

**Comment by HartzDev** [comment]
Hai,
sorry for late response,
i found the problem, 
i change hardcode value onSetPreviewResolution and make the error appear, when i use it again, everything work fine.
